### ISSUE TITLE
Feature request: Notify when "Run for project" completes

### ISSUE THREAD

**Issue by yau-lim** [qupath/qupath#1029]
## Feature request

**Is your feature request related to a problem? Please describe.**
Currently, the only way to know when Run for project completes is by actively watching the progress bar. For analyses that take many hours to complete, this is not feasible as most users would be working on something else, leaving QuPath in the background. Knowing when the analysis is complete will be helpful to be time-efficient with work.

**Describe the solution you'd like**
A "Notify when complete" checkbox that when checked, will result in an audible notification and maybe cause QuPath to flash in the taskbar after "Run for project" is complete.
![image](https://user-images.githubusercontent.com/57093006/181712393-8dfdd384-43a7-4645-b4ee-e7732005ec18.png)

**Describe alternatives you've considered**
Currently, adding the following lines to the end of the script will result in a double ping, which is decently audible at least on Windows. One issue with this is that the last image needs to be explicitly specified, which may vary as the user works on the project.
```
def name = GeneralTools.getNameWithoutExtension(getCurrentImageData().getServer().getMetadata().getName())
if(name.contains("last_imageName")){
    java.awt.Toolkit.defaultToolkit.beep()
    Thread.sleep(1000)
    java.awt.Toolkit.defaultToolkit.beep()
}
```

**Additional context**
@petebankhead has mentioned that the sound is underwhelming on Mac OS, but I think that `beep()` uses the default notification sound from the OS. If necessary, QuPath could potentially come with a small custom sound file for notifications to be consistent across different OS.

**Comment by MichaelSNelson** [comment]
As you pointed out, the final image can be used just as in the [second post](https://forum.image.sc/t/qupath-audible-alert-windows-when-script-is-complete/46919?u=mike_nelson) about this. It has come up before for both [email ](https://gist.github.com/Svidro/5e4c29630e8d2ef36988184987d1028f#file-email-alert-py)and [telegram](https://forum.image.sc/t/qupath-script-telegram-messenger-alerts-how-to-set-up/56288), which is my preference. 

I agree it would be nice to have something built in, but as long as you have a uniquely named file, that file can also be placed last in the Run for Project queue. Move the target file to the left, and then back to the right and it will always be at the bottom of the queue.

**Comment by petebankhead** [comment]
I've looked into this a little bit. I've never really needed or wanted this feature myself, but can see it would certainly help in some contexts. My worry is that power users running long scripts will tend to want different ways of being notified that the script is finished. Ideas that come to mind are:
* Something audible, e.g. the beep
* Email/telegram
* 'Requesting attention', e.g. forcing the app to the front
* A small, unobtrusive progress bar that can be 'always on top' (even if QuPath isn't)

I'm not sure adding one option to the batch script dialog will be enough to solve the problem, and adding many becomes a lot more clutter and effort to maintain.

To overcome that, my initial idea was to provide the option of adding a 'batch script listener' to the script editor. 

So you could add a listener using something like this (in Groovy):
```groovy
def scriptEditor = getQuPath().getScriptEditor()
scriptEditor.addBatchScriptListener(e -> {
   if (e.isLastScript()) {
      // Do something... beep, email, whatever
      java.awt.Toolkit.defaultToolkit.beep()
  }
})
```

The thing is that the listeners would be cumulative, so you'd likely want to just add one on startup and leave it (rather than add multiple listeners and then have them all firing when scripts are run). But then it becomes harder to turn it on/off the listener's behavior.

Nevertheless, this approach would make it possible to add small extensions that offer different kinds of behavior, controlled via preferences or something else. So you could have a preference allowing the user to choose the audio file they want played on completion, for example.... but still, remembering to turn the option on and off could be a pain, since it wouldn't be easy to incorporate it as a checkbox in the batch processing dialog itself.

While writing this, another option I've thought of is to make more info about the current script accessible within the script itself. So it might look like this:

```groovy
if (getScriptInfo().isBatchProcessing() && getScriptInfo().isLastScript()) {
      // Do something... beep, email, whatever
      java.awt.Toolkit.defaultToolkit.beep()
}
```

So any notification would be something pasted at the end of the script itself. It's like @MichaelSNelson's approach except avoids worrying so much about the last file being uniquely named.

What do you all think?

**Comment by MichaelSNelson** [comment]
That sounds amazing. Gives users the flexibility to be alerted remotely or within speaker range - and I can already think of some other uses for a part of a script that runs only at the end of a batch.

**Comment by yau-lim** [comment]
I think it's an amazing idea! Also, thanks @MichaelSNelson for sharing the email/telegram alert options too, I'll look into implementing those, but usually the beeps is sufficient for me most of the time.

**Comment by petebankhead** [comment]
See also https://forum.image.sc/t/problems-when-running-qupath-script-for-project/71946 for some other sub-optimal behavior that could be addressed at the same time as this.

**Comment by petebankhead** [comment]
This is now addressed by https://github.com/qupath/qupath/pull/1078

Specifically, the bit about `ScriptAttributes` explains how you can get this info when running scripts. You'll still need to include something in the script to do the notification, but at least you should be able to tell if you're running the last script or not.
