### ISSUE TITLE
How to export xml file

### ISSUE THREAD

**Issue by XinyeDu1204** [qupath/qupath#1035]
I only use the annotation function, and want to export an xml file about my ROI area.
Do you know how to do?

Thank you very much!!

**Comment by MichaelSNelson** [comment]
That sounds like a question, which as the label indicates, is for the image.sc forum. I recommend starting a topic there.

Note that JSON is already supported as an export format, built in. You would likely need to code your own for XML, in whatever XML format you wanted.

**Comment by XinyeDu1204** [comment]
Thanks for your reply.
Can you tell me how to convert to JSON file?

**Comment by XinyeDu1204** [comment]
I found it. Is that called GeoJSON?

**Comment by petebankhead** [comment]
@XinyeDu1204 as @MichaelSNelson says, questions about QuPath should be posted on the forum at https://forum.image.sc/tag/qupath

You should have seen a message saying this when you tried to create this GitHub issue, and it's also stated on this page (under the 'labels' column). It's important to keep questions and answers in the same place so that others can find them.

There are well over 2,000 discussions about QuPath on the forum, with lots involving XML: https://forum.image.sc/search?q=qupath%20xml

For example, see https://forum.image.sc/t/export-pixel-selection-as-image-scope-xml-format/26549/2

I will close this issue now, feel free to start a discussion on the forum if you have further questions.
