### ISSUE TITLE
Changing Stain 2 Value

### ISSUE THREAD

**Issue by AndrewPennMed** [qupath/qupath#104]
Hi,

Thank you for making this amazing software. Overall I love the love the capabilities so far and I'm hoping to be able to create some extensions as my java knowledge improves.

I can't tell if the issue I'm encountering is an error or a result of the intended design.

I'm attempting to change the value for Stain 2 (DAB) under Image>Properties>Value. When I input a new RGB value (example: 0.296,0.433,0.493) the value does not change from the default value of: 0.269 0.568 0.778. The only way I have been able to get the value to change has been to change one number at a time:
Example: 0.269 0.568 **0.778** -> 0.269 0.568 **0.493**
But when I do this it re-adjusts all 3 numbers to: 0.337 0.711 0.617 

Overall my goal is to use the Positive Pixel Count tool (Analyze>Region identification>Positive Pixel Count (experimental)) to analyze ROI's that have been stained for different protein accumulations (intracellular and extracellular). To do this I need to be able to change the color of the DAB stain (Stain 2) for each unique stain.

A suggestion I have is that there should be a tool to easily set the color of each stain by sampling pixels from the image. Then it will be easier to perform analysis of % area occupied each new stain.

Thank you for your help!
Andrew

**Comment by petebankhead** [comment]
Thanks Andrew, I'm very glad you like it - and extensions would be welcome!

I think what you're seeing is intended design.  A few things that might help:
* Spaces are used (strictly) as the delimiter when you manually input a stain vector - in the example that doesn't work, commas were given instead
* All the numbers adjust when you change any one of them, because QuPath will automatically normalize them to become a unit vector
* It is actually possible to give a sample of each color... although I'm not entirely sure if/where this is documented.  Just draw a small rectangle in the area you want, then double-click on the stain you want to change.  It should ask if you want to set the values from the ROI - instead of typing them manually.

Another possibly-undocumented thing is that if you use 'Estimate stain vectors', you can actually grab the end of one of the stain vectors and move it around by dragging.  Although figuring out the appropriate moves to reposition a vector in 3D based on three separate 2D plots isn't entirely easy...

**Comment by AndrewPennMed** [comment]
Hi Pete,

Thank you for responding so quickly. Option 3 above was exactly what I was looking for! Setting the Stain Value according to an ROI accomplished exactly what I was hoping to do.

Also, while using the estimate stain vectors tool I was able to see that the RGB value I was attempting to put in wasn't a valid combination (0.296 0.433 0.493). I'm assuming that this is because it couldn't be normalized to a unit vector. This was causing the Stain 2 value to remain unchanged even after entering the new value with spaces as a delimiter.

Thanks again for your help,
Andrew
