### ISSUE TITLE
.mrxs file reading problem

### ISSUE THREAD

**Issue by alextitle** [qupath/qupath#106]
Thanks for this great program, I'm really excited about using it - once I get my files to open properly (if it's possible)! I'm trying to open .mrxs files generated by a 3D Histech slide scanner. I've seen several comments from other users regarding problems with .mrxs files, and it seems like some people can open them and some cannot.  I was wondering if there has been any progress made in this direction? My files are not JPEG XR but rather 16-bit JPEG 2000. They're fluorescent images, and they do open in Qupath, but they are then very low resolution. It seems like they're always opened by ImageJ and not OpenSlide. I've tried both Mac and PC, as well as different versions of Qupath (v0.0.7 as well as the newest version). Any suggestions would be welcome, and please let me know if you need more information. Thanks a lot for your help!

**Comment by petebankhead** [comment]
I'm afraid I don't know of any way to open at 16-bit .mrxs files within QuPath... and I don't know of any current developments that will change that situation.

Basically, there are two libraries that can be used to read whole slide images into QuPath: OpenSlide and Bio-Formats.  However, OpenSlide only supports a subset of 8-bit RGB .mrxs files (16-bit multichannel would require a very substantial redesign), and is [not officially supported](https://lists.andrew.cmu.edu/pipermail/openslide-users/2012-July/000377.html).
[This blog post](http://blog.openmicroscopy.org/file-formats/community/2016/01/06/format-support/) explains why there is no support for .mrxs files within Bio-Formats.

If another library became freely available that could read .mrxs files, then potentially this could be used to add support within QuPath.  But I'm not personally aware of any such library, and the blog post above suggests that creation one would be a difficult task.

I've tagged this post as 'help wanted', in case anyone sees a possibility to help by creating such a library/integration.

**Comment by Svidro** [comment]
If you do not want to or are not able to rescan those images, one option is using the free Pannoramic Viewer from 3DHISTECH to export the images in 8bit format.  It can be obtained at: 
http://www.3dhistech.com/downloads

I recommend maximizing the tile size for speed and your own sanity :)  Especially as you would need some kind of external Python script or something in order to convert the images, as Pannoramic viewer only handles one at a time, manually.  I recommend multiple logins on a server, or multiple computers!

Last I checked, the newer CaseViewer did not have as many options for exporting and could not be used for this purpose.

**Comment by erexhepa** [comment]
Hi everyone,

I hope I'm not too late but I wanted to update the feed based on my own experience with the .mrxs format from 3DHISTECH. 

It's a problematic format and we have found at least 2 issues related to interoperability with both OpenSlide and Bio-Format.

1) Bio-Format: When scanning in high throughput the software piloting the scanner sometime saves as a snapshot for the current slide the snapshot of the previous slide. Bio-Format by default load the snapshot.

2) OpenSlide: Because of the issue above we started to use OpenSlide and grab the low-res from the stack but this also is problematic. For some slides the lowres is larger (in terms of area on the slide) then the actual scanned area on the consecutive higher resolution stack representations. We do not know why it happens only on a few slides of the batch.

the converter is an option but this means you have to duplicate the data and when you have a lot slides it is such a pain when you think about the amount of actual data generated.

**Comment by erexhepa** [comment]
I have to agree with the comments from the [OME](http://blog.openmicroscopy.org/file-formats/community/2016/01/06/format-support/) it is indeed the most complex format to work with.

**Comment by petebankhead** [comment]
Thanks for your update!

Please let me know if you ever find any improved solution, or possibly a library/SDK that could be used.  In the last few days I've seen there is now an open source C++ library for Zeiss czi images [here](https://github.com/zeiss-microscopy/libCZI).  It's something I plan to explore a bit more, but I don't know of anything similar for .mrxs.

**Comment by erexhepa** [comment]
I will let you know. Thanks for the link to the Zeiss sdk.

I saw some serious efforts on the DICOM front in a conf lateley and this would ultimately solve this format problems.
