### ISSUE TITLE
Object connections cause moderate viewer lag when downsample factor is less than 1

### ISSUE THREAD

**Issue by MarkZaidi** [qupath/qupath#1069]
## IMPORTANT!

* [X] I've definitely found a bug (it you're not sure, please use [image.sc](https://forum.image.sc/tags/qupath) instead)
* [X] I've checked https://qupath.github.io for a new release that might already have fixed the issue
* [X] I've checked the [Changelog](https://github.com/qupath/qupath/blob/master/CHANGELOG.md) to see if the bug has already been fixed in the next release
* [X] I've checked for existing GitHub issues describing the same problem

## Bug report

**Describe the bug**
Object connections cause moderate viewer lag when downsample factor is less than 1, evident when panning. Very minor and niche issue, but I figured I'd open a ticket anyways.

**To Reproduce**
1. Run cell detection across a whole-slide annotation
2. Generate object connections via "Delaunay cluster features 2D"
3.  Set viewer downsample factor to 0.99 or less
4. Observe lag when panning. Unchecking "show object connections" or setting a downsample factor greater than or equal to 1 will resolve this issue.

**Expected behavior**
Visualizing objects overlaid onto images shouldn't result in substantial lag

**Screenshots**
Video recording: https://www.youtube.com/watch?v=qOBp2X6HVUc

**Desktop (please complete the following information):**
 - OS: Windows 10
 - QuPath Version: Version: 0.4.0-SNAPSHOT
Build time: 2022-01-24, 13:48

**Additional context**
A 24-class composite classifier, annotation-generating pixel classifier, and several other spatial analyses were also performed.

**Comment by petebankhead** [comment]
I've added a PR that is intended to address this... although its main focus is on another related bug: https://github.com/qupath/qupath/pull/1070

> Visualizing objects overlaid onto images shouldn't result in substantial lag

Ideally it shouldn't, but if it does I wouldn't say it's necessarily a bug... since QuPath is already needing to do a *lot* of stuff to get acceptable performance across a wide range of scenarios. Specifically here:
* For a downsample >= 1, repainting detections caches tiles and multiple resolution levels for performance - this is why QuPath can handle millions of objects.
* For downsample < 1, repainting happens for all detections in the field of view (like for annotations) for improved appearance without nasty bitmap-upsampling artefacts. This is inevitably laggier than using cached tiles, but caching itself has considerable overhead in terms of memory and worse appearance.

I think this tradeoff makes sense, since details really matter when viewing the image at high magnification but the number of objects visible should be limited (possibly thousands, but not millions).

However it does mean that if you have a large enough monitor, many detections, and a downsample value slightly less than 1, performance there certainly can be a noticeable lag... and object connections make this worse by meaning that thousands more lines need to be rendered.

However, investigating this revealed that QuPath was painting all the connections twice, which certainly wasn't helping things :)

So the PR fixes the double-painting bug. Along the way, it adds a spatial cache that enables QuPath to be a bit smarter about which connections it paints.

The main reason for this change is to overcome an issue with long connections sometimes being broken at some resolutions:

### Old behavior:
![connection_bug-1](https://user-images.githubusercontent.com/4690904/194024037-795fceaa-e542-4c67-8fa2-84e6a8aca691.png)

### New behavior:
![connection_fix-1](https://user-images.githubusercontent.com/4690904/194024122-00080b78-b59b-4b8f-bf0d-aa990683268c.png)

Together, I'm not certain whether or not you'll see a substantial improvement in performance - but these changes address any related bugs that I know of.

**Comment by petebankhead** [comment]
I'll close this because I think the main bug is addressed - and hopefully the performance is also at least a bit improved for the original use case.
