### ISSUE TITLE
Colors of the table in TMA Data Viewer do not match with "Moderna Dark" theme.

### ISSUE THREAD

**Issue by ajay1685** [qupath/qupath#1083]
## Bug report

**Describe the bug**
1. TMA Data viewer table colors does not match with the "Moderna Dark" theme
2. TMA Data viewer table has missing values for column Object ID, Name, Missing, Centroid X, and Centroid Y
3. Vertical scrolling for the TMA Data Viewer is sluggish (only when loading from the entire project which has a lot of detections) 

**To Reproduce**
1. Open a project with TMA images, open an image with TMA Data
4. Click on File -> "TMA Data" -> "Launch TMA Data Viewer"
5. In the TMA Result Viewer window unchecking the "Group by ID" results in a table with light background and gray text. See the screenshot
6. Values from the following columns are missing:  Object ID, Name, Missing, Centroid X, and Centroid Y
7. Test vertical scrolling in the TMA Data Viewer

**Expected behavior**
1. TMA Data viewer colors should match "Moderna Dark" theme
2. Populate values for the following columns: Object ID, Name, Missing, Centroid X, and Centroid Y
3. Improve table for smooth vertical scrolling - if possible!

**Screenshots**
<p align="center">
<img src="https://user-images.githubusercontent.com/10900214/197264041-a4c298d4-b3b3-43e8-a142-9d8d9b8ff47a.png" width="800">
</p>

**Desktop (please complete the following information):**
 - OS: Windows 10
 - QuPath Version: 0.3.2 & 0.4.0-SNAPSHOT

**Comment by petebankhead** [comment]
Thanks @ajay1685 the PR above should address most of this, and a couple of other bugs I spotted (like measurements not updating if cores were moved on the image). Please let me know if you notice any significant problems with this.

Because the TMA data viewer is unmaintained, I think there is an above-average risk of unreported/unnoticed bugs so I've added a warning now as well. You can double-click on it to make it go away.

<img width="1006" alt="TMA data viewer" src="https://user-images.githubusercontent.com/4690904/197327977-4298edd4-13f3-41d3-b99c-6f95be821ff9.png">

In the longer term, I think it should be removed or rewritten.

Rewritten would be preferable, but it's really a matter of capacity... as the software gets bigger, there are so many different parts to maintain and I haven't worked with TMAs myself in years.
(In that regard, new QuPath jobs to be advertised next week - please share them widely!)

Regarding performance, I couldn't replicate any sluggishness - it was very smooth for me, but then I was only using 'toy' datasets based on generating a grid on a regular whole slide image. If you can provide more info to replicate the sluggishness then I could have a quick look into that, but for now I hope the main issues are fixed.

**Comment by ajay1685** [comment]
@petebankhead thanks for these fixes to the TMA Data viewer. The table now has correct colors and all the columns that were missing values now have correct values. 

I am just realizing that the data table is only sluggish when the TMAs have cell detections present. If I were to calculate my measurements of interest for each TMA and remove detections before testing the TMA Data viewer then it works very smooth. Is it possible that the vertical scroll issue sluggishness is a side effect of being able to view huge combined dataset "live"!

I hope TMA Viewer is here to stay as a legacy feature for a while, it seems to have served well and continues to work. Thank you for keeping it alive.

**Comment by petebankhead** [comment]
Great, thanks!

If you create a regular 'measurement table' for the TMA cores with cells, is it also sluggish (*Measure &rarr; Show TMA measurements*)?

I guess it is connected to the live measurements somehow. In QuPath v0.1.2 (the last time I used the TMA data viewer...) these were based on the hierarchy, so pretty fast. Since then, they are based on the x,y coordinates of cells and so that could require a bit more computation.

**Comment by petebankhead** [comment]
Also, approximately how many TMA cores do you have - and what classifications/measurements?

I've tried it on an image with cells and it is still fast for me :/ But I'm cheating with a non-TMA using the new *Specify TMA grid* command, since I don't have any actual TMA images nearby to work with.

**Comment by ajay1685** [comment]
Project contains total of 6 TMA slides. Each contains approximately ~80 cores. A few cores are marked as missing per slide due to not enough tissue or missing information. I have a total of approximately ~400 valid cores in the project, each slide may contain multiple cores per subject id.

I tested the Measure -> show TMA measurements. This means I can only load the data for the active image. The table does work with a tiny bit of scrolling lag - very little. If I open the same image without detections the table is smooth.

**Comment by ajay1685** [comment]
Ok, I tested the "Offline TMA Data Viewer" (not sure what to call this method!). I exported TMA data (qptma) for all 6 TMA slides. I loaded one file in the TMA Data Viewer in a new QuPath instance which seem to load data for all the qptma files present in the folder ! is that expected behavior ?

With this method the table is very smooth. It makes sense to work offline if I want to look at the combined data from multiple TMAs after completing the cell detection and classification.

I opened one of the qptma file using notepad. I did not see any measurements or survival data in the file content - however the TMA Data Viewer was able to populate all the columns including measurements. Where is the data being pulled from ? what kind of magic is this.

I may also have discovered additional bug(s):

1. I am seeing columnImage is null error in the log at loading - everything seem to work regardless. The same error is thrown everytime I toggle "Group by ID" as well.
```
ERROR: QuPath exception: Cannot invoke "javafx.scene.control.TreeTableColumn.setPrefWidth(double)" because "columnImage" is null
java.lang.NullPointerException: Cannot invoke "javafx.scene.control.TreeTableColumn.setPrefWidth(double)" because "columnImage" is null
    at qupath.lib.gui.tma.TMASummaryViewer.lambda$refreshTableData$66(TMASummaryViewer.java:1463)
```
2. In the log I also noticed ```WARN: Unable to find censored column - survival data will be uncensored``` - not sure why ? 
```
INFO: Update check for https://github.com/qupath/qupath
WARN: You need to enable the startup script in the Preferences if you want to run it
INFO: Starting QuPath with parameters: []
INFO: Update check for https://github.com/qupath/qupath-extension-stardist
INFO: Predicate set to: null
INFO: Parsed 84 from HS-1_Scan1.ome.tif.qptma (84 total)
INFO: Parsed 84 from HS-2_Scan1.ome.tif.qptma (168 total)
INFO: Parsed 84 from HS-3_Scan1.ome.tif.qptma (252 total)
INFO: Parsed 84 from HS-4_Scan1.ome.tif.qptma (336 total)
INFO: Parsed 84 from HS-5_Scan1.ome.tif.qptma (420 total)
INFO: Parsed 84 from HS-6_Scan1.ome.tif.qptma (504 total)
WARN: Unable to find censored column - survival data will be uncensored
INFO: Survival column: Overall survival, Censored column: OS censored
INFO: Survival column: Overall survival, Censored column: OS censored
INFO: No p-values < 0.05
INFO: Smoothing log-rank test p-values by 1
INFO: Longest stretch of p-values < 0.05: 12294.9 - 13980.4 (18 entries, 5 observed)
INFO: Smoothing log-rank test p-values by 11
INFO: Longest stretch of p-values < 0.05: 12294.9 - 13980.4 (18 entries, 5 observed)
INFO: Smoothing log-rank test p-values by 11
```
I can see in the next couple of line the survival data is being loaded , and they are displayed in the table as well.

3. I also noticed the "Missing" column is missing in the TMA Data viewer when I load the qptma file in the Offline TMA Data Viewer.

**Comment by petebankhead** [comment]
>  is that expected behavior ?

Yes!

> Where is the data being pulled from ? what kind of magic is this.

I think text files are exported as well?

> I also noticed the "Missing" column is missing in the TMA Data viewer when I load the qptma file in the Offline TMA Data Viewer.

Are the missing columns included, or were they already excluded at export?

I'm afraid I don't know the answers to anything else, and lacking time and real data I'm not sure when I'll be able to investigate. The null pointer exception looks likely harmless, just annoying; the survival warning is odd - but because both printed statements come on both sides of an `if/else` statement [here](https://github.com/qupath/qupath/blob/17785d7364c39b79e5e09263849031f355c1c0b7/qupath-gui-fx/src/main/java/qupath/lib/gui/tma/TMASummaryViewer.java#L757) it looks like the method must be being called multiple times in succession.

**Comment by ajay1685** [comment]
> Yes!

Ok.

> I think text files are exported as well?

Yes - I found them inside the folder with the images. Thanks.



> Are the missing columns included, or were they already excluded at export?

Only one column is missing for the cores - "Missing" (True or False values for each core). When exporting TMA data there are no options to select which column will be exported. The "Missing" column is included in the text file but is not displayed in the TMA Viewer.




> I'm not sure when I'll be able to investigate

I totally understand, thanks anyways - you have been very helpful as always.



> The null pointer exception looks likely harmless,

Yes - thank you confirming.


Feel free to close this bug report, unless you want to visit it again in the future. All these bugs seems to be minor issues - so it's all good. TMA Data Viewer was really helpful in exploring the data. We are in the process of confirming the findings using GraphPad Prism.

**Comment by ajay1685** [comment]
Here is another issue I ran into. Not entirely QuPath's fault because MS Excel on windows for some reason decided to capitalize the column with values ```True``` & ```False```. When I opened the text file containing TMA data and saved it with MS Excel missing TMAs were no longer flagged as missing!! 

Changing both of this:
https://github.com/qupath/qupath/blob/fca7fa5fd9efd815f4c317705fbe2a0f9c39270f/qupath-gui-fx/src/main/java/qupath/lib/gui/tma/TMASummaryViewer.java#L1627
and,
https://github.com/qupath/qupath/blob/fca7fa5fd9efd815f4c317705fbe2a0f9c39270f/qupath-gui-fx/src/main/java/qupath/lib/gui/tma/TMASummaryViewer.java#L1713

to use ```Str1.equalsIgnoreCase(Str2)``` addresses the issue. i.e.
```java
boolean missing = missingColumn != null && "True".equalsIgnoreCase(missingColumn.get(i));
```

**Comment by petebankhead** [comment]
Intriguing... sure, `"true".equalsIgnoreCase(missingColumn.get(i))` sounds fine to me, if you want to add it to the PR :)
