### ISSUE TITLE
Imported Images with 180 rotation are not displayed as such in ImageJ server type

### ISSUE THREAD

**Issue by lacan** [qupath/qupath#1138]
## Bug report

**Describe the bug**
After importing an image with a Rotate 180 in the import dialog, the image is not shown as rotated. However, using the Magic wand, (which is how we found the bug) the outline is drawn from the rotated version of the image, which does not overlap with the pixels we are seeing.
This seems to be linked to the ImageJ Server type, as forcing Bioformats as the server gives the expected behaviour

**To Reproduce**
1. Make a new project
2. Drag and drop a fluorescent image that will be opened with the ImageJ server type
3. Select Rotate 180 before importing
4. Try to draw a visible shape using the magic wand. 

**Expected behavior**
The image pixels should be displayed with the requested rotation when importing as an ImageJ server type

**Screenshots**
![image](https://user-images.githubusercontent.com/319932/202206940-3e62bc6c-d2d0-4629-b74e-629a656f8fc6.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - QuPath Version: 0.3.2

**Additional context**
[Example QuPath Project with the error](https://github.com/qupath/qupath/files/10022626/QuPath.Flip.Error.zip)

**Comment by petebankhead** [comment]
Thanks @lacan the behavior was *extremely* confusing, but I think I figured it out in the end.
* https://github.com/qupath/qupath/pull/1139

Your project helped a lot - I couldn't replicate the issue with my own image, but the details turned out to really matter (ImageJ server, non-RGB... not sure what else exactly). Ultimately it traced back to the pixels being transformed in-place, which impacted the cached ImageJ `ImagePlus` in a way that shouldn't be permitted.

**Comment by lacan** [comment]
Awesome @petebankhead, yeah it's the first time someone uses an ImageJ server with rotation so we were quite at a loss too. Noticing that it worked with the BioFormats server saved the user's project and helped narrow down the issue a bit.
Thanks so much for looking into it!
