### ISSUE TITLE
Is it possible to change image paths for project slides?

### ISSUE THREAD

**Issue by zibizib** [qupath/qupath#114]
Greetings,

I keep my images on external hard-drive, which used to be assigned to letter D: during the time of creation of the project. I recently changed my working computer, and due to multiple drives in it the letter of external drive changed, which again resulted in QuPath error about not finding the slides when trying to open them in the project. 

Is it possible to modify the project files so, that I could assign them to new image path (just change the drive letter in this case)? I know it is possible to change it, when you try opening each slide separately from the folder, but it still doesn't save the new path to the file itself.

Thank you! :)

**Comment by Svidro** [comment]
Just remove all of the images from your project and reimport them (like when you started the project).  The data files are only associated with the image name.  As long as you have not renamed the image files, only moved them, there shouldn't be a problem.

**Comment by petebankhead** [comment]
You can also open the `project.qpproj` file directly in a text editor, and then use 'Find & Replace' to change the paths.  That is probably easier and faster than reimporting.

You could even duplicate the project file and keep the duplicates in the same directory, each with the paths including a drive letter you might need.  So you might have `projectD.qpproj`, `projectE.qppro`j, `projectF.qpproj`... each containing the different paths that you might need.  Ultimately the data for each image is stored inside the 'data' subdirectory inside the project folder, with a filename based only on the name of the image (not its full path).  Therefore just open the project file that contains the correct paths, and it should immediately have access to the same data.

There is a little bit of information about how projects are structured at https://github.com/qupath/qupath/wiki/Project-structure
It's usually best to leave QuPath to take care of the files in the project directory... but it is intentionally quite simple so that, if you know more or less what it is doing, you can certainly hack it a bit to behave the way you need.

**Comment by zibizib** [comment]
Thanks a million for your answers! I tested both ways, and for my purpose the one @petebankhead proposed works the best, as it's very fast to do and I have over a hundred slides in several projects. Cheers! 🥇

**Comment by batesma** [comment]
Hi, had similar issues as we have multiple backups of our files on different external hardrives. It is possible however to reassign the letter of each hardrive by going into administrative tools, see below

Open the Start menu, and type "Administrative Tools" in the search box. Click it in the list that appears and then double-click "Computer Management." Enter your administrator password if Windows asks for it.

Click the "Disk Management" link, and then click your external hard drive's assigned disk. Right-click the disk and click "Change Drive Letters and Paths."

Click the "Change" button and click "Assign the Following Drive Letter." Click the new letter to assign to your external hard drive and click "OK" to save your change

This way as long as the files and folder structures within the hardrive remain the same all that you need to change is the letter of the hardrive so that it is the same as the original that it was stored on.
