### ISSUE TITLE
Limited number of characters for block comments in groovy scripts

### ISSUE THREAD

**Issue by Rdornier** [qupath/qupath#1176]
## Bug report

**Describe the bug**
If a block comment contains more than a certain number of characters, QuPath throws an error (see below) when I open that script (no other scripts were open before). It is then not possible to run the script because all `Run` buttons are disabled. If I try to change the language to `None`  and then to `Groovy`, it throws again the same error and the `Run` buttons are still disabled. If I open another script, then it enables the Run buttons for both scripts (but the issue is still there if we open again the first script).

**Temporary Fix**
One fix is to reduce the number of characters in the block comment and then, no more error is thrown. For example, splitting a large block comment to smaller ones.

**To Reproduce**
1. Open a script
2. Add the following block comment 
```
/**
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, 
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF 
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
```
3. Save the script.
5. Close the script (Ctrl+w)
6. Open the same script ==> no error
7. Add the following block comment

```
/**
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, 
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF 
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, 
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF 
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, 
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF 
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, 
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF 
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
```

7. Save the script.
5. Close the script (Ctrl+w)
6. Open the same script ==> the follwing error is thrown

**Expected behavior**
Enable to have an unlimited number of characters inside a block comment

**Screenshots**
```
ERROR: QuPath exception
java.lang.StackOverflowError: null
    at java.base/java.util.regex.Pattern$LazyLoop.match(Unknown Source)
    at java.base/java.util.regex.Pattern$GroupTail.match(Unknown Source)
    at java.base/java.util.regex.Pattern$BranchConn.match(Unknown Source)
    at java.base/java.util.regex.Pattern$CharProperty.match(Unknown Source)
    at java.base/java.util.regex.Pattern$Branch.match(Unknown Source)
    at java.base/java.util.regex.Pattern$GroupHead.match(Unknown Source)
*****
    at java.base/java.util.regex.Pattern$LazyLoop.match(Unknown Source)
    at java.base/java.util.regex.Pattern$GroupTail.match(Unknown Source)
    at java.base/java.util.regex.Pattern$BranchConn.match(Unknown Source)
    at java.base/java.util.regex.Pattern$CharProperty.match(Unknown Source)
    at java.base/java.util.regex.Pattern$Branch.match(Unknown Source)
    at java.base/java.util.regex.Pattern$GroupHead.match(Unknown Source)
**** n times (probably n = nb of characters)
ERROR: Error applying syntax highlighting: StackOverflowError
```

**Desktop**
 - OS: Windows 11
 - QuPath Version: 0.4.0

**Comment by petebankhead** [comment]
Hi, I don't think this is a new bug - although maybe its impact is different through the script editor changes. The actual syntax highlighting hasn't changed, and there are lots of reports of `StackOverflowErrors` associated with Java regex.

* https://github.com/qupath/qupath/issues/241
* https://github.com/qupath/qupath/issues/314

Here, QuPath is using the same regex as from the RichTextFX project and I guess that's a limitation.
The code is in [`GroovyStyler`](https://github.com/qupath/qupath/blob/v0.4.0/qupath-extension-script-editor/src/main/java/qupath/lib/gui/scripting/richtextfx/stylers/GroovyStyler.java).

I'm not much of a regex specialist (improvements welcome!) so don't have a quick solution.

An alternative option (which I *think* I prefer) is to abandon regex altogether and compute the styling some other way. It feels like this might be more efficient and less exception-prone, but also feels like something I'll almost certainly get wrong for a few iterations so that it doesn't apply the highlighting properly. Might become a hopefully-small holiday project if I feel inspired.

**Comment by petebankhead** [comment]
I've made a PR at https://github.com/qupath/qupath/pull/1195

It involved entirely changing how the Groovy syntax highlighting works, and adding support for a few other Groovy features (like using colors to indicate `"string $interpolation"`, or numeric values). It doesn't handle everything, because that would require fully parsing the code too avoid getting mixed up (e.g. mistaking a division operator for the start of a slashy string).

The code was very fiddly to write, so I wouldn't be surprised to learn its broken in some places - but as far as I can tell, it's better than the previous version.

@Rdornier if you've time to check it out, please let me know if there are problems.

**Comment by Rdornier** [comment]
Hello @petebankhead, 

Thank you for your quick consideration of the issue.
From what I have tested until now, it works fine. The number of characters in block comments does not throw the error anymore. and I can still run the scripts.
