### ISSUE TITLE
QuPath with CUDA cannot run StarDist on GPU

### ISSUE THREAD

**Issue by MarkZaidi** [qupath/qupath#1180]
Before submitting your bug report, please check the following:

* [X] I've definitely found a bug (it you're not sure, please use [image.sc](https://forum.image.sc/tags/qupath) instead)
* [X] I've checked https://qupath.github.io for a new release that might already have fixed the issue
* [X] I've checked the [Changelog](https://github.com/qupath/qupath/blob/master/CHANGELOG.md) to see if the bug has already been fixed in the next release
* [X] I've checked for existing GitHub issues describing the same problem

## Bug report

**Describe the bug**
Building QuPath from source as described below with CUDA GPU support will throw an error, meaning the official 0.4.0 release (built 2022-12-07) cannot run StarDist on GPUs. Tested with RTX 3090 and GTX 1660 Ti GPUs. I have a version of QuPath built on 2022-11-21 which has no problem running StarDist on the GPU, so it's likely tied to any commits between this period. Issue taken from forum post: https://forum.image.sc/t/stardist-gpu-support-unknown-error/74779

**To Reproduce**
1. Build QuPath from source using the following command:
```
git clone https://github.com/qupath/qupath
cd qupath
./gradlew clean jpackage -Pcuda-redist
```
2. Install either the 0.3.2 or 0.4.0 releases of the StarDist extension: https://github.com/qupath/qupath-extension-stardist/releases
3. Download pretrained models in .pb format
4. Draw an annotation on a brightfield image
5. Download the following script: https://github.com/MarkZaidi/Universal-StarDist-for-QuPath/blob/main/GPU_Multimodal%20StarDist%20Segmentation.groovy
6. Run the script
7. Observe the following error message:
```
INFO: Performing detection on Brightfield image using single-channel trained model
INFO: [Annotation]
ERROR: OpenCV(4.6.0) D:\a\javacpp-presets\javacpp-presets\opencv\cppbuild\windows-x86_64-gpu\opencv-4.6.0\modules\dnn\src\cuda4dnn\csl\memory.hpp:54: error: (-217:Gpu API call) the provided PTX was compiled with an unsupported toolchain. in function 'cv::dnn::cuda4dnn::csl::ManagedPtr<float>::ManagedPtr'
 in GPU_Multimodal StarDist Segmentation.groovy at line number -2

ERROR: org.bytedeco.opencv.opencv_dnn.Net.forward(Native Method)
    qupath.opencv.dnn.OpenCVDnn$OpenCVNetFunction.predict(OpenCVDnn.java:718)
    qupath.opencv.dnn.OpenCVDnn$OpenCVNetFunction.predict(OpenCVDnn.java:732)
    qupath.opencv.dnn.DnnModel.convertAndPredict(DnnModel.java:100)
    qupath.ext.stardist.StarDist2D.detectObjectsForTile(StarDist2D.java:1249)
    qupath.ext.stardist.StarDist2D.lambda$detectObjects$7(StarDist2D.java:934)
    java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
    java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
    java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
    java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
    java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
    java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
    java.base/java.util.stream.AbstractTask.compute(Unknown Source)
    java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
    java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
    java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
    java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
    java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
    java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

```

**Expected behavior**
The script should run without any error, yielding cell detections within the annotation

**Desktop (please complete the following information):**
 - OS: Windows 10
 - QuPath Version: 0.4.0, built from source on 2022-12-07
 - StarDist Extension Version: 0.4.0 (reproducible with 0.3.2 as well)

**Additional context**
The changelog of 0.4.0 points to two separate issues that were marked as resolved, which could be linked to this issue:
https://github.com/qupath/qupath/issues/841
https://github.com/qupath/qupath-extension-stardist/issues/11

Given that issue #841 was marked as resolved 5 days ago, it could be linked to that. Perhaps there were some changes to the API such that closing of the model should be scripted differently?

**Comment by petebankhead** [comment]
QuPath does not include any code that directly relates to the GPU - everything happens through OpenCV/JavaCPP (and sometimes also PyTorch/TensorFlow/DJL). If you search for `the provided PTX was compiled with an unsupported toolchain` you should find lots of discussions separately from QuPath; it seems that the issue is normally related to the driver.

I tried to replicate the issue with the only Windows computer I have access to (including a GeForce 1060) and could not - it runs without errors, and `DnnTools.isCudaAvailable()` returns true.

> Given that issue https://github.com/qupath/qupath/issues/841 was marked as resolved 5 days ago, it could be linked to that. Perhaps there were some changes to the API such that closing of the model should be scripted differently?

I don't think that can be relevant here.

I'm not sure that there is any bug here that can be fixed within QuPath.  I have seen such error messages before, but the solution was always to update my graphics card driver. Have you tried this?

Note that QuPath v0.4.0 gives a range of options for deep learning, but CUDA incompatibilities will mean that probably not all can work at once (e.g. I could get PyTorch with GPU acceleration today by installing CUDA 11.7, but TensorFlow seems to require 11.3... I'm not sure there's a combination that gets both working together).

I don't see that there's really anything much more we can do apart from simply removing the option of GPU acceleration altogether and not documenting it as an option - but that seems a shame when often it does work.

>  I have a version of QuPath built on 2022-11-21 which has no problem running StarDist on the GPU, so it's likely tied to any commits between this period.

Because QuPath doesn't directly access the GPU, please check the .jar files within each installation. I don't know what the problem could be, unless it is somehow related to the inclusion of some Deep Java Library dependencies - or if you have other extensions installed that are conflicting.

**Comment by MarkZaidi** [comment]
>it seems that the issue is normally related to the driver
You're absolutely correct, after updating my GeForce Game Ready driver to 527.37, which is the latest release at the time of posting this comment, I no longer have the issue, and I'm able to segment cells, confirming that the GPU is being used based on VRAM. Unless anyone else is still having this issue after updating their drivers, I'll close this as resolved. Thanks again for all your help!
