### ISSUE TITLE
Bio-Formats Extension (0.0.4) does not show up in Extensions menu, cannot be accessed

### ISSUE THREAD

**Issue by arnmayer** [qupath/qupath#12]
Dear Dr. Bankhead,

First of all: this is an incredible piece of software! We are exploring its multiple possibilities with great excitement. Thank you very much for making it publicly available.

Among others, we are working with a lot of Zeiss *.czi and 3D Histech *.mrxs multichannel fluorescence whole slide images. The default version of QuPath can open the *.mrxs files, but only in the most coarse resolution. So I installed the Bio-Formats extension and it does show up in the "Help/Installed Extensions "dialogue. However, it does not appear in the "Extensions" Menu. Only ImageJ is accessible in this menu.

Best regards,

Arnulf Mayer, University Medical Center Mainz, Germany

**Comment by petebankhead** [comment]
In summary of the above, Bio-Formats probably can't help with either of ```*.czi``` or ```*.mrxs``` files yet - but hopefully it will support CZI files soon, and this should result in (much needed, and much appreciated!) support for Zeiss images in QuPath.  But hopefully the ```*.mrxs``` issue is one we can solve sooner.

**Comment by petebankhead** [comment]
Actually, it may be that the issues with ```*.czi``` or ```*.mrxs``` may be more similar than I realised... it seems that ```*.mrxs``` may also involve JPEG-XR compression, which [OpenSlide does not currently handle](https://github.com/openslide/openslide/issues/184).

If this is the source of the problem, in the short term I'm afraid you may need to change your settings when saving your images in the first place to avoid JPEG-XR (regular JPEG compression should work).  There is also an export ability within [Pannoramic Viewer](http://www.3dhistech.com/pannoramic_viewer), although I have not tried this myself.

**Comment by arnmayer** [comment]
Dear Pete,

thank you very much for your fast reply!

Regarding *.mrxs files, the problems occur only with multichannel fluorescence images. Brightfield images open without a problem. Here is an example:

![brightfield_example](https://cloud.githubusercontent.com/assets/23238491/19998070/e2515342-a26a-11e6-8f3d-8c2746210dc1.jpg)

Indeed, as we can see, OpenSlide is used to access the *.mrxs file. Regarding the fluorescence files, all of the requirements that you stated above are fulfilled for my files. QuPath opens them using ImageJ. When I use ImageJ (or in my case, Fiji) to open them directly, the behaviour is the same: access is only possbile at the most coarse resolution. Both *.czi and *.mrxs can be exported as tiff files from their viewers (ZEN2 and CaseViewer). The monochrome tiffs can be opened in QuPath. However, when I joined three of these monochrome files in an RGB file, my first attempt at opening it in QuPath faild. I am going to keep experimenting.

However, I wanted to point out that the technology to open multichannel *.czi and *.mrxs files already exists because it is implemented in a free viewer application called "Zoom v2.0.0", available from MicroDimensions (https://micro-dimensions.com/zoom/). We have been providing some slides for them over the last years to test their algorithems. They might be interested in a scienctic cooperation.

We can also provide test slides (image data) via our file transfer system for you if you give me an e-mail address.

Best regards,

Arnulf

**Comment by petebankhead** [comment]
Dear Arnulf,

Thanks again for your reply.  I'm glad that the brightfield/RGB ```*.mrxs``` files are working.

I'm not certain, but since Zoom from MicroDimensions is Windows-only, I suspect it may be using the Windows-only software libraries provided by [Zeiss](http://www.zeiss.com/microscopy/int/products/microscope-software/zen/czi.html) and [3D Histech](http://www.3dhistech.com/downloads).  Since these are not open source (as far as I am aware), they [wouldn't be compatible with QuPath's GPL license](https://www.gnu.org/licenses/gpl-faq.html#GPLAndPlugins).  Therefore including them would require a change to QuPath's license, and result in extra functionality being available on Windows but not on other platforms... and for these reasons it would really be a last resort.

Nevertheless, if you or anyone at your place of work would like to give it a try, creating such an extension may be a [reasonable solution for internal use](https://www.gnu.org/licenses/gpl-faq.html#GPLRequireSourcePostedPublic).  The biggest effort required is likely to be in being able to access the pixels from the native libraries within Java, but if that problem is solved then I could certainly help with the relatively small final step of integrating the result with QuPath.

Still, hopefully Bio-Formats will be able to provide a solution for ```*.czi``` files in the near future - I'll post an update here and [Google Groups](https://groups.google.com/d/forum/qupath-users) whenever I see it.

If so, that only leaves non-RGB ```*.mrxs```.  There may be a way to merge separated monochrome TIFFs into a single multi-channel TIFF using [Bio-Formats](http://www.openmicroscopy.org/site/support/bio-formats5.2/supported-formats.html)... although I'm not sure.  Alternatively, [Pannoramic Viewer](http://www.3dhistech.com/pannoramic_viewer) may have alternative export options now present in CaseViewer.

If neither of these approaches are suitable, I can imagine a new custom image reader within QuPath that is able to automatically concatenate the multiple channels of a TIFF, assuming that they are stored in the same directory with a standard naming scheme (e.g. ```name_ch1.tif```, ```name_ch2.tif``` etc.).  That way you wouldn't need to convert to RGB or create a single merged image.

Would that be useful?  If so, then if you were able to send me an example set of monochrome tiffs that have been exported and I would try it out.

Best wishes,

Pete

**Comment by arnmayer** [comment]
Dear Pete,

I understand the problems with the Windows-only algorithms. Unfortunately, we do not have the resources at our institution to create software like that, even though some of our medical physicists may have the programming skills.

In the meantime, I was able to load a smaller three channel RGB tiff exported from a *.czi multichannel fluorescence file. However, in my first attempts I could not get QuPath to identify any cells. I get an error message telling me that my image is not brightfield (which is true).

Do I understand it correctly that QuPath is not (yet?) ready for the analysis of fluorescence  images? Do you plan to implement this functionality? I think that fluorescence files provide some strong advantages with regard to image analysis. 

Best regards,

Arnulf

**Comment by petebankhead** [comment]
Dear Arnulf,

Certainly I'm agreed with you on the benefits of fluorescence for image analysis.  I intended that the cell detection should work with fluorescence, but since I have primarily been working with brightfield until now, this was not taken very far.  Success with fluorescence cell detection previously relied upon several undocumented tricks in terms of choosing parameters, and the good fortune of having your nuclear counterstain in the first channel.

This morning I tried to address this, and hopefully you find it functions better in [v0.0.5](https://github.com/qupath/qupath/releases/tag/v0.0.5), which I've just uploaded.  An example image from a fluorescence microscope is shown below.

![qupath_fluorescence_cells](https://cloud.githubusercontent.com/assets/4690904/20115597/cf2682ae-a5f0-11e6-88c9-82298e3cd1ea.jpg)

A few important points (which will eventually be documented on the Wiki):
* QuPath tries to identify brightfield and fluorescence images when they are opened (although you can ask it not to under *Auto-estimate image type on opening* option in the *Preferences*); if it gets it wrong, you will need to double-click the ```Image type```  in the *Image* tab to set this manually to fluorescence.
* The ```Image type``` needs to be set before running the *Cell detection* command, to make sure that the right options are displayed
* The *Threshold* option under *Intensity parameters* will be important, and will likely need to be adjusted... the default is simply selected for all images of that type and bit-depth, and not based on the information present in the image
* If you are working with images at a relatively low resolution (such as in the screenshot I showed), it can be helpful to decrease the *Detection line thickness* parameter in the *Preferences* so that the cell or nucleus outlines do not obscure your view too much.
* The *Brightness/Contrast* options currently misbehave somewhat with fluorescence.  If you want to show/hide specific channels, it's actually better to simply type the number of the channel you want to hide or show several times (i.e. just the number 1, 2 or 3 etc.).  This should toggle it on or off.

Actually, this last trick to change visible channels also works for brightfield, except that 1 indicates the RGB image, 2 the first color deconvolved channel, 2 the second... and so on through multiple color transforms.

I hope this is useful.

Best wishes,

Pete

**Comment by petebankhead** [comment]
I'll close this issue, since I think most things that can and will be fixed now have been:

* CZI images can now be read with QuPath, as described [here](https://github.com/qupath/qupath/wiki/Supported-image-formats#zeiss-czi) - thanks to the work of OME with [Bio-Formats 5.3.0](https://www.openmicroscopy.org/site/support/bio-formats5.3/about/whats-new.html).
* Cell detection in fluorescence images now gives the option to select the detection channel, and more sensible defaults
* The Brightness/Contrast tricks mentioned above are now documented more fully on the [wiki](https://github.com/qupath/qupath/wiki/Changing-colors)
* Most RGB ```.mrxs``` files should be readable, although unfortunately 16-bit or JPEG-XR-compressed files are not and there are no immediate plans to add this support within QuPath.  However, if OpenSlide or Bio-Formats are able to support these images, then QuPath will benefit through its use of these libraries.
