### ISSUE TITLE
Feature request: brightness and contrast panel: size and select all

### ISSUE THREAD

**Issue by ofrag** [qupath/qupath#1201]
Hi,

I'm using QuPath for analysis of highly multiplexed data (40+ channels), and I would like to ask for the following:

1. The height of the brightness and contrast panel window is limited , and it would be much more convenient if I can make it higher to reduce scrolling down using the slider when I want to turn channels on and off.

2. Can you please add an option to turn On/Off all the channels at once, eg with "Select All" / "Unselect All"  button or checkbox.

Thanks
Ofra

**Comment by petebankhead** [comment]
Quick answer to 2: you can show/hide multiple channels by selecting them, and then right-clicking on the channel list before choosing 'Show channels', 'Hide channels' or 'Toggle channels'.

Ctrl+A should also work to quickly select all channels before right-clicking.

I'll look into the limited resizing later.

**Comment by petebankhead** [comment]
Update to 1: I've removed the dialog height limit in v0.4.2, which has just been released.

I'll close this issue now since selecting/deselecting all is possible as in my last answer.

We might add buttons/checkboxes with these options in the future, but I think we need to explore the whole topic of UX more first - to try to make QuPath's options easier to find, but without making the user interface too cluttered and confused. I don't know what the solution to that is, but I hope someone can figure it out :)
