### ISSUE TITLE
Cannot unlock some annotations

### ISSUE THREAD

**Issue by kellyjakubiak** [qupath/qupath#1224]
I created a bunch of annotations by first using the pixel classifier and then "create objects." I want to quantify the cells in my image but the object creator clumped some together. When I go in and try to split these annotations, I click "unlock" but the software will only sometimes (maybe about a third of the time) give me the draggable points that I can then use to edit the annotation and split it. No error is returned or anything, I'm just unable to edit the annotation despite unlocking it in most cases. There doesn't seem to be any pattern to describe when it will work and when it won't.

I'm on Windows 10 using v0.4.2.

**Comment by petebankhead** [comment]
The annotations probably are unlocked. You can check this by trying to move them, or looking for the lock symbol under the annotations tab.

You will only see draggable points if the annotation ROI is 'simple', e.g. a rectangle, line or polygon. More complicated ROIs (e.g. containing disconnected pieces or holes) are represented differently and can't be edited by dragging points. However they can be edited using the Brush or Wand tool.

Since I don't think there's a bug here, I'll close the issue. Feel free to start a topic on the forum if you would like to discuss this behavior/QuPath's use, or reopen the issue if my explanation is wrong and there really is a problem with unlock not working.
