### ISSUE TITLE
simple tissue detection on ndpi and tiffs generates artefacts in image corners

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#124]
Dear all, 

I observed an artefact in simple tissue detection on ndpi and tiffs. About others, I do not know at the moment. 
It looks like that: 
![grafik](https://user-images.githubusercontent.com/16352785/33805531-c48d2534-ddba-11e7-91b9-275012bf50e8.png)

I used the white channel, because I do not want to show the image content. 
But the cornders are not white. They contain tissue! 

Does somebody have an idea why it is like that?

Best
David

**Comment by erexhepa** [comment]
Hi,

It could be to the thresholds you're using to segment the tissue area that are too low/high depending on what color space or channel you're doing the threshold. 

Normally if all you want to do is segment tissue from background you should have enough room to find a suitable threshold that can work well in different samples but it depends on the tissue sample too and difficult to say without looking at the tissue image.

Anyway I think there is an option to not consider ROIs touching the border, so you can filter them automatically.

**Comment by DavidMHaumann** [comment]
Hi Erexhepa

thanks for your hint. I didnt know the simple tissue detection uses the color deconvolution vectors. I do not have a H-DAB image. I adapted the vectors via the stain estimator but it did not have an effect. 

The I tried all kind of combinations of requestend pixel sizes and Threshold. 
Indeed, it reduced the artefact in the corners - they did not dissapear, but became this small that i would not care. 
Transfer to other pictures failed because of different required thresholds. 

The exclue on boundary option would make my whole ROI disappear. It covers nearly the whole slide. 

Thus i gonna use a superpixel approach for the tissue detection on the glass slide. It will be slower, but more accurate. 

Thanks for your ideas!

**Comment by petebankhead** [comment]
From memory, *Simple tissue detection* doesn't do anything as sophisticated as color deconvolution - but it does take into consideration the 'Image type' (e.g. fluorescence/brightfield) to decide whether it is looking for something 'bright' and 'dark'.  After that it converts the image to grayscale, or takes the first channel (see #93 for a request to add support for another channel).

In many cases, *Simple tissue detection* is probably too simple.  But if the results look especially strange, the first thing I'd do is to turn off the *Smooth coordinates* option.  This basically takes the original shape, and then represents an approximation of it using fewer vertices.  Sometimes this approximation is not particularly good - especially if the tissue overlaps with the image border.  Turning off the option gets closer to the 'original' detection by thresholding.

**Comment by DavidMHaumann** [comment]
Hi Pete, 

indeed, it helped to unselect the Smoothing. Thank you!!
It is suboptimal because of dark artefacts on the slide, but still better than computing intensive Superpixel classification.

**Comment by erexhepa** [comment]
@DavidMHaumann Sorry I wasn't clear on the colour deconv subject. I was generally speaking on the color space, RGB, HSV, LUV but I was also thinking about standart HE and immunostains. Your case might be difficult. 

I was sure SimpleTissueDetection2 was not using ColourDeconv but after looking at #93 I know a bit more what is using. For me it is working fine but I'm working with very standard stains. 

However, I'm working also on some special stains where deconvolution is necessary and of added value, especially with regard to the cell-object segmentation that would follow. The link to ImageJ is very useful because you can send the region to ImageJ , deconvolve, normalize, analyse and return the objects ROI back to qupath interface for further visual inspection/analysis. There is a plugin on the embedded ImageJ installation with QuPath that allows the integration of regions from ImageJ to QuPath.
