### ISSUE TITLE
Slide label doesn't update as expected when changing the image

### ISSUE THREAD

**Issue by finglis** [qupath/qupath#1246]
## Bug report

**Describe the bug**
Changing the image while the slide label is open does not update the slide label to represent the open image. 

**To Reproduce**
1. Open an image and the slide label image
2. Change to another image
3. Note the original slide image remains and doesn't update

**Expected behavior**
Slide label image updates to the corresponding image open

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - QuPath Version: 0.4.3

**Additional context**

**Comment by petebankhead** [comment]
I can replicate this if I open the slide label under the 'Image' tab.

It turns out, the label **is** updated if it is shown via *View &rarr; Show slide label*.

I agree it's confusing to have different behavior, although I'm not sure what is the best way to fix it because both ways of showing the label have different aims:

* Under the 'Image' tab, the aim is to show all the associated images and be able to freely choose.
* With *View &rarr; Show slide label*, QuPath tries to determine which associated image corresponds to the slide label, and uses that

The second command is more complicated, because there's no guarantee that any image will have an associated label - and, if it does, there's no guarantee what precisely it will be called. Here's the awkward code that tries to figure that out:

https://github.com/qupath/qupath/blob/75ec9cebe5e3bc5843fc60b07b455ce1215e1fb9/qupath-gui-fx/src/main/java/qupath/lib/gui/panes/SlideLabelView.java#L130-L148

I'm not sure if either command can or should fully replace the other. Maybe it would be better if *View &rarr; Show slide label* was more prominent (e.g. somewhere under the 'Image' tab as well)?

**Comment by petebankhead** [comment]
Another option would be to give showing the associated images (i.e. under the 'Image' tab) the same kind of behavior as *View &rarr; Show slide label*.

The idea would be that, once you've picked an associated image name by double-clicking, the window remembers the name, e.g. 'macro'.

Whenever a new image is opened in QuPath, QuPath will check if the new image also has an associated image called 'macro'. 
* If yes, the new macro image replaces the old one
* If no, the old macro image is removed and the window that contained it becomes black (reporting 'No image' in the title bar)

I haven't given it a lot of thought, but I have a feeling that might be more logical - effectively meaning that choosing *View &rarr; Show slide label* and double-clicking on 'label' under the image tab share (more or less...) identical behavior.

What do you think?
