### ISSUE TITLE
.bif format from Ventana become pixelated after zooming using QuPath

### ISSUE THREAD

**Issue by viviiviiii** [qupath/qupath#1253]
I use QuPath for reading DP200 Ventan Slide Scanner, however after I zoom the image, it become pixelated.
May I know how to solve this issue? Thanks.

**Comment by MichaelSNelson** [comment]
Hi @viviiviiii, it would help if you could provide more information. Assuming this is a Ventana scanner, the file type could be .bif, .tif, or DICOM. Including the information in, or a screenshot of, the Image tab would help.

It sounds like you are only opening the thumbnail image, but it is not clear why.

**Comment by petebankhead** [comment]
Hi @viviiviiii 

As @MichaelSNelson says, more information would be needed to understand what the problem might be. I don't work with images from Ventana scanners myself.

@viviiviiii could you post your question at https://forum.image.sc/tag/qupath please?

Because this isn't really a bug report, and probably doesn't relate to a bug in QuPath, it doesn't really fit in this section so I'll close the issue.

If you post in the forum, more people are likely to see the post and may have more experience with your scanner. Also, be sure to check out https://qupath.readthedocs.io/en/0.4/docs/intro/formats.html - and please always state the version of QuPath you are using when asking a question like this. If you aren't using the latest version, upgrading might already solve the problem.
