### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by 464hee** [qupath/qupath#1256]
## Please do not post questions here - use [image.sc](https://forum.image.sc/tags/qupath) instead!

QuPath's 'Issues' section on GitHub is used by developers to manage bugs and priorities - please do **NOT** post general questions here about the software.

Rather, post any questions to the official QuPath forum at https://forum.image.sc/tags/qupath
![8C3E8E42-2000-4681-852D-902EFF6BE785](https://user-images.githubusercontent.com/100740023/228717976-7c882690-ed55-485f-99df-9c5988adbbfd.png)

Be sure also to check out the [documentation & tutorials](https://qupath.readthedocs.io/en/latest/docs/starting/index.html).
Does it support changing the default settings? I found that every time I open a new image, this setting will be reset to the default

**Comment by petebankhead** [comment]
Hi @464hee the default settings for this command can't currently be changed.

If you want to export a lot using specific settings, a script is generally much more convenient (e.g. [see here](https://qupath.readthedocs.io/en/0.4/docs/advanced/exporting_annotations.html#geojson)).

If you want to discuss more, please use the discussion forum at https://forum.image.sc/tags/qupath rather than GitHub - as the instructions at the top of the post request.
