### ISSUE TITLE
fail to build qupath with openjdk 20

### ISSUE THREAD

**Issue by hubutui** [qupath/qupath#1262]
## Bug report

**Describe the bug**
fail to build qupath with openjdk on ArchLinux.

**To Reproduce**
```bash
cd qupath-0.4.3
gradle clean jpackage -Porg.gradle.java.home=/usr/lib/jvm/default
```

**Expected behavior**
success to build qupath 0.4.3

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - QuPath Version: 0.4.3
 - java: jdk-openjdk 20.0.1.u9-3
 - gradle: 8.1.1

**Additional context**
logs:
```text
> Configure project :qupath-app
Unable to determine Java version from toolchain: No matching toolchains found for requested specification: {languageVersion=17, vendor=any, implementation=vendor-specific}.
Unable to determine Java version from toolchain: No matching toolchains found for requested specification: {languageVersion=17, vendor=any, implementation=vendor-specific}.

FAILURE: Build failed with an exception.

* Where:
Build file '/build/qupath/src/qupath-0.4.3/qupath-app/build.gradle' line: 540

* What went wrong:
A problem occurred configuring project ':qupath-app'.
> Failed to calculate the value of task ':qupath-app:compileJava' property 'javaCompiler'.
   > No matching toolchains found for requested specification: {languageVersion=17, vendor=any, implementation=vendor-specific}.
      > No locally installed toolchains match (see https://docs.gradle.org/8.1.1/userguide/toolchains.html#sec:auto_detection) and toolchain download repositories have not been configured (see https://docs.gradle.org/8.1.1/userguide/toolchains.html#sub:download_repositories).
```
It seems related to how we specify the toolchain, https://github.com/qupath/qupath/blob/1368912885c1a191beaea32c28d85a3707f657f8/qupath-app/build.gradle#L535-L548
Maybe, we could follow this: https://github.com/Project-MONAI/MONAILabel/blob/0332f42643015046055a3410b770d1e8a0e1bd57/plugins/qupath/build.gradle#L39-L51
Just add a project property `toolchain` with a default value, so user could specify it with `-Ptoolchain=20` or simply use the default one (eg. 17).

**Comment by petebankhead** [comment]
Hi @hubutui could you try building with `gradlew` (Gradle wrapper) instead? That's the 'proper' way to build QuPath - see https://qupath.readthedocs.io/en/stable/docs/reference/building.html

The part you link to in `build.gradle` isn't actually trying to specify the toolchain, but rather to recover the Java version for the toolchain that is already being used.

When it comes to *specifying* the toolchain, it looks like the example you give is just copied from the code I wrote here :)
https://github.com/qupath/qupath/blob/main/buildSrc/src/main/groovy/qupath.java-conventions.gradle#L11

That's what QuPath already uses, so you can already pass it a `-Ptoolchain=20` if you like.

**However** I think the problem is that QuPath's build is locked to Gradle 7.5.1 because of 
* https://github.com/bytedeco/gradle-javacpp/issues/28

There hasn't been another `gradle-javacpp` release yet, and I don't want to switch to a snapshot - so I'm waiting for that before updating our build scripts. Since Gradle releases break stuff pretty often, I suspect other changes will be needed. Also, older Gradles can't build using toolchains for newer Javas and Java 20 wasn't around when Gradle 7.5.1 was released - so you're probably stuck building QuPath v0.4.x on Java 17-19.

But using Gradle wrapper avoids most of those problems, as long as you use a compatible toolchain version.
