### ISSUE TITLE
"create detection classifier" function not found in QP version0.4

### ISSUE THREAD

**Issue by swZhang1** [qupath/qupath#1269]
Dear qupath author,
i met a problem in qp v0.4 software as below:
In youtube web ur vedio shows the function  "create detection classifier", 
<img width="579" alt="9489b4d45da04b74f3c20854bf2d9d4" src="https://github.com/qupath/qupath/assets/70978097/eb076397-4e1c-4581-9fec-3bbaf99cb945">
but i CANNOT find it in  my qu-path  V0.4.
![35e753143f4f4812de29d22fa32c218](https://github.com/qupath/qupath/assets/70978097/4f749806-deb0-4f68-a75b-9b0ee0325905)
 How can i fix it?

**Comment by melvingelbard** [comment]
Hi @swZhang1 ,
Usually it is better to use the [official QuPath](https://forum.image.sc/tag/qupath) forum for these types of questions :)
But to reply anyway, you need to have an image currently open to use an object classifier. It doesn't seem to be your case here.

**Comment by petebankhead** [comment]
Adding to @melvingelbard's answer (hi!), *Train object classifier* is the v0.4 alternative.

This is described in detail in the documentation at https://qupath.readthedocs.io/en/0.4/docs/tutorials/cell_classification.html

I'll close this issue because it isn't a bug - and https://forum.image.sc/tag/qupath is the place for questions and discussions.
