### ISSUE TITLE
Make SVG export include overlays, not just the original image

### ISSUE THREAD

**Issue by zindy** [qupath/qupath#1272]
## Feature request

**Is your feature request related to a problem? Please describe.**
At the moment, SVG exports [1] behave differently from their bitmap counterparts [2], in the sense that the bitmap exports include whichever overlays are currently displayed, but the SVG exports only include the original image.

[1] File -> Export images -> Rendered SVG and File -> Export snapshot -> Current viewer content (SVG)
[2] File -> Export images -> Rendered RGB (with overlays), File -> Export snapshot -> Main window content and File -> Export snapshot -> Current viewer content

**Describe the solution you'd like**
I would *both* types of exports to include overlays if the user so wishes.

See the discussion on https://forum.image.sc/t/export-snapshot-current-view-content-svg-does-not-include-the-density-map/82740

**Describe alternatives you've considered**
I have a two-step workaround in the meantime:
1. Export images -> Rendered SVG (Linked raster)
2. Hide the annotations and detections, then Export images -> Rendered RGB to overwrite the linked raster image, using PNG and the same downsample as used in step 1.

**Additional context**
SVG is a great format. The files can be edited in [Inkscape](https://inkscape.org/) and also be used as-is in (recent versions of) Microsoft Office Word and Powerpoint. And they look great when printed, which is why I think it's important for QuPath to have the best possible SVG export functions.

**Comment by MichaelSNelson** [comment]
I would like to second this, and add some references that QUAREP-LiMi is pushing for! Make good quality exports easy for users, and we can hope/expect better quality figures in publications:
https://arxiv.org/abs/2302.07005
Work in progress video from @biovoxxel https://my.hidrive.com/lnk/Mfimluif#file where the latter parts discuss creation of SVG image overlays and their advantages in publication.

**Comment by biovoxxel** [comment]
I have to add that this is the first and inofficial version of the video but hope it helps. The location might soon change and I will post it here. I am also happy to help in case the QuPath team has some questions on the implementation. To have comparable and interchangeable SVGs at the end I would plea for embedding the images as a base64 png in the SVG.
Here is the ImageJ implementation: https://github.com/biovoxxel/BioVoxxel-Figure-Tools

**Comment by petebankhead** [comment]
Thanks, I've merged some changes into the `dev` branch for v0.5.0.

Basically, SVG export will now add the active overlay layers. It does this using either a vector representation (e.g. for objects or gridlines) or separate images with opacity set according to the overlay display. This means that individual layers should remain editable later.

Example SVG below.

![Cells as SVG](https://github.com/qupath/qupath/assets/4690904/518b341c-1c2a-4d95-a70a-115809fe1167)

The big limitation is that scalebars etc. aren't included, because these aren't rendered as overlay layers in QuPath - they are separate JavaFX controls sitting on top of the main viewer, which can't easily be converted to SVG using our current approach. We're giving some thought to adding a figure-creating UI in the future that would support scalebars etc. with more customizations, but that doesn't currently exist.

PS. @biovoxxel video looks great! QuPath already supported base64 embedding, but now it's the default option (linked & no base image are also supported).

**Comment by biovoxxel** [comment]
@petebankhead,

An idea out of ignorance, would it be easily feasible to just create the scale bar as annotation during the exportation process. So, basically, it would just be a filled rectangle and some text. This way it might export as annotation together with the other ones and you do not mess around in the JavaFX part or add new functionalities. 
I don't know if that makes sense or would work, but it would be a potentially quick solution.

**Comment by petebankhead** [comment]
It could be done, but it would be fiddly to try to get the location of the bar and font size to exactly match what is displayed in QuPath's viewer (since this adapts dynamically based upon the zoom level and background color). And if it doesn't match what's in the viewer anyway, then I think a proper UI component that allows the user to specify the location, size, color etc. of the scalebar would be more useful.

The overview image (top right) and pixel coordinate & value control (bottom right) have the same issues - a proper viewer 'snapshot' should really include all of them, if they are present, so the task starts to grow bigger.

I'll think about it some more, but I currently think the only workarounds would involve duplicating code from existing JavaFX components and rewriting them in a Java2D-friendly way just for SVG export, which sounds be a bit painful to maintain. Since QuPath's minimally-customizable, auto-adjusting scalebar isn't exactly what everyone wants for creating figures anyway, I like the idea of designing something more specific for the task.

**Comment by zindy** [comment]
> but it would be fiddly to try to get the location of the bar and font size to exactly match what is displayed in QuPath's viewer

I don't think this is strictly necessary because in the viewer, the scalebar tries to be unobtrusive, but as part of a figure, I think it would look too small (or that was the case for the figure I was trying to make). So yes, which corner, which physical length / thickness, length displayed (above/below) should ideally all be user defined (IMHO).  Maybe an "export preview" window would help?

And as in @biovoxxel's video (thanks for the resource!), our users sometimes struggle with the "DPI/PPI" calculations. If this was a set parameter in preferences (e.g. 300PPI by default), then you could write next to downsample what would be the maximum figure size for that PPI (e.g. downsample 2, 300PPI -> up to 1200cm x 800cm figure).

The user would then be able to choose an appropriate downsample for their figure that's say, up to 20cm wide at the requested PPI.

Anyway anyway, I'll compile a v0.5 and check out the new additions. Thank you very much for taking the time to implement this @petebankhead !

**Comment by biovoxxel** [comment]
> And as in @biovoxxel's video (thanks for the resource!), our users sometimes struggle with the "DPI/PPI" calculations. If this was a set parameter in preferences (e.g. 300PPI by default), then you could write next to downsample what would be the maximum figure size for that PPI (e.g. downsample 2, 300PPI -> up to 1200cm x 800cm figure).
> 
> The user would then be able to choose an appropriate downsample for their figure that's say, up to 20cm wide at the requested PPI.

Side note:
I would fully avoid scaling and adapting to DPI, since this is not very helpful regarding the figure quality. Once you have the SVG you can adapt it to the document size without the need of changing any resolution etc. Boils down to: Less need for thinking and calculating with a better result image!

**Comment by zindy** [comment]
Hey @biovoxxel 

> I would fully avoid scaling and adapting to DPI, since this is not very helpful regarding the figure quality.

Problem is, the original images in QuPath are whole slide images, and rather large. [OS-2.ndpi for example](https://cytomine.com/collection/os-2/os-2-ndpi) is 126976 pixels wide.

So first thing QuPath asks when doing an SVG export (with the image + overlay as background) is what downsampling factor should be applied to the original image. It's a necessary step, but what is not clear, is which factor would actually match some publication guidelines (for example, 300PPI + width of 170 mm for full page width figure [as defined here](https://cancerandmetabolism.biomedcentral.com/submission-guidelines/preparing-your-manuscript)).

> Once you have the SVG you can adapt it to the document size without the need of changing any resolution etc

I agree with you, but the background bitmap embedded in the SVG document only needs to be as big as the physical size it will be printed at. Some reviews also impose a maximum file size for the SVG documents (e.g. < 20MB), so we can't just use a downsample of 1 or 2 and hope for the best.

Then yes, anything vectoriel on top of the background image (lines, polygons, text...) just needs to be readable at the printed size and could easily be modified in Inkscape if not (fond size, linewidths...).

Maybe I'm missing something (wouldn't be the first time), so let me know how you see this work.

Cheers,
Egor

**Comment by biovoxxel** [comment]
Ok, I see. For such big images, I would agree that you have to down sample. I would try to stick to a factor divisible by two.
If you want to stick to the 300 PPI to theoretically have a pixel per printed dot (which is plain theory because dependent on printing device and final printing size) you could calculate it as follows (please check it again not that I made a mistake):

17cm = 17cm / 2.54 cm/inch ~6.7 inches
At 300 PPI you would need an image width of 300 * 6.7 = 2,010 pixels minimally.

Principally, you could divide your real original image width by this ~2010 pixels and you have the approximate down sampling factor. I would then use the closest factor, smaller than that to give it slightly more PPI.
So, if you have an original image width of 120,000 pixel, that would be an approximate factor of 120,000 / 2,000 = 60.

**Comment by aliys97** [comment]
is there a solution for batch processing with qupath script?
below code partly work and export the original picture with detected cells overlay but it does not export the created density map overlay (which is showing in the content view).

**Comment by petebankhead** [comment]
@aliys97 I've hidden this comment as it is really a question about using QuPath and the forum is a better place to discuss that. Also, it looks like you have already posted about it [on the forum here](https://forum.image.sc/t/batch-processing-create-and-save-density-map/82135/7) and I'd like to avoid having two parallel discussions.

**Comment by petebankhead** [comment]
I'll close this issue as part of my Saturday repo-cleaning, since support for overlays in SVG exports has now been merged and will be available in the next release (v0.5.0).
