### ISSUE TITLE
Absolute coordinates in IO

### ISSUE THREAD

**Issue by Aiosa** [qupath/qupath#1278]
## Feature request

**Is your feature request related to a problem? Please describe.**
OpenSlide supports `bounds` which are [used to crop the image](https://forum.image.sc/t/roi-annotation-to-openslide-coordinates/44475/3). Annotation exports (and possibly other exports) then have basically invalid coordinates to the image data, unless one's using OpenSlide's bounds. 

**Describe the solution you'd like**
Exports should be wrt. the original image dimensions, so that other SW can work with the data without OpenSlide dependency.
Export should by default use absolute coordinates, and offer relative ones only as an option. Or, the offset information should be exported along with annotations.

**Describe alternatives you've considered**
Manual management of metadata for each slide. Clumsy, chaotic and inflexible.

**Additional context**
IMHO this is more a bug report than a feature request. We are dependent on some software (or worse, its version) to be able to work with the data. Any change to the OpenSlide, the library, failure to derive these coordinates etc. breaks everything.

**Comment by petebankhead** [comment]
When importing images to a QuPath project, there is a space to input arguments. Inserting `--no-crop` there will avoid using the OpenSlide bounds.

I don't consider this to be a bug, because other software *already* handles the bounds differently. For example, I remember that QuPath started cropping by default because failing to do so gave different image dimensions when using Bio-Formats and OpenSlide. Cropping actually improved consistency, and removed enormous amounts of unnecessary whitespace. The original commit is at https://github.com/qupath/qupath/commit/52c9c32fa2add760d1338b1b81b2c0c6eed8908b

I think it would be more problematic and inconsistent if QuPath started exporting coordinates with a different origin for some images from that seen in the viewer, and then if there was a wish to import the regions in a project where Bio-Formats (rather than OpenSlide) was the default then it wouldn't be easy to identify or fix the problem.

> Exports should be wrt. the original image dimensions, so that other SW can work with the data without OpenSlide dependency.

That doesn't work for the reasons given above (i.e. at least one other very popular image-reading library will 'crop' at least some relevant formats automatically anyway). I'm curious as to what other software this causes an issue with that doesn't use OpenSlide.

> Or, the offset information should be exported along with annotations.

May be preferable, but would be awkward because the annotation export aims to follow the GeoJSON spec. Potentially all objects would need to store that info, or else they would need to be export as a `FeatureCollection` with an additional custom property. The second sounds preferably, but would remain very QuPath-specific.

**Comment by petebankhead** [comment]
See also https://github.com/openslide/openslide/issues/353 and the quote

> You can get the bounding box of the actual pixel data from the `openslide.bounds-{x,y,width,height}` properties. This is what the VIPS `autocrop` option uses to trim the slide to the available pixels.

While OpenSlide's approach is internally consistent and may be justifiable, it doesn't seem to me that it is more 'correct' than using the 'bounding box of the actual pixel data'... and failing to crop by default to the actual pixel data seems at least as likely to make the problem you describe *worse* rather than better:

> Any change to the OpenSlide, the library, failure to derive these coordinates etc. breaks everything.

As it currently stands, I think QuPath is more internally consistent by cropping - and this reduces rather than increases the dependency on OpenSlide, by making its use interchangeable with Bio-Formats. If there are cases where QuPath crops* and Bio-Formats or other popular libraries don't, then we might need to look at it again, but I don't know of any.

*-From the description above, it sounds more like QuPath/Bio-Formats *don't pad* than that they crop...

**Comment by Aiosa** [comment]
> When importing images to a QuPath project, there is a space to input arguments. Inserting --no-crop there will avoid using the OpenSlide bounds.

Thanks, very helpful.

> Potentially all objects would need to store that info, or else they would need to be export as a FeatureCollection with an additional custom property. The second sounds preferably but would remain very QuPath-specific.

Already `properties` values are very QuPath specific (`isEllipse`...), so I don't see much of a problem here.

> As it currently stands, I think QuPath is more internally consistent by cropping - and this reduces rather than increases the dependency on OpenSlide, by making its use interchangeable with Bio-Formats. If there are cases where QuPath crops* and Bio-Formats or other popular libraries don't, then we might need to look at it again, but I don't know of any.

I did not know about the Bio-Formats approach. Since DICOM is slowly opening up to the open-source WSI world, I think the problem will arise sooner or later. For now, for performance reasons, we go with TIFF files that do not have this metadata stored, and all software (including quPath) fails to read cropped data, thus having inconsistencies everywhere. Thanks for the insight.

**Comment by petebankhead** [comment]
> For now, for performance reasons, we go with TIFF files that do not have this metadata stored, and all software (including quPath) fails to read cropped data, thus having inconsistencies everywhere. 

I don't understand the issue here, but it sounds like the problem is outside of QuPath, right?

If you are writing the TIFFs in your own software, then the use of [ome-tiff](https://www.openmicroscopy.org/2018/11/29/ometiffpyramid.html) might be one way to improve consistency (but then I'm not sure if it's supported by OpenSlide...).

**Comment by Aiosa** [comment]
> I don't understand the issue here, but it sounds like the problem is outside of QuPath, right?

If I use QuPath on some image data, then transform the data in some way that preserves the dimensions, I expect the behavior consistent, which is not the case in QuPath. To my knowledge, there is also software (image servers such as IIPImage) that do not have these cropping capabilities (or they do, but not implicit from the given file). 

I do understand the reasoning, I just don't agree that some popular libraries decided on IMHO wrong design choices; following them is necessarily a good choice. I would prefer explicit export options for given platforms instead of silent default, unintuitive behavior. 

>I think it would be more problematic and inconsistent if QuPath started exporting coordinates with a different origin for some images from that seen in the viewer 

People do not care what coordinates are as long as they align. For a developer, this is very confusing since if you get data of some dimensions, you expect the data to start at [0,0]. I guess all the people working with Python have to adjust all the coordinates all the time, too, manually. There are use cases where realizing this too late can hurt a lot (large WSI databases).

So, at least the offset information in `FeatureCollection` would be much appreciated.

**Comment by petebankhead** [comment]
> > I don't understand the issue here, but it sounds like the problem is outside of QuPath, right?
> 
> If I use QuPath on some image data, then transform the data in some way that preserves the dimensions, I expect the behavior consistent, which is not the case in QuPath. To my knowledge, there is also software (image servers such as IIPImage) that do not have these cropping capabilities (or they do, but not implicit from the given file).

I still don't understand what you're talking about. I can't tell specifically what you've done or what you say is inconsistent.

I'm also not sure if you're referencing any specific problem you know of when working with IIPImage, or if this is only speculative.

> I guess all the people working with Python have to adjust all the coordinates all the time, too, manually. There are use cases where realizing this too late can hurt a lot (large WSI databases).

Again, this is too abstract for me to follow. Is your assumption that 'all the people working with Python' are also working with OpenSlide, and ignoring bounds? Or do you have any specific examples where *other* popular libraries definitely provide pixels using the same coordinate system as OpenSlide, without using OpenSlide themselves?

> So, at least the offset information in `FeatureCollection` would be much appreciated.

I'll give it some more thought, but I'm still lacking specific use cases that would justify a change in the core software. It would already be easy to write a QuPath script to export in some other way, with whatever extra metadata is desired.

**Comment by Aiosa** [comment]
I'd like to give generic examples of how others might (and will, IMHO) find this problematic in the future. Let's get more specific then:

My use cases include QuPath exports that do not align with the true image dimensions. The IIPImage server does not auto-crop images or read these bounds from server files. My files do not even store this data. ML researchers work with libraries (TF, pytorch...), and they might rely on OpenSlide/BioFormats to read the data, they might as well be unaware of behind the scenes and be surprised later. We are writing ML pipeline data loaders for OME-TIFF and DICOM that use, for example, [wsidicom](https://github.com/imi-bigpicture/wsidicom).

>I'll give it some more thought

Thank you.

**Comment by petebankhead** [comment]
Hmmm, I still fail to see any evidence of a QuPath bug here. Your reference to 'the true image dimensions' is hard to interpret since I don't know where you're getting the 'true' dimensions from, or what is the source of your files.

Without actual specifics (e.g. an example file), I don't see why you should assume the 'bug' is in QuPath and not elsewhere. OpenSlide only sets the bounds for a subset of file formats, so most shouldn't be affected anyway. I've only seen it for scn and mrxs, which are the two formats mentioned in the commit that makes the bounds available: https://github.com/openslide/openslide/commit/421cb647acdc8fe35e33c2683949f5098925c8ac

Note my comment above about 'cropping' being arguably the same as 'not padding'... one could argue that QuPath simply removes the padding that OpenSlide has added, because [the bounds define where there is pixel data](https://github.com/openslide/openslide/issues/424#issuecomment-1382416341). QuPath aims to read the pixels from an image consistently, regardless of whether OpenSlide is used or not.

As a specific example from my side, see the image `Leica-1.scn` from the OpenSlide freely-distributable data:
https://openslide.cs.cmu.edu/download/openslide-testdata/Leica/

Screenshots below show the image with a full image annotation within QuPath.

## Bio-Formats
<img width="939" alt="SCN-Bio-Formats" src="https://github.com/qupath/qupath/assets/4690904/039b2449-5c20-4b93-a4af-d65928324a50">

## OpenSlide (default, cropped to bounds)
<img width="941" alt="SCN-OpenSlide" src="https://github.com/qupath/qupath/assets/4690904/771af2d0-2dcb-44ee-95e6-31ff62f0f7e2">

## OpenSlide (with `--no-crop` arg)
<img width="941" alt="SCN-OpenSlide-no-crop" src="https://github.com/qupath/qupath/assets/4690904/3cf52a48-ca91-4dff-8eb4-7e299d851b3e">

The size is identical when read using QuPath v0.4.3 when using either OpenSlide or Bio-Formats by default (no extra arguments passed to either).

Explicitly passing the `--no-crop` arg causes QuPath to ignore what OpenSlide considers to be bounds, and generate a much larger image with extreme padding that causes both much higher memory use and can thwart processing tasks like thresholding or pixel classification.

What's more, if I call `tiffinfo `Leica-1.scn` I see
```
=== TIFF directory 3 ===
TIFF Directory at offset 0xfe4f444 (266662980)
  Image Width: 36832 Image Length: 38432
  Tile Width: 512 Tile Length: 512
  Resolution: 20000, 20000 pixels/cm
  Bits/Sample: 8
  Compression Scheme: JPEG
  Photometric Interpretation: YCbCr
  YCbCr Subsampling: 2, 2
  Samples/Pixel: 3
  Planar Configuration: single image plane
  Reference Black/White:
     0:     0   255
     1:   128   255
     2:   128   255
```
and also
```xml
<?xml version="1.0"?>
<scn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" uuid="urn:uuid:2b930baa-4b05-4936-a937-ccf5a0b3276d" xmlns="http://www.leica-microsystems.com/scn/2010/10/01">
  <collection name="ImageCollection_0000000128" uuid="urn:uuid:d0fa25ee-baa8-48cd-944d-5598a36b3f7b" sizeX="26564529" sizeY="76734666">
    <barcode>MDQwNTA2MjlD</barcode>
    <image name="image_0000001819" uuid="urn:uuid:4a9c1d8d-1f66-4df6-98e7-9d3efe746932">
      <creationDate>2011-05-31T09:33:14.31Z</creationDate>
      <device model="Leica SCN400;Leica SCN" version="1.4.0.9691 2011/03/30 10:30:59;1.4.0.9708" />
      <pixels sizeX="1616" sizeY="4668">
        <dimension sizeX="1616" sizeY="4668" r="0" ifd="0" />
        <dimension sizeX="404" sizeY="1167" r="1" ifd="1" />
        <dimension sizeX="101" sizeY="291" r="2" ifd="2" />
      </pixels>
      <view sizeX="26564529" sizeY="76734666" offsetX="0" offsetY="0" spacingZ="0" />
      <scanSettings>
        <objectiveSettings>
          <objective>0.60833</objective>
        </objectiveSettings>
        <illuminationSettings>
          <numericalAperture>0.7</numericalAperture>
          <illuminationSource>brightfield</illuminationSource>
        </illuminationSettings>
      </scanSettings>
    </image>
    <image name="image_0000001834" uuid="urn:uuid:5349587f-b351-4049-ad76-67229b3a0bf1">
      <creationDate>2011-05-31T09:43:06.873Z</creationDate>
      <device model="Leica SCN400;Leica SCN" version="1.4.0.9691 2011/03/30 10:30:59;1.4.0.9708" />
      <pixels sizeX="36832" sizeY="38432">
        <dimension sizeX="36832" sizeY="38432" r="0" ifd="3" />
        <dimension sizeX="9208" sizeY="9608" r="1" ifd="4" />
        <dimension sizeX="2302" sizeY="2402" r="2" ifd="5" />
        <dimension sizeX="576" sizeY="600" r="3" ifd="6" />
        <dimension sizeX="144" sizeY="150" r="4" ifd="7" />
      </pixels>
      <view sizeX="18416000" sizeY="19216000" offsetX="5389341" offsetY="17548313" spacingZ="400" />
      <scanSettings>
        <objectiveSettings>
          <objective>20</objective>
        </objectiveSettings>
        <illuminationSettings>
          <numericalAperture>0.4</numericalAperture>
          <illuminationSource>brightfield</illuminationSource>
        </illuminationSettings>
      </scanSettings>
    </image>
  </collection>
</scn>
```

Note that the image size is reported as 38432 x 36832, which is what QuPath gives by default (but not when using OpenSlide + `--no-crop`).

Finally, if I use `tifffile` in Python
```python
from tifffile import TiffFile
with TiffFile('/Users/petebankhead/Desktop/mrxs/Leica-1.scn') as tif:
    for p in tif.pages:
        print(p)
```
the output is
```
TiffPage 0 @291809396  4668x1616x3  uint8  ycbcr tiled jpeg  scn
TiffPage 1 @1383258  1167x404x3  uint8  ycbcr tiled jpeg
TiffPage 2 @1400444  291x101x3  uint8  ycbcr tiled jpeg
TiffPage 3 @266662980  38432x36832x3  uint8  ycbcr tiled jpeg
TiffPage 4 @290139490  9608x9208x3  uint8  ycbcr tiled jpeg
TiffPage 5 @291674862  2402x2302x3  uint8  ycbcr tiled jpeg
TiffPage 6 @291793778  600x576x3  uint8  ycbcr tiled jpeg
TiffPage 7 @291809012  150x144x3  uint8  ycbcr tiled jpeg
```

Note that again the largest image is 38432 x 36832.

Therefore I still believe that QuPath is doing the most sensible and consistent thing under these circumstances, and you should really revise the assumption that 'QuPath is cropping' to 'QuPath isn't padding'. At least in this case, QuPath, Bio-Formats, tiffinfo and tifffile are all in agreement about the size of the image. Are there any examples where this isn't the case?

**Comment by petebankhead** [comment]
Last bit... Aperio ImageScope (the free viewer from the company behind .scn) also reports the image to be 38432 x 36832. I think that's pretty conclusive...

From the screenshots and `tiffinfo`, it seems that OpenSlide's default image size is based upon 
```xml
<view sizeX="18416000" sizeY="19216000" offsetX="5389341" offsetY="17548313" spacingZ="400" />
```
where the size of the 'view' is defined in nm. This may be useful in some cases, e.g. trying to align with the macro image in the file, but I think it's more natural to consider the 'true' image size based upon
```xml
<pixels sizeX="36832" sizeY="38432">
```
which is what QuPath does since v0.2.0. In my opinion, the main issues are
* whole slide formats aren't very standardized, so there is plenty of room for ambiguity
* too many people ignore the bounds that OpenSlide provides... and if this involves converting the image or generating objects, then the information is lost.

Either way, if QuPath stopped applying the OpenSlide bounds then I believe the result would be far more confusion and inconsistency... and the challenge is rather to get others to recognize that the bounds are important and should be considered when using OpenSlide, at least if the user expects interoperability elsewhere.

**Comment by Aiosa** [comment]
Yes, I have `mirax` file that has dimensions of   105185 X 221772 pixels. By 'true dimensions' I mean the dimensions stored in the raw file. Converted to a tiff image I get:

tiffinfo:
````
TIFF Directory at offset 0x27e43676 (669267574)
  Image Width: 105185 Image Length: 221772
  Tile Width: 512 Tile Length: 512
  Resolution: 10, 10 pixels/cm
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: JPEG
  Photometric Interpretation: YCbCr
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 3
  Planar Configuration: single image plane
  Reference Black/White:
     0:     0   255
     1:   128   255
     2:   128   255
  JPEG Tables: (574 bytes)
...
````

Opening in QuPath (crop), QuPath (no crop), Web Viewer (IIPImage):
![image](https://github.com/qupath/qupath/assets/34658867/132bd3f6-ed24-41fd-8f43-f9be5bc497b4)

Full image annotation rectangle from QuPath (crop):
```{"type":"FeatureCollection","features":[{"type":"Feature","id":"e23c4b41-3966-4e64-af97-665f7edf753d","geometry":{"type":"Polygon","coordinates":[[[0, 0],[76832, 0],[76832, 190655],[0, 190655],[0, 0]]]},"properties":{"objectType":"annotation"}}]}```

**Comment by petebankhead** [comment]
I understand the problem, but it seems to have occurred at the stage the tiff was created because the bounds were ignored. QuPath wasn't involved in that.

Alternatively, if you consistently use the tiff in both QuPath and IIIPImage then it should be fine - neither QuPath nor IIIPImage will crop the tiff.

As I understand it, the issue only occurs if you try to match an unpadded mrxs image with a padded tiff image.

As shown in the scn example, it would be very bad for QuPath to ignore the crop bounds. Because mrxs isn't tiff-based (and seems to be a particularly awkward proprietary format), it's harder to find other sources to resolve what exactly the bounds mean, but in the scn case it's very clear that the most sensible and consistent behavior is to apply OpenSlide's bounds... which is why it's QuPath's default for all OpenSlide images.

**Comment by petebankhead** [comment]
> By 'true dimensions' I mean the pixel dimensions stored in the raw file

I'm curious where you get these from, because I can't find them in the `.ini` file associated with .mrxs.

`tiffinfo` isn't really relevant here, since it can only get from a tiff what was written there during the conversion process... and if OpenSlide was used to help convert the file without cropping, then the tiff dimensions will inevitably agree. `tiffinfo` is meaningful for .scn because the original format itself is tiff-based, so no conversion is needed. As shown in that example, it's possible that the true dimensions stored in the original file are the ones you get *after* cropping with OpenSlide's bounds, not before.

I can't check the dimensions of any .mrxs image with other software as I don't have any viewer for mrxs files that isn't using OpenSlide (and ImageScope failed to open it). There is supposedly a free viewer from the company behind the .mrxs format, but it requires too much personal info to install so I don't want to use it.

There are some [links here](https://qupath.readthedocs.io/en/0.4/docs/intro/formats.html#mrxs-3d-histech) that may help give some idea what it's not exactly my favorite file format for whole slide scans.

I have seen examples of mrxs images where failing to crop results in very excessive padding (and the associated computational problems), so I still thing cropping / avoiding padding is the more appropriate choice for QuPath to make as a default... and the .scn example demonstrates that it's the right choice there.

In conclusion, it sounds like:
* QuPath isn't doing anything weird or buggy - it's behaving as it should here
* You can use QuPath with your pyramidal tiffs, no matter how they are generated (as long as they can be opened by either OpenSlide and Bio-Formats)
* You can use QuPath with the mrxs images used to generate tiffs if you do **one** of the following
   * generate the tiffs to give the cropped/unpadded region, e.g.
        * using [`libvips` and `autocrop`](https://github.com/openslide/openslide/wiki/OpenSlideAndVIPS#slide-bounds)
        * using QuPath itself (to write an ome-tiff)
   * import into QuPath with the `--no-crop` option
   * correct the coordinates as required when switching between software depending upon whether it adds padding or not
* You *may* be able to use QuPath with other software as long as it doesn't use OpenSlide to read the .mrxs files... but this is untested since very little software seems to support .mrxs directly, and the format is so complex that it doesn't seem at all clear what the 'true' size of an .mrxs file is

Finally (again), OpenSlide Python itself supports conversion to .dzi, which has a [`limit_bounds` option](https://openslide.org/api/python/).

All in all, I don't think QuPath is the thing that's making this complicated... it's just unfortunately complicated because of the use of proprietary formats at a lack of standardization around how exactly they *should* be handled.

**Comment by Aiosa** [comment]
Thank you.

Of course I could not get these dimensions directly from the mirax file either (easily), but since the tiff file was generated 'as-is' from mirax, and since I know how these glass slides look like physically, the 'padded' version is 1:1 to the glass, so naturally what QuPath shows me is not something I consider the whole slide, thus cropped.

I did consider these workarounds, but most of them include some effort from the pathologist's side - probably a no go. Re-generating the whole database of 5+years of data is something I would like to avoid. Thanks for the exhaustive list and your effort.
