### ISSUE TITLE
PositiveCellDetection and Classifier fails

### ISSUE THREAD

**Issue by iamsirhc** [qupath/qupath#130]
I am running a simple script to detect positive cells for DAB using a classifier.
Usually it works, but randomly (often for larger files) it suddenly stops classifying halfway through, and all of the workflow tiles change from red/yellow (in progress/completed) to blue.  I wonder if this is due to memory issues, or is there another bug that I can work around?
Thanks!
Chris

script: 
setImageType('BRIGHTFIELD_H_DAB');
clearDetections();
resetSelection();
selectAnnotations();
setColorDeconvolutionStains('{"Name" : "H-DAB default", "Stain 1" : "Hematoxylin", "Values 1" : "0.65111 0.70119 0.29049 ", "Stain 2" : "DAB", "Values 2" : "0.26917 0.56824 0.77759 ", "Background" : " 255 255 255 "}');
runPlugin('qupath.imagej.detect.nuclei.PositiveCellDetection', '{"detectionImageBrightfield": "Hematoxylin OD",  "backgroundRadius": 40.0,  "medianRadius": 0.0,  "sigma": 3.0,  "minArea": 10.0,  "maxArea": 400.0,  "threshold": 0.1,  "maxBackground": 2.0,  "watershedPostProcess": true,  "excludeDAB": false,  "cellExpansion": 10.0,  "includeNuclei": true,  "smoothBoundaries": true,  "makeMeasurements": true,  "thresholdCompartment": "Cytoplasm: DAB OD max",  "thresholdPositive1": 0.3,  "thresholdPositive2": 0.4,  "thresholdPositive3": 0.5,  "singleThreshold": false}');
runClassifier('E:\\qupath projects\\prongf_cancer_project\\classifiers\\ptc_3.qpclassifier');

**Comment by Svidro** [comment]
Does the View->Show log give you any information when this happens?  

I am not sure in your case, but if you are running the full script I wonder if it isn't the cell detection rather than the classifier that is erroring out.  I don't believe the classifier runs in tiles, it should apply to the entire image at once, and only after the cell detection part of the script is completed.  Memory might be an issue there, though there used to be some possible edge cases with very small tiles (where the tile clips the edge of the tissue and a very tiny region is generated) causing problems.  I usually was able to get around that by changing the Simple Tissue detection settings, as it was incredibly rare.  The logs should help determine what is happening.

You said randomly, so this means you can't reproduce it on any single slide running it twice?  Are the images QuPath is accessing stored across a potentially busy or slow network?

As an aside, you are running both a classifier in the cell detection (Positive cell detection with three thresholds), and again with a trained classifier?

**Comment by petebankhead** [comment]
It sounds like a memory issue to me too, although I'm not certain.  Hopefully the log can help.

I plan to write a better script to help explore memory issues soon, but in the meantime you could try this very basic one:
```groovy
// Print the current memory situation
def runtime = Runtime.getRuntime()
double scale = 1.0/1024.0/1024.0
print 'Max memory (MB): ' + (runtime.maxMemory() * scale)
print 'Total memory (MB): ' + (runtime.totalMemory() * scale)
print 'Used memory (MB): ' + ((runtime.totalMemory() - runtime.freeMemory()) * scale)

// Try to reclaim whatever memory we can, including emptying the tile cache
javafx.application.Platform.runLater {
    getCurrentViewer().getImageRegionStore().cache.clear()
    System.gc()
}
```

The top bit gives some numbers on current memory usage.  Roughly, the 'max' is what QuPath/Java is allowed to use, the 'total' is what it is currently claiming the right to access (which might change over time, potentially increasing towards the 'max' as required),  and the 'used' value is what is currently needed.

The second bit of the script then tries to bring down the 'used' value by clearing out the cache of image tiles and reclaiming whatever memory if can.  So if you run the script twice in a row, the 'used' memory value should generally be lower the second time, assuming you had previously been browsing around the image (and therefore filling up the tile cache).

Running this script before running the cell detection might increase the chances of it ending successfully.  If it still sometimes fails, but it looks like a memory problem, then either increasing the memory limit or decreasing the number of parallel threads could help - see https://github.com/qupath/qupath/wiki/Troubleshooting for more info.

**Comment by iamsirhc** [comment]
Hi Pete,
I really appreciate your fast reply and your support.
As a non-code-speaking researcher I have found qupath relatively easy to navigate, although there is a degree of trial-and-error involved.
I have implemented your suggestions and it seems to have got around the problem.  My main issue is that I need more memory on my computer for the processing that I am doing (4GB RAM is not enough).
Thanks again,
Chris

**Comment by petebankhead** [comment]
The better script to help track memory issues is now [here](https://gist.github.com/petebankhead/fa0d43213fb6e30c73700f0cc5e7d7ec).

It includes a chart to show how the memory use varies over time, and some buttons to influence it.  More details are in the comments at the top of the script itself.

![qupath_memory_monitor_small](https://user-images.githubusercontent.com/4690904/35185662-f3723046-fdff-11e7-8f59-bad685728be6.jpg)
