### ISSUE TITLE
How to specify ROI size by pixel, e.g. 256x256?

### ISSUE THREAD

**Issue by yil8** [qupath/qupath#137]
Hi there,

First, thanks so much for developing such great tool! I'm wondering if there is anyway I can directly specify the size of a rectangle in terms of pixels, e.g. 256x256? Preferably, I can specify the pixel size of currently focused region denoted by the red box on the top right overview. It is also great if I can specify the pixel size of a ROI annotation in a shape of rectangle. The reason I'm asking this is because I'm developing deep learning tools to analyze WSI, and most deep learning algorithms currently only work with small patches, e.g 256x256 on level 0 WSI. I want to see to how large these patches look like and how much area they occupy in the context of the full WSI.

Thanks

**Comment by petebankhead** [comment]
You can use *Objects &rarr; Specify annotation* to create an annotation of a certain size, although it's a bit hard to decide suitable x, y coordinates to use.  You either need to know the coordinate of the top left of the bounding box, or set the x, y coordinates < 0 and the annotation will be added at the middle.

However the following script adds a new annotation in the center of the current field of view:
```groovy
import qupath.lib.roi.RectangleROI
import qupath.lib.objects.PathAnnotationObject

// Size in pixels at the base resolution
int size = 256

// Get center pixel
def viewer = getCurrentViewer()
int cx = viewer.getCenterPixelX()
int cy = viewer.getCenterPixelY()

// Create & add annotation
def roi = new RectangleROI(cx-size/2, cy-size/2, size, size)
def annotation = new PathAnnotationObject(roi)
addObject(annotation)
```

There are various other changes you could make... for example, you might want to identify the annotations you create this way by assigning them a classification with a certain color.  Inserting these lines would do that:
```groovy
def rgb = getColorRGB(50, 50, 200)
def pathClass = getPathClass('My region', rgb)
def annotation = new PathAnnotationObject(roi, pathClass)
```

If you want to generate and compare multiple such annotations, you could run the script multiple times or alternatively duplicate each annotation with *Shift + D* and position the new one accordingly.  Another script could extract the regions and write them to separate files if needed.

**Comment by Svidro** [comment]
I am actually just getting into this from the other side, learning how to set up a deep learning model to take in images generated by QuPath.  Part of the question is what kinds of images do you want to send out, and do you want to classify them ahead of time?  For example, I am probably going to be looking at cells, so I intend to export the cell object (in this case each cell is "polygon" as an image:
```
 img = server.readBufferedImage(RegionRequest.createInstance(path, downsample, polygon.getROI()))

    ImageIO.write(img, 'PNG', new File(dirOutput, name + '.png'))
```
although I will need to edit the write name to both increment so that it does not overwrite, edit the name so it includes the class (for anything in the training set), and edit the "polygon.getROI()" so that it is the correct size. 

Also, once you have your 256 by 256 tile size in micrometers (multiply out by the pixel width in the Image tab), you can also use the _Analyze-> Region identification-> Tiles and superpixels -> Create tiles_ to see what a grid export could look like for your Simple tissue detection annotation.

And Pete beat me to it anyway!  So I won't include my much more terrible box drawing script!

**Comment by yil8** [comment]
Objects → Specify annotation works well. Thanks!
