### ISSUE TITLE
Multi-viewer Scrolling

### ISSUE THREAD

**Issue by finglis** [qupath/qupath#1408]
## Bug report

**Describe the bug**
In v0.5.0 rc2, when multiple viewers are open and zooming in occurs (not on the image currently selected with the red outline) an error is produced in the log but functions as expected.

**To Reproduce**
1. Open multiple viewers (eg 2x2) and fill each with images.
2. With one image selected, scroll to zoom in on ANOTHER image. 
3. Each scroll wheel turn will create an error in the logs as seen attached. 

**Expected behavior**
No bugs :)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - QuPath Version: v0.5.0 rc2

**Additional context**
[multiviewer scroll bug.txt](https://github.com/qupath/qupath/files/13221309/multiviewer.scroll.bug.txt)

**Comment by petebankhead** [comment]
I couldn't replicate the issue as described, but the exception text shows me that it's related to painting.

My guess is that you had one or more objects with really large and complex ROIs whenever the bug struck, could that be the case?

I've attempted to fix the underlying issue at https://github.com/qupath/qupath/pull/1410 although it requires a bit of guesswork since I couldn't recreate the exception myself.
