### ISSUE TITLE
.SCN files not opening correctly

### ISSUE THREAD

**Issue by MustafaElshani** [qupath/qupath#141]
Hi Guys 
We are having trouble opening .SCN files, when we open an HE scan it does not display correctly with a Pink overlay. Also it seems that QuPath does not recognise it as HE but rather as fluorescence, I have tried to change to HE but with the same result. Have also tried to change the Brightness Contrast to no effect. The zoom feature does not seem to function even when viewing the actual slide image.

![qupath scn error](https://user-images.githubusercontent.com/35562636/35095344-076ed048-fc40-11e7-8a1e-3ab26579946a.png)

Your help would be very much appreciated 

Kindest of Regards

**Comment by Svidro** [comment]
Can you take a look and see which XMLNS type they have?  I notice QuPath is trying to use BioFormats and not Openslide.  See  https://github.com/openslide/openslide/issues/151

Since QuPath is using BioFormats, it also may be related to this issue, which did not seem to be resolved, unfortunately.
https://github.com/openmicroscopy/bioformats/issues/2811

**Comment by petebankhead** [comment]
Oh dear, that does look suspiciously similar to the picture in @Svidro's link.

As it happens, I've just been working on a pretty major revision of the QuPath Bio-Formats extension this morning.  It should solve a lot of issues, but I don't know if it will solve this one.  However, it will at least give some extra entries in the preference pane that would allow you to selectively enable/disable Bio-Formats for specific image extensions, so that you could ensure that OpenSlide is used for scn if you wanted.

If nothing too bad appears in the next couple of hours I'll merge the changes with the main branch and then the extension will be available for testing.  Or see [here](https://github.com/petebankhead/qupath-bioformats-extension) if you're happy to compile it yourself while it's still a work-in-progress.

**Comment by petebankhead** [comment]
In the meantime, I see at the bottom of the panel on the left *Image list (3)*.

If you double-click on that, you should see another two images - and you can double click on each of them to see how they look.  From the few .scn files I've seen, the 'default' that opens up usually isn't the whole slide scan that you probably want, and it's necessary to go to the *Image list* to access it.

You can also remove the Bio-Formats extension from your QuPath extensions directory, so as to let OpenSlide have a go.  Maybe it has more success.

**Comment by MustafaElshani** [comment]
Hi Guys 

Thank you for the prompts reply, 
Regarding the XMLNS, the leica links on the page don't seem to work, how would you go about to see the xmlns details 

@petebankhead 
Regarding the other 2 image, the display is the same they are the megapixel images of the tissues while it seems the first one is the macro image of the slide.

I can change the Image type to Bright field H&E but nothing changes, in this mode using Brightness and contrast I displayed Hematoxylin on its own which I think is correct while eosin is not ( see attached)

![scn heamatoxilin](https://user-images.githubusercontent.com/35562636/35099205-00f88c72-fc4f-11e7-88fc-55a8bdc73968.png)
![scn eosin](https://user-images.githubusercontent.com/35562636/35099207-011aaa28-fc4f-11e7-871d-c9373ccb75e1.png)

**Comment by MustafaElshani** [comment]
The closest I could get to looking like and he is by dropping the Max display in reconvolve standard stain
![reconvulte scn](https://user-images.githubusercontent.com/35562636/35099394-c3783144-fc4f-11e7-809a-d80078ea54a8.png)

**Comment by petebankhead** [comment]
The extension update is now [here](https://github.com/qupath/qupath-bioformats-extension/releases/tag/v0.0.4).

If it doesn't solve the problem, try going to *Edit &rarr; Preferences...* and find the entry called *Never use Bio-Formats for image extensions*.  Type `.scn` there and QuPath should default to using OpenSlide... which may possibly help.

**Comment by MustafaElshani** [comment]
I have installed the new extension with the same results. I tried to exclude the .scn file from bioformats so that OpenSlide opens it to no avail it comes up with file can't open, however, I downloaded a sample of the .scn file from openslide it opens OK 
It could well be the issue @Svidro illuded to.
Its seems like this is an ongoing issue https://github.com/openslide/openslide/issues/189, The files I have here are produced by Leica Versa while our older .scn from SCN400 work OK

**Comment by petebankhead** [comment]
Ah, I was also using the OpenSlide example to see if it worked.

If you can somehow send me an example file with the problem I'd be happy to investigate.  Although it sounds like it is outside the domain of QuPath, which depends on either OpenSlide or Bio-Formats to access the pixels.

(If it looks ok when opened by Bio-Formats in Fiji (www.fiji.sc) then it might be a QuPath thing again, although not one I've seen before.)

**Comment by MustafaElshani** [comment]
Hi Pete

I tried ImageJ earlier to no avail same issue with the pink overlay, looks like a bioformat issue, 

here is a link to the file if you would like to have a look.

I will try and get in touch with the guys up at Dundee regarding this issue 

https://drive.google.com/file/d/1-zEYM58GxPxk5ldECU3LU-A4ZpSMVqJd/view?usp=sharing


Mustafa

**Comment by petebankhead** [comment]
Do these colors look more plausible to you?

![scn_tile](https://user-images.githubusercontent.com/4690904/35150365-09106222-fd12-11e7-9be4-701173eac3a8.jpg)

My suspicion is that the photometric interpretation is causing the trouble.  Here's a (very hack-y) QuPath script that looks to pull out some tiles after having switched the photometric interpretation from Y_CB_CR to RGB.

```groovy
import ij.ImagePlus
import ij.process.ColorProcessor
import loci.formats.in.LeicaSCNReader
import loci.formats.tiff.IFD
import loci.formats.tiff.PhotoInterp
import loci.formats.tiff.TiffParser
import qupath.lib.images.servers.BioFormatsImageServer
import qupath.lib.scripting.QPEx

// Access the current image
def server = QPEx.getCurrentImageData().getServer() as BioFormatsImageServer

// Try to get the TIFF parser (this takes a bit of a search?)
// Assume that we have a LeicaSCNReader somewhere
def reader = server.manager.getPrimaryReader(server, server.filePath)
while (!(reader instanceof LeicaSCNReader))
    reader = reader.getReader()
reader = reader as LeicaSCNReader
def tiffParser = reader.tiffParser as TiffParser

// Get tile size
int w = reader.getOptimalTileWidth()
int h = reader.getOptimalTileHeight()

// Loop through the IFDs and see if we can extract an image, somehow
for (ifd in tiffParser.getIFDs()) {
    try {
        // Check the original photometric interpretation
        print 'Original photometric interpretation: ' + (ifd.getPhotometricInterpretation())
        // Hack to artificially set it to RGB
        ifd.putIFDValue(IFD.PHOTOMETRIC_INTERPRETATION, PhotoInterp.RGB.code)
        def bytes = tiffParser.getTile(ifd, null, 0, 0)
        // Convert to an ImageJ image for display
        int[] rgb = new int[w*h]
        for (int i = 0; i < w*h; i++) {
            int r = bytes[i]
            int g = bytes[w*h+i]
            int b = bytes[w*h*2+i]
            rgb[i] = (r << 16) + (g << 8) + b
        }
        def cp = new ColorProcessor(w, h, rgb)
        new ImagePlus("Tile", cp).show()
    } catch (Exception e) {
        print e.getLocalizedMessage()
    }
}
```

If this is correct, hopefully it would be possible to resolve the issue through a fairly minor change on the Bio-Formats side... but I don't know that for sure.

**Comment by MustafaElshani** [comment]
That looks good, do you have any higher magnification images?.


It does sound like a quick fix, I have been in touch with a developer at bioformats hopefully this can be addressed

**Comment by petebankhead** [comment]
Well, there's a way you could do it....

If you try opening the image and running the following script, it should intercept the requests and change the photometric interpretation when needed.  So you should then be able to work with the whole slide image directly.

It does this with some very messy code, accessing private fields and such.  Therefore I don't really recommend it... but it might help check whether it's on the right track.

Note that I think you'll need to go to the QuPath preferences and turn off the Bio-Formats parallelization option for it to work.

```groovy
import javafx.application.Platform
import loci.common.RandomAccessInputStream
import loci.common.services.ServiceFactory
import loci.formats.ClassList
import loci.formats.FormatException
import loci.formats.IFormatReader
import loci.formats.ImageReader
import loci.formats.gui.BufferedImageReader
import loci.formats.in.LeicaSCNReader
import loci.formats.services.OMEXMLService
import loci.formats.tiff.IFD
import loci.formats.tiff.PhotoInterp
import loci.formats.tiff.TiffParser
import qupath.lib.gui.QuPathGUI
import qupath.lib.images.servers.BioFormatsImageServer
import qupath.lib.scripting.QPEx

// Access the current image
def server = QPEx.getCurrentImageData().getServer() as BioFormatsImageServer

if (server.willParallelize())
    print 'For this to work, you will need to turn off parallelization in the QuPath preferences!'

// Create a new reader that intercepts the photometric interpretation, and 'trick' QuPath into using it
def classList = new ClassList<>(IFormatReader.class)
classList.addClass(LeicaSCNReaderRGB)
def reader2 = new ImageReader(classList)
reader2.setFlattenedResolutions(false)
def factory = new ServiceFactory()
def service = factory.getInstance(OMEXMLService.class)
def meta = service.createOMEXMLMetadata()
reader2.setMetadataStore(meta)
reader2.setId(server.filePath)
server.manager.mapPrimary.put(server.filePath, BufferedImageReader.makeBufferedImageReader(reader2))

// Clear the tile cache
def viewer = QPEx.getCurrentViewer()
def imageData = viewer.getImageData()
Platform.runLater {
    viewer.setImageData(null)
    viewer.getImageRegionStore().clearCacheForServer(server)
    viewer.setImageData(imageData)
}

// See https://github.com/openmicroscopy/bioformats/blob/master/components/formats-bsd/src/loci/formats/in/MinimalTiffReader.java
class LeicaSCNReaderRGB extends LeicaSCNReader {

    /** Reinitialize the underlying TiffParser. */
    protected void initTiffParser() {
        QuPathGUI.getInstance().logger.info('INITIALIZING TIFF PARSER')
        if (this.in == null) {
            try {
                this.in = new RandomAccessInputStream(getCurrentFile(), 16);
            }
            catch (IOException e) {
                LOGGER.error("Could not initialize stream", e);
            }
        }
        tiffParser = new TiffParserRGB(this.in);
        tiffParser.setDoCaching(false);
        tiffParser.setUse64BitOffsets(use64Bit);
    }

}

class TiffParserRGB extends TiffParser {

    public TiffParserRGB(RandomAccessInputStream stream) {
        super(stream)
    }

    public byte[] getTile(IFD ifd, byte[] buf, int row, int col) throws FormatException, IOException {
        ifd.putIFDValue(IFD.PHOTOMETRIC_INTERPRETATION, PhotoInterp.RGB.code)
        return super.getTile(ifd, buf, row, col)
    }

    public byte[] getSamples(IFD ifd, byte[] buf, int x, int y,
                             long width, long height, int overlapX, int overlapY)
            throws FormatException, IOException
    {
        ifd.putIFDValue(IFD.PHOTOMETRIC_INTERPRETATION, PhotoInterp.RGB.code)
        return super.getSamples(ifd, buf, x, y, width, height, overlapX, overlapY)

    }

}
```

**Comment by BenjiP87** [comment]
I also had some problems using the bioformats package and scn files.  After installing the plugin, when I try to open my images on qupath, qupath tries to open my scn files using the bioformats server (not openslide)  and it cannot determine the magnification metadata   I tried manually editing the metadata into the qpproj file, but this had no effect.  Turning off the bioformats plugin in edit>preferences resolved my error.

**Comment by petebankhead** [comment]
Hi @pssaha did you also try it without Bio-Formats, e.g. before installing it or by turning it off for .scn (as was reported to workaround the problem at https://github.com/qupath/qupath/issues/141#issuecomment-400023655 ?  Further instructions are at https://github.com/qupath/qupath-bioformats-extension#performance
This would leave the job of reading the image to OpenSlide; I don't know what the status of .scn support is there.

Regarding the script, I don't see why my code should be limited in the resolution; is it possible that you're actually looking at an overview image/thumbnail rather than the full resolution image?  Many slide formats contain multiple images, and versions of the same image.  Under the 'Image' tab you can explore the 'Image list' and 'Associated images'.  Or if you're working with a [Project](https://github.com/qupath/qupath/wiki/Projects) then all images in the file should be added to the project immediately.

Nevertheless, I don't really recommend my script.  It was just put together to try to help explore the issue, but it is rather inconvenient to use and I don't know if the image it produces in the end really matches with the original or not.

**Comment by pssaha** [comment]
Hello @petebankhead, I apologize for being out of network for a while. You asked me two questions above. Please let me answer them:

1. Did you also try it without Bio-Formats, e.g. before installing it or by turning it off for .scn (as was reported to workaround the problem at #141 (comment)? 
Answer: Sure, I did that as before I wrote my first comment, but it says "sorry I can't open *.scn". That perhaps says that OpenSlide is not being used by default on my system. 

In order to let OpenSlide help in some ways externally, I went back to Openslide.org, specifically to https://files.openslides.org/releases/1.3/INSTALL-1.3.txt , followed the instruction to install openslide on Windows 32bits. But could not have success in installing finally (couldn't run on cmd). I even didn't know whether or how I could link this to QuPath. Anyway, just letting you know my attempt.

2. is it possible that you're actually looking at an overview image/thumbnail rather than the full resolution image? 
Answer:  I am afraid, it's not possible as I'll have to quantify the signals in the fully resolved scanned brightfield image (X20). That is the main goal of using QuPath for my project. I already had success in segregating my signals based on their intensity in the extracted region of the entire image, but I am stuck in loading the whole image on QuPath. If I can solve this, I am all set. Looks like this is challenging now!! I have in my mind to convert these .scn files to tiff if it is possible.

I thank you for your care and suggestions. Please let me know if you have something in mind. I'll appreciate your help. Sorry again for the belated comment. Many thanks, Sincerely, Partha

**Comment by petebankhead** [comment]
Closing this issue as I understand it should now be addressed in Bio-Formats, see https://github.com/ome/bioformats/issues/2811
