### ISSUE TITLE
Feature request: Freetext field to annotations and image-tab

### ISSUE THREAD

**Issue by teheikki** [qupath/qupath#144]
Hi!

We are planning to use qupath as a tool to teach histology to medical students at our university. We plan to make a self containing package of the image material that students can download for self study.

What we currently miss is an option to write longer descriptions to annotations and to the images.

We were planning to make a separate project per exercise like "Muscle" where there would be sample images from different muscle types. When you choose from project-view an image and you go to image-tab, there would be a good place for "Description" - freetext field where longer description of the image could be written.

When I open the "Annotation"-tab and choose an annotation, under the current "key-value" box there could be again "Description" freetext field for longer text. This could be edited in annotation set view. 

Would this kind of new additional text fields be doable? 

Br
Tero Heikkinen

**Comment by petebankhead** [comment]
I had a quick look on my local version of the code, where I've been exploring new things.  Here's a screenshot:

![image_descriptions](https://user-images.githubusercontent.com/4690904/35859449-04d0dfd2-0b38-11e8-9696-f549f97208d4.jpg)

I've added the description to the 'Project' tab rather than the 'Image' tab, so that it can be accessible without actually opening the image at all.  In this instance, the description that is shown depends upon which image entry is *selected* (i.e. blue), which is potentially different from the image that is actually opened.  The 'opened' image is now highlighted with bold text to make it clearer (n this case, they are the same image).  I hope that feels intuitive, but I guess it needs tested.

My reason for doing it that way is that I thought it would be useful to give the option of checking the description before deciding whether or not to open the image.

I've also been looking into several other changes, including the ability to set metadata values for individual images (you can see the options on the popup menu).  This means a project can have multiple image sets, and you can sort them to get a tree-like structure.  (Admittedly it's a small tree, since it only goes one level deep...)

Do these changes look like they would help for your applications?

Adding descriptions to annotations would be a more 'core' change, that would affect the .qpdata files.  So I'll need to think a bit more about how to achieve it, although I certainly agree it could be very useful.

**Comment by teheikki** [comment]
Hi!

Approach, where description is in the project tab is suitable. I'll attach a couple of screenshots from our current commercial solution that we need to abandon. 

We have a frontpage for each exercise and all images + their descriptions form a long singe page. It could be a project in qupath. So the approach you have been experimenting with is suitable for our needs and also in my opinion is better aproach that we now have.

Currently the annotations we use have possibility to attach short description. It has been useful for the students and the teacher to describe the findings, especially when it comes to the pathology course (who also may need to find a new tool for teaching) 

Do you save description data to the image files or to the qpproj file? Are the annotations stored to the project or to the image? 

In the long term I find qupath based solution very intriguing since it enables us to introduce every student about the possibilities of image analysis during the early stage of studies. 

![images_example](https://user-images.githubusercontent.com/36188931/35909832-649ca174-0bfd-11e8-9086-2a9dc6c5e4fb.jpg)
![annotation_example](https://user-images.githubusercontent.com/36188931/35909836-66e3ad2e-0bfd-11e8-98ee-f866aeadb12b.jpg)

**Comment by petebankhead** [comment]
I explored a bit more, and it turns out that I had already done most of the difficult part in storing annotation descriptions, and what remains is to make them accessible.

I had a quick look (the code is on my fork of QuPath) and can add descriptions to both the images and the annotations.  Currently, the annotation descriptions are just displayed as a tooltip under the 'Annotations' tab; they need a better home eventually.

I won't get a chance to look further for at least the next few days, but to answer your questions:

> Do you save description data to the image files or to the qpproj file?

Currently to the `.qpproj` file.  This is just JSON and can be opened in any text editor.

> Are the annotations stored to the project or to the image?

In the `.qpdata` file.  This is a binary file, which is in a trickier format (using Java serialization).  Potentially these files can be large and complex, storing the relationship between millions of objects (annotations, cells...).  But in your case they might be very small, and easily parse-able in a script.

**Comment by Svidro** [comment]
I had wanted to play with something like this for a while now, and this post finally got me going!  It took some time as I am not great with Java, but I have put together a two part system that is independent of the .qpdata file, though you could certainly enhance it's usefulness with annotations.

To start (assuming you have a project with an image), you would create an "Explore" (capitalized) folder within your project folder, at the same level as the "data" folder. Then run the "Location file creator" and select the views that you would want the student to cycle through, in order, while writing a text file referencing each location (which will be labeled 1,2,3, etc.).
Once you have both the text file and the object file saved to your Explore folder, anyone currently looking at an image should be able to run the Slide Explore script which takes the text file and the object file with the views, and allows the user to read and cycle through the various views that were set up.

I created a sample for JP2K-33003-1 if anyone wants to try it out and give some feedback.  Once I am a little better with Java, I would like to change the Next/Previous buttons into hyperlinks in the text, but I am not quite there yet :)

Scripts at: https://gist.github.com/Svidro/86fb224d69484ae5955631ce68d27054

The test image can be accessed at: http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/JP2K-33003-1.svs
The ".log" file needs to be renamed to ".obj" as I cannot post that file directly otherwise.

I am sure there are a lot of improvements that could be made, and any feedback is welcome.

[JP2K-33003-1.txt](https://github.com/qupath/qupath/files/1715587/JP2K-33003-1.txt)

[JP2K-33003-1.log](https://github.com/qupath/qupath/files/1715588/JP2K-33003-1.log)

**Comment by petebankhead** [comment]
Check out the updates described [in this blog post](https://petebankhead.github.io/qupath/2018/03/19/qupath-updates.html) - it explains how projects can be arranged and descriptions added.

Also, in the version described there, you can press *Enter* and then add some description text for annotations.

(*Viewing* the description remains rather sub-optimal... either press *Enter* again, or see it as a tooltip when hovering over the annotation under the *Annotations* tab on the left.)

**Comment by teheikki** [comment]
Seems that these features are just what we need!
@petebankhead is there some way directly (email) contacting you. Our cell biology professor would like to contact you.

**Comment by petebankhead** [comment]
Sure, I'm in far more places online these days than I ever intended to be... Twitter, LinkedIn, ResearchGate.  Or if you sign up to the [QuPath forum on Google Groups](https://groups.google.com/forum/#!forum/qupath-users) I should get a notification and can email you back from there.

**Comment by petebankhead** [comment]
In an effort to reduce our pending 'GitHub issues', and because this has been mostly addressed, I'll close this :)

It is now possible to add descriptions to annotations (in v0.2.0-m12... and soon the stable v0.2.0).

It's also possible to view the 'name' of the annotation superimposed on top of the image (press `N` to show/hide it).
