### ISSUE TITLE
Subcellular detection - expand to 4 categories? 

### ISSUE THREAD

**Issue by vetdocjim** [qupath/qupath#146]
Thanks for sharing this excellent program!! Is there a way to expand the subcellular detection categories to 4? Perhaps 1-3, 4-9, 10-15 and >15 spots per cell to correspond with the RNAscope scoring system? Thanks! Jim

**Comment by Svidro** [comment]
Many things are possible with scripting!  The original classifier script is around somewhere, but here is a simplified version I have on my gist.  I edited it a bit so that you can see how it would be used in your case.

https://gist.github.com/Svidro/5b016e192a33c883c0bd20de18eb7764#file-classifier-sample-groovy
Note that in this case it was looking for Channel 2 spots, but you can adapt this to any channel or stain, or multiple channels of spots at the same time (Dual positive 1-3, etc)

**Comment by vetdocjim** [comment]
Hi Svidro:

Thanks for your help!. I attempted to run your script but was unsuccessful. 

I used the Estimate stain vectors function > Auto to make sure that the vectors were set correctly. I then ran Cell Detection followed by the Subcellular Classifier (Experimental) to identify the spots. QuPath nicely identifies the spots and separates the clusters! I then annotated "Stroma" (where the ISH signal is located) and "Tumor" and ran the Detection Classifier. QuPath perfectly separates stroma and tumor cells. Then I ran your script. QuPath seems to have classified all cells as if they have > 15+ spots. 

Here is a screenshot. I would appreciate your thoughts. , ![image](https://user-images.githubusercontent.com/36250970/36341754-3ad312da-13c1-11e8-9287-eaed3de4b7d2.png)

Thanks for your help!!!

Jim

**Comment by Svidro** [comment]
Whenever everything is classified as positive, it usually means the wording is not quite right in the description of the feature (which is going to be from your example, not the script).  For example, if I change my fluorescent example to read "Surbcellular:" all of my spots become classified as 15+.  For your brightfield images, it is probably something like Subcellular: DAB: etc.

If you have trouble getting it just right, you can try using:
https://gist.github.com/Svidro/5e4c29630e8d2ef36988184987d1028f#file-print-a-list-of-detection-object-measurements
It will print out a list in your script window which you can directly copy and paste.

**Comment by Svidro** [comment]
And in case it helps with visualization, you can create the classes again in the Annotations tab by right clicking, and recolor them there by double clicking on your newly created class.
![image](https://user-images.githubusercontent.com/23145209/36343953-015e4e46-13c8-11e8-87b6-ad809b5e696f.png)

**Comment by vetdocjim** [comment]
Hi Svidro:

When I run the Subcellular detection (experimental) command, the program perfectly identifies the red ISH spots in the image. Here are my subcellular detection parameters:
![image](https://user-images.githubusercontent.com/36250970/36643217-911c24d2-1a16-11e8-9693-b8e3aeb1aee2.png)

When I run the script: setCellIntensityClassifications("Subcellular: DAB: Num spots estimated",1,4,10), The program perfectly divides the classes into 4 categories, Negative 1+, 2+ and 3+:
![image](https://user-images.githubusercontent.com/36250970/36643281-3288c096-1a17-11e8-8920-e47c8109b580.png)

However, when I substitute your script for the one above (using exactly the same settings), the program fails to divide the classes into 5 categories (Negative through 4+) and here is the output: 
![image](https://user-images.githubusercontent.com/36250970/36643319-b580f8ba-1a17-11e8-909d-6e6c5e619ee0.png)

My goal is to have an 5-category output that will match the Advanced Cell Diagnostics scoring scheme. I would appreciate your thoughts. 

Thanks!

Jim

**Comment by Svidro** [comment]
Ah, no, the script does not create sub-categories for each cell type, it overwrites cell classes based on the subcellular detection count.  I would have to look into something a bit different to do what is in your top image.  I'm not sure what the bottom image is though.  The result of the script if you swap in DAB should be something like:
![image](https://user-images.githubusercontent.com/23145209/36644405-c7245426-1a0e-11e8-8c52-4a525fd5588f.png)

At least based on the shoddy naming scheme I used in the basic script!

Note that it was not designed to subdivide tumor or stroma cells into categories, but to create new categories within annotation regions purely based on a spot count.  I would have to look into some different scripting to subdivide that way, though Pete recently posted a script that has a function I did want to test out.

**Comment by petebankhead** [comment]
I've added a script here that might help: https://gist.github.com/petebankhead/e0c9038e072d7beb488790f936a8d7e5

Be sure to check the comments at the top for warnings/explanations etc... but it is based on the `setIntensityClassification` scripting method, with the key relevant bit of the code [here](https://github.com/qupath/qupath/blob/3577d75b4a3bfb6b4676962f34fd10b95b61dcfe/qupath-core-processing/src/main/java/qupath/lib/scripting/QP.java#L1102).

**Comment by vetdocjim** [comment]
Pete and Svidro:

That's got it! Thanks both so much for your help. 

I have one final question. The subcellular spot detection seems to be picking up yellow in addition to red. After designating the ROI and doing a cell count, I used the Analyze > Preprocessing > Estimate stain vectors command, selected "Auto", then OK. The program picks up the red spots, beautifully, but also seems to pick up some aberrant yellow pigment. Here are a few images:
![image](https://user-images.githubusercontent.com/36250970/36645494-c2c50a14-1a37-11e8-9932-2b15b61a5e31.png)

![image](https://user-images.githubusercontent.com/36250970/36645503-d0a0d780-1a37-11e8-9e32-3dca42a8ec52.png)

Any thoughts on how to avoid detection of the yellow pigment?

Thanks again for this program and your help!!

Jim

**Comment by petebankhead** [comment]
When you run the *Estimate stain vectors*, it is good to have the smallest region selected that contains 'a bit of everything' (red staining, nuclei, background - although probably not the yellow pigment here).  If the region selected is large, then QuPath will need to scale it down and then may give a less good estimate.  You can also set individual stains manually by drawing very small rectangles around an area containing the stain, and then double-clicking the name of the stain under the *Image* tab.

Ideally, a really good estimate would allow you to set a higher intensity threshold and still detect what you want - but not what you don't.  However it is quite possible that no settings really achieve this.

Since I understand you are looking at counts - and not intensity values - you *could* set the image type to be *Brightfield (other)* and then this activates the 'third' stain color.  You could then set that based upon a small rectangle drawn in a yellow area.  QuPath will then try to separate this as an extra stain.

This will certainly negatively impact intensity measurements, and I'm not sure if it's a good idea.  Nevertheless, the meaningfulness of intensity measurements in this kind of image is probably pretty limited anyway, so it is perhaps worth a try to see if it results in much better detection of what you can see by eye really should be detected.

In the future, I'm wondering if it would be better to create a machine learning approach in QuPath for tasks like this, i.e. something more 'learn-by-example' (like with training the tumor/stroma cell distinction), rather than relying on color deconvolution.  I think the current approach may be too simple, because there are always little anomalies or artefacts that can play havoc with trying to set a threshold for detection.  What do you think?  Are there any other changes/additions that would help here?

**Comment by vetdocjim** [comment]
Hi Pete:

Thanks so much for your helpful comments!

I am a veterinary pathologist working with novel immunotherapeutic approaches to cancer treatment. We use in situ hybridization extensively for target discovery and to identify target + cells within our xenograft models. In addition to measuring a reduction in xenograft size via calipers, I am interested to use QuPath to document a reduction in the number of ISH target + cells / unit area of the xenograft. It would be incredibly helpful to have a "learn by example" approach to speed the task. Maybe you would select ISH- stromal cells, ISH+ stromal cells, ISH- tumor cells and ISH+ tumor cells, etc. as annotations and then run the Classifier?

I am also involved in gene therapy experiments in which we are attempting to knock down mRNA expression in specific cell populations in vivo. I would like to use QuPath to identify the cell population using annotations, then measure the amount of ISH signal per cell in treated vs untreated animals. In this case, rather than eliminating the cells of interest, we are attempting to demonstrate a reduction in ISH signal per cell. Thus, simply designating cells as "positive" or "negative" will not suffice. Rather, using the script you wrote above would be helpful to show that you have a reduction of cells listed as 4+ and 3+ and an increase in cells listed as 0 or 1+. Alternatively, if you could calculate an "H score" based upon a 5-point scale (negative, 1+, 2+, 3+, 4+), that would be a great way to compare between groups. 

I think the intersection between pathology and artificial intelligence / machine learning is fascinating. I wonder if it would be feasible to learn Groovy so I can write my own scripts? 

Thanks again!

Jim

**Comment by Svidro** [comment]
My experience with ISH makes me prefer straight measurement of estimated spot count versus using or creating H-scores.  Sets of numbers representing+1 to +4 can be useful to distinguish populations with both high and low members versus a medium number of spots, but once you want to compare samples by a single number you might be better off with the spot count Mean/Median/Standard deviation, since those are all probably one or two lines of code.  Plus I am not sure how well the new version of the H-score would compare to older publications, even if the math was adjusted to a 0-300 scale.

I second using the Brightfield (other) when eliminating yellow areas like that for brightfield ISH.  Sometimes once you have enough colors, though, you have to apply multiple sets of measurements to the ISH spots (select the subcellular detections, pick your color vectors, Add Intensity Measurements), and then filter them in a script, and update a "Filtered Red Estimated Num spots" or something like that.  Two color brightfield ISH with red blood cells in the background gets to be a real pain.

For a first pass you could try moving the color vectors in Estimate color vectors to something like :
![image](https://user-images.githubusercontent.com/23145209/36652180-ed8010a8-1a61-11e8-8d09-d639962fd706.png)
One vector picks up as much red as possible, and one to get "the rest" of what is in your sample.  They do not need to be the same as when you did the cell detection.


Picking up Groovy isn't bad if you understand programming basics like variables, if/for loops, etc.  The main trick (for me) is learning the QuPath specific functions to use, and making use of either Gists, the forums, or IntelliJ to figure out how doable my plans actually are!  I mostly just modify other people's scripts.  I'm trying to fill out some of what I have learned in my Gists as I go along.

On the image, it looks like you are missing quite a few of the smaller spots.  If that isn't intentional, I would try turning off all of the check boxes, lowering the min spot size, and make use of the clusters as all of those get combined into the Num spots estimated.

**Comment by vetdocjim** [comment]
Svidro:

Thanks for your comments. I think your point about the estimated spot count vs "H score" for ISH measurements make sense. 

I tried the Brightfield (other) approach that you and Pete recommended and selected yellow as the third color. QuPath seems to have nicely subtracted that from the Red spot analysis. Now, the next step is to adjust the parameters to pick up the smaller spots. I'll try your advice above. 

Pete suggested that I draw small rectangles around the Hematoxylin, Red and Yellow colors I wish to identify and then use those rectangles to reset the corresponding colors on the "Image" tab. This seems to be working well, however, I'll try your approach for the red vectors above and see how that works. 

Thanks again for your help,

Jim
