### ISSUE TITLE
Merge annotations - afterwards QuPath does not count Cell detections anymore

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#147]
Hi Pete, dear all, 

I merged annotations of the same class into an Area annotation with class. 
Afterwards I let QuPath run cell detection. 
But it does not count the cells inside the ROI anymore!
Normally the cell count will be shown in the annotions tab: 
![grafik](https://user-images.githubusercontent.com/16352785/36159106-368468ea-10de-11e8-886e-467bf90ae69d.png)

And, even a bigger problem: the cell count does not appear anymore in the annotations results!

Is it maybe a formation error after merging annotations?

I use the following script to merge annotations: 

selectAnnotations();
annotations = getAnnotationObjects().findAll {it.isAnnotation() && it.getPathClass() == getPathClass("NameOfClass")}
mergeAnnotations(annotations)
selectObjects {it.isAnnotation() && it.getPathClass() == getPathClass("NameOfClass")}
mergeSelectedAnnotations();

**Comment by Svidro** [comment]
Regarding the script, are you merging two different annotation classes two different ways?  Or merging the same annotation twice?  Are you running the cell detection command in the script immediately after the second merge?  That could be a big problem if so.

You have two merge statements, each done a different way.  If you are actually running the script as is, you are probably running into the same problem as before, where one merge has not completed when the second starts running, and everything is getting "bugged out."  If that is the case (and you are running your cell detection in the script right after the second merge), you may want the thread sleep command from https://github.com/qupath/qupath/issues/129.


I am not certain, but I have a feeling that this has more to do with the shape of your annotation causing cell detection a problem than the merge statement.  

When I have had something like this happen (cell detection starts running, but no cells show up in the annotation tab), it does not always show an error in the log, but the first thing to do would be to check the View->Show log to see if there is an error message there.  If there is, great, that might be useful.  On the other hand, if there is nothing, it may just be the cell detection not completing, but without causing any errors.  

If none of the above helps, could you paste your .qpdata file as a .log file (rename the file extension), with ONLY the annotations saved.  It should be quite small.  I would like to try importing it onto another dummy whole slide image just to try running cell detection to see if the shape of the annotation is causing problems.

**Comment by DavidMHaumann** [comment]
Hi Svidro, 
thanks for your ideas. 
I discovered that I merged twice and now work with the first part. 

selectAnnotations();
annotations = getAnnotationObjects().findAll {it.isAnnotation() && it.getPathClass() == getPathClass("NameOfClass")}
mergeAnnotations(annotations)

It does not change anything about the problem. 
Also the sleep time of 100 milliseconds does not help. 

And I do not start celldetection immeadetly after merging. It comes much later. 

The cell detection runs very well - as allways. They appear in the viewer and in the "show detection results". 
But not in the annotation results anymore AND not in the anntoations tab, where you can normally see the object count within an ROI/annotation. 

I try to upload such an annotation qudata file.

**Comment by DavidMHaumann** [comment]
[Final_1-100_H211_HD_20x_19.log](https://github.com/qupath/qupath/files/1722139/Final_1-100_H211_HD_20x_19.log)

**Comment by Svidro** [comment]
Interesting, I can get the file, and when I look inside it, I see the same .qpdata structure as ones I have with only annotations, but when I load it there are no annotations.  I am unsure if the reason I do not get any annotations is related to your problem, or something else related to regional settings/commas/periods.

One last try before I leave this for Pete... sometimes cells can get trapped "outside" of the annotations, and you need to force an update.  I honestly forget when this happens, but I have an example of it right now where the Annotations tab shows the annotation with no cells, and the Hierarchy tab shows the annotation at the top (but empty) and a list of polygons below it, all on the first level.

In order to resolve the above case, you can either select and "jiggle" the annotation slightly, or to be more precise, use the following script to try and force it to update.  Be aware it may seem to freeze if you have a large number of detections.  For ~600,000 detections it took about 10-15 minutes on my fairly fast computer since it only runs on one CPU core.

https://gist.github.com/Svidro/5829ba53f927e79bb6e370a6a6747cfd#file-force-update-selected-annotation-groovy

**Comment by petebankhead** [comment]
I don't think changing the extension of .qpdata files works here, and this may be the source of not being able to access it - would need to zip up the original file.

But note that the cell count is never shown when an annotation is *classified* in that location in QuPath v0.1.2.  It's also not an ideal place to get this number, because it is not actually a cell count but rather a count of the number of *direct child objects*.  This should be the same as the cell count if there are no other objects (e.g. nested annotations), but otherwise it may not be.

In my own QuPath fork I've added a detection count to the main built-in measurements for all annotations, which looks deeper through the hierarchy to get all cells - even if they are inside nested annotations.  This works also for unclassified cells, but in v0.1.2 counts are only provided if the cells are classified.

As a workaround in v0.1.2 you could set your cells to have any arbitrary class, e.g.
```groovy
getCellObjects().each { it.setPathClass(getPathClass('My cell')) }
fireHierarchyUpdate()
```
Then they should at least appear in any annotation measurement tables.
