### ISSUE TITLE
ParameterPanelFX does not validate text field input

### ISSUE THREAD

**Issue by alanocallaghan** [qupath/qupath#1541]
## Bug report

**Describe the bug**
You can enter arbitrary values in the text fields of a ParameterPanelFX, even though it knows what type(s?) the parameter accepts.

**To Reproduce**
1. Ctrl/Cmd + L
3. Cell detection
5. Tab twice/select pixel size text field
7. Type "dakjdpokowakdapodw" into pixel size text field

**Expected behavior**
Parameter input fields should only accept (potentially) valid input

**Comment by alanocallaghan** [comment]
Also eg the histogram nbins can be set to crazy large values which results in a broken plot

**Comment by petebankhead** [comment]
How bad is this really...?

I remember from conversations with @melvingelbard that validating numbers in a text field is far from straightforward... at least if trying to handle `+-.,e`. These might be used for valid numbers, but at the point they are typed the text may not be a valid number. He wrote [this method](https://github.com/qupath/qupath-fxtras/blob/007d91581049d7fd9439fd233211dcecf44d8fef/src/main/java/qupath/fx/utils/FXUtils.java#L260) to help sort that.

ControlsFX doesn't handle this so well: you can see it in the preference pane, built using ControlsFX. Find a numeric field, e.g. `Brush diameter`. You can type `50` but you *cannot* type `-50` in the usual way. But you *can* type `50` and then go back to add the `-` (or even `+`). It seems to use a validation that is much too eager.

I find this to be more annoying and problematic, so the `ParameterPanelFX` errs on the side of 'type anything, it's up to you for it to make sense'. The main thing is that we shouldn't through exceptions too quickly. But you could try switching the parameter pane to use Melvin's method linked above and see if it behaves better. In any case, I think a solution belongs in `qupath-fxtras` since it is so fiddly.

For the number of bins, you can set an upper limit on the parameter - but this will have the effect of using a slider instead. That might be fine in this case; if you need more customisation, then it'd be better to avoid `Parameter` altogether and just got straight to JavaFX (which could be preferable for the measurement table histograms since then it'd be easier to make the selections persistent).

**Comment by alanocallaghan** [comment]
Wow, fair point. My memory from the awt/swing era was that it was fairly straightforward, albeit I figured that there might be some trickiness in mapping between the parameter types and valid default inputs/ranges.

Agree it's not really a problem, although very large values in the histogram does do something unexpected.

**Comment by petebankhead** [comment]
I wanted to switch the measurement table histogram to use JavaFX yesterday, using observable values and making them persistent, but didn't have the time / concentration / will to actually do it. That would give more customisation control - there is no real reason they need to use the `Parameter` stuff (which is primarily to make it easier to write scriptable commands, like cell detection, without needing to code the whole UI).

Feel free to make that change. Or, the easy one, just clip a maximum number of histogram bins in the code and log a warning if the user requests something unreasonable that we don't use.

**Comment by alanocallaghan** [comment]
Sounds sensible, I was planning on refactoring the current version to trial thresholding histograms/gating scatter plots, so I'll close this and do "something" when merging that.

There's already an internal cap, though I'll add a logged warning
