### ISSUE TITLE
immunohistochemistry of stroma

### ISSUE THREAD

**Issue by geodza** [qupath/qupath#157]
Hello!
I am a pathologist and a doctoral student from Estonia. My research field are stromal changes in cancer. I ve been using blinding so far to achieve an impersonal result. Recently appeared an opportunity to use a digital scanner. I ve been trying to make analytics using Your software (to replace blinding) but was unable to achieve a good result. For example I have a picture like this:
https://imgur.com/a/dOIqN
stroma stained with actin (SMA). Brown color is a positive staining
Is is possible to count an amount of the positive staining?
Are there any manuals? I was unable to find any information about stroma in FAQ.
Thanks in advance!

upd I can upload a sample slide if needed.

**Comment by Svidro** [comment]
If you upload a sample slide I could probably generate a sample script...

but from the image it seems like either _Analyze->Region Identification->Positive Pixel Count_ within an annotation (you might try searching https://groups.google.com/forum/#!forum/qupath-users), or _Analyze-> Cell Analysis-> Cell Detection_ (https://github.com/qupath/qupath/wiki/Detecting-objects) with Optical Density chosen instead of Hematoxylin should give decent results.

SLICs might also give you a simple way to detect area, and then if you add more measurements to them (Add Intensity Measurements) relating to texture (Haralick, etc) you might be able to automatically distinguish between tumor and stroma.  If  you want to play around with that, it's also under _Region Identification->Tiles and Superpixels_.   https://github.com/qupath/qupath/issues/121 has an example.

**Comment by geodza** [comment]
Thanks for Your answer!
I will upload a couple of slides ASAP, but due to my slow internet these will be ready probably by tomorrow. I ll try using Your solution during these time. My best result so far was with photoshop color histograms :)

**Comment by geodza** [comment]
Hi!
Sorry for the delay.
Here is the link (huge, 7.3 gb)
http://pathology.ee/test/slide.scn
One of my slides (Leica). Quite good example, has positive and negative areas and a damaged area (no need to measure it).
I was trying to solve the problem using Your advice, but still no results.
If You ll be able to help me, I d be very grateful.

**Comment by Svidro** [comment]
Sounds good, but I have been a bit busy here, just started the download now, and probably won't be back to take a look at it for ~12 hrs.  Should be able to have a look at it then.

**Comment by geodza** [comment]
OK, thanks! no need to hurry :)

**Comment by Svidro** [comment]
So I took a quick run at it, and came up with a few options.
First off, due to your somewhat off-white background, I would definitely use something like:
```
setImageType('BRIGHTFIELD_H_DAB');
setColorDeconvolutionStains('{"Name" : "H-DAB default", "Stain 1" : "Hematoxylin", "Values 1" : "0.69602 0.66056 0.28145 ", "Stain 2" : "DAB", "Values 2" : "0.47625 0.62539 0.61811 ", "Background" : " 224 224 224 "}');
```

Next I drew a square that had some DAB and non DAB stained areas and tested the following **with the annotation selected**:
```
runPlugin('qupath.imagej.detect.tissue.PositivePixelCounterIJ', '{"downsampleFactor": 1,  "gaussianSigmaMicrons": 0.5,  "thresholdStain1": 0.1,  "thresholdStain2": 0.2,  "addSummaryMeasurements": true}');
```

Alternatively you could try superpixels, which I like, but would also require a classification step.  For now you can use the Measure->Show measurment maps command to look at what values you could use for a classifier.  Again **with the annotation selected**:
```
runPlugin('qupath.imagej.superpixels.SLICSuperpixelsPlugin', '{"sigmaMicrons": 1.0,  "spacingMicrons": 10.0,  "maxIterations": 10,  "regularization": 0.25,  "adaptRegularization": false,  "useDeconvolved": false}');
selectDetections();
runPlugin('qupath.lib.algorithms.IntensityFeaturesPlugin', '{"pixelSizeMicrons": 0.25,  "region": "ROI",  "tileSizeMicrons": 25.0,  "colorOD": true,  "colorStain1": true,  "colorStain2": true,  "colorStain3": false,  "colorRed": false,  "colorGreen": false,  "colorBlue": false,  "colorHue": false,  "colorSaturation": false,  "colorBrightness": false,  "doMean": true,  "doStdDev": true,  "doMinMax": false,  "doMedian": false,  "doHaralick": false,  "haralickDistance": 1,  "haralickBins": 32}');
```

You can also choose a larger size for your SLICs if you want to do more of a tissue structure analysis.  Smaller is usually better if you are looking for color differences though.

Another options is just using the cell detection mentioned above:
```
selectAnnotations();
runPlugin('qupath.imagej.detect.nuclei.PositiveCellDetection', '{"detectionImageBrightfield": "Optical density sum",  "requestedPixelSizeMicrons": 0.25,  "backgroundRadiusMicrons": 0.0,  "medianRadiusMicrons": 0.0,  "sigmaMicrons": 1.5,  "minAreaMicrons": 15.0,  "maxAreaMicrons": 60.0,  "threshold": 0.1,  "maxBackground": 2.0,  "watershedPostProcess": true,  "excludeDAB": false,  "cellExpansionMicrons": 5.0,  "includeNuclei": true,  "smoothBoundaries": true,  "makeMeasurements": true,  "thresholdCompartment": "Nucleus: DAB OD mean",  "thresholdPositive1": 0.2690789473684211,  "thresholdPositive2": 0.4,  "thresholdPositive3": 0.6,  "singleThreshold": true}');
```

Which yielded the following for my square.  You may want to tweak the DAB threshold value, and you can always create your own classifier as well based on more data than just the Nucleus DAB OD mean (https://github.com/qupath/qupath/wiki/Classifying-objects):
![image](https://user-images.githubusercontent.com/23145209/37378645-52636d20-26ed-11e8-88ac-5401852cb5bc.png)

It really depends on what exactly you are interested in measuring.

**Comment by geodza** [comment]
WOW!
Thanks for the great answer!
Unfortunately I am not currently at home; I was only able to test it on my notebook, which sometimes crashes.
Still, thanks to You I got a very good result:
https://i.imgur.com/3eaQ7s1.jpg
All the positive areas are detected and the % of positive staining in selected area is also calculated (the main idea is to show that the expression of positive staining changes depending on the cancers grade).
I will only be able to take an adequate try in a couple of days.
Anyway, I am very grateful!

**Comment by Svidro** [comment]
Ah, sorry, I probably should have mentioned, it might not be your laptop...
One of the dangers with using Positive Pixel detection is the strain it puts on the program when updating the screen with many very finely defined areas.  I would recommend turning OFF all detection visualizations, then moving the screen to the location you want to see, then turning detection visualizations back on (might be the D or H key?  I don't have access right now and forget).  Turn them off again before you want to move the screen to a new position.  It is somewhat cumbersome, but usually prevents my program from crashing.  

In fact, the program is not usually crashing, but just very slowly rendering the entire image again.  Though depending on your system it might sometimes take an hour or so!  If you use Superpixels or Cell detection, this is not usually a problem.

**Comment by petebankhead** [comment]
> might be the D or H key?

It's 'H' for 'Hide' :)
But I've been tempted to make it 'D' for 'Detections'...

[List of shortcut keys](https://github.com/qupath/qupath/wiki/Shortcut-keys)

**Comment by geodza** [comment]
Thanks!
I have had no crashes on my desktop PC so far :) The software is very stable.
It must be "H"
I have like 100 more scanned slides with different immunostains (stromal). Canˇt wait to reach my PC :)

**Comment by Svidro** [comment]
Sounds great!  If they were taken on the same slide scanning system, I would definitely recommend checking out the section in https://github.com/qupath/qupath/wiki/TMA-CD3-analysis called **Estimate Stain Vectors**

The relatively dark background might cause some problems for lighter colored stains if you aren't careful with that step.  Pete even included a video!

**Comment by geodza** [comment]
Well, as promised
I had an opportunity to test Your script on a bigger amount of glasses.
It seems that everything is fine
I will now start a new project with a new staining, probably ~100 glasses, with analytics fully based on QuPath
Still need to understand, how to analyse stroma in H&E staining :)
But anyway, I am really grateful for Your advice. If ill be able to publish my results, I will let You know!
I`ll close this topic as the solution was found.

**Comment by Svidro** [comment]
If you are looking at H&E, I usually found it best to divide up the tissue
using superpixels, add texture and color measurements, then classify based
on the measurements.

Once your areas are classified, there is a command to merge them all into
new annotations, which you can then perform Positive pixel or Cell
detection on.  A combination of two of the steps described above.

**Comment by geodza** [comment]
Thanks for the advice!
I will firstly start with immunohistochemistry; the H&E step will be in a month or two. I hope to learn QuPath more fluently during this time, but I am almost sure this was not the last scream for help I post on Your forum :)

**Comment by Svidro** [comment]
Well, Pete's forum, really!  I am just a user that really enjoys this
stuff.  :)

**Comment by petebankhead** [comment]
Everyone's forum :)

You might want to check out [this new blog post](https://petebankhead.github.io/qupath/2018/03/19/qupath-updates.html) describing how to try out lots of new QuPath improvements early.

Especially check out the bit about *Positive pixel count* (about half-way down the page), which describes now & improved outputs that the command can give.
