### ISSUE TITLE
Script annotation setPathClass().

### ISSUE THREAD

**Issue by N0s3n** [qupath/qupath#158]
Hi. 

I would like to be able to loop though my annotations (rectangles and circles) and set a specific class to each one of them. 
To print the current classes works fine:
`getAnnotationObjects() each {annotation -> print(annotation.getPathClass())}`

But I would like to set the class based on which pixel on the x-axis the centroid is located at. The function setPathClass() only gives errors. 

`getAnnotationObjects() each {annotation -> annotation.setPathClass(annotation.getROI().getCentroidX())}`

If it's not possible to give them a class that isn't defined I would like to set the first annotation to Tumor then Stroma and so on. 

By the way. Is there a sheet or file in qupath that lists functions you can use on different objects? My current workflow is that I'm "grep'ing" the source code for function names that sound like it could work. 

Regards,
Björn

**Comment by petebankhead** [comment]
You need an instance of [`PathClass`](https://github.com/qupath/qupath/blob/v0.1.2/qupath-core/src/main/java/qupath/lib/objects/classes/PathClass.java).

*But*, you should never call the construction for `PathClass` directly.  There is some explanation [here](https://groups.google.com/d/msg/qupath-users/44HBd-5nbaQ/VHbENs9TBAAJ).

Something like this should work:
```groovy
def tumor = getPathClass('Tumor')
def stroma = getPathClass('Stroma')
getAnnotationObjects().eachWithIndex { annotation , i ->
   if (i % 2 == 0)
      annotation.setPathClass(tumor)
  else
      annotation.setPathClass(stroma)
}
fireHierarchyUpdate()
```
But you can change the text to be whatever you want, rather than `Tumor` and `Stroma` (although probably best to avoid colons`:` in any name, since these are typically used to separate *sub*-classifications).

Regarding finding available methods, I've just added a [blog post](https://petebankhead.github.io/qupath/scripting/2018/03/16/script-print-methods-and-fields.html) with a bit more info.  If you are happy to use IntelliJ, that's probably easiest.

**Comment by N0s3n** [comment]
Hi ,

Thank you for your fast reply and code suggestion! 

Regards,
Björn

**Comment by N0s3n** [comment]
Hi again,

Your code worked perfectly. 

Another question: I'm doing what we call it virtual TMAs to complement a set of TMAs. I'm drawing two circles per slide that are 4000 µm in perimiter. That is almost equal of the TMA's 1.2 mm diameter.

Can you script so that you can click on two places on your slide and it will draw 2 circles with a 4000 µm perimiter?

Regards,
Björn

**Comment by petebankhead** [comment]
Potentially, with a bit of effort.  It's easier if you can avoid needing to handle mouse clicks etc., and don't mind simply placing the circle at the center of the current field of view.  You can always then move it afterwards if you need to refine the position manually, using the existing *Move* tool.

A similar processing for creating a rectangle is described on [this blog post](https://petebankhead.github.io/qupath/scripting/2018/03/09/script-create-fixed-size-region.html).

`RectangleROI` appears twice in that script.  If you just replace it with `EllipseROI` in both places it should do the job (and of course change the `PathClass` bit if you want).

The `sizeMicrons` value specified in the script should correspond to the diameter.

**Comment by N0s3n** [comment]
Thank you again for your fast reply. I won't mind moving the circles. It is just to make them as close to 4000 µm that is a hassle. I'll check out the example. 
/Björn
