### ISSUE TITLE
Application keeps crashing/not responding

### ISSUE THREAD

**Issue by spatts14** [qupath/qupath#1580]
## IMPORTANT!

This section is **only** for bug reports, which **must** follow the template below.

Please post any other questions to the official QuPath forum at https://forum.image.sc/tags/qupath

If in doubt, use [image.sc](https://forum.image.sc/tags/qupath). This helps us keep things organized.

## Before we begin...

Before submitting your bug report, please check the following:

* [X] I've definitely found a bug (it you're not sure, please use [image.sc](https://forum.image.sc/tags/qupath) instead)
* [X] I've checked https://qupath.github.io for a new release that might already have fixed the issue
* [X] I've checked the [Changelog](https://github.com/qupath/qupath/blob/master/CHANGELOG.md) to see if the bug has already been fixed in the next release
* [X] I've checked for existing GitHub issues describing the same problem

## Bug report

**Describe the bug**
Whenever I try to use QuPath, the application crashes on me. I have uninstalled and reinstalled x2 and am fully up to date (QuPath-v0.5.1-Mac-arm64). I can open the application and open my project, but when I try to view an image it crashes on me. 

It also causes my computer system wide issues and Ive had to restart twice.

I am on a Mac with 

**To Reproduce**
Unsure

**Expected behavior**
It should open the image for H&E (20x) for an scn file from Versa
<img width="1498" alt="Screenshot 2024-08-08 at 3 24 02 PM" src="https://github.com/user-attachments/assets/c69bcc7f-14ca-450b-ac7c-6981ca2903c1">

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 14.4.1.
 - QuPath Version: v0.5.1

**Additional context**
This is happening for all my QuPath projects, not just a specific one.

**Comment by MichaelSNelson** [comment]
It sounds like this might be better addressed on the forum, preferably with an example file hosted and shared, the bio-formats tag added, and the error message from the log (question mark, upper right) included.

**Comment by petebankhead** [comment]
Hi @spatts14 as @MichaelSNelson suggestions, please try posting this on the forum at https://forum.image.sc/tag/qupath

If it is related to the specific file formats, then QuPath is reading them through Bio-Formats or OpenSlide - and the developers of both are active on the forum as well. I'm afraid that without an example file there is nothing we can do on the QuPath side (and possibly nothing we can do even _with_ a file, if the problem needs a fix in Bio-Formats or OpenSlide).

However, because you mention
> It also causes my computer system wide issues and Ive had to restart twice.

One possibility is that it is *Finder* crashing and not QuPath. I've seen that before on a Mac. I describe it a little bit [here](https://forum.image.sc/t/qupath-on-mac-poor-performance-slow-crashes-loads/53243/2) - if that's the issue, relaunching Finder (similar to force quitting) should fix that without a restart. It happens when a whole slide image is selected in Finder, and Finder tries to show a preview thumbnail - but it can't because the image is huge.

But there's a good chance it's the problem @MichaelSNelson links to - in which case you can try the creating a new project and [specifying 'Bio-Formats' as the 'Image provider'](https://qupath.readthedocs.io/en/stable/docs/tutorials/projects.html#add-images). You may find the images then open, but could be the wrong color.

I'll close this issue as there's a better chance of finding success on the forum, and it's not clear that there's a bug in QuPath that we can do anything about.

**Comment by spatts14** [comment]
Thanks so much for the suggestions and feedback!
