### ISSUE TITLE
Getting area out of detection objects

### ISSUE THREAD

**Issue by oriolarques** [qupath/qupath#159]
Hi,

I would like to know if it is possible to detect not only the percentage of positive cells but also the area that they occupy. 
What I tried to do was: 1. Use positive cells selection. 2. Create a classifier to differentiate between tumour and stroma and 3. send detections to ImageJ (in an intend to merge all the detections into a ROI and calculate the area occupied by positive tumour cells). My problem is that when I send the region to ImageJ i get all (tumour and stroma) detections and I cannot differentiate them anymore (in ImageJ all objects are treated as the same overlay).
Is there any way in QuPath to calcuate the area that occupy all positive tumour cells? and if not, is it possible to send only the detection of tumour cells to ImageJ already as a single selection? (because if I have thousands of detections and I want to merge them as a single ROI it has an extremely high cost in terms of processing power for the computer).

Thanks.

**Comment by Svidro** [comment]
Hi!
If you want to calculate the area, I wouldn't merge anything, but sum it up instead with a short script.  If you intend to do something else with the merged cell area, that is another matter.

```
def tumorCells = getCellObjects().findAll{it.getPathClass() == getPathClass("Tumor")}
def totalArea = 0
for (cell in tumorCells){
    totalArea = totalArea + cell.getMeasurementList().getMeasurementValue("Cell: Area")
}
println("Total area of your class of cells in square micrometers is: " + totalArea)
```
If you want to sum up any other type of object, swap out Tumor for your class of choice.  You could also then add this value to an annotation rather than printing it out, or if you knew you only had one annotation, calculate the percentage of that annotation's area that the totalArea represents.  Your choice!

**Comment by oriolarques** [comment]
Thanks for the quick reply!
This script is good. However, it would be great to do, as you pointed, calculate the percentage of that annotation's area that the totalArea represents. Could you post a script for that?
Thanks in advance

**Comment by Svidro** [comment]
I may have to wait until I get home for this to actually work correctly, or Pete can fix it, but mostly you want to change the way you choose the objects you get, since I don't know if you have several annotations, or one giant merged annotation.

A script from a while back here: https://gist.github.com/Svidro/68dd668af64ad91b2f76022015dd8a45#file-cell-summary-measurements-to-annotation-groovy
Shows how to add the sum of the positive areas to the annotation, though I don't recall at the moment how to access the annotation's area in a script.  I'm sure I have done it before, but most of my QuPath stuff is at home (~8 hours from now).  All you would need at the end of this script (within each annotation loop) is to divide your new value by the total area and multiply by 100, if desired.

Be very careful doing this, however, as little things like your cell expansion radius can have a dramatic effect on this value depending on the density of your cells!  And sometimes depending on the perimeter of your annotation as the cells can stretch outside of your annotation.

**Comment by Svidro** [comment]
I had a little bit of time and think I have it figured out...

```
//In this case, it will add the total area taken up by Positive class cells within each annotation to their parent
//annotation as "Positive Area"

import qupath.lib.objects.PathCellObject

hierarchy = getCurrentHierarchy()

for (annotation in getAnnotationObjects()){
    //Block 1
    def positiveCells = hierarchy.getDescendantObjects(annotation,null, PathCellObject).findAll{it.getPathClass() == getPathClass("Positive")}
    double totalArea = 0
    for (def cell in positiveCells){
        totalArea += cell.getMeasurementList().getMeasurementValue("Cell: Area")
    }
    //Comment the following in or out depending on whether you want to see the output
    //println("Mean area for Positive is: " + totalArea/positiveCells.size)
    //println("Total Positive Area is: " + totalArea)
    
    //Add the total as "Positive Area" to each annotation.
    annotation.getMeasurementList().putMeasurement("Positive Area", totalArea)
    def annotationArea = annotation.getROI().getArea()
    annotation.getMeasurementList().putMeasurement("Positive Area %", totalArea/annotationArea*100)
    //Block 2 - add as many blocks as you have classes
    //repeat above
}
```

Just change all instances of Positive to your class, and duplicate as many times as you want within the annotation loop.

**Comment by oriolarques** [comment]
Thank you very much. 
It was a very instructive answer. I think I can go from here myself.
