### ISSUE TITLE
Anyway I could move/rotate tiles?

### ISSUE THREAD

**Issue by YHGim** [qupath/qupath#162]
I think showing images in tiles is a fascinating feature in qupath because I work with

multiplex IHC and tiles makes it a lot easier to cut areas without overlapping images.

However I was curious if tiles could be moved or rotated like annotations because

if possible, it will be easier to match same TMA slides with different antigens since scanned TMA

slides (although technically an identical slide) are not always aligned perfectly.

**Comment by petebankhead** [comment]
I think the current answer is 'no'.  As I understand your question, you mean tiles containing pixel data - is that right?

I have been working on some related things that could change this situation, making it possible to overlay different images and apply a (rigid) transformation if necessary to aid alignment... but as one project among many, it could take some time for the changes I'm making to become really useful.  And I'm not actively working on any more complex registration - just shifts and rotations.

Can you say more about what your aim is?  For example,
* Do you primarily want this for visualization or analysis?
* Do you have different tissue sections, or the same tissue restained?  (I guess the first, but the second is certainly easier on the image processing side...)
* Which stains (colors) are you using for each TMA?

I'm not sure if it helps or you have already seen it, but with [Multiple viewers](https://github.com/qupath/qupath/wiki/Multiple-images) it is already possible to view different TMA cores side-by-side, and then navigate the grid using the arrow keys.  TMA cores at the same grid location will be displayed together.

You could also export each TMA core as a TIFF image from QuPath, and explore aligning these using some of Fiji/ImageJ's [image registration](https://imagej.net/Category:Registration) tools on a core-by-core basis.  This could require quite a bit of effort.

> Sidenote: I'm using [this blog](https://petebankhead.github.io) to describe some of the updates I'm working on, but which aren't yet in a QuPath release - it's also a good place to give feedback/suggestions to help shape where the changes go.

**Comment by YHGim** [comment]
Thank you for the reply.
Currently my aim is to cut identical areas in the same TMA slide but with different antigen captured.
All IHC are DAB-based, so all antigens are expressed in brown
(we are not using multicolored multiplex IHC). 

We scan a TMA slide after IHC, bleach it clean, and then repeat IHC and scanning with the next antigen. 
So technically all our scanned slides are from one identical slide, but after the scanning process 
the slides are misaligned and aligning the whole slide (or even a TMA core) 
without sacrificing image quality was impossible
(at least with a normal desktop with i7 cpu and 32gb of ram). 

For now, we manually cut parts of TMA image (about 4K x 4K pixels), align images, and overlap perfectly align images with cellprofiler.
 
I thought it would be much easier to cut the images from identical regions if tiles provided from
qupath could be moved and rotated (as a sequence of rough alignment before perfect alignment with
cellprofiler) since we are using literally putting rulers on monitors to get a similar region from different scans.

**Comment by petebankhead** [comment]
Ah!  Bleaching and rescanning changes things; what I'm currently working on *might* be exactly what you need.  This is some related discussion on [Google Groups](https://groups.google.com/d/msg/qupath-users/XNdaWK_9Ex4/VKHAbBGDBAAJ).

If you'd be interested in collaborating on this, and perhaps sharing some images to help me develop the tool to do what you need, please send me a message.  I'm quite find-able on Twitter, ResearchGate or LinkedIn... or if you sign up to the QuPath Google Group I'll get a notification and can write to you directly.

Otherwise I'll post a reply back here once I have something worth testing, but I haven't got an expected timeframe yet. 

The CellProfiler bit is also interesting.  If we can achieve the alignment then maybe this step wouldn't be necessary and everything could be done in QuPath.  But if you do need more CellProfiler-specific functionality then it would be good to discuss if there's a way to help streamline that bit of the process too - since better integration with CellProfiler is something that has already come up (e.g. #123).

**Comment by YHGim** [comment]
I would like to share images if it helps the developing process, but for the time being, 
I don't have my own material that I can use without permission (I'm helping someone else's 
research). I hope that I find a proper subject that I could do my own multiplex IHC slides and perhaps
contribute to your development soon.

**Comment by petebankhead** [comment]
Thanks for your reply - and no problem, that's the situation I usually find myself in too.
