### ISSUE TITLE
Automatic Quantification Issue

### ISSUE THREAD

**Issue by MegMTD** [qupath/qupath#163]
Hello,

I am having trouble with automatic quantification for cellular staining (ISH with puncta) using QuPath. 
I have worked on counting ISH-puncta inside the neuron (mainly DRG or spinal cord).

The program I use is below.
1. Open ND2 file
2. Draw the cells by hand
3. Turn annotation into detection with script
4. Analyse -> Cell Analysis -> Subcellular detection

Everything was going well until now. However, the program did not work suddenly even though I did not change anything. After turning into the detections, I cannot carry out subcellular detection analysis. The images I took previously still work well now even though I took and saved the images the same way, same setting, same file type. Do you have any solutions? 

I found the window of "Subcellular spot detection" has changed. "Spot & cluster parameters" has gone.

Before
![2018-04-06 20 12 47](https://user-images.githubusercontent.com/38146083/38448988-801756b2-39d7-11e8-9c2f-72b9dfe16258.png)
 
Now
![2018-04-06 20 15 30](https://user-images.githubusercontent.com/38146083/38448999-99ee0f36-39d7-11e8-8ec7-a8087e40e9cd.png)

And also now I cannot get the "Centroid X/Y data" on annotation measurements.
![2018-04-06 20 19 23](https://user-images.githubusercontent.com/38146083/38449026-f5001298-39d7-11e8-8fce-4e077545e43c.png)

Do you have any solutions?

Thanks,

**Comment by Svidro** [comment]
The last time I remember those fields being missing from an image, the pixel size information was missing from the metadata.  For example, if you load a basic JPG file into QuPath, you will see the same missing Spot and cluster parameters since there are no micron based measurements to make.

**Comment by Svidro** [comment]
I haven't yet had time to write up my guide on google groups, but at the following link 
https://gist.github.com/Svidro/6171d6d24a85539d3af5d417bc928d50

**Comment by MegMTD** [comment]
Thank you for your prompt reply. 
I checked and made sure them as per your suggestion. Although the original files have their metadata (Pixel width/ height), they have been missing after loading into QuPath.

I can use the QuPath program on the pictures taken before, and they still have the metadata after loading into QuPath.
![2018-04-07 14 48 28](https://user-images.githubusercontent.com/38146083/38459044-d6b4add0-3a72-11e8-96fb-894f69624a8d.png)

However the pictures taken recently have lost their metadata after loading into QuPath.
![2018-04-07 14 51 12](https://user-images.githubusercontent.com/38146083/38459068-268df8d4-3a73-11e8-9075-84300f43d46b.png)

What could be the problem? Do you have any solutions?

And also I appreciate your advice about nuclear counting. Actually what we need to do is "counting the ISH-puncta inside the cell", not nuclear. Pete helped us on this program before. Here is the link (https://groups.google.com/forum/#!topic/qupath-users/_k4SkC445ZE).

Thanks,

**Comment by petebankhead** [comment]
It's strange that the pixel sizes are now missing...  do I understand correctly that they are visible in the Nikon software?  Is there any possibility they were saved with a different version of the software, or someone else might have changed some obscure setting?

Your description and the screenshots are very helpful to rule out some of my other guesses; because the images are both described as 14-bit and read using Bio-Formats, I don't see any clear reason why there would be a problem - although I see there is a small difference in the width & height, which makes me wonder if there was at least some small change at the time of acquisition... but I don't know what.

I'd suggest trying to open the images in [Fiji](http://fiji.sc) and checking under *Image &rarr; Properties...* to see if the pixel size information is there.  If it is, the first thing I'd do is make sure you have the latest [QuPath Bio-Formats extension & bioformats_package.jar](https://github.com/qupath/qupath-bioformats-extension), and try again.  Alternatively, you can manually enter the pixel width & height values in Fiji (if you know them - is it safe to assume they are the same as in your other images?).  Then you can save the image with pixel sizes as a TIFF in Fiji, and read the TIFF rather than ND2 file into QuPath.

However, I should warn you: if you use the save-as-TIFF-in-Fiji trick, then ImageJ will be used to read the image and there is an unfortunate bug in QuPath v0.1.2 that means for this application you should probably also change the preferences to only use 1 parallel thread (described [here](https://github.com/qupath/qupath/issues/74)).  Alternatively, you could try the latest-not-quite-released QuPath changes described [here](https://petebankhead.github.io/qupath/2018/03/19/qupath-updates.html), which should include a fix for the bug.

(In case that sounds alarming: the bug shouldn't cause any trouble if you see *Server type: Bio-Formats* or *Server type: OpenSlide*, only *Server type: ImageJ* is affected - and even then not always.  It should be fairly clear if it causes trouble, in that spots appear where they shouldn't.)

**Comment by Svidro** [comment]
Oh, I didn't realize you worked with him!  I have chatted with Alex a bit from the microscopyra account.  I would guess something changed with how you are taking or processing the images before loading them into QuPath.  One he checked early on was whether the metadata showed up in the default Nikon viewer, so I would start there.  It is probably there, but I want to start from being sure of that point!

Another thing is I think you might have been working with MIP files, so I would check to see if both the originals AND the MIP both have the correct metadata.

Finally, one option might be to add the metadata back in.  In one of the emails to Alex I mentioned how to add the metadata into the .nd2 files using ImageJ.  If you want to try that... And Pete just beat me to it  :)  You should be able to use that Image-Properties to edit the correct pixel data back in!

**Comment by MegMTD** [comment]
Thank you so much. Actually we frequently faced the problems on our microscope these few months and we renewed the software. Although the timing at which the software was renewed is not coincident with the timing at the problem occurred, that could be the cause of the problem. I will try all of your suggestions. 

Thanks again,

**Comment by MegMTD** [comment]
Hi,

I tried some of your suggestions, but I cannot figure out yet. Could you tell me how to add the metadata into the ND2 files using ImageJ, again?

Thanks,

**Comment by Svidro** [comment]
In ImageJ it's quick, but as Pete mentioned, you can't actually save the file as a .nd2 file (unless there is a plugin that I do not know of!).  If you use FIJI, you can save as an OME-TIFF, which will open with the Bio-Formats server, thus avoiding the threading problem (I think) that Pete mentioned above, so I would recommend that.

Open FIJI/ImageJ, then File->Open your .nd2 file.
Then go to Image-> Properties, and change your XY pixel sizes to whatever you want.
![change pixel size 1](https://user-images.githubusercontent.com/23145209/38470206-591f7e0c-3b14-11e8-8588-0952d4715b42.JPG)
![change pixel size 2](https://user-images.githubusercontent.com/23145209/38470212-5d7bdad6-3b14-11e8-97d9-586637de7659.JPG)

Save as the OME-TIFF type, which for me was all the way at the bottom of the Save as... menu.

I looked into a couple of other programs to try to edit the metadata while still keeping the file as .nd2, but did not have any success with nip or XnView.  If you do convert, definitely keep both versions of the file!  While the TIFF will have pixel sizes, it will not have most of the other metadata contained in the .nd2 files, such as microscope settings.

**Comment by MegMTD** [comment]
Thank you for your kind information! I will try soon.

Thanks again,

**Comment by Svidro** [comment]
Also, since these files are being read with the Bio-Formats extension, I looked that up quickly and at:
https://docs.openmicroscopy.org/bio-formats/5.7.2/formats/nikon-nis-elements-nd2.html
You can read that there are two versions of .nd2 files.  It may be that previously you were saving as the older version (jpeg2000 compressed) versus the new version which may be ZIP compressed.  I am unsure if the updates you mentioned might have transitioned you between versions, but there may be some file settings you could change regarding how it compresses your data.
