### ISSUE TITLE
Deep Java Library problem

### ISSUE THREAD

**Issue by RAHoebe** [qupath/qupath#1640]
Hi,

I spend a few hours to get the Deep Java Library, PyTorch to work. And I did not succeed. Installed Cuda 11.8 and cudnn 11.x. Made a python env with mamba, created the launcher. Changed my System Path. And finaly it seemed to work. But:

ai.djl.pytorch.jni.LibUtils - No matching cuda flavor for win-x86_64 found: cu118

Looked at all forums and searched the internet.

I am sorry to say, but I give up. There is just no way to get this running easily it seems. So no InstanSeg and other Deep Learning models that depend on this Deep Java Library for me. 

There just must be a way to make it work more easily. Maybe just use the python version (like BIOP/Cellpose does). In that case you depend on a single python environment!

Best, Ron

**Comment by alanocallaghan** [comment]
I think it would be better to post a question like this on [the forum](https://forum.image.sc/) along with a clear description of what you tried, which software versions you're working with, etc.

> So no InstanSeg and other Deep Learning models that depend on this Deep Java Library for me.

DJL generally and InstanSeg specifically should still work with CPU support only.

> There just must be a way to make it work more easily

We have indeed done our best to do so; it's not necessarily easy to handle all of the possible configurations people have

**Comment by petebankhead** [comment]
See also https://github.com/qupath/qupath/issues/1636


> Maybe just use the python version (like BIOP/Cellpose does). In that case you depend on a single python environment!

My understanding is that the BIOP CellPose extension will [write all the tiles to disk, then effectively run CellPose from a command line](https://github.com/BIOP/qupath-extension-cellpose/blob/b97efdad82df59ace5a149ca91f7fb963549bcc5/src/main/java/qupath/ext/biop/cellpose/Cellpose2D.java#L390). That may be easier for configuration, but it will surely reduce the benefits of using the GPU. It can be justified for CellPose because it is infeasible to recreate the required postprocessing in Java, but for InstanSeg we would suggest instead just using the CPU - or discussing on the forum. Perhaps someone there might figure out instructions that work where our existing ones do not.

I will close this because there is no bug in QuPath described here that we can fix.

**Comment by RAHoebe** [comment]
Hi

Your right it is (maybe) not a bug. But the beauty of QuPath is/was the ease of use and ease of installing. We run it on 20+ workstations. But these new extensions that use the DeepJava Library are (for me) a big pain. Maybe you (not me) can after installing all the prerequisites and tweaking get it working. But it will be impossible to install it next to many other programs on all our workstations. There must be a easier way. Or a better explanation.

And for just using the CPU only. I still had to do all the Cuda and tweaking. Out of the box it does not support CPU only.

Best, Ron

And just to be clear. I love your work!!! I love QuPath!!!
