### ISSUE TITLE
macOS Applications Signed with Ad-Hoc Certificate

### ISSUE THREAD

**Issue by uurazzle** [qupath/qupath#1672]
Hi:

The latest release of the QuPath v0.5.1:

[QuPath-v0.5.1-Mac-arm64.pkg](https://github.com/qupath/qupath/releases/download/v0.5.1/QuPath-v0.5.1-Mac-arm64.pkg)
[QuPath-v0.5.1-Mac-x64.pkg](https://github.com/qupath/qupath/releases/download/v0.5.1/QuPath-v0.5.1-Mac-x64.pkg)

The issue with Mac applications that use ad-hoc signatures is that, while they provide a code signing digest (or cdhash) allowing macOS to verify whether the app or component has been altered, they don't verify the identity of the developer. This means that macOS can detect if the code has changed but has no way to confirm who signed the code or if it comes from a trusted source.

Key concerns with ad-hoc signatures include:

No Developer Identity Verification: Ad-hoc signatures don’t provide information about the developer’s identity, unlike certificates from Apple, which are linked to verified developer accounts. This can pose security risks as it’s harder to establish trust in the source of the code.

Limited Use Cases: Ad-hoc signing is typically used for specific scenarios, such as:
Unsigned code running on Apple Silicon, where macOS requires all code to be signed, even if it’s just ad-hoc.
Web Apps on macOS 14 Sonoma, where the code isn't distributed via traditional app distribution methods.

Security Risks: Since there is no certification authority involved in ad-hoc signing, it is easier for malicious or unauthorized code to be signed ad-hoc and executed, which could expose the system to potential vulnerabilities.

I would recommend moving away from ad-hoc certificates and following the Apple Developer guidelines on application creation &  distribution.

For example, here is a free GUI application called "Apparency" that will help explain issues and test your applications.
https://mothersruin.com/software/Apparency/

![image](https://github.com/user-attachments/assets/d69830e4-e271-430a-987c-c58b1b708481)
![image](https://github.com/user-attachments/assets/4a03b7ba-c911-486b-91de-2d86d0eefc2c)

I thought this post from Quinn “The Eskimo!” @ Developer Technical Support @ Apple would be good to share with your Mac development team:

Resolving Gatekeeper Problems | Apple Developer Forums:

The post titled "Resolving Gatekeeper Problems" on the Apple Developer Forums, written by Quinn "The Eskimo!" from Developer Technical Support at Apple is a comprehensive guide addressing common issues related to Gatekeeper on macOS. Gatekeeper is a security feature designed to ensure that only trusted software runs on a user's Mac, and the post focuses on helping developers troubleshoot and resolve issues that may arise in this context.
The post identifies four common Gatekeeper problems that developers may encounter:

1. App blocked by a dangling load command path.
2. Broken code signature.
3. Lack of notarization.
4. Command-line tool blocked by Gatekeeper.

For each of these issues, the post provides detailed steps and guidance on how developers can resolve them. The emphasis is on the importance of passing Gatekeeper checks to maintain customer trust and avoid potential loss of customers.
Key points covered in the post include:

• Verification of Code Signature: Developers are advised to use the codesign tool to verify that their code is signed correctly. The post provides examples of command-line usage to check for issues such as missing or invalid sealed resources.
• Notarization Issues: Gatekeeper requires that apps be notarized, and the post guides developers on how to identify and resolve notarization problems. It includes information on checking system logs for specific entries related to notarization issues.
• Hash Mismatch: In cases where there's a hash mismatch, the post provides guidance based on the file type (e.g., zip archive, signed disk image, installer package) and recommends specific actions to address the problem.
• Command-line Tool Blocking Bug: A known bug in macOS is acknowledged, where double-clicking a command-line tool in Finder may lead to it being blocked by Gatekeeper. Workarounds, such as embedding the tool in an application or using an installer package, are suggested.

Throughout the post, there are references to Apple's documentation and resources related to code signing and notarization, providing developers with additional information for a deeper understanding.

https://forums.developer.apple.com/forums/thread/706379

**Comment by petebankhead** [comment]
Thanks, we're aware this is an issue, and not only on Mac. It has come up several times, e.g.
* https://github.com/qupath/qupath/issues/1605

and is [mentioned in the docs](https://qupath.readthedocs.io/en/0.5/docs/intro/installation.html).

As far as I can tell, any solution would require an Apple developer account (at a cost), which no QuPath developer currently has. And if we were to do it for Mac, we really ought to do something similar for Windows since a much higher proportion of our downloads are for Windows.

As an open-source project, we don't have the time or resources to deal with these issues currently. We aren't *too* concerned about losing customers as we don't sell anything. The other main open-source software applications for bioimage analysis have the same issue and I'm not aware of any of them providing signed applications.

We do provide instructions to [build QuPath from source](https://qupath.readthedocs.io/en/stable/docs/reference/building.html) for anyone who needs to take extra steps to ensure they are confident in the source of their own build. With Gradle, the process should be relatively painless - at least compared to building most native applications.

I certainly agree it's annoying and seems to get progressively more annoying with every operating system update (I'm a Mac user myself). I'll close this issue since it isn't a 'bug' as such, and not something we can address in the near future. If/when we do, we'll need to consider code signing across all platforms  - so I've created https://github.com/qupath/qupath/issues/1731 and linked to this post for reference, so thanks again for the detailed information and links.
