### ISSUE TITLE
MSI installer tries to install in AppData even when runned in admin

### ISSUE THREAD

**Issue by skid9000** [qupath/qupath#1703]
## IMPORTANT!

This section is **only** for bug reports, which **must** follow the template below.

Please post any other questions to the official QuPath forum at https://forum.image.sc/tags/qupath

If in doubt, use [image.sc](https://forum.image.sc/tags/qupath). This helps us keep things organized.

## Before we begin...

Before submitting your bug report, please check the following:

* [x] I've definitely found a bug (it you're not sure, please use [image.sc](https://forum.image.sc/tags/qupath) instead)
* [x] I've checked https://qupath.github.io for a new release that might already have fixed the issue
* [x] I've checked the [Changelog](https://github.com/qupath/qupath/blob/master/CHANGELOG.md) to see if the bug has already been fixed in the next release
* [x] I've checked for existing GitHub issues describing the same problem

### Describe the bug

The MSI installer always install in AppData by default now instead of Program Files, which results in being unable to deploy it properly by an IT department even when the ALLUSER var is at 1.

`msiexec /i QuPath-v0.5.1-Windows.msi ALLUSERS=1 /qn`

![image](https://github.com/user-attachments/assets/cf66ffbc-0f2d-46d2-9280-7b03d2740182)

### Desktop (please complete the following information):
 - OS: Windows 10 22H2
 - QuPath Version: 0.5.1

**Comment by petebankhead** [comment]
QuPath builds are made using `jpackage` and we are limited by the options it provides.

It looks like it may be possible to change this only at the point the .msi is created. The options are specified [here](https://docs.oracle.com/en/java/javase/21/docs/specs/man/jpackage.html). So you might want to try modifying this and [building QuPath from source](https://qupath.readthedocs.io/en/0.5/docs/reference/building.html) if you need a package that behaves differently.

Please see also [this forum discussion](https://forum.image.sc/t/qupath-windows-installer-configure-shortcut-location/44632).

I think the forum would be a better place to discuss this, because as far as I can see it isn't a 'bug' that we can fix - rather it's a choice between which options to provide to `jpackage`, and it would be worth requesting more opinions or potential workarounds.

**Comment by skid9000** [comment]
Not a lot of people are going to look on the forum unfortunately especially an IT department or occasional users.

I think the problem is in this option : https://github.com/qupath/qupath/blob/4e6691470de88459a580727b01d61892bf253341/qupath-app/build.gradle#L594C9-L594C62

```
--win-per-user-install

    Request to perform an install on a per-user basis

```

I'm not sure what it will be using by default once this option is removed, tho, that path could always be set through the `--install-dir` option.

Imo an msi installer should always install system-wide by default unless told otherwise.

**Comment by petebankhead** [comment]
Are you able to try removing the option to see how the behavior improves? I can't easily access a windows system to test this, and don't know what kinds of options are used by IT departments for deployment.

I gave a link to build from source in my last post.

> Not a lot of people are going to look on the forum unfortunately especially an IT department or occasional users.

There are over 4,500 qupath-tagged discussions there, with tens of thousands of posts... it's the main place for users to discuss the software. We try to keep GitHub issues limited for clear bugs / task planning.

Since the .msi for the current release has been downloaded over 64,000 times, and we haven't made any change to the installer for a long time, making a change seems almost certain to annoy some users who rely on the current behavior - so I'd be reluctant to do it without trying to reach as many potentially-affected people as possible for feedback.
(Note that we also provide a .zip distribution, and instructions for anyone who wants to make a different build.)
