### ISSUE TITLE
Is there a way to create single "horseshoe" polygon around hole regions?

### ISSUE THREAD

**Issue by rwtam121** [qupath/qupath#177]
I'm wondering if it's possible for QuPath to automate a process that draws something like the below right image, breaking apart the lines of the left image. 
![image](https://user-images.githubusercontent.com/29108723/41568774-90e2c228-731c-11e8-993b-94d0641e4fd2.png)

I ask because when deploying my qupath coordinates to a server the server currently does not support hole generation. I also don't want to force a connection between the outer and inner polygons, leaving a line in between the two. So I was wondering if the "horseshoe" idea is possible...can we write code to break a small part of the inner and outer polygons and establish a connection between them, and do this across all inner polygons (if an outer polygon has multiple inner polygons?).

**Comment by petebankhead** [comment]
It's an interesting idea and challenge, but I agree with @Svidro - it would be hard to solve in a really generic way.  And then there are potential issues with having multiple holes within the same annotation, or multiple disconnected regions as well as holes...

Can you describe a bit more why this is necessary?  For example,

- In which format do you plan to export the polygons?
- Do you need to visualize the polygons on the server, or just store them there?
- Do the polygons need to be used for measurements / analysis in software other than QuPath?

If only for storage, alternative approaches might be

* Store binary images representing the annotations instead
* Store zipped .qpdata files

If not need visualization too, you could potentially export separate exterior and hole polygons - and then flag which is which using a naming scheme or colors.  The 'true' shapes might then be recreated with an import script in QuPath, if necessary.

**Comment by Svidro** [comment]
I wonder if there is some way to convert AWT objects into polygons?  You could then classify by parent/child and export two sets of polygons... which you might be able to subtract on arrival or use one set for exclusion.  Which I suppose fits in with the questions about final use.

**Comment by rwtam121** [comment]
Thanks for the responses. @Svidro , yeah @petebankhead provided code to split area AWT regions into polygons here: https://github.com/qupath/qupath/issues/99. It definitely works to isolate the parent/child polygons and is a step in the right direction; plotting area AWT creates all these interior regions which cannot be drawn without extraneous lines in my server, since it doesn't support hole generation.

@petebankhead , my workflow involves exporting the polygons into a text file and consolidating its coordinates into a JSON format. I am visualizing the polygons on the server (and also storing its respective JSON as well). If the server supported reading in a JSON format that accepted holes, it would look something like this (via geojson, which unfortunately our server does not support currently):

![image](https://user-images.githubusercontent.com/29108723/41989496-55d49dc6-79f4-11e8-83bd-f831223e6b15.png)

Without hole support, I'm currently visualizing the "hole" region by through the use of overlapping polygons in the server (those polygons created from the split AWT in QuPath). For instance, in the below image in the server, class 1 has the two overlapping polygons indicating that its larger polygon has a hole in it; class 2 is the region that fills that hole. 
![image](https://user-images.githubusercontent.com/29108723/41990309-e57de9e4-79f6-11e8-8b5d-7f8725a44ad5.png)

But that's inelegant for visualization, which is why I wanted to look into the horseshoe idea. The server renders polygons that connect to the exterior well, and if we can draw lines connecting to the outer region within QuPath that would help (even if it seems difficult and troublesome as you mentioned).

**Comment by petebankhead** [comment]
I guess since the split method gives you the arrays for the exterior polygons and for the holes, you could do an exhaustive search for the pair of vertices where one of the points on the exterior is closest to a point on the interior.  Then insert the interior points into the exterior polygon's list of vertices and... see how that looks.

It sounds like you've been able to get all the data out of QuPath, and now it becomes a problem to solve elsewhere.  Not sure how much influence you have on the server, but getting it to support GeoJSON/shapes with holes would sound more rewarding... albeit potentially difficult.

I can definitely envisage writing a generic GeoJSON exporter for QuPath ROIs; that sounds like something worthwhile (related to the recent discussion on [shapefiles](https://github.com/qupath/qupath/issues/95#issuecomment-395886486)).  This has been on my personal todo list for a while, but pretty low priority as I don't have a specific need for it at the minute - and nor do I know of anyone with such a need.  It would definitely be higher priority it it helped interoperability with software for some genuinely useful purpose.  But I'm not sure if it would help much in your case, unless you can get your server to support GeoJSON.
