### ISSUE TITLE
Save .roi files by script

### ISSUE THREAD

**Issue by Philipp-Seidel** [qupath/qupath#182]
Hello,

Instead of just displaying the ROIs of detections with their annotations (as color code), as it occurs by pressing the button "Export to ImageJ --> send region", it would be great to save those detections (with annotations) in a .roi file so it can be read by "normal", external ImageJ.  
Could this be done in a grooyv script?
 Best regards and merci
Philipp

**Comment by petebankhead** [comment]
Potentially, but since ImageJ couldn't read any corresponding whole slide image (at least not at full resolution, in one go) then in general the ROIs would need to be scaled/translated to be useful.  If that happens, then you would most likely either require the pixels as well (similarly scaled/cropped), or at least the information regarding scaling/translation so that they could be requested in the future.

This all happens for you when send the region to ImageJ.  Once there, you can save the image as a TIFF from within ImageJ (which will preserve any active ROIs/Overlays).  You can also save an active ROI as a .roi file (_File &rarr; Save as &rarr; Selection..._), and use _Image &rarr; Overlay &rarr; To ROI Manager_ to send an overlay to the ImageJ ROI Manager - from which you can save individual ROIs, or all ROIs in a single zip file.  Furthermore, the image that QuPath sends to ImageJ has everything set under _Image &rarr; Properties..._ that is required to determine its original origin in the whole slide image - therefore it gives the pixels if you want them.

Therefore I think the functionality you need is already there (e.g. save the image QuPath sends as a TIFF, open it in any ImageJ/Fiji externally).  Potentially if you have a very well-defined export need that could be scripted to reduce the manual steps.  [My blog](https://petebankhead.github.io/qupath/scripting/2018/03/08/script-imagej-to-qupath.html) has some information about linking QuPath and ImageJ by scripting.

Does that answer your question, or do you have something else in mind?  If so, can you describe in more detail your preferred workflow?

**Comment by petebankhead** [comment]
What I am thinking of doing is writing a nice import script or command that can pull back ImageJ ROIs from multiple image tiles that have been processed externally of QuPath (e.g. by batch processing in Fiji) - and pulling them back into QuPath as objects in the correct positions for visualization in the whole slide image.

Not sure if that would be relevant to you, let me know if so.  The main reason I haven't bothered to do it yet is that I haven't needed it myself, and no one has asked.

**Comment by Philipp-Seidel** [comment]
Okay, I think I describe what I want to do. And I would like to do that as automatically as possible, so in qupath in a .groovy script, I guess:

1) I have a folder with IHC-fluorescence images (DAPI + antibody staining) of tumors with stroma

In Qupath:
For every image of the folder:
2) In QuPath - perform cell detection
3) In Qupath - object classification with a pretrained classifier (tumor vs. stroma)
4) Export detections with annotation into .roi file

In Fiji:
For every image of the folder:
5) open .roi file
6) --> discriminate tumor and stroma
7) perform DNA-damage focus analysis in tumor and stroma separately (algorithm potentially uses other Plugins)
8) Finished

So, I want to use quPath for what it does very, very good and fast, cell identification, segmentation and classification, and not for anything else. Scripting in FIJI is more or less easy for me, so once I have the .roi files, I can do almost anything with them there. Just, for the "QuPath part", I dont even know how to script those simple steps, because there is not much documentation, no Qupath API, so its hard for me to even get started. I am not a professional programmer, but a biologist with some (Python, Java, ImageJ) programming background,

So, do you think, something like this is possible?

Overall, its very sad that there is so limited possibilities for scripting and export of those objects. It kind of destroys all that nice classification features, because it cannot be integrated in practical workflows. I think, the project would profit a lot to improve there asap, because, the core functionality itself is very interesting for people. Segmentation is either too slow, too complex or not precise enough with other tools.

Best regards and thank you
Philipp

**Comment by petebankhead** [comment]
> Okay, I think I describe what I want to do. And I would like to do that as automatically as possible, so in qupath in a .groovy script, I guess:
> 
> I have a folder with IHC-fluorescence images (DAPI + antibody staining) of tumors with stroma
> In Qupath:
> For every image of the folder:
> 2) In QuPath - perform cell detection
> 3) In Qupath - object classification with a pretrained classifier (tumor vs. stroma)
> 4) Export detections with annotation into .roi file

Ok, you don't describe your images being whole slide images - so I assume they can be read into ImageJ fully and without problems.  In that case, you might try this QuPath script:
https://gist.github.com/petebankhead/8d541effc8898d6a07edd4ed95b6929c

Keep in mind that a `.roi` file contains a single region; as far as I'm aware, a `.zip` file is needed for all the QuPath objects to be represented in a way ImageJ can access all in one go.

> So, I want to use quPath for what it does very, very good and fast, cell identification, segmentation and classification, and not for anything else. Scripting in FIJI is more or less easy for me, so once I have the .roi files, I can do almost anything with them there. Just, for the "QuPath part", I dont even know how to script those simple steps, because there is not much documentation, no Qupath API, so its hard for me to even get started. I am not a professional programmer, but a biologist with some (Python, Java, ImageJ) programming background,

Ok, but please keep in mind that ImageJ has existed in some form for more than 30 years, and has had input from many fantastically knowledgeable people both in terms of development and documentation.  There has been a huge amount of volunteer effort, alongside many components and plugins developed as part of larger, funded projects.

On the other hand, QuPath was created and documented essentially by one person and has only been available for a couple of years.  The same person also wrote all the wiki, the [blog](https://petebankhead.github.io), is the main person writing scripts to everyone who asks on GitHub and Google Groups, teaches workshops on it when invited and has got time, and wrote detailed instructions for setting it up with IntelliJ to script with auto-completion & access to the full source code (and internal javadocs) [here](https://github.com/qupath/qupath/wiki/Advanced-scripting-with-IntelliJ).  At this time, all continued work and support is entirely unfunded and unpaid.

I'm also not a professional programmer (nor a biologist).

As described in the [Getting help](https://github.com/qupath/qupath/wiki/Getting-help) section of the Wiki, the [Google Group](https://groups.google.com/forum/#!forum/qupath-users) exists to answer questions and cover any gaps in the documentation.

Therefore, please do try to be fair in your expectations :)

> Overall, its very sad that there is so limited possibilities for scripting and export of those objects. It kind of destroys all that nice classification features, because it cannot be integrated in practical workflows. I think, the project would profit a lot to improve there asap, because, the core functionality itself is very interesting for people. Segmentation is either too slow, too complex or not precise enough with other tools.

I hope the above comments explain why this is the case.  The possibilities with Groovy are pretty limitless - sometimes all it takes is to ask.  But the software is being used by hundreds of groups across the world for very different applications (if you see the [Citing QuPath](https://github.com/qupath/qupath/wiki/Citing-QuPath) page you will observe that others _do_ manage to use it in 'practical workflows'), and from what you describe you aren't working with whole slide images.  Adding the functionality you want to the core software would potentially not benefit anyone else using it... which is why the ability to script things is so essential.

I wish the software could do everything already, but it's a process.  But for reasons that should become clear in the next few months, it's a pretty exciting time and I hope you'll like what is to come over the next year or two.

**Comment by Philipp-Seidel** [comment]
![roi_image](https://user-images.githubusercontent.com/40424957/42136435-27fb3254-7d53-11e8-849a-be9f82ae2613.png)

Dear Pete,

yes, I chose the wrong words, I didnt want to say bad things about QuPath, I like it. I just described what I miss most (acutely, get the .rois to ImageJ and in general, some API to look up classes and methods and so on), with caring too less about my wording. I am sorry. 
Yes, I am not using whole slide images this time, but IHC-fluorescence. And I want to quantify DNA-damage foci and that I know best in ImageJ. I tried to attach an image, so the script for the .rois works very well, thank you.

But I would like to do more with QuPath, now that I know the .rois get out, I can write the script to do the cell detection and the classification for the whole folder of images automatically.

And I also like to contribute to the project, so if there is a place to donate...
Best regards
Philipp

**Comment by petebankhead** [comment]
No problem, thanks for your reply.

If you have an ImageJ/Fiji macro/script that completes your analysis (once the ROIs are out), then I could think some more about whether the entire thing might be callable from within QuPath.  It's already possible to connect QuPath to a specific ImageJ plugins directory for an existing installation (through _Edit &rarr; Preferences..._), and thereby do more complex ImageJ analysis - including the use of additional plugins - all launched and managed from within QuPath via Groovy.  However, I haven't got that to work with _all_ plugins and functionality of Fiji because of conflicts in dependencies... or perhaps just because I don't know enough about the ImageJ2 API.

That might well be solvable if it turns out to be necessary, but it hasn't been something I've needed myself or anyone else has asked for yet (that I recall).

Direct export of ROIs only wouldn't help most QuPath applications, for the reasons outlined above (i.e. most are for whole slide images, in which case you'll need to scale the image as well - and then exporting the pixels as well as the ROIs is necessary, which _is_ possible).  But I appreciate that it makes sense in your case.

Just to be clear: you should be able to run the script unchanged across your entire folder if you just add all the images to a QuPath project, and choose _Run &rarr; Run for project (without save)_ from the QuPath script editor.  Because that script doesn't make changes, there's no point saving the (same) results after running the script to update the `.qpdata` files... although it also shouldn't matter if you do.

Regarding documentation, at the time of the QuPath's release I was in the process of leaving the university where I wrote it, and lacked the time and resources to document the API and find somewhere to host it; also, I didn't consider it stable enough at that point anyway, and planned to continue working on it.  For reasons largely beyond my control this wasn't possible, unfortunately, but you can access a lot of the existing Javadocs through setting up scripting with IntelliJ (and indeed a similar process works to set up IntelliJ for Groovy scripting with Fiji).

In a couple of months I will start a new position and be able to manage QuPath as a more active open source project - and be a bit stricter with myself about compiling the Javadocs and finding a home for them.  In the meantime, there is some additional documentation and developments described on [my blog](https://petebankhead.github.io).

**Comment by Philipp-Seidel** [comment]
Dear Pete,

Sounds good. From the outside, maybe I can give two remarks that might be helpful to consider:

Because QuPath is your "baby", you are thinking a lot about how to include outside functionality (ImageJ) into QuPath. At the same time, you say rightly, ImageJ has much more documentation and support, and more users and more diverse users. Maybe it might be a good project to access QuPath from ImageJ, either the whole GUI, but even better, just its functional structures, by writing a ImageJ Plugin. And I guess, you would not necessarily need to do that yourself, because it might be easier to find someone to help, because there is more people experienced with writing ImageJ Plugins.

QuPath itself is really good for Digital Pathology, and Digital Pathology is booming. A lot of people probably already gave you very positive feedback. This means, there must be ways to get more funding for that project and then you can actually hire people to do the programming. But somehow I think, you might have thought about that already.

If there is anything I can help with (unfortunately not programming a software), I would like to support.
Best Philipp

**Comment by petebankhead** [comment]
It's not so much that QuPath is my baby - it is more the other aspect you allude to, i.e. that there are certain tasks that (realistically) only I can do at this time because they are entwined with QuPath itself, whereas others could work on things like ImageJ integration if they wanted.  I'm not personally very interested in maximizing QuPath use or replicating what other software already does well, I'd prefer people use the right software for the job - and for QuPath to fill an unmet need.  I personally still use and recommend Fiji a lot, and when I teach general bioimage analysis courses I use Fiji, not QuPath.

I've considered a few times creating a QuPath-related update site for Fiji, but haven't found a compelling reason to do so.  I've also learned that everything costs not only the time to create it, but also to support it; additionally, something like this can place constraints on how QuPath can be further developed if backwards compatibility needs to be maintained.  This effort might distract from other efforts that are more likely to lead to a more compelling argument in favor of funding continued work, so I haven't done it.

The main way that anyone can help is to make sure to [cite the _Scientific Reports_ paper](https://github.com/qupath/qupath/wiki/Citing-QuPath) whenever QuPath is used in any publication.  I'm also very interested in any particularly exciting academic collaborations that may lead both to new functionality of general applicability being created, and also to joint publications that might help maximize the potential to obtain funding for continued development.  But again I need to be selective; there are lots of things I am already working on and many more I would like to do, and in recent times my decisions are guided a lot by what I believe is best for ensuring the sustainability and (more importantly) usefulness of the project in the longer term.
