### ISSUE TITLE
What's the meaning of specific features in Qupath?

### ISSUE THREAD

**Issue by XiaxiaMeng** [qupath/qupath#185]
I calculate some features in Qupath, like: coherence features, delaunay cluster features and smoothed features, but I'm not sure about the meaning of those features. Thank you so much!

**Comment by petebankhead** [comment]
I'm travelling and without access to a proper computer this week, but will try to write a brief description when I get back.

I have used smoothed features often, but not really the other two. There is more information on smoothed features at https://github.com/qupath/qupath/wiki/Classifying-objects

**Comment by XiaxiaMeng** [comment]
Got it! Thank you so much and looking forward to your description.
Have a good trip!

**Comment by DavidMHaumann** [comment]
hi, I use the coherence features as well. The mathematics are very abstract to me as well. 
But if you want to know, if these statistical values for superpixel or cell objects help you or not, you can figure that out by opening "measure" ==> "show measurement maps".   

![grafik](https://user-images.githubusercontent.com/16352785/42624909-cb6a0070-85c6-11e8-9d82-05e6406c2fe8.png)
you can then chose any calculated feature, and the meaning of the feature in terms of specificy to discriminate between different tissue areas is shown as a heatmap: 

![grafik](https://user-images.githubusercontent.com/16352785/42625007-0765924c-85c7-11e8-8247-af052d957923.png)

In most cases, haralick texture features are enough to segment tissue. 

The delaunay cluster features are useful in cell analysis to describe the cluster behaviour of cells (or other objects). It calculates all kinds of statistics about neighbour distance. It can also help to segment cell types, if a cluster behaviour is typical for a specific cell aggregation. 

The smooth features help a lot to segement an image homogeneously!  If you do not use smooth features, it can happen that single wrongly classified superpixels or cells appear in a tissue area.

**Comment by XiaxiaMeng** [comment]
Thank you so much! But I still feel a little puzzled about the specific meaning of indexes, like: OD mean, OD sum (25.0 um) mean and the number (50.0 um) of smoothed feature. Do you have more idea about that?
Looking forward to your reply, Thanks!

**Comment by Svidro** [comment]
[OD](https://en.wikipedia.org/wiki/Absorbance) is usually used for brightfield images while intensity is used for fluorescence images due to the way the light is measured (how much passes through your sample versus how much is emitted).  Sums and averages are exactly that based on all pixels, though usually applied to the detection area in question (a single SLIC, a single cell, or a single nucleus, etc).  If you had a 2 pixel detection of 1 OD and 0.5 OD, it would have a OD sum of 1.5 and an average of 0.75.  The distance value after the measurements using add intensity features determines how finely the features are calculated.  Smaller values tend to take longer but be more accurate, and I almost always use my pixel size (height or width) for any _Add intensity features._

Smoothing, as far as I can tell, is a straight radius for inclusion, calculated from the centroid of the detection object to the centroid of all other detection objects.  I tested this using the scale bar at 20um and two cells that were about 22um apart (center to center), and gradually expanded the radius until the smoothed features became a mix of the two (Nearby detection counts for each became 1).  The radius is a hard limit, while the smoothing is applied over a FWHM gradient as mentioned in Pete's link.

In that example, if the two cells were 22um apart and I performed a 22um smoothing, they would have less of an impact on each other's "smoothed" values than if they were only 5um apart.  A cell with a centroid at 23um away would have 0 impact on another cell's measurements, while a cell that was 22um away would have about half of the impact of a cell that was almost right on top of the original cell.  Every cell's smoothed features are calculated independently, imagine drawing a quick circle around each cell and calculating the smoothed features based on what centroids are inside that circle.

**Comment by Svidro** [comment]
More specifically for the coherence features, OD sum (you can have an OD sum sum, if you add up the total of each pixel's OD sum value, as opposed to the OD sum mean which is the average of each pixel's OD sum) will be the total optical density, and the tile diameter appears to be a circle/square around the centroid of the detection.  Here I ran the coherence twice on OD sum where i had a very dark center of the cell.  Notice that the sum/mean go up as I shrink the "tile" size to only fit inside the nucleus.
![coherence](https://user-images.githubusercontent.com/23145209/42643926-29b98578-85af-11e8-9c33-385e5588d7e3.JPG)
The most dramatic change is in the minimum, once the entire tile would fit inside of the dark "nucleus."

In general you might want to use that instead of smoothing, if you want ALL of the pixels around a detection out to a certain distance included in the measurement (tissue based measurements).

**Comment by XiaxiaMeng** [comment]
Thank you so much, it helped me a lot on the understanding of the indexes. @Svidro

**Comment by XiaxiaMeng** [comment]
Hi, Svidro
Thank you so much for your help on the understanding of the features’ meaning! Do you know how to draw the cluster of the cells, or calculate the cluster features, as the photo I attached. I know it’s easy but I can’t find the way to make it.
Thank you so much for your help!
Xiaxia

**Comment by XiaxiaMeng** [comment]
Hi, Svidro
Thank you so much for your help on the understanding of the features’ meaning! Do you know how to draw the cluster of the cells, or calculate the cluster features, as the photo I attached. I know it’s easy but I can’t find the way to make it.
Thank you so much for your help!
Xiaxia

**Comment by Svidro** [comment]
Sorry, I do not see an image on my end.  Not sure what you mean.

**Comment by Svidro** [comment]
You may want to try posting the question to the forum, as it seems more like a "how to use" question rather than a bug.  https://groups.google.com/forum/#!forum/qupath-users

**Comment by XiaxiaMeng** [comment]
Sorry, my question is how to draw the cluster of the cells, like how can I connect cells with each other and calculate its features?
 
 @![capture34](https://user-images.githubusercontent.com/41025519/42763310-a6c9e5ec-88e0-11e8-92a3-1a34092dbfe9.PNG)
Thank you so  @Svidro

**Comment by XiaxiaMeng** [comment]
Sorry, my question is how to draw the cluster of the cells, like how can I connect cells with each other and calculate its features?
 Thank you so much!
![capture34](https://user-images.githubusercontent.com/41025519/42763372-d6a28d46-88e0-11e8-815e-1e393f37d6dd.PNG)
@Svidro

**Comment by petebankhead** [comment]
@XiaxiaMeng This image was created with the help of 
* _Analyze &rarr; Calculate features &rarr; Add Delaunay features (experimental)_ (to calculate the features and connections)
* _Measure &rarr; Show measurement maps_ (to color-code the cells - you might not need this)

Note that the connection lines are only displayed when you're zoomed in.

**Comment by XiaxiaMeng** [comment]
@petebankhead I tried it, awesome!
Thank you!

**Comment by XiaxiaMeng** [comment]
Sorry, also there are some local binary pattern features, what's the meaning of the number of the OD sum LBP 1-18?
Thank you! @petebankhead

**Comment by Svidro** [comment]
I do not think they mean much on their own, other than what you can read in: https://en.wikipedia.org/wiki/Local_binary_patterns

I have mostly found them useful used as an entire set being fed into a classifier, where they can be used to find different "textured" areas.  How successful this is can heavily depend on your radius and sample variability within the color setup you have chosen.  Remember that OD sum will be gray-scale, the same as pressing "5" when you are in the main viewing window.

**Comment by XiaxiaMeng** [comment]
Hi! I find that there are some tools for calculating  TMA features, but I only have HE slides, I want to make sure can we get circular on HE slides, and assume it as TMA, and use the tools to calculate some local cluster features, or is there any method to extract the ROI or specific cells what we want to analysis.
Thank you!

**Comment by petebankhead** [comment]
I don't understand; most commands don't require working with TMAs and you can just apply them to other regions.  Can you describe more step-by-step what you want to do, and what the final output should look like?

**Comment by Svidro** [comment]
Any time you draw an annotation region, you should get separate statistics for that annotation in the Annotation Measurements.  So if you are able to manually draw areas, it should be fairly easy to group the results.

If you do a full tissue annotation, then generate your cells, you can create smaller annotations within the first annotation, then run the Delaunay clustering within each separate "sub-annotation."  Just select the annotation you want to perform the cluster analysis on before you click Run.

Note that the connecting lines will only show up for the most recent sub-annotation, though you can select more than one and run them all at once.

**Comment by Svidro** [comment]
I think if you want to add the number of clusters, or mean size of clusters, or anything like that to the annotation, you might have to do that through scripting.

**Comment by petebankhead** [comment]
> So I need to write scripting by myself?

Generally yes, if you want to do something non-standard... there is some more information under the [Automation](https://github.com/qupath/qupath/wiki) section fo the wiki.

In time, the software will have more features - but if you need something customized, or a feature that doesn't exist yet, then scripting is the way to do it.

There are lots of posts related to scripting at [Google Groups](https://groups.google.com/forum/#!forum/qupath-users) - which is generally a better place to ask questions than here, since this is really for 'Issues' (e.g. bugs, feature requests).  But it helps a lot to explain very clearly what you want to achieve, what you've tried, and ideally to include screenshots.

**Comment by XiaxiaMeng** [comment]
Thank you, later I will post my question at google group, and describe it more clearly.
