### ISSUE TITLE
Calculate the H-Score on TMA cores

### ISSUE THREAD

**Issue by Qasim2018** [qupath/qupath#190]
I am not successful in estimating the H-Score on my TMAs  based upon the percentage of the cell intensities. I am very new to this program and I do not know the geek stuff. I would really appreciate the help. Thanks

**Comment by Svidro** [comment]
A fairly complete description of TMA setup is here: https://github.com/qupath/qupath/wiki/TMA-CD3-analysis

The only difference for H-score is running "Positive cell detection" instead of "Fast Cell Counts"

You can find information on Positive cell detection here: https://github.com/qupath/qupath/wiki/Detecting-objects

**Comment by Svidro** [comment]
Note that you have to have Single Threshold unchecked to get the H-scores calculated

**Comment by Qasim2018** [comment]
Thank you. I am still struggling to precisely annotate the heterogeneity in the core tissue. Is there a way to do it manually each core after we apply TMA de-array grid?
