### ISSUE TITLE
New/merging annotations when using the classifier

### ISSUE THREAD

**Issue by LiezeB** [qupath/qupath#198]
Hi, 

I am using the classifier to detect positive and negative cells in a tumor, I am measuring them in three different areas: 500µm outside of the tumor (green), the whole tumor (blue) and tumor centre (black). When I substract the black one from the green one I get an idea of how many cells there are located in the invasive front of the tumor.
 
I do this by running the classifier on the biggest area (green) and expanding this annotation with -500µm to get the blue one and expanding this one with -500µm to get the black one. It gives me nice results
But because some of my slides only have a part of the tumor (cut), I want the black annotation to be merged with the yellow annotation (to get a correct estimation of the cells located in the invasive front).
When I do this, I get very low cell counts, while I see a lot more cells in that yellow area that should be counted as well. Is there a way to get the correct number of cells when merging two annotations after using the classifier?.

Thanks!
Lieze

![qupath classifier](https://user-images.githubusercontent.com/42168520/43763207-771611c6-9a2a-11e8-812a-5765bc54cdac.jpg)

**Comment by petebankhead** [comment]
I suspect the difficulty is with how the [hierarchy](https://github.com/qupath/qupath/wiki/Object-hierarchies) handles annotations that overlap... that can make knowing that's inside what a bit awkward, and not always very intuitive.

There may be a manual way to do want you want through the user interface, but I suspect it could be quite laborious.  Since this looks like it could be generally useful for others as well, my mind always turns to whether it would be cleaner to write a script or add a new command to the software instead...

I have a few questions to check if I understand correctly what you need:
* What are the final outputs you want?  Is it the number of immune cells per mm^2 or something else?
* Is it problematic that the green region extends outside the tissue?
* Do you have a strong opinion on having the outer areas (here, green and blue) containing _everything_ (i.e. black nested inside blue, then blue inside green), or would it be acceptable/preferable if each area was independent and non-overlapping (i.e. the black area would be one polygon, but the green and blue would be more like 'hollow rings' around the outside)?
* Does the _Positive cell detection_ work directly (e.g. if you've got hematoxylin and DAB staining, and you just need a count based on cells where DAB is evident), or do you really need a classifier?
   * If you _do_ need a classifier, do you need to train it new for every image - or do you plan to train it once, and then apply the same classifier for every image?
* Roughly how many images do you need to analyze in this way?  (e.g. tens, hundreds, thousands... to get a rough idea of how automated the approach ultimately needs to be)
* Have you already got a lot of existing annotations / cells that you need to reuse, or are you just starting?  Usually adding new annotations when there are already a lot of cells can be _very_ slow, and it might be easier to create the annotations first before doing the cell detection.  But potentially either way could work.

**Comment by LiezeB** [comment]
Hi Pete,


-          We want the number of positive and negative cells and also the percentage of positive cells in the different regions: in the tumor center (500 µm from the tumor border) (black), in the invasive front (area between the green and black annotation) and in the tumor (blue).

-          In this case it was not problematic that the green region extended outside of the tissue since there were no cells of interest in this “white space”. But ideally it would also fallow the “cut”.

-          I always start with lining the tumor border (blue) and then I extend it 500µm to get the green one. After this I perform the cell detection in the green one (but the blue one always disappears) after this I run the classifier and when this is completed I ‘expand’ my green annotation with -500µm to get the blue one again and after this I ‘expand the blue one with -500µm to get the black one.

I think it may be better that the green and blue would be hollow rings around the outside of the black one. Since we want to measure cells in three different regions: in the tumor center (500 µm from the tumor border) (black), in the invasive front (area between the green and black annotation) and in the tumor (blue).But as of now I don’t know if it is possible to establish this?

-          We want to count every immune cell in the tumor (+ and -) but not the tumor cells. In the beginning I tried “Positive cell detection” but when using this command, the software also counted a lot of cells that weren’t immune cells. That is why I switched to the classifier, I am very pleased with the results the classifier is giving me. We are scoring 7 different staining’s (70 samples per staining) and I would like to train the classifier for each staining but within a staining I would like to apply the same classifier for each sample.

-          In total it will be around 500 images.

-          I am just starting and trying some things out. I will try to create the annotations before cell detection, but as I have mentioned above: I start with the blue annotation and then I extend it 500µm to get the green one. But when I want to perform the cell detection the first annotation (blue) disappears. So I thought it was nog possible to perform a cell detection in overlapping annotation, or is there a way I can overcome this?


Thank you!

**Comment by petebankhead** [comment]
I suspect this will be a frequent enough need to deserve its own command in the future... in the meantime I've written a script that I hope will help.

You can find it along with a description [here](https://petebankhead.github.io/qupath/scripts/2018/08/08/three-regions.html).

I hope it helps, but if you see a way to improve it just let me know.

**Comment by Tkilvaer** [comment]
I find that defining the inner region from expanding the outer region and intersecting with the original area helps to avoid getting an inner margin in regions where the area of interest expands all the way to the tissue border where it makes no sense to add an inner margin. The central margin is then just the original area - the inner margin
