### ISSUE TITLE
problem reading svs file

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#211]
Hi Pete, 

was this reported before? 
I have a svs file. 
It looks like that: 
![grafik](https://user-images.githubusercontent.com/16352785/45087131-32cc4200-b105-11e8-8242-ee85cd7e73c4.png)

QuPath is reading it like that: 
![grafik](https://user-images.githubusercontent.com/16352785/45087109-1fb97200-b105-11e8-96d7-3af31decd6eb.png)

**Comment by petebankhead** [comment]
Not for SVS, but for SCN:
* https://github.com/qupath/qupath/issues/141
* https://github.com/qupath/qupath/issues/191

It's not really something that can be solved on the QuPath side, I assume that Bio-Formats is being used to read the image (rather than OpenSlide)?
Here is the associated Bio-Formats issue: https://github.com/openmicroscopy/bioformats/issues/2811

**Comment by DavidMHaumann** [comment]
it was a converted svs.  Original SVS from the scanner work. 
I converted the foreign format also to SCN. Same problem there...

**Comment by petebankhead** [comment]
I'll close this issue as it doesn't really sound like a QuPath problem, it's more between the scanner conversion and the image reading library (I'm assuming Bio-Formats).  Please reopen if you get new information or find a solution.

**Comment by DavidMHaumann** [comment]
I could solve the problem by loading the image in the free ImageScope, cuting the whole WSI out and resave it with JPEG2000 compression. (i did not try the other options yet). 
QuPath is now able to display the image in a correct way.
