### ISSUE TITLE
Exporting Detection Centroids

### ISSUE THREAD

**Issue by Shushalsec** [qupath/qupath#214]
I have an issue with the example script called Exporting detection centroids [https://github.com/qupath/qupath/wiki/Scripting-examples#exporting-detection-centroids](url). The script is outputting the X and Y coordinates of detections but these are not the same as the X and Y coordinates I see when I click on _Show measurement table_ then _Show detection measurement_. And in terms of the general pattern of the numbers (as compared by scatterplots) they seem to be the same but after min-max normalisation they were still different. I am a bit confused by what exactly is this command (_roi.getCentroidX()_ for Centroid X) in the script doing and why is it different from the one I see on the left hand side of QuPath _(Hierarchy--Value--Centroid X)_?

Any help is much appreciated!

**Comment by petebankhead** [comment]
There are two main reasons why centroids might be different:
* the centroids are in um instead of px
* the centroids for cells are given for the cell boundary or the nucleus

I suspect the first one is the issue here.  By default,  `roi.getCentroidX()` gives values in pixel coordinates from the top left of the image, and these would need to be multiplied by the 'pixel width' to convert into other units.

**Comment by Shushalsec** [comment]
I see, thank you for helping so promptly!
