### ISSUE TITLE
Point color import

### ISSUE THREAD

**Issue by MichelV2** [qupath/qupath#218]
Hello,

I am trying to load points from a zip file that has previously been saved from QuPath. The points and their class open correctly but the color that is associated with each class is not imported and all the points inherit the default red color on import. I have checked the text files where the points are saved and there is a line containing the color information. Would anyone know how to get the points automatically colored on input as indicated in the files?

Thank you

**Comment by petebankhead** [comment]
This looks like a small typo in the original code (calling `getInteger` instead of `parseInt`), which should be easily fixed in the next QuPath release.

The relevant bit of the code is [here](https://github.com/qupath/qupath/blob/v0.1.2/qupath-core-processing/src/main/java/qupath/lib/io/PointIO.java#L207).  If you need a temporary workaround, that bit could be extracted into a separate Groovy script with the fix.

If you just save the `.qpdata` file (the standard file format with QuPath, also used within projects), then all the points should be retained with the appropriate color/name/classification... so the problem should only affect points that have been manually exported/imported.  I've never had much call to reimport exported points (and so didn't notice the bug)... is there a particular workflow where this is important?

An alternative workaround might be to use the 'name' for the points, and then write a script to assign all your reimported points a color or classification based upon their name.

**Comment by MichelV2** [comment]
Hello Pete,

Thanks for your quick reply. I was just testing the import functionality as I wanted to get point coordinates from a third party software. I've written a short Groovy script as you suggested.

Thanks a lot for your help!

**Comment by petebankhead** [comment]
I think this bug should be addressed in v0.2.0 (current milestone anyway)... but please reopen if this proves not to be the case.
