### ISSUE TITLE
Remove small annotations and fill small holes

### ISSUE THREAD

**Issue by ksirinuk** [qupath/qupath#219]
Hi Pete,
1. What is the best way to remove annotation objects with area smaller than a certain threshold value?
2. How to automatically fill in holes inside each annotation if their areas are smaller than a certain threshold value.
Example Groovy scripts would be very helpful.

Thanks.

**Comment by Svidro** [comment]
1. https://groups.google.com/forum/#!searchin/qupath-users/small$20annotations%7Csort:date/qupath-users/TL6KCc6aB_E/UG3ESt5HBgAJ
2. If your annotation is being generated by simple tissue detection, it might be easier to increase the minimum hole size value (Max fill area).  Otherwise, I think the only way to do that would be to split the annotation into it's component parts, and then somehow reform it using only the components over a certain area measurement.

**Comment by ksirinuk** [comment]
Thanks a lot for the solution to Q1. 

For Q2, I was trying to do something as simple as finding the polygon coordinates of holes and remove any polygons with smaller number of vertices. The trouble is the coordinates of the outer boundary of an annotation and the holes seem to merge together when you query them with `annotation.getROI.getPolygonPoints()`

**Comment by petebankhead** [comment]
[`PathROIToolsAwt.splitAreaToPolygons`](https://github.com/qupath/qupath/blob/v0.1.2/qupath-core-awt/src/main/java/qupath/lib/roi/PathROIToolsAwt.java#L533) should help, since it returns separate arrays of PolygonROIs for 'positive regions' and 'holes'.  You can then request the areas for each.  (From memory, I think the first array is for holes, the second is for positive regions)

But even with that, Q2 is definitely a lot harder...
1. You'll need to reassemble the shapes into new ROIs.  [`PathROIToolsAwt.combineROIs`](https://github.com/qupath/qupath/blob/v0.1.2/qupath-core-awt/src/main/java/qupath/lib/roi/PathROIToolsAwt.java#L75) is one way to do that (although probably not very performant if you have lots of ROIs to combine).
2. You'll need to either set the ROI of the annotation object (which is possible, but discouraged...) or create a new annotation object with the appropriate ROI.  The first method can have problems if the modified ROI results in the hierarchy being 'wrong' (e.g. there was another object inside a hole that has since been removed).  The second requires that you remember to set all the properties of the new annotation appropriately (e.g. name, color, classification...) then remove the old annotation and add the new one to the hierarchy.
