### ISSUE TITLE
Black squares for large whole slide images

### ISSUE THREAD

**Issue by SahPet** [qupath/qupath#224]
Hi! I'm struggling with QuPath showing black squares on large parts of the image when zooming in on whole slide images. File extension is *.ndpi (Hamamatsu scanner) an size of the images are 200-2000 mb. Anyone know how to fix this? Using Qupath 0.12 with the latest BioFormats update.
![picture1](https://user-images.githubusercontent.com/43611111/46150670-564e5c80-c26d-11e8-98a4-3af22df9f8be.png)

**Comment by petebankhead** [comment]
I haven't seen this problem - does it happen consistently or intermittently?  If you restart QuPath and open the same image again, does the problem persist?  Also, is the image on your local hard disk or on a network drive?

If you are able to share an image, then I can investigate some more - otherwise if I can't reproduce it I can only really look out for it in the future.

In the meantime, for .ndpi it should be possible to open the image with either OpenSlide or Bio-Formats, and the settings described at the bottom of this page give ways to toggle Bio-Formats on/off for specific file extensions: https://github.com/qupath/qupath-bioformats-extension

**Comment by SahPet** [comment]
When I think of it, it might be a problem connected with very large whole slides (sometimes used for eg. prostate and breast), as I can't remember having seen it otherwise.

**Comment by petebankhead** [comment]
Closed due to lack of activity. Please reopen if there is further information/a sample file to share that shows the issue.
