### ISSUE TITLE
IHC membrane staning

### ISSUE THREAD

**Issue by jayasinghe99** [qupath/qupath#227]
hello,
How can I quantify IHC membrane staining using QuPath software? 
Thank you

**Comment by Svidro** [comment]
That is a tricky one.  If your staining is DAB, have you tried _Analyze-> Cell Analysis->Cell+Membrane detection?_
Another option might be more of an area analysis.  In other words, use QuPath to define areas (by SLICs/tiling) high in concentration of your membrane stain, then calculate the number of nuclei within those areas plus the average value of your membrane stain.

**Comment by jayasinghe99** [comment]
I want to get the percentage or quantify the  DAB membrane staining cells. Could you please tell me how can I use cell+membrane detection tool?

**Comment by petebankhead** [comment]
I'd suggest working through some of the tutorials on the wiki under _2. Getting started_ - https://github.com/qupath/qupath/wiki/Getting-started - there is a combination of text and videos.  A recurring example focusses on Ki67.

You can adopt a similar approach, but switch _Positive cell detection_ with _Cell + membrane detection_.  To generate a score at the end, you will need to also work through the sections concerned with [creating a classifier](https://github.com/qupath/qupath/wiki/Classifying-objects) (which also allows you to specify to make the positive/negative decision based on the staining in the membrane, rather than the nucleus).

**Comment by petebankhead** [comment]
Closing as a question rather than an issue, and now at https://groups.google.com/d/msg/qupath-users/cuuanti-ig0/HSXe6x3fAQAJ
