### ISSUE TITLE
Feature request - polyline

### ISSUE THREAD

**Issue by Tkilvaer** [qupath/qupath#228]
Hi
As previous I really enjoy the software. The line tool is very good when you want to explore borders. Just draw the line and expand it. However, many borders are uneven. A polyline would be really helpful to address these cases.

Workarounds with the polygon tool and inner and outer margins can be made, but in cases where only part of the border is present and the object you wish to investigate goes all the way to the tissue limit it makes no sense to have an inner or outer border around or within the entire object.

**Comment by petebankhead** [comment]
I agree!  I've got an experimental version of a polyline tool on some branch of my fork... I plan for it to be included in the upcoming beta once I finally finish some (fairly major) refactoring for Java 11.  And recreate the toolbar icons (currently I'm repurposing the polygon tool icon to have a button to show).

Although the case you describe may be a little more complex; the polyline currently doesn't have any 'thickness'.  It could be expanded, but this would be in _both_ directions.  This would be hard to use to draw right up to the tissue boundary, since then you'd need to steadily draw along the center of the to-be-expanded line, i.e. slightly _within_ in the boundary.  I think that an easier option in such cases is still to annotate the entire tissue and expand only inwards, before creating a coarse annotation around the 'uninteresting' part of the tissue and subtracting it from the boundary 'ring' annotation previously created.  The result should be the desired line, stretching right up to the tissue boundary.

**Comment by petebankhead** [comment]
True, I will give it some thought and investigate a bit when I return to the tool to update the icon.  Left/right would break down for a horizontal line, although that could be resolved.  However it's not clear to me what a kind of result a U shape of polyline should produce.... inner/outer is an easier concept there, but returns to closed polygons.  But it gets worse when thinking of S shapes... or intersecting polylines.

If we can come up with a clear and unambiguous definition for what polyline expansions make sense then we can look at how it might be implemented.  Failing that, is there a way that adding extra commands/options could preserve your current approach, but make it more streamlined?

I've also been looking into the ability to transform ROIs to a Java Topology Suite-compatible format, which should give more options for interesting shape transforms and determining spatial relationships... although I don't recall anything in the library directly helpful here.

**Comment by petebankhead** [comment]
Thinking about it some more... the polygon/polygon could be expanded, and then the _original_ polygon/polyline could be subtracted from the result (this would require that it has some thickness; perhaps one pixel).  This would result in multiple annotations being created - at least two (one for each side), but possibly more if the shape is self-intersecting.  Then it becomes a matter of deleting the annotations that you didn't want.

What do you think?  Currently it's only an idea, I haven't tried implementing it...

**Comment by Tkilvaer** [comment]
I we can define the start of the line, left and right could be defined from
the perspective of the starting point looking down the line towards the
end. Inner/outer will be confusing as this will change according to where
your object of interest is (unless there is some kind of way to manually
decide inner/outer).

The latter approach seems interesting. However, I have problems envisioning
its. Perhaps it has to be tested. I has the potential to create a lot of
annotations fast.

Den tir. 16. okt. 2018 kl. 10:38 skrev Pete <notifications@github.com>:

**Comment by petebankhead** [comment]
I guess that's true - I tend to forget to think of it from the line's point of view :)

**Comment by petebankhead** [comment]
Ok, so there's a polyline tool in the current milestone releases.
![Line](https://user-images.githubusercontent.com/4690904/62520963-8cae1e00-b826-11e9-9e21-4cbc94065b33.jpg)

I've updated the 'Expand annotations' command for v0.2.0-m4 as follows.

Previously, expanding line/polyline annotations would expand in all directions - and 'remove interior' had no effect (since the line had no thickness):
![Rounded](https://user-images.githubusercontent.com/4690904/62520803-38a33980-b826-11e9-946a-c3365e251bd2.jpg)

Now, there is an option to set the 'line cap' to be round (as before), flat or square. Also, 'Remove interior' will remove an approximately 1-pixel thick line if requested.
![Flat](https://user-images.githubusercontent.com/4690904/62521003-a9e2ec80-b826-11e9-81b8-a16db61769af.jpg)

This is enough to make a separation. You can then use _Objects &rarr; Annotations &rarr; Split annotations_...
![Split](https://user-images.githubusercontent.com/4690904/62521123-f1697880-b826-11e9-965e-12510c734579.jpg)

...which allows you to separate the inner/outer expansion regions.
![After split](https://user-images.githubusercontent.com/4690904/62521078-d72f9a80-b826-11e9-8a1b-cc1293b44d60.jpg)

**Comment by petebankhead** [comment]
Should clarify that m4 isn't released yet, but the change is in the last commit linked to above.
