### ISSUE TITLE
Javadocs for qupath groovy

### ISSUE THREAD

**Issue by maths-qureshi** [qupath/qupath#230]
Hi Pete,

Do you have any JavaDocs or tutorials on using qupath libraries then please do share. I think they would be very useful for people who want to learn using Qupath well. I would really like to use it in my work.

**Comment by petebankhead** [comment]
For now I'd suggest trying to link up with the source code directly through IntelliJ: https://github.com/qupath/qupath/wiki/Advanced-scripting-with-IntelliJ

I was finally convinced of the value of Javadocs recently, and also discovered that those for QuPath v0.1.2 didn't compile nicely due to illegal characters and various other issues... I think I've resolved most of these problems and plan to have them working and online somewhere for the next release, once the necessary refactoring for Java 11 is completed.

**Comment by maths-qureshi** [comment]
Hi Pete,

Just as on twitter. Let me know if I can help with Javadocs or creating
tutorials on Groovy for Qupath.

**Comment by petebankhead** [comment]
QuPath javadocs have been much improved for v0.2.0. Instructions for building them are at https://qupath.readthedocs.io/en/latest/docs/reference/building.html#building-javadocs
and they are also mentioned in the FAQs at https://qupath.readthedocs.io/en/latest/docs/reference/faqs.html#where-are-the-qupath-javadocs

I do think they should be hosted online at some point as well, but first I would prefer QuPath is properly modularized to better control the public API. We hope to do that for a future version.

**Comment by petebankhead** [comment]
API docs for v0.3.0 are now at http://qupath.github.io/javadoc/docs/
