### ISSUE TITLE
Elongated nuclei not correctly detected 

### ISSUE THREAD

**Issue by LuciaMontorsi** [qupath/qupath#231]
Dear all,

 I am trying to classify a slide from a colon cancer FFPE stained with a lymphocytic marker labelled with DAB, counterstained with Hematoxylin and scanned at 20X with Hamamatsu scanner. My aim is to quantify how many lymphocytes are stromal and how many are in the tumour/epithelium.

 the first issue I have is that Qupath is not able to pickup nuclei correctly and it either fragments them or downsizes it especially when they are elongated and packed together. 

the second issue is that if I only classify objects as tumoural or stromal, I can only quantify the positive cells in the tumour and not in the stroma.

Many thanks in advance,

Lucia

**Comment by Svidro** [comment]
For the nuclei, I would recommend starting a thread on the forum where you can post some pictures, that sounds like more of a image analysis problem.  20X might also be challenging with truly thin, elongated nuclei.  Even more challenging if the Hamamatsu defaults to saving with JPEG compression (bad for analysis, great for file size).

You can both classify regions and cellular populations, so you can subdivide your sample into "tumor" and "stroma" annotations first, and then perform positive cell detection within each of those (or however many classifications you want).  Another option is using derived classes, so that you would first classify by tumor and stroma, then classify the cells as positive or negative within those classifications: https://github.com/qupath/qupath/wiki/Object-classifications

Either way, you can then ignore the stromal positive cells in the data processing (merge populations) however you want, or create a step that re-classifies any Stroma-positive to Stroma-negative, etc.

**Comment by petebankhead** [comment]
In the second video tutorial I talk about different cell detection parameters, and the impact they have on detection - this may help with optimizing the detection a bit further: https://petebankhead.github.io/qupath/2018/08/22/qupath-video-tutorials.html

It's hard to judge without seeing an example image, but it's quite possible that QuPath's generic cell detection isn't accurate enough for your application.  In this case, it might require a custom detection method (e.g. with an ImageJ macro or script) to get the results you want, although that may involve a considerable amount of work and image processing.  I'd definitely recommend exploring what can be achieved by adjusting the parameters first.

For more information about setting cells as positive/negative (regardless of cell type), see https://petebankhead.github.io/qupath/tips/2018/03/22/setting-positive.html

**Comment by LuciaMontorsi** [comment]
Hi Svidro,

Many thanks for the help. I think derived classes should work fine with me. I have trained a classifier and the problem is that it makes the sub-class “Tumour: Positive” but not “Stroma: Positive” and I can’t understand how to create this.

Many tanks again, I’ll work on the nuclei shape more extensively later on.

Lucia
