### ISSUE TITLE
Export Detection Measurements per Annotation

### ISSUE THREAD

**Issue by Shushalsec** [qupath/qupath#234]
Hey Pete,
The script for exporting annotations as binary masks here [https://petebankhead.github.io/qupath/scripting/2018/03/13/script-export-import-binary-masks.html](url) works perfectly and is super helpful, thanks a lot! 
I was wondering though if it would be possible to modify it to run nucleus detection (with 'qupath.opencv.WatershedNucleiCV' and save detection measurements but for each annotation in a separate file. So far I have been using saveDetectionMeasurements() command but it exports everything in one file. Would be ideal to get separate .txt for each annotation feature export (for my further analysis I need to know which cells come from the same annotation). 
I tried adding the script lines to the _export binary masks_ script but with no result, so any help would be much appreciated!

**Comment by Svidro** [comment]
This is a very shoddy way of doing the detections per annotation, and is written for version 1.2 where the default names might not be unique.  1.3 could simply use the annotation name instead of incremental numbers.  If the annotations were all uniquely (manually) named, that could potentially be used for the file name.
https://gist.github.com/Svidro/5e4c29630e8d2ef36988184987d1028f#file-export-detections-per-annotation-groovy

Note that this is very slow and poorly written :)  It would be much more elegant to write out the detection measurements that had already been created by using getChildObjects... but this was something I could easily do!

Good luck and let me know if you have any questions.

**Comment by Shushalsec** [comment]
Dear Pete and Svidro,

Thank you very much for your support, I really do appreciate it!
Pete,  thank you for the link to the other issue, I followed the instructions there and renamed the detections according to the annotation (which I also renamed to have a unique index) they are in.

Svidro, thanks a lot for the script! I tried doing exactly this and failed because of not knowing enough groovy and your script is very educational (apart from doing exactly what I need) in that sense.

Thanks again!
