### ISSUE TITLE
IQR for detection measurements?

### ISSUE THREAD

**Issue by asasama12** [qupath/qupath#236]
I would like to use IQR of DAB intensity in the nucleus, cytoplasm, and cell detections.  Is there any way to get this information from QuPath?

**Comment by Svidro** [comment]
I think the closest you can get is the median whole cell measurements, at the moment.  Of course, if you can script it, you can generate that information easily!  All of the base values should exist, you would just have to do the calculations.

Depending on your experience, though, it might be easier to export the detection measurements to Excel or R.

Actually, re-reading, if you mean a cell by cell measurement of IRQ (based on the pixel values for each individual cell), you might need to use ImageJ scripts?  I am not sure about that one.  Overall IQR of all detections shouldn't be too hard though.

**Comment by asasama12** [comment]
Yeah, I'm working with the detection measurements in R and can calculate IQR on those, but I was interested in the cell by cell pixel IQR values.

**Comment by petebankhead** [comment]
I'm afraid that would be tricky... you'll definitely need access to the raw pixels.  To achieve this after detection, it's best _not_ to choose _Smooth boundaries_ in the cell detection parameters, to keep the contours as close as possible to their original shapes... then you could potentially loop through every cell, extract the pixels for the cell, create a binary mask for the nucleus and another for the cell, and work from there.  Or alternatively you could write an entirely new cell detection (e.g. with ImageJ or OpenCV).

Another option would be to look at exporting the pixels, and the cell ROIs as labelled images (with unique integer labels for each cell).  Then you can potentially tackle the task in Python or R.

Whichever way you choose it's not entirely straightforward, and calculating the values efficiently for large numbers of cells would be a further challenge.  So... it's technically possible, but would require quite a lot of effort.

**Comment by Svidro** [comment]
Ah, that will be a Pete question, but I don't know of any way currently.  It took a bit of work for me to get find new _mean_ stain intensities for the nucleus/cytoplasm when applying a variety of color vectors for multiplexing...  
I suspect the nucleus would be doable since that is a stand alone ROI, especially if you dig into the java files (the pixel by pixel cytoplasmic values, as far as I know, are only used as the cells are generated), but the cytoplasm might be more difficult.  
The file I am thinking about is: https://gist.github.com/Svidro/eaf29399e36d34caacddf345ab668b0c#file-watershedcelldetection-java
That is a version of it that I edited to use % of different color vectors for the nuclear detection, rather than just OD sum or Htx.  That is where I would recommend starting if you want to try to insert an IQR measurement.  But I really don't know!

It would be nice to have that information available, if you/Pete can get it working, but I don't think I can help much more here.

**Comment by asasama12** [comment]
Gotcha, I was hoping for something a bit more straightforward, but I might look into exporting the ROIs when I have more time to dig into this.  I appreciate your input!

**Comment by petebankhead** [comment]
Closed due to lack of activity, and because https://forum.image.sc/tags/qupath is the best place for questions & further discussion.
