### ISSUE TITLE
Annotations' classes inconsistent with project‘s classes list

### ISSUE THREAD

**Issue by ZhMJiang** [qupath/qupath#243]
The main propose of this issue is to report a problem that the classes of annotations in a open image do NOT appear in the classes list (that panel on the right of the annotations list panel, in Annotations tab).

Q1. When I create a new project, the software seems to keep all classes I add in the previous project, while I want to use a new set of classes in a different task. Is this a designed behavior?
---I try to do "Reset all classes", which make the classes list become the default one; then I delete all classes and added wanted classes.

Q2. Then I work with this new classes list, make some annotations in an image, and save them in a .qpdata file (use Ctrl+S). Some time after that, my computer crashed (unlikely caused by QuPath) and restarted.  I open the new project again, finding that QuPath load the classes list of my PREVIOUS project (which I don't want, as I mentioned in Q1), and lost all the classes I create in the new project. Meanwhile, the annotations in the image are with correct classes (those I add in the new project). Now, the classes of annotations in the image is inconsistent with project‘s classes list, as is shown in the screenshot below. Now I can neither create annotations with classes I added before (which are lost), nor get back my new classes list or manage them (like changing the color of the annotations). What should I do? 
---I'm not sure what will happen if I do [reset, delete, add classes] again will help. I think even I add classes with the same name, it is another classes (which is not the same of those existed in the qpdata file). Is it true?
![image](https://user-images.githubusercontent.com/22469724/48327969-b150dd00-e67c-11e8-848f-f44727ef29bd.png)

**Comment by petebankhead** [comment]
This is intended, even if it's not optimal.  And because it could be better, it will change in the next version:
https://petebankhead.github.io/qupath/2018/03/19/qupath-updates.html#classification-lists-are-stored-in-projects

### Current situation (v0.1.2) & planned changes
Currently, the class list is saved in the preferences - and not any individual project or data file.  In the next release, I plan that the class list will be saved in the preferences as _also_ in the project.  Furthermore, it will be possible to import class lists from different projects.

I hadn't realised when I was writing it at first how long or complex the class lists would become... and I understand that losing a long list can be very frustrating.

### The class list & object classes in the image
The classes actually applied in the image _don't_ need to correspond to the class list.  The purpose of the class list is only to provide a way to assign classes to annotations manually.  It's very possible to have objects with other classes in the image; this happens often (e.g. with 'Positive cell detection' you can get cells with 'Positive' and 'Negative' classes - but these don't need to appear in the class list for it to work).

### The uniqueness of classes
If you create a new class in the class list and it has _exactly_ the same name as a previous one, then it should refer to _exactly_ the same class.  If the class doesn't exist, it will be created.  But if it exists anywhere in the image, then the existing class with that name will be used.  This is important for how QuPath does things.

Unfortunately, the rule is _very_ strict.  Any difference in class name (e.g. different capitalization, spaces) results in a different class.  So it is necessary to be very careful when doing this.

> I _think_ the color for the class is random.  I may have changed that for the next version to make the color pseudo-random, but consistently the same if the same name is typed (making it easier to identify discrepancies).  I'll have to check the code to make sure if I made this change or only thought about it...

### What to do in the short term
There are three main options in the short term:
* Add the classes you need manually (and looking out for any problems/tiny discrepancies) if/when they are lost
* Create a script to set the contents of the class list more easily (this is possible, but needs caution as well... if the class list is corrupt in v0.1.2, QuPath won't start)
* [Follow the instructions to build my test version](https://petebankhead.github.io/qupath/2018/03/19/qupath-updates.html#step-by-step-guide) that already has some of these changes available, ahead of them being actually packed up into a full QuPath release

If a script to set the class list would save you a lot of time, let me know I can help create one; otherwise, I hope one of the other two options and this explanation can help.

**Comment by ZhMJiang** [comment]
Thanks a lot. The biggest problem is solved.
I think scripts that export/import classes list to/from a (human readable, maybe) file may help, or maybe a classes manager implemented as a feature. But it's not urgent for me now, and maybe I can try to write the script myself.
