### ISSUE TITLE
Is it possible to load a custom external jar or .class binary? 

### ISSUE THREAD

**Issue by CielAl** [qupath/qupath#253]
Hi,

I have some java code which might be useful to apply in the scripts but containing syntax not yet supported by groovy, and I am wondering if I compile/export that code to be binaries, what might be the best way to import them into the environment of the script editor?

**Comment by petebankhead** [comment]
You can drag a .jar onto QuPath to add it to the extensions directory, and then it should be available on the classpath for any scripts.  Although I'm curious about what syntax isn't supported?

**Comment by petebankhead** [comment]
True, lambdas are the only incompatibility that has particularly bothered me at times & required adjusting the code, although it's not too tricky: http://groovy-lang.org/differences.html#_lambdas
Other differences (e.g. with `equals` or numbers becoming `BigDecimal` if not explicitly made something else) can be a bit troublesome, but more so when using most Groovy-specific features.

Fortunately, it looks like the lambda situation will change with Groovy 3.0: http://groovy-lang.org/releasenotes/groovy-3.0.html

With implementing `QuPathExtension`, the `META-INF/services/qupath.lib.gui.extensions.QuPathExtension` part is crucial (see [here](https://github.com/qupath/qupath/wiki/Creating-extensions), or [this](https://docs.oracle.com/javase/tutorial/ext/basics/spi.html#implement-the-service-provider) may also help - since the general idea isn't QuPath-specific).  But if you just want to access the contents of the .jar from the script, then this shouldn't be necessary.

It sounds like the problem you are seeing happens inside the imported code, because if I import something that doesn't exist then at least the errors are displayed (and sensible), e.g.:
```groovy
print 'hello'

import something.that.does.not.exist
```
gives me
```
ERROR: Error: startup failed:
Script18.groovy: 4: unable to resolve class something.that.does.not.exist
 @ line 4, column 1.
   import something.that.does.not.exist
   ^

1 error
```

When that happens, QuPath doesn't handle such exceptions very well and I've also seen the multiple-logging problem occasionally when things go badly wrong.  A recent fix I made on my fork should help address this: https://github.com/petebankhead/qupath/commit/c3f8fd49f8c14dbf7956490d2fa4f79d8e11b057

Finally, there are different ways to integrate Groovy into a Java application: http://docs.groovy-lang.org/latest/html/documentation/guide-integrating.html
Currently, QuPath goes down the _JSR 223 javax.script API_ route to give (potentially at least) support for different scripting languages.  I'm tentatively considering a switch to use _GroovyShell_ instead, which looks like it makes it easier to access other classes.

I haven't yet explored the implications, but I think that Option 1) having really good Groovy support (only) would be more worthwhile than Option 2) trying to support multiple languages/syntaxes (but none of them quite as well).  If you've any thoughts on that please let me know, I'd be interested in other opinions before getting too embroiled in making the changes.

**Comment by petebankhead** [comment]
Without knowing the details, my best guess is that the .jar you've added to the extensions directory also has dependencies on other .jars that _aren't_ in the directory.  You'll need to make sure that all dependencies and sub-dependencies are either in the extensions directory or a core part of QuPath.

**Comment by CielAl** [comment]
> Without knowing the details, my best guess is that the .jar you've added to the extensions directory also has dependencies on other .jars that _aren't_ in the directory. You'll need to make sure that all dependencies and sub-dependencies are either in the extensions directory or a core part of QuPath.

Appreciate the reply!.
I look into the Bio-Formats extension. It appears that the package of the classes is "qupath\lib\images\servers", which is somehow an existing package in the qupath source code. Is it required that all classes of extensions must be in such existing package?

Besides, under the Meta-Inf/service, there are two files:
qupath.lib.gui.extensions.QuPathExtension
qupath.lib.images.servers.ImageServerBuilder


with strings like
qupath.lib.images.servers.BioFormatsOptionsExtension
qupath.lib.images.servers.BioFormatsServerBuilder

It looks like some class relationship (the source code shows that BioFormatsServerBuilder extends ImageServerBuilder). May I ask what is the reason to include these two files under the META-INF?

**Comment by petebankhead** [comment]
The contents of META-INF is essential here... the relevant QuPath documentation is at https://github.com/qupath/qupath/wiki/Creating-extensions#creating-an-extension but the `Service Provider` concept is from Java, and not QuPath-specific.
