### ISSUE TITLE
Classifying multi-structural features

### ISSUE THREAD

**Issue by lmun8409** [qupath/qupath#254]
Hi, my name is Luis and I was wondering if there is a way of training an additional classifier that takes into account an image that has been cell-type classified. For example, if an image of a tumour was stratified into its respective cell type regions (tumour, immune cell, stroma etc) and use a classifier to identify a multi-cell type structure (eg, the boundary between the necrotic core and viable tumour tissue). I imagine a classifier of this type would also have to take into account spatial relationships between the different types of cell regions.

**Comment by lmun8409** [comment]
Thanks for the prompt response, but the example I gave was probably one of the more simple type of structures that I'm interested in looking at. Another type of structure I'd be interested in looking at is the marginal invasive zone of a tumour. While at first it may seem simple (boundary between tumour and non-tumor tissue), there isn't always a clear boundary; instead there could be a lot of interwoven tumour tissue among non-tumour tissue. 
I'd be interested in a function that could classify (after training) this boundary, and I imagine it'd take into account the ratio of tumour to non-tumour regions or something like that if the computer found that to be a reliable and consistent variable in the classification of this structure.

**Comment by lmun8409** [comment]
Thank you for your help

**Comment by petebankhead** [comment]
It's not possible to try an additional classifier directly through the user interface, but that is just because the functionality the user interface gives access to is necessarily very limited.

QuPath gives the tools to solve many problems like this, but constructing the specific solutions could still take a lot of work.  It is hard to judge without seeing any images, but it sounds like one or more research projects to figure out how to approach the analysis, develop the techniques and write the necessary code.  There is no built-in command to do all of what is needed here, but that is why it is also possible to write scripts and extensions for QuPath.
