### ISSUE TITLE
How to run Qupath as an application in eclipse

### ISSUE THREAD

**Issue by gunjanmehra1** [qupath/qupath#257]
I have setup Qupath project on my eclipse using the steps mentioned in the below url https://github.com/qupath/qupath/tree/master/src/main/resources/eclipse

How do I run it in eclipse environment ?

**Comment by petebankhead** [comment]
It's not clear to me if this is a QuPath question or an eclipse question, or if you are already familiar with eclipse.  There are various other posts if you search for "eclipse" either here or on the [QuPath Google Group](https://groups.google.com/forum/#!forum/qupath-users) and I don't know what you've read or tried.

In any case, I'm working on my own fork currently and making major changes (including a switch to Java 11, and from Maven to Gradle).  The code here was always a bit awkward to set up, but once I have merged in the changes the process will be different... I'm afraid I can't write up any more extensive documentation on setting up this version, because it will soon be out of date and all my spare time to work on this really needs to be devoted to the update.  Someone else may be able to help more.
