### ISSUE TITLE
Superpixels changing to cells?

### ISSUE THREAD

**Issue by simonesteffens** [qupath/qupath#261]
Hey Guys,
you helped me a lot with my last issues, so I´ll try it again. 

I used "Tiles and superpixels", classified the pictures in stroma and tumor and used "Tile classifications to annotations" to get the measurements of the classified area.

But I also should get the number of cells of every classified area/annotation.
So I was wondering, is there a possibility to change the superpixels (already classified and in annotations) in cells by a script?
I know that I can select every annotation individually and use cell detection. But where can I figure out the number of cells in the selected annotation without a new classifier?
And is there a script wich I could use for an automatically cell detection in every picture of a project?

Thanks for your help, hope you have an idea :)
Simone

**Comment by Svidro** [comment]
Not sure, it looks like you could mean two different things.

I don't think you can really turn the superpixels into pathCellObjects since there is no nucleus/cytoplasm, though you could possibly use the XY centroids of each superpixel, create a small circle there, and then convert it plus it's parent superpixel into a cell.

Alternatively, if you want to run cell detection, you should be able to selectAnnotations(); and then run your cell detection command. Sum the results in the annotation tab, or use a script to select only the annotations of a particular class and then use mergeSelectedAnnotations();
See here: https://gist.github.com/Svidro/8f9c06e2c8bcae214cdd7aa9afe57c50#file-a-selection-guide-groovy
That could at least get you one annotation per class, and make it easier to read out the results. Another option might be to generate all of the cells and then classify them by their parent annotation's class.


Might need an image or something to be more help.

**Comment by Svidro** [comment]
And like in the most recent question, things that aren't really QuPath bugs should be directed to the forum:
https://groups.google.com/forum/#!forum/qupath-users

I also realized I missed a spot.  Any script you write for a single image should be able to be run on all images within a project using the Run for Project option in the Run menu. If you need to do any manual annotating, prior to running your script, make sure to do it in all images before running the script!
