### ISSUE TITLE
Moved .qudata and need step by step to fix the file path. HELP!

### ISSUE THREAD

**Issue by Clemonsg109** [qupath/qupath#266]
This is urgent as I have a lot of work which I have done on a separate computer. I recently put all of the .qpdata files I have onto a flash drive by copying them. When I click on a .qpdata file I am prompted to "Set path to missing file" when I click "choose file" and select the .qpdata file I am trying to open, the program remains black and no file opens. I am pretty much clueless regarding writing and programming and would be very grateful for some kind of step by step help to fix the file paths. 

EDIT: To clarify, this issue has arisen when trying to open the files from the flash drive while it is plugged into the new computer. The original files on the computer which I analyzed the images in can open most of the .qpdata files without prompting me to change the file path.

**Comment by Svidro** [comment]
.qpdata files are files full of objects, not the image itself. The error you are getting is probably QuPath trying to find the same file path to the _image_ file. In general, it is best to store the images within the project folder, and transfer the entire project folder.

Regardless, you should be able to look at your data again, even with a completely new project. Just create the project, import the images again, and then copy the qpdata files into the "data" folder.

**Comment by Svidro** [comment]
https://github.com/qupath/qupath/issues/246
and 
https://github.com/qupath/qupath/issues/249
also cover some other aspects of qpdata files, or have useful links to more information.

**Comment by Clemonsg109** [comment]
When I attempt to create a new project, and open the folder containing the .tif image file, I get a dialogue box telling me the project directory must be empty. However I can simply open the .tif image in qupath if that helps.

**Comment by Svidro** [comment]
Yes, you have to create the project, then copy the images into the project.
Sorry for not being clearer on the order.

Or don't bother making the project portable and just import the tif from
wherever it currently is. Then create a data folder and put the qpdata file
in it. In the end, you just need an image with name X "in your project,"
and a qpdata file with name X in the data folder.

**Comment by Clemonsg109** [comment]
So, after creating a project with the proper .tif file, how would I add the existing .qpdata to the project in such a way that it overlays with the .tif file? I'm really sorry, as I am sure this is really simple, I'm a cell biologist and not computer savvy at all

**Comment by petebankhead** [comment]
@Clemonsg109 The tips from @Svidro above assume you used a project in the first place; if not, then your .qpdata files might not have the names that they should have in the project.  Of course the file names could be changed if necessary, although I don't know how many files you're dealing with.

[This video](https://www.youtube.com/watch?v=2yoRMl1IaJ4&index=4&list=PL4ta8RxZklWkPB_pwW-ZDVAGPGktAlE5Y&t=0s) might help to explain more about projects (and how to tame them).

**Comment by Clemonsg109** [comment]
I simply opened a .tif file in qupath, then used the points tool to put counting dots over cell images. When I would finish and image I would save the file by clicking "save" and saving the .qpdata file right below the original .tif I was counting from. I'm not sure if this is helpful.

**Comment by petebankhead** [comment]
Yes, in that case you weren't using a project.  It can make life considerably easier if you do use projects.  Hopefully the video helps.

That said, how many .qpdata files do you have?  And are they all in the same folder as the .tif images (just now on a different computer)?

**Comment by Clemonsg109** [comment]
I would safely estimate 200+ .qpdata files

**Comment by Svidro** [comment]
Ah, I wasn't aware the naming changed when not using a project... but it seemed to work for me with CZI files.
Steps.
1. Open a bunch of individual images in QuPath, save .qpdata files for them.
2. Close QuPath (not really necessary, but eh)
3. Open QuPath and Create project from the Project tab.
4. Go to the empty folder used to create the new project and add "data" and "images" folders
5. Copy all .qpdata files (with the exact same name as the images) into the "data" folder
6. Copy all (in my case czi) image files to the images folder
7. Back in QuPath, select Import images in the Project tab, and select all of the images in the "images" folder.
8. At this point, for my files, all of the data loaded to the appropriate image. Again, CZI images rather than TIF, so not sure about the naming scheme. I suppose he might have renamed the .qpdata file rather than left the name the same as the image? That _would_ be a problem!

**Comment by petebankhead** [comment]
> I would safely estimate 200+ .qpdata files, and all .qpdata files are saved right below their respective .tifs in their respective folders.

Hmmm, but that is not all the same folder...?

I ask because this could probably be resolved in a script, or with a change to QuPath to search for missing files in the same directory as the .qpdata file.  Because you say it's urgent, the second option may not work for you.  The first option requires knowing exactly how the files are arranged... and also the file format (if you are using Bio-Formats to read them rather than OpenSlide, the process may need to be slightly different).  The operating system would also help (Windows/Linux/macOS).

But @Svidro 's approach would be the most straightforward and fastest if it works for you.

**Comment by Clemonsg109** [comment]
Yes, the .qpdata files I saved after I had finished manually counting them I would rename as "complete" to know that I had finished the counting on that particular slide.

**Comment by Clemonsg109** [comment]
The schema is:
1)open .tif of the slide I wished to count in qupath (ie 1.tif)
2)use points tool to count the slide 
3)after completing the slide, clicking file>save and naming the file "1 complete.qpdata"
4)this file would then be saved right below its respective original .tif image.

this is the process I used to count many slides with the expectation that i would go back into qupath and take the data from my counts at the end of the endeavor to perform statistical analysis on etc.

**Comment by Svidro** [comment]
Ah, well, the above option I mentioned will only work if you fix the names. I use Bulk Rename Utility for that on Windows systems, but you could also manually edit the names. I am not good enough with the .qpdata loading system to figure out a script for that :)

**Comment by Clemonsg109** [comment]
So essentially, if I make the .qpdata file name match the file name of its respected tif within the folder they're in, I should be able to use the process above? Additionally, if I open the .tif, and then save a .qpdata file of the unaltered .tif, save this file into a project folder, then drag and drop the matching .qpdata files that have my counting points into the data section of that project folder, I should be able to open the files and see the data overlayed?

**Comment by Svidro** [comment]
Sounds about right. Though for any new image files, it is easiest to open them within a project.  Then the qpdata file associated with the image will automatically be saved into the data folder. But go ahead and try it for a single file to make sure it works for you.

**Comment by Svidro** [comment]
Though one point, you say "unaltered .tif" files... nothing in QuPath ever alters your .tif files. The .qpdata files are just a point/line based overlay using XY coordinates related to the image. 

You could rename your 1.qpdata file to 2.qpdata and see the points created in 1.tif overlayed onto 2.tif. That can actually be useful sometimes with sequential slices and similar experiments.

**Comment by petebankhead** [comment]
Basically, the .qpdata file contains a full path to your image.  If your image isn't there (e.g. because you moved the image, or changed to another computer) then this will fail.

The project also contains the full path to the image, but it only needs to match the _name_ of the image with the name of the .qpdata file, and the .qpdata files are all stored in a folder called 'data'.  So if you create a new project, add all your images based on wherever they are currently (so they have the right paths), then you only need to make sure that .qpdata file names correspond with the image names.  Pop these .qpdata files inside the 'data' folder of the project and all should be well.

That being said, strictly speaking you don't need to do any of this if you only need to extract points from a .qpdata file... it's possible to write a script that just extracts the points without needing to open the image at all.

What isn't clear to me is where exactly your .tif files are relative to one another.  Is it 200 .tif files in one folder, or 200 folders, or spread across subfolders of folders....?

**Comment by Clemonsg109** [comment]
I understand, I'd like to think that all I want to do is associate the grid of dots I counted with the .tif file that I counted them on. I did what you specified above and after clicking "import" qupath opened the .tif file that I selected but the .qpdata file associated with it was not layered over the .tif.

**Comment by Svidro** [comment]
Try reopening QuPath :)

**Comment by Clemonsg109** [comment]
Pete, 

I have a folder for each slide that contains tif files named "1" "2" and "3". and for each of these .tif files is a corresponding .qpdata file named "1 DOTS" "2 DOTS" "3 DOTS".

**Comment by Clemonsg109** [comment]
Reopening qupath and the the project I just created only opens the image file in the project. I made sure change the names of the .tif and .qupath file to match before creating the project.

**Comment by Clemonsg109** [comment]
Some how by opening the .qpdata file from the "data" folder within the project and then selecting the .tif file from the "images" folder of the project when prompted to "set path to missing file" they opened without a hitch. I guess I just did manually what making the project folder is supposed to do automatically? I guess my next question would be, can I expedite this process so that I don't have to go folder to folder making a project for each image and then linking the .qpdata set for that image after being prompted to set its path back to its respective .tif from within the project folder?

**Comment by petebankhead** [comment]
Here is an _extremely_ quickly put together script that I have tested precisely once... may or may not do what it is meant to.

But basically you'd create an entirely new project, go to _Automate &rarr; Show script editor_ and paste the contents there.  When you run it, you should be prompted to select a folder.  Choose the _base_ folder that all your .qpdata files are inside (doesn't matter if they are in subfolders).  Note that this assumes that _all_ the .qpdata files are worth using; you may want to delete any extra .qpdata files if that is not the case.

The script should then search (recursively) for all .qpdata files that it can find, and all .tif files that it can find, somewhere below the folder you selected (don't choose something like C:/ or it will take a _long_ time).  It then peaks inside the .qpdata file, checks what .tif file it is associated with, and if it finds a match it will add the .tif file to the project and copy the .qpdata file to the 'data' folder where it belongs.  Then your project should be fully formed and ready to go.

You could just try it... but ideally not on the only copy of your data, lest it go badly.  However I _think_ it works.

```groovy
import javafx.application.Platform
import qupath.lib.gui.QuPathGUI
import qupath.lib.gui.helpers.DisplayHelpers
import qupath.lib.io.PathIO
import qupath.lib.projects.ProjectIO
import qupath.lib.projects.ProjectImageEntry

import java.awt.image.BufferedImage

// Get the current project
def project = getProject()
if (project == null) {
    DisplayHelpers.showErrorMessage("Project from .qpdata", "Create a project first!")
    return
}

// Get the base directory
def dirBase = QuPathGUI.getSharedDialogHelper().promptForDirectory(null)

// Get all the .qpdata files
def qpdataFiles = new ArrayList<File>()
def tiffFiles = new ArrayList<File>()
dirBase.eachFileRecurse {
    if (!it.isFile())
        return
    if (it.getName().endsWith('.qpdata'))
        qpdataFiles << it
    else if (it.getName().endsWith('.tif'))
        tiffFiles << it
}

// For each .qpdata file, look for the image & copy it to the data folder
def entries = new ArrayList<ProjectImageEntry>()
for (file in qpdataFiles) {
    // Look for an image with the same name
    def path = PathIO.readSerializedServerPath(file)
    def name = new File(path).getName()
    def tiff = tiffFiles.find {it.getName() == name}
    if (tiff == null) {
        print('Could not find file for ' + name)
        continue
    }
    // Create a new image entry & copy the bytes
    def entry = new ProjectImageEntry<BufferedImage>(project, tiff.getAbsolutePath(), null, Collections.emptyMap())
    def fileData = QuPathGUI.getImageDataFile(project, entry)
    fileData.bytes = file.bytes
    entries << entry
}
project.addAllImages(entries)
ProjectIO.writeProject(project)

Platform.runLater {
    getQuPath().setProject(null)
    getQuPath().setProject(project)
}
```

**Comment by Svidro** [comment]
> Reopening qupath and the the project I just created only opens the image file in the project. I made sure change the names of the .tif and .qupath file to match before creating the project.

Hmm, if the .tif and .qpdata (not qupath) file match, that should be fine. The .qpproj file can be whatever you want it to be, and that is what you open for the project. I am guessing something is getting lost in translation :)  Hopefully Pete's script will work cleanly.

Ideally, what you described in the next post is exactly what the project does automatically for all images imported, and all data files in the data folder. They have to be named exactly the same thing though, including spaces etc.

**Comment by Clemonsg109** [comment]
I have renamed all .qpdata files to match their .tif files. When I ran the script to try to create a mass-project for all of the files in their subfolders, it resulted in 3 .tif files being added to the project with random .qpdata files overlayed.

**Comment by Svidro** [comment]
Ah, re-reading this, it makes more sense. If all of the file names are the exact same (well, 1 2 and 3, over and over), that will be confusing to any given project, I think. I thought that your images would be named 1-200. The way I mentioned above would only work for any single group of 3; you would need a separate project per group of same file names.

The lack of unique file names will be problematic. Stumped for the moment.

**Comment by Clemonsg109** [comment]
Alternatively, I could try to figure out how to do an automated recount and just run all of the .tif files through this and scrap my manual counts. Goal is just counting blood smear slides to determine the ratio of sickled vs. nonsickled RBCs in each frame.

**Comment by petebankhead** [comment]
> I thought that your images would be named 1-200.

That was also my misunderstanding, and why the script gave the results that it did.

**Comment by Clemonsg109** [comment]
I can try to rename the files to be ordinal, and see if anything changes.

**Comment by petebankhead** [comment]
Updated script to try...
```groovy
import javafx.application.Platform
import qupath.lib.gui.QuPathGUI
import qupath.lib.gui.helpers.DisplayHelpers
import qupath.lib.io.PathIO
import qupath.lib.projects.ProjectIO
import qupath.lib.projects.ProjectImageEntry

import java.awt.image.BufferedImage

// Get the current project
def project = getProject()
if (project == null) {
    DisplayHelpers.showErrorMessage("Project from .qpdata", "Create a project first!")
    return
}

// Get the base directory
def dirBase = QuPathGUI.getSharedDialogHelper().promptForDirectory(null)

// Get all the .qpdata files
def qpdataFiles = new ArrayList<File>()
dirBase.eachFileRecurse {
    if (!it.isFile())
        return
    if (it.getName().endsWith('.qpdata'))
        qpdataFiles << it
}

// For each .qpdata file, look for the image & copy it to the data folder
def entries = new ArrayList<ProjectImageEntry>()
for (file in qpdataFiles) {
    // Look for an image with the same name
    def path = PathIO.readSerializedServerPath(file)
    def name = new File(path).getName()
    def tiff = new File(file.getParentFile(), name)
    if (!tiff.exists()) {
        print('Could not find file for ' + name)
        continue
    }
    // Create a new image entry & copy the bytes
    def imageName = tiff.getParentFile().getName() + "-" + name.replace('.tif', '')
    def entry = new ProjectImageEntry<BufferedImage>(project, tiff.getAbsolutePath(), imageName, Collections.emptyMap())
    def fileData = QuPathGUI.getImageDataFile(project, entry)
    fileData.bytes = file.bytes
    entries << entry
}
project.addAllImages(entries)
ProjectIO.writeProject(project)

Platform.runLater {
    getQuPath().setProject(null)
    getQuPath().setProject(project)
}
```

**Comment by Clemonsg109** [comment]
Ok, now that was proper wizardry! magnificent!

**Comment by Svidro** [comment]
Yeah, a Python script calling QuPath on every tif file within a directory tree, followed by saving a text file of the results. There are a couple of posts in the forum that handle things very similar to this, like watching a folder for new files, then running a script on them and saving the output in another folder.

Counting cells by shape would actually be very easy.... provided there is very little overlap. Overlap would be problematic. Something like this:
![image](https://user-images.githubusercontent.com/23145209/52373680-216ac700-2a10-11e9-8fa1-e271d59c5da5.png)
I nabbed from a Google search.
Classifying by mean red coloration and Circularity might do the trick.

**Comment by Clemonsg109** [comment]
> Yeah, a Python script calling QuPath on every tif file within a directory tree, followed by saving a text file of the results. There are a couple of posts in the forum that handle things very similar to this, like watching a folder for new files, then running a script on them and saving the output in another folder.
> 
> Counting cells by shape would actually be very easy.... provided there is very little overlap. Overlap would be problematic. Something like this:
> ![image](https://user-images.githubusercontent.com/23145209/52373680-216ac700-2a10-11e9-8fa1-e271d59c5da5.png)
> I nabbed from a Google search.
> Classifying by mean red coloration and Circularity might do the trick.

There are some pretty densely populated slides, though many of them look similar to your example. I'm assuming that waterfall can help with segmentation on the more dense slides however? I would be ecstatic even to just identify all of the normal RBCs in a field so I could go manually select the sickling cells.

**Comment by Svidro** [comment]
Ah, I actually have MORE trouble with the normal cells, since the white center frequently causes problems with the segmentation.  The darker sickle cells are easier to pick out as they are larger than the "half of a normal blood cell" that occasionally gets segmented from a normal RBC.

**Comment by Clemonsg109** [comment]
The images I have are horrible in terms of having white centers, they are poorly stained and at best there is only an outline of the rbc membrane (normal or sickled) to go by. This is probably why I have struggled so much with getting automation going on these slides.

**Comment by Svidro** [comment]
Ah, yes, that sounds like it would be very difficult for standard cell detection methods. Good luck counting! Or you might be able to use an ImageJ script to manipulate each image into a state where it can be processed and the results sent back to QuPath... but it might be easier to just count if the fields are small.

**Comment by petebankhead** [comment]
It is a complete guess without seeing your image, but I'd try:
* Send the image to ImageJ: https://github.com/qupath/qupath/wiki/Working-with-ImageJ
* _Process &rarr; Find Maxima_ and preview the point selection. Experiment with the noise tolerance, with the goal of _detecting_ the white center.
* If the count looks basically ok, make sure the output type is 'Point Selection' and click 'OK'
* Use _Plugins &rarr; Send ROI to QuPath_ to initialize the point selection
* Edit the points in QuPath as necessary

**Comment by Clemonsg109** [comment]
Yes, the manual method has been time consuming but unfortunately the image quality sort dictates what I can do with them. I didn't personally process the tissue, so hopefully when I have more input I will be able to spot check the slides before sending them off for scanning. Thank you both @Svidro and @petebankhead  for all of your assistance! This saved my hide as I thought months of counting was wasted.

**Comment by Elena195** [comment]
Hello everyone, 

I have the same problem like Clemonsg109. 

I need to move pictures and qpdata from my OneDrive Cloud (without having created a project) to our server and want to create a project with the server adress. Unfortunately, nothing from above works. 

If I copy the qpdata in the project folder "data", and open the image again, it is always an extra "data.qpdata" created instead of using the "Image1.qpdata" (if my image is called "Image1.tif"). 
Also, the project is creating in the "data" folder enumerated subfolders, which are named "1", "2", etc. Within those subfolders, the "data.qpdata" is created, even if I have the "Image1.qpdata" also in this subfolder.

Also when I open the qpdata in the editor and change the path to the server path of the picture, it doesn't work. I don't know what to do now.

Version: Qupath 0.2.0-m8

Additional question: At home I was also using Qupath on my Mac for some pictures, is there an additional problem concerning Mac /Windows?

**Comment by Svidro** [comment]
That sounds standard for M8. The first thing I would recommend trying it deleting the empty data.qpdata and then renaming the Image1.qpdata to data.qpdata. The trick is, you need to place the image1.qpdata (renamed) into the correct folder matching the image1 image. With none of the folders/files being named, you can either look at the thumbnail (if you can ID your files visually), or navigate through the Project tab within QuPath by right clicking on a file, and opening it's data folder.

I think normally the order of the folders (1,2,3,4,etc) matches the order of the files in the Project tab, so that might save you some time.
![image](https://user-images.githubusercontent.com/23145209/73287937-eaf10380-41ae-11ea-9163-cc5a712a6b4f.png)

Also, _as this isn't really a bug, and it is a closed topic_, posts like this should go on image.sc, as the label indicates.

I don't know of any problems opening QuPath projects between Mac and PC.

**Comment by petebankhead** [comment]
Projects in v0.2.0-m8 are quite different from in v0.1.2. The above instructions won't work and the awkward workarounds should no longer be necessary.

I've written a bit about how to update paths since v0.2.0-m4 [here](https://petebankhead.github.io/qupath/2019/08/20/fourth-milestone.html#repair-projects-by-finding-missingmoved-images).
