### ISSUE TITLE
Script runs on single image but not as a project

### ISSUE THREAD

**Issue by paulage** [qupath/qupath#268]
I created a script to detect CD3 positive cells and export annotations as txt. It runs on a single image, although the txt file only contains the column headers, no results. When I run it for project it does not run (no cell detection) and also creates txt file only contains the column headers. Could you help me out?

**Comment by Svidro** [comment]
It would help to have the script to go off of, but there's a good chance you aren't selecting the annotation as part of the script (before running cell detection). I am not sure why your annotation export would contain no results if you have annotations.

More info!

**Comment by paulage** [comment]
Actually the script runs on project, there is something wrong with the export script. I don't have scripting experience, so I just copied the code form the post. 
![qupath](https://user-images.githubusercontent.com/47432131/53455622-c154b880-39f0-11e9-94a5-db081a2e3ca2.JPG)
There is another issue as well, the image is a whole slide scn file, so I choose one of the thumbnails for each image to run the project on. Could the original image name and not the thumbnail name be used to export the annotations?

**Comment by Svidro** [comment]
Ah, that is possible. The script looks good otherwise. Unfortunately I don't have any SCN files to test things on. However, the fact that some of the thumbnails show whole slide images (including label) while others are only the tissue suggests there might be some different types of SCN files in play. 

I am not sure how run for project works in these situations. Have to see what Pete thinks.

I take it running that script on your current image both generates the *mostly empty text file, and an annotation plus a bunch of cell objects in the Hierarchy?

**Comment by paulage** [comment]
scn file are pyramidal. I only selected the "only tissue" images (corresponding to the maximum magnification/resolution) to run the project on. 
![selected for project](https://user-images.githubusercontent.com/47432131/53500012-2949e400-3a6f-11e9-8ebe-f29757c2d817.JPG)
There are no objects in the Hierarchy or on the image
![hierarchy](https://user-images.githubusercontent.com/47432131/53500109-50a0b100-3a6f-11e9-8577-d70b98b49a08.JPG)
However, the script is running and detecting objects as you can see in the script editor. I added the "merging annotation results" script and now the merged txt file has all the annotations, although the single txt files still don't. Which is fine, since I only want the merged file.
![exported txt file](https://user-images.githubusercontent.com/47432131/53500335-bbea8300-3a6f-11e9-9e55-76e6e881da5f.JPG)
Now I want to know if there was a way to have the original image name exported with the annotations instead of the maximum resolution image name.
![image name](https://user-images.githubusercontent.com/47432131/53500384-d45a9d80-3a6f-11e9-82ce-83c16e53627f.JPG)
And if you could help me modify the merging annotation script so that instead of prompting for a directory file it saves the merged annotations on the project file directly. Do I have to replace
def dirResults = QuPathGUI.getSharedDialogHelper().promptForDirectory()
with
def dirResults = buildFilePath(PROJECT_BASE_DIR, 'annotation results')
?

**Comment by Svidro** [comment]
Haha, I tried to do that too once! I never did pursue it though, since it only needed to be run once at the end of a project. The dirResults object is not a file path though, so manually selecting a directory means at least some of the downstream code needs to be rewritten. I will take another crack at it unless Pete gets to it first :)

**Comment by Svidro** [comment]
Oh, that was actually easier than I thought. This shows the code that needs to change:
```
//def dirResults = QuPathGUI.getSharedDialogHelper().promptForDirectory()
def dirResults = new File(buildFilePath(PROJECT_BASE_DIR, 'annotation results'))
```

**Comment by Svidro** [comment]
And I'll do a quick poke @petebankhead as far as getting the whole slide file name rather than the current image name. All of my current images have the same names as their files, so I can't really run a test. Only suggestion I have there is to try this: 
https://gist.github.com/Svidro/5e4c29630e8d2ef36988184987d1028f#file-get-current-image-name-without-extension-groovy
and see if that gives you the correct result.

**Comment by paulage** [comment]
It worked! Thanks! It prompted me for the file pathway after every image, that's why I needed a fix. 

Any idea if the image name change is possible?

**Comment by Svidro** [comment]
The summary script isn't intended to be run for each image. It definitely CAN be used that way, but you are essentially re-summarizing and overwriting a new summary file for every image. Generally not a slow process, though, so not likely a problem.
