### ISSUE TITLE
Problem installing qupath v0.1.3

### ISSUE THREAD

**Issue by AliceL90** [qupath/qupath#270]
Hi!
I am having some problem re-installing Qupath v0.1.3.

Here is what happened recently:

I used Qupath v0.1.3 for while on mac OS with no big issues until I upgraded to Mojave. At this point Qupath started crashing (with a few more other Apps on my Mac) so I decided to downgrade to macOS Sierra using an old backup. Once I have done that, Qupath was working nicely again, however, one day I opened the software and the first things I have noticed, was that the setting I have changed in the preferences were back to the default ones. I didn't really bother, but then when I tried to open any of my immunofluorescence or chromogenic scans (.scn) Qupath was giving me an error saying that it was not able to find the images in the selected path (even if the images were there). I tried to change location of the slides or start a new project, but nothing worked. Then I tried to re-install the bioformat and qupath extentions. In this way the error message went away and I was apparently able to open the images but for some reason the actual scan wasn't there, it was only able to open the label and the prescan. I tried with different images (all .scn) but I wasn't able to fix the problem. Then I have decided to uninstall Qupath and re-install everything, and now the problem I have is that Qupath is not even opening. The installation from the repository went fine, I have also did `./gradlew clean` before running `./gradlew jfxNative` again. No errors during the installation but now when I double click on the Qupath icon, the software starts but before even opening the main interface it crashes.

Any idea of what I am doing wrong?
Many thanks in advance for any help you can give me!

**Comment by petebankhead** [comment]
The crashes on Mojave sound a lot like this: https://twitter.com/petebankhead/status/1080743299454025728
So if you upgrade your JDK and rebuild QuPath using Gradle then that might be enough.

The inability to handle the .scn files would be because, if the preferences are reset, then the extensions directory gets reset also.  Reinstalling Bio-Formats has the side-effect of also setting the extensions directory.

For the not-opening issue, if you're able to start QuPath from the command line then you should get a more meaningful error message.  It might be trouble in the extensions directory or some corrupting preference.  Opening v0.1.2 and using it to reset the preferences again might help resolve the not-opening problem.

Finally, if all else fails but you can wait a week, then I should have a bit more info to share then...

**Comment by AliceL90** [comment]
Thanks a lot Pete for you prompt answer and sorry for my late reply!

So, I did as you suggested to fix the not-opening issue: I have installed QuPath v0.1.2 and installed the 2 extension .jar file in it. This solved the problem and allowed me to open v0.1.3.

However, I was still not able to open my .scn file properly. So, I decided to remove the qupath-extension-bioformats.jar v0.0.7 and install v0.0.5. This solved the problem. I can properly open my images now with the advantage of not having the pink image and the grey low resolution scan on the image lists. However, if I try to update the qupath-extension-bioformats.jar to v0.0.6 or 0.0.7, I have the same problem as before. Qupath load the images showing me the white macro and another image that does not open in the image list. The error it gives me is about location:

"Sorry, I can't open /Users/alice/Desktop/Analysis/images/AL_p21ko_edu2color_20x_5_3e68c69d-05c4-4cbc-9fbc-25f745e724a9.scn::"

It is like QuPath is not able to locate my images anymore when I upgrade to the newer version of qupath-extension-bioformats.jar.

Any idea why? I can wait a week or more if needed. I can still use QuPath with the v0.0.5 version, so I am not in a super rush.

Thanks a lot for your help, I really appreciate. 

Alice

**Comment by petebankhead** [comment]
v0.0.6 had (accidentally!) a different name, `qupath-bioformats-extension.jar` rather than `qupath-extension-bioformats.jar`.  Having both installed may be the cause of the trouble.  It's not possible to install multiple copies of any other version of the extension (without renaming them).

A couple of related .scn problems came up recently:
* https://github.com/qupath/qupath/issues/271
* https://github.com/qupath/qupath-bioformats-extension/issues/10

More info to come when I have time...

**Comment by AliceL90** [comment]
Thanks Pete.
I removed the `qupath-extension-bioformats.jar`before installing the new version, so having 2 versions at the same time should be reason why I cannot open .scn file with the v0.0.6 and v0.0.7 version.

If you have time and can find a solution for that it would be great. At the moment I am doing fine with v0.0.5.

Many thanks!

**Comment by petebankhead** [comment]
[This](https://qupath.github.io/QuPath-v0.2.0) is what I was referred to. _Hopefully_ your images work with it already... if not, could you share some examples?

**Comment by AliceL90** [comment]
Thanks Pete! The new version of Qupath looks very interesting! I tried to open my images with it and it seems to work perfectly. I will play with it as soon as I have some time and see if everything I was doing before works on this new version too!

I will let you know if I have any trouble.
Thanks again for your help!
