### ISSUE TITLE
Zoom in multiview

### ISSUE THREAD

**Issue by Svidro** [qupath/qupath#284]
**You've checked https://qupath.github.io for a new release that might already have fixed the issue, right?**

**And you've searched for related issues here to see if the issues has already been reported?**

Good, then please fill in the template about the bug...

> For general questions about the software (not bugs) use [image.sc](https://forum.image.sc/tags/qupath)

----

**Describe the bug**
Zooming in and out with the mousewheel with multiple viewers open results in slight "zoom lag" in unselected (non active) windows. Harder to confirm, but I believe there is related XY drift.
**To Reproduce**
Open two windows using multiviewer. Open an image in both, it should default to the same zoom.  Rapidly zoom in, and the zoom will desync, with the non-selected window 

**Expected behavior**
Zoom stays synchronized within all windows.
**Screenshots**

**Desktop (please complete the following information):**
All versions, Win10,7 64 bit.

**Additional context**
Testing bug submission

**Comment by Svidro** [comment]
I take that back, opening 3 images, one (lower left) consistently zoomed in faster, while the other in the upper right zoomed in slower. Controlling the image in the upper left.

**Comment by petebankhead** [comment]
I made two recent commits:
* https://github.com/petebankhead/qupath/commit/a0e1ec253dd790dfceb89b845848c037183d46e7
* https://github.com/petebankhead/qupath/commit/05aaf8f83b8de9166832d64fa6cdba53163e8d92

I'm not entirely sure if the issues have been resolved, but I haven't been able to reproduce any viewer synchronization issues since then. If you have a chance to build m8-SNAPSHOT (or wait until v0.2.0-m8 is released) please let me know if you can replicate the problems (or find new ones) connected to multiple viewers.

**Comment by Svidro** [comment]
I haven't been able to reproduce the issue either in m8.  I can now add a duplicate image and look at one image with the masks on while looking at a second image with no objects. Miniviewer for masks! Except not mini. I guess.

I used to be able to do some other stuff like turn the masks off or on or color them differently per viewer, but that no longer seems to be possible. Not a big deal though, not not really relevant to this.
