### ISSUE TITLE
buildFilePath on m2

### ISSUE THREAD

**Issue by lguerard** [qupath/qupath#289]
Hi all,

I'm trying the new milestone to check speed of script but I'm getting weird results now with the buildFilePath method. 

While it was working with 0.1.* and 0.2_m1, now using the method adds the path to the software in the path.

```groovy
println(path)
> file://path_of_the_file
println(buildFilePath(path))
> G:\Software\QuPath\QuPath-0.2.0-m2\app\file:\path_of_the_file
```

Thanks.

**Comment by petebankhead** [comment]
The path is now a URI, which is useful in distinguishing between a local file and something else (e.g. image hosted with OMERO). Additionally, a URI might have some additional info (query or fragment) necessary to distinguish a specific image found within the same file.

The critical thing is that the path should be unique for each image because it is used for caching image tiles, but it isn't safe to assume that it is a valid path to a local file.  Probably `buildFilePath` happened to work before because the path _was_ usually a path to a local file (albeit sometimes with an extra identifier appended for Bio-Formats) but it wasn't really intended to.  Its main purpose was to build paths relative to the project directory*.

I'm not sure what the purpose of `buildFilePath(path)` is in your script, but it probably now needs replaced with something else.  Otherwise, even if the URI thing was dealt with your script wouldn't work with OMERO-hosted files (and probably others read by Bio-Formats).

> *-Although projects aren't now guaranteed to be local directories either, since a project is now an interface which would be implemented in some other way...

**Comment by lguerard** [comment]
Ok I see, makes sense ! 
The ```buildFilePath(path)``` was used to create a file and save objects there. I guess just a ```new File(path)``` should be enough then ?

**Comment by petebankhead** [comment]
It depends what `path` is... if it's the result of `server.getPath()` then probably not. But if it's some other path in your local file system then yes.

**Comment by lguerard** [comment]
Yes it was just a file to save the objects in order to be able to load them later on. I'll try with the ```new File(path)``` and let you know !

**Comment by lguerard** [comment]
Hi @petebankhead,

I just tried 

```groovy
objects_to_save = getAnnotationObjects()

def out_muscle_path = getCurrentImageData().getServer().getPath() +'_muscle_objects'

println(out_muscle_path)

new File(out_muscle_path).withObjectOutputStream {
    it.writeObject(objects_to_save)
}
```

and just got 

```
ERROR: Error at line 272: file:\network\path\to\the\file.ome.tiff_muscle_objects (The specified path is invalid)
```

Anything I can improve to make it work ?

Thanks :)

**Comment by Tkilvaer** [comment]
I think the problem is the "file:" prefix in path
Try:
def reg = ~/^file:/

def out_muscle_path = getCurrentImageData().getServer().getPath() +'_muscle_objects' - reg

**Comment by lguerard** [comment]
That seems to be working ! Thanks a lot ! :)
