### ISSUE TITLE
Location for extensions seems to fail in QuPath 0.2.0-m2

### ISSUE THREAD

**Issue by lacan** [qupath/qupath#298]
1. There seems to no longer be an 'extensions directory' in the `Preferences` menu
2.  When drag and dropping an extension, you are prompted whether to use the default location or to choose one. If you choose one, it does not work.

Is this a conscious choice? For us in the facility, it is useful for the extensions to be shared among users, this avoids us from having to install them for everyone when as they use their own logins on our processing PCs.

**Comment by petebankhead** [comment]
It's intentional to have a 'user directory' rather than an 'extensions directory', as described here: https://qupath.github.io/QuPath-v0.2.0 (no direct links to headings yet...)

The idea is much the same though. Since Bio-Formats became built-in, I haven't had reason to use it much though and need to check some more how it behaves...

Does setting it to _any_ other location fail, or does it fail _only_ if the location is on a network drive? I've learned of some network drive weirdness, e.g. QuPath can't be started from a network location on Windows, but don't know if it's related to this or not.

> Note that it's not a good idea to use an existing directory extension because older extensions can be horribly incompatible because of the many code changes.  I could look at failing more elegantly in this case, but I only know of a couple of other people who had installed extensions other than Bio-Formats or Weka...

**Comment by Svidro** [comment]
And I am interested in what more extensions are out there!

**Comment by lacan** [comment]
>Does setting it to any other location fail, or does it fail only if the location is on a network drive? I've learned of some network drive weirdness, e.g. QuPath can't be started from a network location on Windows, but don't know if it's related to this or not.

Setting it to another location simply does not load the extension. But I have not tested whether this is because QuPath does not read the preference (which cannot be set anymore in the Preferences menu).
This was the case when the extension was going to be added to a local disk. No network drive.

> Since Bio-Formats became built-in, I haven't had reason to use it much though and need to check some more how it behaves...

We created an extension which you can found here https://github.com/BIOP/qupath-biop-extensions which we have been using sucessfully (and which is not updated to work with our little modifications to QuPath 0.2.2-m2

**Comment by lacan** [comment]
> And I am interested in what more extensions are out there!

The one we have is here https://github.com/BIOP/qupath-biop-extensions

But you should use our branch biop-java11 if you want it to work...
https://github.com/BIOP/qupath/tree/biop-java11

**Comment by petebankhead** [comment]
This commit aims to fix the use of non-default directories: https://github.com/petebankhead/qupath/commit/8d7693b22c79446b0d92b6dac1afab6ccb2b0745

Note that you can set the directory in the preferences, but search for 'user' rather than 'extensions'.

Note that this is in a particular branch of my fork; I plan to sanitize the various branches/forks in the near future to make it a bit clearer where everything is/should be.

**Comment by petebankhead** [comment]
This should be fixed in [v0.2.0-m3](https://github.com/qupath/qupath/releases/tag/v0.2.0-m3) - please reopen if it turns out not to be!
