### ISSUE TITLE
Some IF fluorescent .scn images do not open correctly (not stitched)

### ISSUE THREAD

**Issue by r-mvl** [qupath/qupath#300]
**Describe the bug**
Some fluorescent .scn images scanned on Leica Aperio Versa do not open properly on QuPath. Not sure where the problem is. I can open them just fine in ImageScope on windows, but for some reason in certain cases, QuPath opens the individual images instead of recognising it as stiched/pyramidal images?

**To Reproduce**
2 example images:
[image that do not open properly](https://www.dropbox.com/s/4281rsnql1wc3k0/bug.scn?dl=0)
[image that opens fine](https://www.dropbox.com/s/x8zaexcb8rx3j69/fine.scn?dl=0)

**Desktop (please complete the following information):**
 - OS: macOS
 - QuPath Version 0.1.3 and 0.2.0-m2

**Comment by Svidro** [comment]
I haven't had a chance to test this, but if you have a log file and which
ImageServer is being used (in the image tab) that would be helpful. If it
is a BioFormats server, you should also try opening the file with FIJI
through the BioFormats importer plugin to see if you get the same behavior.
If you do, it is a problem that likely needs to be dealt with through the
BioFormats people. I had a similar sounding issue with 8bit CZI brightfield
images where only one tile would open, and that turned out to be a
BioFormats thing.

**Comment by Svidro** [comment]
I had a look, and can confirm that this is some sort of alteration to the metadata. BioFormats reads it both in QuPath and in Fiji as a list of 350 images. It also has the telltale pink pixel problem of .scn files that are buggy. https://github.com/qupath/qupath/issues/141
Disabling BioFormats prevents the files from opening.
More info here, which probably won't help since it was also you. https://github.com/qupath/qupath/issues/191

Most likely you will need to handle this through BioFormats.

**Comment by petebankhead** [comment]
I also had a look, and it seems to be more of a Bio-Formats question than a QuPath one.

**Comment by rmd06** [comment]
I also had a look. It seems that the bug.scn file was captured in a different way as fine.scn.
In the more than 300 images, the most of them are several ROIs in the whole slide, with different magnification and even Z-stack. I also note that a few of the image cannot be opened because of java heap space, for example the 1st image in the list.
There is a possibility that these large images that cannot be opened were the stitched complete whole slide images. It's just too large that cannot be opened.
In the future, you can capture only 1 ROI at a time and generate a .scn file, just like the fine.scn.

**Comment by rmd06** [comment]
For example, 6 ROI x 7 maginification x 8-slice = 336 images, plus several other images, make up the 350 imahes

**Comment by rmd06** [comment]
I know that some kinds of whole slide image format could be shown in QuPath as several rectangular ROIs in a whole slide with blank white filled between the undefined spaces outside ROIs. In this case the ROIs even can be viewed at highest resolution when you zoom in. 

However, it should be noted that different whole slide scanner must deal with this situation in different ways, and each has their own viewers.
The OpenSlide package may help deal with some, but not all of the formats in terms of arranging multiple ROIs in a whole image.
Bioformats  may support less compared to OpenSlide when dealing with this situation.

Usually if cannot deal with it, just show the pieces of images. If can, show the merged whole image.
I'm not sure .scn was supported to which extent. But according to my experience, .scn and .mrx were the two formats that hard to deal with.

**Comment by r-mvl** [comment]
Thanks for your answers and trying to open them. I think I have always used bioformats to open .scn images.

Regarding the different ROIs, I have to say that previously, I have managed to open .scn images with different ROIs. In QuPath, they would open as different images in the image list tab, which is fine to work with. But the bug.scn file is not >300 ROIs, it is meant to be a normal slide scan, and for some reason it seems to detect each tile as an individual ROI. It is frustrating to see that it opens fine in ImageScope, but not in QuPath... if this is a bioformat issue perhaps I should post on the bioformat page then...

ps: I appreciate that mrx and scn files are annoying to work with, but there are unfortunately very common file types in the research/academic world at least...

**Comment by petebankhead** [comment]
QuPath tries to have as few customizations as possible for specific file formats (almost none...), relying only on what OpenSlide and Bio-Formats provide. If images in the same format end up opening differently in QuPath, then it is most likely because there is something in the file that causes OpenSlide or Bio-Formats to handle them differently*.

The Bio-Formats and OpenSlide teams have done an incredible job in support many formats to date, but of course they are under no obligation to do so. Unlike the software developed by the vendors themselves, who have access to the full details of their proprietary formats, open projects often need to make educated guesses to try to figure out how to read the files.

In my opinion, if someone has a proprietary file format then it should be up to them to help ensure it is supported in open software... _if_ they want that to be possible. It's perfectly legitimate for them to decide that they don't want their format to be open, but in that case potential customers for whom this matters need to find this out.... ideally before paying a lot of money for something they will be unable to use fully.

Presumably Bio-Formats don't have a specification for the .scn format (on the website it is listed as [something they would like to have](https://docs.openmicroscopy.org/bio-formats/6.0.1/formats/leica-scn.html)) and they have also [blogged on mrxs](http://blog.openmicroscopy.org/file-formats/community/2016/01/06/format-support/).

It seems really unfortunate that formats that are common in the research community aren't always well supported in open software. Ultimately it's really only the people behind the formats that can change this... I hope that greater awareness of the underlying reasons might help the research community exert pressure in the right direction - in the way that the Bio-Formats blog post describes.

>*-Although it is always possible that there is a bug in QuPath causing the trouble... but if some work and some don't, with exactly the same QuPath settings, I think this is less likely to be the explanation.

**Comment by petebankhead** [comment]
Admittedly that turned into a bit more or a rant than intended, and an obscure comment buried in a GitHub issue probably won't be a major part of any path to 'greater awareness' in the research community... still, hoping the situation will improve somehow!

**Comment by petebankhead** [comment]
I will close this issue as it doesn't appear to be something that can be resolved within QuPath.
Please reopen if there are further developments, otherwise this sounds like it is a file format/Bio-Formats question.
