### ISSUE TITLE
MRXS slides only opening in lowest resolution (worked in 0.0.7)

### ISSUE THREAD

**Issue by mariokreutzfeldt** [qupath/qupath#32]
Hi,
the update from 0.0.7 to 0.1.1 broke MRXS support.
The files (Brightfield, RGB, JPG) now only open in lowest resolution.
Changing back to version 0.0.7 fixes the problem.

Thanks for all you great work,
Mario

**Comment by petebankhead** [comment]
Hi Mario,

Thanks for letting me know.  I have tried several MRXS images on v0.1.1 using Mac and it seems to be working here, so it would be good to know a bit more about the problem you are seeing.

* Are you running QuPath on Windows/Linux/Mac?
* When it doesn't work, do any errors appear - or do you see any errors logged under *View &rarr; Show log*?
* Do you know if v0.1.0 works?

Thanks,

Pete

**Comment by petebankhead** [comment]
One other question: when it doesn't work, what is the *Server type* that you see in the *Image* tab?

In the screenshot below, the *Server type* is *OpenSlide* (which is what it should be for MRXS files).

![Server type](https://cloud.githubusercontent.com/assets/4690904/19970686/a81eaf8a-a1d4-11e6-810e-491db8fb6612.jpg)

**Comment by mariokreutzfeldt** [comment]
Hi Pete,

I'm running QuPath under Mac. We replicated the issue on 2 machines.

Version 1.0.0 works fine, too.
Server Type: OpenSlide

V1.0.1. Error in log is: Could not load OpenSlide native library (followed by a lot of Java errors)
Server Type: ImageJ server

Cheers,
Mario

**Comment by petebankhead** [comment]
Thanks, that's quite strange... I've just downloaded it again, and it is working here on two different Macs.

Are you running macOS Sierra, or some other version?

If QuPath can't load OpenSlide, then I expect it can't load any other whole slide formats (unless you have the Bio-Formats extension installed).  In that case, I would expect it to fall back to using ImageJ for MRXS images to read only the low-resolution data.

If you right-click on QuPath.app and select 'Show package contents', you should be able to see something like what is shown below:

![libopenslide](https://cloud.githubusercontent.com/assets/4690904/20973479/a23ad306-bc90-11e6-9863-e9281c2c9110.jpg)

I suspect the issue may be connected to differences in the many ```lib*``` files.  One way to test this is to copy all the ```lib.*``` files from a QuPath version that works (i.e. anything before v0.1.1?) and paste it into the QuPath that doesn't.  This may cause v0.1.1 to function.

If these instructions make any sense, could you try this?

Thanks,

Pete

**Comment by petebankhead** [comment]
It would also be good if you could copy and paste the full long error message, in case that helps identify exactly which library is failing to load (OpenSlide links to several).

**Comment by petebankhead** [comment]
Actually, no need to send the error... I was able to reproduce the problem on an older Mac here.

It would still be good to know what version of the operating system you are running.  It works for me on Sierra, but not on Mavericks - although I'm not sure if that's relevant.

In any case, my awkward hack of copying the ```lib*``` files from a working version to v0.1.1 appears to work - so I will try to find which part is missing in v0.1.1, and recompile a version with everything that is required.

**Comment by mariokreutzfeldt** [comment]
Great to hear that you could reproduce the error.
we've tried under osx Sierra and osx el Capitan with the same results.
thanks again!

**Comment by petebankhead** [comment]
I've just updated the Mac release [here](https://github.com/qupath/qupath/releases/tag/v0.1.1).
It works for me on all three computers now.  Please let me know if it also solves things on your side.

(Thanks again for reporting this - it appears to have been connected to libraries I have installed on my own computers but didn't include in the distribution, so I assume the Mac version was not working for anyone else... so it was a pretty big problem!)

**Comment by mariokreutzfeldt** [comment]
Working like a charm now! 
Just for the sake of completeness. Openslide still reports some "Errors":
ERROR: Openslide: Property not available: openslide.level[0].tile-width
ERROR: Openslide: Property not available: openslide.level[0].tile-height

But they are the same across all versions of QuPath I've tested and don't hinder 
image analysis on MRXS slides.

Thank again for fixing this issue so fast! 
Have a great day,
Mario

**Comment by petebankhead** [comment]
Fantastic, that's a relief, thanks!
I saw those errors tile width/height too, only with MRXS files... but yes, they don't seem to cause trouble.

For reference, this is what happened:
I recompiled OpenSlide for Mac back for v0.0.7, to address issues related to opening MRXS files with certain types of compression (possibly BMP or PNG).  However, I appear to have accidentally included the previous versions of the library + dependencies in the Mac download, possibly because the machine on which I finally compiled the Mac version of QuPath for distribution had cached the original libraries, which had the same version number (since they traced back to the same version of OpenSlide).

So v0.1.1 was the first download to actually contain the Mac OpenSlide updates intended for v0.0.7.  And it turned out that those updates were missing a couple of required files, but which were available on my development machines... lulling me into a false sense of security that all was well.

Anyhow, I've now repackaged OpenSlide + dependencies, added in the license notices for the additional required files, and bumped up the version number to 3.1.4_2 to make it clear which OpenSlide should be included in all future versions of QuPath compiled for Mac - regardless of machine.

Outcome:
* OpenSlide included with the Mac distribution of v0.1.1 should be able to handle slightly more kinds of image than previous versions... but in the overwhelming majority of cases, it will look the same
* None of this matters for QuPath running on anything other than Mac
* I was never going to figure out there was a problem on my own, since it was working for me... so thanks for letting me know!
