### ISSUE TITLE
Bug or feature? - project files in 0.2.0-m2 store all paths to images as absolute path

### ISSUE THREAD

**Issue by sekro** [qupath/qupath#325]
**You've checked https://qupath.github.io for a new release that might already have fixed the issue, right?**

**And you've searched for related issues here to see if the issues has already been reported?**

Good, then please fill in the template about the bug...

> For general questions about the software (not bugs) use [image.sc](https://forum.image.sc/tags/qupath)

----

**Describe the bug**
Not sure if this is a bug or intended:
In 0.1.x versions of qupath the qupath project would save the relative path to the images if placed inside a folder inside the project folder.
In version 0.2.0-m2 the path to an image is always absolute.
This makes moving a project folder very risky :)

**To Reproduce**
- How I setup a project under QuPath 0.2.0-m2 and 0.1.2:
1. In QuPath choose empty folder for the project
2. mkdir images inside the project folder
3. copy images into new folder images
4. In QuPath add images from this images folder to the project
5. Save/Close
5. Check QuPath project file with texteditor:
-> v 0.1.2 - path to images are relative to project folder
-> v 0.2.0-m2 - path to images are absolute

**Expected behavior**
Same behavior in v0.2.0-m2 as i v0.1.2 - usage of relative path in project file

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - QuPath Version 0.2.0-m2 vs 0.1.2

**Additional context**
- Work-around:
- setup project folder directly in the base directory (https://github.com/qupath/qupath/issues/325#issuecomment-497796974)
- Edit project file with text editor to replace/update absolute path

**Comment by Svidro** [comment]
Yep. Odd, I thought I had posted this already, but it looks like I did not! Good to have it listed.

For the moment I have resorted to storing project folders directly in the base C directory, so that I can transfer them to collaborators and they can drop the folder directly into their C drive. Images and all.

**Comment by sekro** [comment]
Updating the path inside the project file with a text editor is my current work-around :)

**Comment by petebankhead** [comment]
Not a feature, just a lack of time... this commit aims to restore an improved check for relative paths https://github.com/petebankhead/qupath/commit/309d6e58560791d17af0580fbad2b6a5d24100b2

This should be better than the old behavior, since it _always_ checks relative paths regardless of where the original images were relative to the project (previously the images needed to be inside the project directory).

But much more work remains to be done on updating projects, and it's not yet entirely clear how they'll look on the other side.

**Comment by petebankhead** [comment]
Changes now available [v0.2.0-m3](https://github.com/qupath/qupath/releases/tag/v0.2.0-m3).
Absolute paths are stored, but QuPath checks relative path if the image is not found.
