### ISSUE TITLE
Feature request: Cell Detection nuclear channel mini-viewer

### ISSUE THREAD

**Issue by Svidro** [qupath/qupath#327]
After using the "Show" button for the pixel classifier features, it would be nice to have a similar feature for the image the Cell Detection function uses to generate nuclei. Even better if we could see a small area change in real time as we adjust the values!

**Comment by petebankhead** [comment]
Hmmm, so if I follow correctly, you're saying it was a mistake to give you a "Show" button for the pixel classifier features?

**Comment by Svidro** [comment]
Hmmmmm....

**Comment by Svidro** [comment]
Maybe also include an option for world peace.

**Comment by petebankhead** [comment]
I suppose you'll want that in real time too?

**Comment by Svidro** [comment]
Retroactively applied would be better, but I could settle.

**Comment by petebankhead** [comment]
Closing this issue because I'm afraid I don't see it as possible - at least not with the current cell detection. It might be more feasible in a future incarnation, but that may need to be radically different (e.g. like how the simple threshold in [v0.2.0-m5](https://github.com/qupath/qupath/releases/tag/v0.2.0-m5) can potentially replace simple tissue detection).

Of course, feel free to prove me wrong with a pull request :)
