### ISSUE TITLE
Saved classifier doesn't work

### ISSUE THREAD

**Issue by takakono** [qupath/qupath#331]
Describe the bug
Saved classifier doesn't work

To Reproduce****Expected behavior

I made a classifier file for Ki-67 and saved them.
I could load the classifier file during the another slide analysis, but it didn't work as using "Run classifier" button. 
How can I get it working?

Desktop (please complete the following information):
Windows 7
QuPath Version [0.2.0-m2]

**Comment by takakono** [comment]
sorry I forgot to attach the screen shots
![QuPath classifier run TMA version](https://user-images.githubusercontent.com/51498119/59464592-bb3aea00-8ddd-11e9-89ef-8c6a0367b3bb.PNG)
![Ki67 run classifier surgical specimen](https://user-images.githubusercontent.com/51498119/59464604-c55ce880-8ddd-11e9-8659-9d9a309c50b8.PNG)

**Comment by Svidro** [comment]
Have you tried running the saved file from a script?

`runClassifier("C://path//here")`

Also, I don't actually see any cells in your images, so there is nothing in your images to classify yet. Not sure if they are just to demonstrate the image or not.

**Comment by takakono** [comment]
I have tried running from a script, but 'run' button didn't become active status.
This screenshot is the case I made the classifier file from it.
![script](https://user-images.githubusercontent.com/51498119/59467877-9cd8ec80-8de5-11e9-8eca-5ed9a03906ae.PNG)

**Comment by Svidro** [comment]
Right, you have cells there, so it should work on those cells. If you create new cells with the same measurements, it should also work. 

You do need to both have cells, and a classifier file though. It looks like you... I guess copied output text into the macro window, along with the runClassifier command with no file path. So nothing should happen.

If you generate some new cells in a new image, and _include the path to the same classifier_, you should only need to run that one line script.

**Comment by Svidro** [comment]
Final script (after the TMA cores are set) would probably look something like:
![image](https://user-images.githubusercontent.com/23145209/59468488-060d2f80-8de7-11e9-9023-aa9b1edb402b.png)
Though you need the correct path. That is not the correct path :)

**Comment by petebankhead** [comment]
@takakono this looks like confusion over the purpose of the classifier. You need to detect cells first before there can be anything to classify.

Running the classifier won't do anything if you haven't already detected cells on the image.

The supplementary material in the [Scientific Reports paper](https://www.nature.com/articles/s41598-017-17204-5) may be helpful, especially the PDF, as it describes step-by-step how I applied some similar analyses.

I will close this because it doesn't appear to be a bug in QuPath after all. The forum is the right place for questions about using the software: https://forum.image.sc/tags/qupath
