### ISSUE TITLE
Building extensions

### ISSUE THREAD

**Issue by hackothaurus** [qupath/qupath#338]
Hello. I want to build an extension to qupath. I have never built an extension before, and I set up IntelliJ and followed the tutorial about advanced scripting present on the qupath wiki, but I was unsuccessful. My OS is Linux Ubuntu. Can someone tell me how I can get started using IntelliJ? I tried using Maven too but was unable to find any pom.xml file.

**Comment by petebankhead** [comment]
Hi, the instructions are for QuPath v0.1.2 (which uses Maven) but the repo contains the code for the next release (which uses Gradle and has a build.gradle instead of pom.xml).

As part of that, the API is also changing rather considerably. The goal is to stabilize things to make it easier to add extensions, but limited by a chronic lack of time and the fact I'm the only person working on the software (although there's [a position being advertised to join me](https://www.vacancies.ed.ac.uk/pls/corehrrecruit/erq_jobspec_version_4.jobspec?p_id=048500)...).

I don't know what's the goal of your extension, but my advice would be to focus on scripting first. It's generally much faster to get things working, and you can convert your Groovy script to a Java extension at some point in the future. I often prototype extensions first as scripts (and usually never actually need to convert the scripts to extensions).

My instructions for getting started with IntelliJ are on the Wiki, which you've seen. I don't know what specifically 'I was unsuccessful' means, so really can't expand on that without knowing _exactly_ where or how it went wrong. Note that the instructions were written for v0.1.2 and need updated, but this won't happen until v0.2.0 is ready.

Note also that the Q&A forum is at https://forum.image.sc/tags/qupath and this is the place to ask questions that are not directly related to a bug in the software.

**Comment by petebankhead** [comment]
Closed as discussion now at https://forum.image.sc/t/building-extensions/27713
