### ISSUE TITLE
DoG superpixels leave a gap between tiles

### ISSUE THREAD

**Issue by saramcardle** [qupath/qupath#345]
When using DoG superpixels, there is a 1 pixel gap between tiles. When I convert these superpixels into annotations, the resulting annotation in broken into 2 pieces, with weirdly shaped boundaries. Could you generate the tiles such that there is overlap between the superpixels?

![image](https://user-images.githubusercontent.com/29264310/62152808-1eaea780-b2b8-11e9-8d6d-96af6137057f.png)

**Comment by petebankhead** [comment]
It looks like this was intentional, albeit not a very good idea when tiling is involved:
https://github.com/qupath/qupath/blob/b4a442535b2bd8169aacf16ecf6aac61004971b0/qupath-core-processing/src/main/java/qupath/imagej/superpixels/DoGSuperpixelsPlugin.java#L185-L194
However it seems that removing these lines doesn't (quite) address the issue - at least some gaps can remain. A proper fix will take some more effort.

The workarounds [here](https://forum.image.sc/t/filling-gaps-in-dog-superpixels-in-qupath/28269/8) are likely best for now.

**Comment by petebankhead** [comment]
This should be improved in [v0.2.0-m5](https://github.com/qupath/qupath/releases/tag/v0.2.0-m5) but isn't fully resolved... so the issue remains.

**Comment by petebankhead** [comment]
Closing this issue because the proposed fix is now available in v0.2.0-m10 - please feel free to open it if you find the problem remains.
