### ISSUE TITLE
[Issue with solution] WSIs not displayed correctly

### ISSUE THREAD

**Issue by EKami** [qupath/qupath#355]
## IMPORTANT!

**This is only for bug reports - for questions or discussions, please use the forum at [image.sc](https://forum.image.sc/tags/qupath) instead**

## Before we begin...

**You've checked https://qupath.github.io for a new release that might already have fixed the issue, right?**

**And you've searched for related issues here to see if the issues has already been reported?**

If not, please do these things first.

Otherwise, please fill in the template below with as much information as possible to help us reproduce the bug & fix it.

## Bug report

**Describe the bug**
Black/White squares are appearing in the WSIs when viewed under QuPath 0.2.0-m4 Linux (also happen on older versions). QuPath 0.1.2 does not have this issue, I think it started with QuPath 0.2.0+. See below for a resolution.

**To Reproduce**
1. Select a WSI of any type (Mirax, SVS, Tiff...)
2. Notice the display bug

**Expected behavior**
No display bug

**Screenshots**
![2019-09-02_09-24](https://user-images.githubusercontent.com/4030626/64131323-864a8d80-cd63-11e9-8e66-e4a9201d409c.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - QuPath Version 0.2.0-m4

**Additional context**
This issue is caused by the Pixman library used as a dependency of Openslide. As QuPath ships with a bunch of precompiled shared libraries on Linux (and not using those from the system), it also carries with it this bug. Have a look at [this thread](https://github.com/libvips/libvips/issues/1401) for more information.

**Comment by petebankhead** [comment]
Wow... I haven't seen this before, but I've only used QuPath with Ubuntu occasionally and not with other Linux distributions. But I'm pretty sure it was working for me in the past... and I didn't _think_ anything had changed from v0.1.2 in this regard.

I remain a big fuzzy on the cause and the solution. Is the problem that the OpenSlide with QuPath is actually using the local installation of pixman as a sub-dependency... and an update to this is what has caused the problem? Any time I've delved into the Java library path and sub-dependencies on different platforms I haven't enjoyed the experience or emerged much smarter.

Alternatively, now that Bio-Formats is included by default and OpenSlide doesn't appear to be being actively developed, would it be best just to exclude OpenSlide from the Linux distribution - but try to pick it up from a system-wide installation? Or is there another way?

The main trouble I expect with relying on a local installation entirely is that the openslide-jni file will still be needed.

**Comment by EKami** [comment]
> Is the problem that the OpenSlide with QuPath is actually using the local installation of pixman as a sub-dependency...

I don't think any library from the system is being used. Here:
```
$ ldd ./QuPath-0.2.0-m4
        linux-vdso.so.1 (0x00007ffe0e363000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fe33f2be000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007fe33f178000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fe33efb5000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fe33f309000)
```
And I would ship QuPath with the integrated libraries like you, using the system wide libraries would only cause more trouble as people would probably be complaining about this bug forever if they don't use the right version on their system (even worse if they use 3.4.0 which has its own set of problems).

Update: I just tried with an Ubuntu 18.04 vm and it works fine there... So it probably means QuPath is actually looking for the pixman lib somewhere in my system where it's corrupted. I'm on the latest version of Manjaro Linux (arch).

**Comment by EKami** [comment]
Yep, somehow the libpixman used is the one from my system:
```
$ cat /proc/30668/maps | grep pixman
7f0c393d0000-7f0c393db000 r--p 00000000 103:07 42091621                  /usr/lib/libpixman-1.so.0.38.4
7f0c393db000-7f0c39461000 r-xp 0000b000 103:07 42091621                  /usr/lib/libpixman-1.so.0.38.4
7f0c39461000-7f0c39471000 r--p 00091000 103:07 42091621                  /usr/lib/libpixman-1.so.0.38.4
7f0c39471000-7f0c39479000 r--p 000a0000 103:07 42091621                  /usr/lib/libpixman-1.so.0.38.4
7f0c39479000-7f0c3947a000 rw-p 000a8000 103:07 42091621                  /usr/lib/libpixman-1.so.0.38.4
```
On both QuPath 0.1.2 and QuPath 0.2.0. Now I have no idea with 0.1.2 works fine while 0.2.0 doesn't... that doesn't make sense...
Ideally it would be great if it could ship with a QuPath release with the fix.

**Comment by Tkilvaer** [comment]
Perhaps this is related to the bounding box?

man. 2. sep. 2019, 22:46 skrev Tuatini Godard <notifications@github.com>:

**Comment by petebankhead** [comment]
Did I correctly understand that v0.1.2 works on the same Linux machine where v0.2.0 fails?

If so, it may be because the native libraries are in the same location as the launcher. This happened 'naturally' with the `javafxpackager` in JDK 8, but not with `jpackage` now. Because loading [sub-dependencies is not exactly straightforward](https://bugs.openjdk.java.net/browse/JDK-8213772) the only way I could see to get it working on Windows was to load the dependencies in reverse order [here](https://github.com/qupath/qupath/blob/v0.2.0-m4/qupath-extension-openslide/src/main/java/qupath/lib/images/servers/openslide/OpenslideServerBuilder.java#L51).

The problem may be masked on Linux where OpenSlide is already installed and so the libraries are found on the system... just not the expected ones. So the 'bug' in QuPath is separate from the pixman issue - it's rather around how the native libraries are made available. Therefore updating pixman on a broken system could at least get things working again.

I can think of three possible ways around this within QuPath:
* Try to load the sub-dependencies 'backwards', as with Windows; not terribly maintainable, but if OpenSlide isn't actively developed then it won't be updated often
* Change the build script to try to get the native libraries alongside the launcher; I'd _prefer_ not to fight `jpackage` regarding locations in case it causes more trouble, but may be ok
* Require a separate OpenSlide installation (but the JNI library will still be needed)

Overall, getting OpenSlide to behave well cross-platform has proven very difficult... not helped by my lack of C. The situation with OpenCV had been similar, but is now _much_ better thanks to JavaCPP.

Any help with packaging OpenSlide up in a portable, cross-platform way would be much appreciated. See also https://github.com/qupath/qupath/issues/151

**Comment by EKami** [comment]
> Did I correctly understand that v0.1.2 works on the same Linux machine where v0.2.0 fails?

Yes, that's correct.

I'm not sure how I'm supposed to load the dependencies "backward" tho. I'll try a few things and come back if I find a solution for this. Thanks a lot!

**Comment by petebankhead** [comment]
You can see the awkward way I do this on Windows via the link in my last post.

Basically, as far as I can recall `System.loadLibrary` will check if a library is loaded, and if not then it will look on the Java library path for it. However if that library has a sub-dependency then the Java library path becomes irrelevant... and the search for sub-dependencies will be system dependent*.

Therefore if you explicitly load the sub-dependencies first, they will already be available whenever `System.loadLibrary` is needed for the main library you wanted in the first place - and the less controllable, system-dependent search can be avoided.

Somewhat inconveniently, in this case there are sub-dependencies and sub-dependencies of sub-dependencies... so figuring out the order in which they need to be loaded isn't entirely straightforward.

It feels like there should be a far more elegant way to do this, but I haven't found it.

*-This may mean searching in the directory from which QuPath was launched, so copying the library files there could be an easy workaround - I'm not entirely sure.

**Comment by EKami** [comment]
Hi, sorry for the late reply.

Ok I understand. 

> Somewhat inconveniently, in this case there are sub-dependencies and sub-dependencies of sub-dependencies... so figuring out the order in which they need to be loaded isn't entirely straightforward.

Yep it's something that I noticed when looking for what lib uses what lol

I was wondering if you plan to drop Openslide entirely from the dependency tree and use [libvips](https://libvips.github.io/libvips/) instead? It uses Openslide internally for cetain formats but accept much more format, automatically fixes the unmaitained bugs Openslide didn't (as the support for this lib is non-existent since a while now) and is much faster than Openslide.

**Comment by petebankhead** [comment]
I hadn't really thought of libvips for this purpose as it seems much more than an image-reading library - but if it could offer a more extensive and maintainable alternative to OpenSlide alone that would be fantastic.

I notice that bindings are available for multiple languages, but Java isn't listed as one of them. I can also only see binaries provided for Windows.

Therefore, assuming it can be used in a similar way to OpenSlide (i.e. open an image, retaining a reference to it and requesting tiles on demand) then to get it into QuPath I think it would need:
* Binaries for Windows, Linux and Mac (including OpenSlide and potentially other optional dependencies - assuming the licenses all fit)
* Java bindings, presumably with JNI (or [can JavaCPP help...?](https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes))
* A QuPath extension to bridge the gap

The last one of these should be quite straightforward. I'm afraid I don't have the time or skills for the first two, but they can be treated entirely separately from QuPath.

Do you know of a solution to the first two requirements / have any interest in coming up with one to make libvips available in a cross-platform way that could be distributed through QuPath?

**Comment by petebankhead** [comment]
I'll close this issue because of lack of activity, and because the practical solution lies outside QuPath (i.e. updating the dependency).

The question remains of how best to continue using OpenSlide within QuPath, and especially how (or whether) to try to package it up more portably for Linux - but that's probably best considered in a separate issue.
