### ISSUE TITLE
0.2.0-m4 doesn't open VSI-files correctly + two other VSI remarks 

### ISSUE THREAD

**Issue by HADale** [qupath/qupath#361]
Hi. 
Main issue:

- Version QuPath 0.2.0-m4 (OS Windows) doesn't open olympus VSI files correctly anymore.

See attached image: 
![VSI_m2_vs_m4](https://user-images.githubusercontent.com/55238250/64780209-0fca3e80-d560-11e9-817d-c90eeee4865c.PNG)

Left hand side is the 0.2.0-m2, right hand side is 0.2.0-m4.
m4 only opens the label and the Image list is lost. Hope this will be fixed soon :)

Another two issues: 

- The 0.2... version in general; it doesn't any longer recognize the image type when opening VSI-files. This worked fine in  0.1...versions with the Bio-Format extension. 

- In all versions (0.1... included) the color of the different fluorescent channels are mixed up, for example the FITC channel is displayed in red and TRITC channel in green . This must be manually corrected under brightness and contrast, and it would of course be convenient if it was recognized automatically.

**Comment by HADale** [comment]
Hi again and thanks a lot for the fast feedback. 
Opening the VSI files works fine when a project is created, and choosing fluorescence as the image type when importing images helps on the flow.  
Petes suggestion of changing colors once for all images of the same type once in a project works, and is remembered when opening the project again (except with a few glitches).

Just to show you how the channels appear by default, see attached image. The naming (Dapi, Fitc etc.) is correct, but the colors always comes up in this order R G B Y, regardless of which channels the image consists of.  
![color vs channel](https://user-images.githubusercontent.com/55238250/64848050-aa825600-d610-11e9-8baa-49af6501c8d4.PNG)

**Comment by petebankhead** [comment]
> Petes suggestion of changing colors once for all images of the same type once in a project works, and is remembered when opening the project again (except with a few glitches).

Yeah, I do need to look into that one day... I haven't noticed anything that reproducibly doesn't work, but there's definitely room for improvement.

> Just to show you how the channels appear by default, see attached image. The naming (Dapi, Fitc etc.) is correct, but the colors always comes up in this order R G B Y, regardless of which channels the image consists of.

If you'd like to run the following one-line script and share the output I can investigate:
```groovy
print getCurrentImageData().getServer().dumpMetadata()
```
The result should be a long string of text (XML). Basically, it should reveal what Bio-Formats has read from the file. If the colors encoded within this text match with what QuPath shows then QuPath is doing what it is supposed to.... otherwise there is a bug on the QuPath side.

**Comment by HADale** [comment]
EmissionWavelength="455.0" EmissionWavelengthUnit="nm" ID="Channel:7:0" Name="DAPI" SamplesPerPixel="1"><DetectorSettings Binning="1x1" ID="Detector:0:7"/><LightPath/></Channel><Channel EmissionWavelength="518.0" EmissionWavelengthUnit="nm" ID="Channel:7:1" Name="FITC" SamplesPerPixel="1"><DetectorSettings Binning="1x1" ID="Detector:0:7"/><LightPath/></Channel><Channel EmissionWavelength="565.0" EmissionWavelengthUnit="nm" ID="Channel:7:2" Name="TRITC" SamplesPerPixel="1"><DetectorSettings Binning="1x1" ID="Detector:0:7"/><LightPath/></Channel><Channel ID="Channel:7:3" Name="CY5" SamplesPerPixel="1"><DetectorSettings Binning="1x1"

**Comment by petebankhead** [comment]
This is the kind of data I get for another image:
`<Channel Color="-16776961" ID="Channel:0:0" Name="Some name" SamplesPerPixel="1"><LightPath/></Channel>`
I guess it may be different for different formats - QuPath queries only the color properly, not the wavelength.

So it doesn't look like a bug, although it may be worth supporting emission wavelength if the color is not otherwise provided. I thought Bio-Formats already did this but I don't know.

**Comment by HADale** [comment]
Just checked to be sure, and there are no matches for color in the result either... 
But thanks anyway for the efforts, and if you find time at some point to look into the support for emission wavelength it would of course be appreciated : )  
Great software by the way!

**Comment by petebankhead** [comment]
Great, thanks :) I'll close this issue but will keep an eye out for other cases where emission wavelength is ignored.
