### ISSUE TITLE
Small tif files are pink and large tif files won't import

### ISSUE THREAD

**Issue by thinkCara** [qupath/qupath#374]
## IMPORTANT!

**This is only for bug reports - for questions or discussions, please use the forum at [image.sc](https://forum.image.sc/tags/qupath) instead**

## Before we begin...

**You've checked https://qupath.github.io for a new release that might already have fixed the issue, right?**

**And you've searched for related issues here to see if the issues has already been reported?**

If not, please do these things first.

Otherwise, please fill in the template below with as much information as possible to help us reproduce the bug & fix it.

## Bug report

**Describe the bug**
A clear and concise description of what the bug is:
TMA tif files of magnification 0.25, 0.625, 1.25, 2.5, and 5x all load with a bright pink background. I don't know how to remove the pink color and the TMA dearrayer doesn't work properly. TMA tiff files larger than 5x will not load at all. 10, 20, and 40x fail to be added to the project. Error message, "Failed to load one image." is shown when trying to add one file at a time.

**To Reproduce**
1. Click on 'Create project' (make a new folder and name it)
2. Click on 'Add images'
3. Click on 'choose files'
4. Navigate to file and select it. 
5. Click on 'Open'
6. Click on 'Import'
7. The result is either a pink thumbnail and pink image or an error message and no image added.

**Expected behavior**
A clear and concise description of what you expected to happen:
All tif files should be added to the project and names and thumbnails should be visible on the left hand side of QuPath. Slide backgrounds should be white and not pink. (I know the background isn't actually pink because the files open correctly in ImageScope.)

**Screenshots**
Pink background for TMA tiff files
![2019-11-07_1304](https://user-images.githubusercontent.com/6699385/68389277-db8b8c80-0162-11ea-9a67-38f297589135.png)

Failure to upload error message with the attempted upload file highlighted in the Windows window
![2019-11-07_1334](https://user-images.githubusercontent.com/6699385/68389530-74baa300-0163-11ea-993d-a55b99b93934.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise version 1809; Intel i7; 64GB RAM (45 GB alotted for QuPath)
 - QuPath Version: 0.2.0-m5

**Additional context**
The accompanying .ndpi files for this data set load without issue. This problem was noticed because I tried to load png files for another data set that loaded in the previous version (Version: 0.1.2) but not the new version of QuPath. We realized the png files needed to be higher quality so they need to be rescanned at 40x and saved as tif files. Here I was testing to see if 40x tifs could successfully be analyzed using QuPath. The pink smaller tif files that do load appear to load and zoom correctly. The problem is the pink background and the inability to load the high resolution files that are needed for cell segmentation.

**Comment by petebankhead** [comment]
If the images are being rescanned, can they be saved as .ndpi? Or what is the scanner being used?

As a format .tif can be very variable inside, and I'm afraid I can't really predict what may have gone wrong without a sample image. Different software can write .tif images in very different ways.

However, there have been discussions here about Leica images (usually .scn) that appear pink, and this seems to be an issue with Bio-Formats, e.g. https://github.com/qupath/qupath/issues/141 and https://github.com/ome/bioformats/issues/2811

I think it is likely that the issue is related to this, and not actually a bug in QuPath itself. If it worked in v0.1.2 then perhaps QuPath was at that time using OpenSlide rather than Bio-Formats to open the image (or else an earlier version of Bio-Formats with different behavior).

I suggest three possible options:
* Try to use a different file format, or write the .tif image in a different way
* Add the image to a project in v0.2.0-m5, and when doing so specify the 'server'. Try both Bio-Formats and OpenSlide to see if either works.
* If under the 'Image' tab in QuPath, you see the words 'Bio-Formats server' then you can report it to the Bio-Formats team

**Comment by petebankhead** [comment]
Closed due to lack of response, and because it seems to be a bug outside QuPath itself.
