### ISSUE TITLE
File -> Open on OME-TIFF with multiple images only opens first/macro image on sample OME-TIFF data

### ISSUE THREAD

**Issue by f--f** [qupath/qupath#383]
## Bug report

**Describe the bug**
This is kind of minor, but I noticed that opening the `Leica-1.ome.tiff` example OME-TIFF provided on [this page](https://docs.openmicroscopy.org/ome-model/6.0.0/ome-tiff/data.html) using File -> Open opens the "macro" slide image instead of the full-resolution scan. 

**To Reproduce**
1. File -> Open (Ctrl+O), choose `Leica-1.ome.tiff`.

**Expected behavior**
I'm assuming this is happening because the example file defines the first image as the macro image, or because the first IFD in the TIFF is the macro image. 

I realized that you can view the full-resolution scan by creating a new project and importing the ome.tiff through "Add Images", which adds both images into the project, but I often use File -> Open for quickly viewing things and found this behaviour to be unexpected.

I think it would be great if you added the option to select which image should be loaded when opening an OME-TIFF with multiple images in it.

**Desktop (please complete the following information):**
 - OS: Windows
 - QuPath Version: 0.2.0-m7

**Comment by petebankhead** [comment]
There is an explanation for why this is the current intended behavior [here](https://forum.image.sc/t/third-milestone-on-the-path-to-qupath-v0-2-0/27953/7).

I've changed the tag to _enhancement_ and not _bug_ because it really concerns adding a popup whenever opening such images. This is pretty non-trivial though, since other file formats support multiple images in different ways and QuPath doesn't just use Bio-Formats to open images; it could become pretty complicated getting a balance between popups when required but not so often that they are really annoying (e.g. for every single image where there is a macro/label image associated with it).

Currently 'just use a project' is the workaround, and in general using a project is advised if you will be saving anything. But I do also sometimes drag an image onto QuPath to quickly preview outside a project it as well (although never go to the bother of _File &rarr; Open_ :) )

**Comment by petebankhead** [comment]
The enhancement is now included in v0.2.0-m9, in terms of a popup dialog enabling specific series to be opened (thanks to @melvingelbard !): https://github.com/qupath/qupath/commit/553a5b0082fcf8bfb83ab69329f3284b24a8ecec
