### ISSUE TITLE
Unable to resolve class qupath.imagej.objects.ROIConverterIJ

### ISSUE THREAD

**Issue by pacia-c** [qupath/qupath#384]
I am trying to implement a script to assist in [IF colocalization calculations](https://forum.image.sc/t/if-colocalization-calculations-for-qupath/25165) and one of the classes does not exist. The script was originally written in 0.2.0m2, but I am using 0.2.0m6. Was this class modified between milestones, [similar to the IJTools](https://petebankhead.github.io/qupath/2019/08/21/scripting-in-v020.html#working-with-imagej)? 

My code reads: 
`import qupath.imagej.objects.ROIConverterIJ`
With an error as below:
`ERROR: It looks like you have tried to import a class 'qupath.imagej.objects.ROIConverterIJ' that doesn't exist!`
`ERROR: Error at line 26: startup failed: Script6.groovy: 27: unable to resolve class qupath.imagej.objects.ROIConverterIJ`

I have tried importing all objects:
`import qupath.imagej.objects.*`
But receive the following error:
`ERROR: I cannot find 'ROIConverterIJ'!`
`ERROR: Error at line 56: No such property: ROIConverterIJ for class: Script7`

Thanks in advance for your help.

**Comment by Svidro** [comment]
I would recommend taking a look through:
https://petebankhead.github.io/qupath/2019/08/21/scripting-in-v020.html#working-with-imagej
when updating any code.
I haven't tried it, but I suspect the code Pete lists there is what you are looking for:
"Often we don’t need the PathImage wrapper, but here we keep it so that we can pass it to IJTools.convertToIJRoi(roi, pathImage) later."

**Comment by petebankhead** [comment]
You might just need to change RoiConverterIJ to IJTools, e.g. see [here](https://github.com/qupath/qupath/blob/85e00e0e69bca2d7e9c21aa2d3be16dabc9c3f6d/qupath-core-processing/src/main/java/qupath/imagej/tools/IJTools.java#L593). The blog post explains more of the reasoning.

(Please close the issue if this resolved it. Because it isn't a bug in QuPath, and also because it concerns a script posted on the forum, it would really be better posted at https://forum.image.sc/tags/qupath )

**Comment by pacia-c** [comment]
The switch to IJTools did the trick. Thank you for answering even though this wasn't the correct forum. I'll be sure to ask future issues for QuPath in the appropriate forum.

**Comment by petebankhead** [comment]
No problem, thanks for reporting back - glad it worked!
