### ISSUE TITLE
QuPath and Image Distortion

### ISSUE THREAD

**Issue by michaelmooreny** [qupath/qupath#386]
## Bug report

**Describe the bug**
In a project I'm currently working on, QuPath seems to be distorting images so that I am unable to reliably do a cell detection, analyze and even view the images. When I open the images in other image processing programs like gimp the images do not appear distorted. It looks like the distortion that is taking place is that part of the image is being copied and translated into a different part of the image. 

**To Reproduce**
1. Go to QuPath 0.1.2
2. Click on File -> Open Image
3. Select specific image

**Expected behavior**
The image should not be cut into pieces and distorted. 

**Screenshots**
Here is what the image should look like:( Here I opened the .tif image in gimp)

![image](https://user-images.githubusercontent.com/10617598/70916106-1f3aa700-1fe9-11ea-91d2-72f5340bdcb4.png)

Here is what the image looks like in QuPath:( note I have drawn an annotation in the image here- the red rectangle which can be ignored)

![image](https://user-images.githubusercontent.com/10617598/70915929-c79c3b80-1fe8-11ea-87b3-7c16e5dc3fef.png)

Here is what the image looks like in QuPath when I do a cell segmentation on the image

![image](https://user-images.githubusercontent.com/10617598/70916181-3da0a280-1fe9-11ea-9d5d-fff3625a9fe5.png)

You can see here that there are areas of the screen which have no cells but are being marked as having cells due to this distortion. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - QuPath Version 0.1.2

**Additional context**
The images being analyzed were originally .ndpi files which were converted to .tif files. When I open them in other image processing programs like gimp the images are not distorted. Also, the thumbnails which are displayed in the image list of the left of the QuPath window do not appear distorted like in the gimp images. 

![image](https://user-images.githubusercontent.com/10617598/70916404-a1c36680-1fe9-11ea-9068-8e3454810d32.png)

**Comment by petebankhead** [comment]
This seems likely to be a bug in the image reading library (OpenSlide or Bio-Formats - you can tell which is used under the 'Image' tab by looking at the server type), or perhaps a non-standard representation of the pyramidal levels within the converted TIFF image.

In general, it should be possible to work directly from the .ndpi image in QuPath. Because there are all sorts of (supposedly) pyramidal TIFFs in the wild, I really don't know what kind your conversion has produced.

In any case, QuPath does not contain its own image readers, and therefore it is unlikely the issue can be resolved within QuPath alone. Also, v0.1.2 will not be further updated - so the first thing to do would be to check if the error persists in the latest milestone release (currently v0.2.0-m8). Depending upon the image reader used, you might want to report it as a Bio-Formats or OpenSlide issue.

**Comment by petebankhead** [comment]
Closing this as I see it is now reported as an OpenSlide issue.
