### ISSUE TITLE
Cannot open Qupath projects made with 0.2.0-m2 on 0.2.0-m2 or on 0.2.0-m8

### ISSUE THREAD

**Issue by smospina** [qupath/qupath#388]
![image](https://user-images.githubusercontent.com/52460788/71204451-24f4ee80-226e-11ea-85e3-745eb9e8fe69.png)

When I try to open projects that I have already successfully worked on using the 0.2.0-m2 milestone, the project itself will open but I cannot open any of the images from the project. I figured maybe the milestone version was outdated and so I tried downloading milestone 8 but now my project will not open at all and I get the message shown above. What can I do to access my old projects?

**Comment by Svidro** [comment]
Going to have to make a few assumptions here, but I think that you probably changed locations or moved your project around from M2. M2 did not really tolerate changes to project locations very well, which led to the URI update detection and some other things.

To work with the M2 projects in M2 again, the project file should either be in the same place, or I think you may need to edit the .qpproj file to update the new file path to the images. That is why the project will open (that path is set wherever you have run it from), but the images will not be found. If you open the log, I suspect that is the error message (and it will show the old file path).

M8 will not run M2 projects, and I don't think it is very easy to even transfer annotations between them (you would probably need a script... and I'm not sure how well it would work even then).

**Comment by petebankhead** [comment]
There is really not enough information here to answer, and since it does not relate to a bug https://forum.image.sc/tags/qupath would be the right place to post this question.

My guess is that your images may have moved / be on an external disk that is not accessible when you try to reopen the m2 project using QuPath v0.2.0-m2. But I would need to know what error messages are displayed, and if anything appears under *View &rarr; Show log*.

It is not expected that a project created using m2 will open with m8 because of large changes between milestones; specifically I recall the project structure changed from m2 to m3 (I don't remember if there were subsequent changes).

There is a script to migrate old projects from m2 to m3, but use with caution (i.e. with backups) and be sure to read the description at the top if you use it: https://gist.github.com/petebankhead/8dfbaf2de91f6432b79c7678e2997d6a

**Comment by petebankhead** [comment]
I will close this due to lack of activity (and it really belongs on image.sc)
