### ISSUE TITLE
RAM not cleared before opening next file --> error after opening a few files

### ISSUE THREAD

**Issue by AnesthesiaNeurotoxicity** [qupath/qupath#393]
Hello,

I am using Qupath for manual cell counting for which I need to open a lot of files, the one after the other.

My computer has 8 GB of RAM memory.

When I only open QuPath, 2 GB of my RAM memory is in use.  When I open the first file, the RAM use increases to 4 GB.  As soon as I open the next file (I do not need the first file anymore), 6 GB of my RAM is occupied.  When I then want to open the third file (or during the cell counting), I get the error "GC overhead limit exceeded".

Info of the log:
`INFO: Writing object hierarchy with 3 object(s)...
INFO: Image data written to E:\Konijnen\Histologie\117\N 01 h.qpdata in 0.02 seconds
INFO: Returning server: Bio-Formats for E:\Konijnen\Histologie\117\N 02.czi
ERROR: java.lang.OutOfMemoryError: Java heap space
ERROR: deleting invalid memo file: E:\Konijnen\Histologie\117\.N 02.czi.bfmemo
WARN: file deletion failed E:\Konijnen\Histologie\117\.N 02.czi.bfmemo
ERROR: QuPath exception`

When I close QuPath and reopen the program, there is no problem anymore untill I open again the third file.

The problem seems to be that the previous file is not closed before I open the next file, as the usage of the RAM only further increases.  I have the same problem when I use another computer with 16 GB of RAM, but the problem appears only after opening more slides.

Is there a way to close the previous file or to clear the RAM memory before I open a new file without entirely closing QuPath?  (To maintain a few settings like showing the grid, grid settings, contrast window, cell couting window)

Thanks in advance!

**Comment by petebankhead** [comment]
Which version of QuPath are you using? In recent milestones there is a [memory monitor command that can be used to clear the cache directly](https://petebankhead.github.io/qupath/2019/11/02/fifth-milestone.html#memory-monitor--show-input).

In general, QuPath retains image tiles cached in memory until that cache is full, after which they are deleted. It does *not* empty the cache when an image is closed, because it's quite possible the same image might be reopened later - and in general it isn't needed to do so. This behavior is intentional.

In v0.2.0-m8 you can adjust the proportion of memory given to this tile cache under *Edit &rarr; Preferences...*.

One potential explanation is that QuPath generally stores some pieces of information (e.g. a thumbnail) about previously-opened files outside the normal tile cache, and these might not be cleared - but usually they are very small and so don't cause a problem.

But I have seen rare instances were .czi files read by Bio-Formats have huge memory requirements.

To check this, can you look to see the file size for one of the `.bfmemo` files created by Bio-Formats? There are paths shown in the log message you give. Usually each file should be just a few MB in size.

**Comment by AnesthesiaNeurotoxicity** [comment]
I am using QuPath 0.1.2, I don't find the setting of the title cache here.

The .bfmemo files are only 9 MB.

Is there a way to clear the cache manually before opening the next slide?

**Comment by petebankhead** [comment]
The setting doesn't exist in v0.1.2, and this version will not be updated further.

Even if you do not wish to switch to v0.2.0 yet (while it is still unstable/regularly changing, and not backwards compatible with v0.1.2) I would be interested to know if the issue remains there or if it has already been resolved by one of the changes in the new version.

**Comment by petebankhead** [comment]
I will close this issue because of lack of activity, and it is unclear if there is any issue remaining on the QuPath side.
