### ISSUE TITLE
Loaded Points objects are unclassified

### ISSUE THREAD

**Issue by Svidro** [qupath/qupath#410]
## Bug report

**Describe the bug**
Using the Load Points option to load a zipped points file faithfully recreates the points, except that they are named after their class rather than including their class (they repopulate unclassified). Given the increased frequency with which people may be using points with the multiplex classifier, it might be worthwhile to load the classification of the point as well to prevent confusion.
https://forum.image.sc/t/qupath-0-2-0-m9-multiplex-classifier-classes/34797/22

 :) Or include a link to the multiplex classifier tutorial in the Counting dialog box :)

**Expected behavior**
Loading points would recreate the points exactly as they were when they were saved.

**Screenshots**
See link.

QuPath 0.1.2 -> 0.2.0M9

**Comment by petebankhead** [comment]
This is intended behavior rather than a bug, although I'm not sure if it is the *right* intended behavior.

The ability to load points wasn't really intended for this purpose - rather, it's an easy way to exchange points with other software (e.g. someone writes a Python script and wants to visualize detected locations within QuPath). The current implementation is agnostic regarding whether a name or classification is set during export.

The current *best* way to export/import annotations is using a method described at https://qupath.readthedocs.io/en/latest/docs/advanced/exporting_annotations.html (probably GeoJSON). This should preserve the class (if not, then that *would* be a bug).

With that in mind, I don't know if it's better to 1) add complexity to the save/load command to support classes, or 2) remove those buttons altogether (since I suspect it is rarely used for its original purpose, and points can be loaded by scripting anyway).

What do you think?

**Comment by Svidro** [comment]
Ah, ok. My bad. I am loathe to remove functionality, but with the increased emphasis on points for picking out individual cells in multiplexes, I have a feeling it may come up more often.

A couple of other possibilities that require more or less coding...
3) Move the Save and Load buttons to the ... along with create points for all classes so that they are less obvious.
4) Instead of one text box, have a columns for the points that include "Name" "Count" and "Class" fields. That would at least make it slightly more obvious that loaded points are unclassified.
5) One more button (possibly in combination with 3) to "Set Points names as Classes"
6) One new Label beneath the Load and Save points buttons that says "Points loaded in this way will not have classes" possibly with a link to the Exporting annotations page you posted above.

Easiest seems like 6, though as long as the current functionality is scriptable anyway.
I'm pretty sure there was a comic about removing functionality that I saw somewhere recently. Aaaanyway...

**Comment by petebankhead** [comment]
I've discussed this with @melvingelbard and we propose to change the export to a single csv/tsv table that includes class and name as optional columns, and avoids the 'header' information in the current export format. I suspect that the main usefulness of this is to support spatial analysis outside QuPath, or import points from other sources.

Following the instructions in the tutorial to create duplicate images, or using the annotation export methods in the docs, there shouldn't be any need to rely on this method of saving/loading points for training.

**Comment by Svidro** [comment]
Sounds good. My main worry was the people who aren't following/haven't found the readthedocs page, thus the link recommendation :)

Can close whenever.

**Comment by petebankhead** [comment]
These changes from @melvingelbard update the way the points are saved/loaded, which makes them more portable and can retain the classification: https://github.com/petebankhead/qupath/pull/42
