### ISSUE TITLE
Tiling with Overlay

### ISSUE THREAD

**Issue by ClnSchlssr** [qupath/qupath#44]
Is there a way to tile the image like the scripting example in the wiki [here](https://github.com/qupath/qupath/wiki/Scripting-examples ) but with the classification overlay or other cell features "burned in"?

**Comment by petebankhead** [comment]
Yes, there are a few ways to do that, depending on what exactly you want.

https://gist.github.com/petebankhead/66e70e5deaa9c6e6a009ad027b135a0d may help to give a starting point, since it shows how to do the export of a (very) downsampled version of the image as a single tile.  But it still involves using a ```RegionRequest``` object to define the part of an image and downsampling factor to use, and then writing that out... so the idea is the same.

Therefore you could use that to modify the original tiling script.  After importing ```ImageWriterTools``` at the top, the main thing to do is to change the contents of the ```try``` block, e.g. something like the following:

```groovy

...
import qupath.lib.gui.ImageWriterTools

...
try {
                // Put at top of file for neater code...
                ext = ".jpg"
                imageData = getCurrentImageData()
                overlayOptions = getCurrentViewer().getOverlayOptions()
                
                // Write out the region with overlay
                String name = String.format("%s (d=%.2f, x=%d, y=%d, w=%d, h=%d, z=%d).%s", serverName, downsample, xi, yi, wi, hi, z, ext)
                File file = new File(dirOutput, name)
                ImageWriterTools.writeImageRegionWithOverlay(imageData, overlayOptions, request, file.getAbsolutePath())

                // Print progress
                counter++
                println("Written tile " + counter + " to " + file.getAbsolutePath())
            }
...
```
This should include all detections and annotations.  If you need TMA cores to be displayed too, then some modification would be required... although then *File &rarr; Export TMA data* is usually a better choice in most cases.

Note, here I set the output format to JPEG to get smaller file sizes.  The original script wrote ImageJ TIFF images, which used lossless compression and had more image properties set (e.g. pixel sizes in microns) - at the cost of writing much larger files.

If you want similar ImageJ TIFFs, but with the overlay drawn on top, then the changes are a bit more awkward and require going more into the details or how images are handled by Java and QuPath.  The following should work (at least for RGB images):

```groovy
...
try {
                // Read the image region
                ImagePlus imp = server.readImagePlusRegion(request).getImage(false)

                // Get the hierarchy overlay (could put at top of the file)
                def hierarchyOverlay = getCurrentViewer().getOverlayLayer(qupath.lib.gui.viewer.overlays.HierarchyOverlay.class)

                // Paint the overlay (except TMA grid)
                def img = imp.getProcessor().getBufferedImage()
                def g2d = img.createGraphics()
                g2d.scale(1.0/downsample, 1.0/downsample)
                g2d.translate(-request.getX(), -request.getY())
                g2d.setClip((int)request.getX(), (int)request.getY(), (int)request.getWidth()+2, (int)request.getHeight()+4)
                hierarchyOverlay.paintOverlay(g2d, request, downsample, null, true)
                g2d.dispose()
                imp.setProcessor(new ij.process.ColorProcessor(img))

                // Get a suitable file name
                String name = String.format("%s (d=%.2f, x=%d, y=%d, w=%d, h=%d, z=%d).%s", serverName, downsample, xi, yi, wi, hi, z, ext)
                // Create an output file
                File file = new File(dirOutput, name)
                // Save the image
                IJ.save(imp, file.getAbsolutePath())
                // Print progress
                counter++
                println("Written tile " + counter + " to " + file.getAbsolutePath())
            }
...
```

Because the display settings are obtained from the current viewer, then settings applied there should be maintained (including the use of measurement maps to visualize cell features in context).

**Comment by ClnSchlssr** [comment]
Thanks for the detailed response Peter. That's a great starting point. 
As a follow up, is there a good place to learn about how to access QuPath data from the groovy scripting interface? Perhaps a list of the available data stored in various objects and the methods that can be used to access them? The examples are a great start, and have been very good at interpreting the kinds of things we're hoping to do, but it can be hard to go beyond them (short of diving deeper into the QuPath code itself).
The software has been very impressive so far - great interface and the scripting capability makes it feel quite extensible.

Best,
Colin

**Comment by petebankhead** [comment]
Hi Colin,

Thanks very much for your reply and positive comments.

With regard to resources, I’m afraid the only ones I know of are the ones that I have written myself.  These are mostly on the Wiki, however three other sources of scripts are:

* the Supplementary Material for the recent [bioRxiv preprint](http://biorxiv.org/content/early/2017/01/12/099796) - this also includes descriptions of how the scripts are used
* my own [Gists on GitHub](https://gist.github.com/petebankhead)
* the built-in examples under *Automate &rarr; Open sample scripts*

Beyond that, I find [using IntelliJ](https://github.com/qupath/qupath/wiki/Advanced-scripting-with-IntelliJ) to be really essential.  Its Groovy support is excellent, and it is full of tricks that help with finding the parts of code that are needed.  I hadn’t used IntelliJ previously, so I am only gradually learning what it can do*.

Scripting is something that I would like to revisit in the future to make both simpler and more powerful - depending upon what is needed most.  Currently, I use scripting for working with projects, working with objects/classifications, working with pixels, and working with GUI components… but the classes and techniques involves are quite different, and some are easier than others.  I’m not sure which of my uses are of general interest... or just useful to me.

Therefore in the absence of more complete documentation, it’s probably best to ask specific questions here and I’ll try to answer.  In the short term, I plan to add links to the most generally-useful questions in the [FAQ section](https://github.com/qupath/qupath/wiki/FAQs) to make them a bit easier to find.

Pete

*-Just now I learned that ```Ctrl + h``` with the cursor on a relevant class or interface name (e.g. ```PathObject``` or ```ImageServer```) opens up a class hierarchy to help see related classes.
