### ISSUE TITLE
Cell detection over tiled regions fails on some images

### ISSUE THREAD

**Issue by reynoldscem** [qupath/qupath#459]
## Bug report

Sometimes when running cell detection (`qupath.imagej.detect.cells.WatershedCellDetection`) in the parallel tiled mode it will fail saying `ERROR: Exception during post-processing`.

It appears the final QuPath method call before calling into a library is `qupath.lib.plugins.ParallelTileObject.resolveOverlaps`, and the error is from [line 280](https://github.com/qupath/qupath/blob/cf618cb91a7e43716c3a4bc7b431de6a88ee98be/qupath-core/src/main/java/qupath/lib/plugins/ParallelTileObject.java#L280), the offending call being `firstGeometry.intersection(secondGeometry)`.

The error message from this is `Caused by found non-noded intersection between LINESTRING ( 6336.81 3918.04, 6335.4 3918.39 ) and LINESTRING ( 6335.39013671875 3918.389892578125, 6335.41 3918.39 ) [ (6335.400213222254, 3918.38994707249, NaN) ]        at org.locationtech.jts.noding.FastNodingValidator.checkValid(FastNodingValidator.java:140)`.

**To Reproduce**
[This script](https://gist.github.com/reynoldscem/4d5f5bf0428057769da6bfd54037e02e) should reproduce the issue.

One such image for which this happens is `breast_2/scale-20pc/HE.jpg` from the [ANHIR](https://anhir.grand-challenge.org/Data/) dataset.

To reproduce manually we can:

Load an image, and make a rectangular selection around it all. Go to Analyze, Cell Detection, choose the appropriate settings and run.

**Expected behavior**
I expect the cell detection to work. As it is, the cells are only detected for some subset of the tiles.

**Screenshots**
As we can see only some of the tiles here finish.

![image](https://user-images.githubusercontent.com/5931862/80495409-c9471a00-895f-11ea-942d-cd3b98446c0d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - QuPath Version 0.2.0-m10, but I have seen the same issue in m9.

Please let me know anything I can try to work around this, or any info on potentially fixing this problem.

**Comment by petebankhead** [comment]
Thanks @reynoldscem, I haven't seen this before.

Is there an easy way for me to get an image that fails without downloading the whole dataset? I will only have a few minutes to look at it today and couldn't easily identify the offending image through the ANHIR link.

Otherwise I can wrap the code where the error occurs in a try/catch block so that if it can't resolve the overlap it will at least fail less catastrophically... but I will be guessing the fix without being able to test it directly.

**Comment by reynoldscem** [comment]
It appears that raising the min area fixes this issue, at least on the example image. The error goes away with `minArea` set to `5.0`.

**Comment by reynoldscem** [comment]
@petebankhead Hi, thanks for the prompt and clear response.

Their website is a little unclear about obtaining the data. There is a link on their page to a directory listing where you can download individual images. You unfortunately have to sign in to their site I believe to access this.

**Comment by Svidro** [comment]
Interesting, I hadn't seen that challenge. 

I notice the image you reference is a jpeg. If that is the case, the min size is 5pixels? That seems rather small for defining a cell. I saw on the website a mention of the images being 40x. 

The other settings in the watershed cell detection part of your script do suggest that you are running your detection in pixels.

**Comment by reynoldscem** [comment]
@Svidro Yes it is rather small. They mention their images being up to that size, but images only a quarter of that size are actually available. I realize it's incredibly small, but there's not much I can do about it.

**Comment by petebankhead** [comment]
v0.2.0-m11 now tries to recover more gracefully when this happens. It can't resolve the problematic overlap, but at least it doesn't lose the other cells.

I'll close this issue because I think it is now as fixed as it is going to be (the whole overlapping code may be revised before v1.0.0), but feel free to reopen if you find  it reoccurs.
