### ISSUE TITLE
ObjectMeasurements class is package private

### ISSUE THREAD

**Issue by lacan** [qupath/qupath#466]
Hello, 

I was interested in using qupath.imagej.detect.cells.ObjectMeasurements in a package I am creating separately, but this class is currently package-private.
https://github.com/qupath/qupath/blob/c5cc1895f5ff6ff94b2431b4b2ede7fad78b071f/qupath-core-processing/src/main/java/qupath/imagej/detect/cells/ObjectMeasurements.java#L42

Would it be possible to have access to this class outside the package? I can use it in a script within QuPath without issues, but not in Java... 

Thank you for any help/comments. 

All the best

Oli

**Comment by lacan** [comment]
sorry for the bug tag, I cannot for the life of me find where to remove that. It is clearly not a bug, just a request.... 

All the best

**Comment by petebankhead** [comment]
Yes, lots more things are package private now to try to trim things down and have fewer public things moving.

The thinking with `ObjectMeasurements` is that it really should be tied to QuPath's built-in cell measurement command, since this is the only place it's currently used. But future cell detection commands deserve better measurements.

Because the functionality is pretty limited, I'd suggest just copying the code into your own package if you want it.

For similar functionality for other cell detection methods, I myself plan to use JTS - since this avoids ImageJ's need to rasterize things when making measurements.

(Since this isn't a bug, I'd really rather use image.sc...)

**Comment by petebankhead** [comment]
BTW I plan to revisit my StarDist-related code soon. [`CellMeasurements`](https://github.com/qupath/qupath/blob/cf618cb91a7e43716c3a4bc7b431de6a88ee98be/qupath-core-processing/src/main/java/qupath/imagej/tools/CellMeasurements.java) was created to aid with adding intensity measurements to cells from different sources.

Still very early and everything subject to change (we remain far from v1.0.0 and any API stability promises...), but my intention is to make it 'easy' to add standardized measurements to cells and detections generated from any source.

This is also why the 'intensity measurements' command is deprecated - but it will remain for now, since replacing it is rather more complicated (since it needs to support measurement intensities in regions that may be larger than what can be reasonably rasterized in one go).

**Comment by lacan** [comment]
Hello, 

Thanks for the info regarding [CellMeasurements](https://github.com/qupath/qupath/blob/cf618cb91a7e43716c3a4bc7b431de6a88ee98be/qupath-core-processing/src/main/java/qupath/imagej/tools/CellMeasurements.java)! I will try these. Do they give the same column names as the ones in the Watershed cell segmentation command?

> Because the functionality is pretty limited, I'd suggest just copying the code into your own package if you want it.

I though if it  too, but then I also had to copy ShapeStatsIJ (which is small too) but I'll do that for now and try out  [CellMeasurements](https://github.com/qupath/qupath/blob/cf618cb91a7e43716c3a4bc7b431de6a88ee98be/qupath-core-processing/src/main/java/qupath/imagej/tools/CellMeasurements.java)!
