### ISSUE TITLE
Add several czi-file Images with 2 scenes each within a Project causes crash

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#47]
allways when i load more than one czi image file in a project with the button "add images", 
QuPath stopps working. It stopps in a modus that looks like that: 
![image](https://cloud.githubusercontent.com/assets/16352785/22469485/79aa21c8-e7cc-11e6-8dd0-4160efa42b3f.png)

the only way out is exit via Taskmanager and restart of QuPath. 

I figures out, that it allways crashes with the same czi file in the list. I might be able to share this file, if required to solve the issue.

**Comment by DHaumannHSA** [comment]
The file that causes the crash has 5 scenes

**Comment by DHaumannHSA** [comment]
if the file is loaded just als single file, not within a project, it also crashes QuPath

**Comment by petebankhead** [comment]
If you can send me the file somehow, then I can have a look.  What I would do is to try opening the same image with [Fiji](http://www.fiji.sc), since Fiji can also use Bio-Formats to read files.  The connection between Bio-Formats and Fiji is well-established, and is much more tested than that between Bio-Formats and QuPath.

If Fiji can open all scenes within the file, then the problem may be within the QuPath extension.  However if Fiji cannot open all the scenes, then it is more likely to be either an issue with the CZI file itself, or with Bio-Format's support for CZI.  If this is the case, then perhaps the developers of Bio-Formats may be able to help further.  There are several ways to contact them described at http://www.openmicroscopy.org/site/community

**Comment by Veronika77** [comment]
I know it is an old thread and I am not sure the question has been solved or not but I am having the same problem when just try to open a single czi image with two scenes. It is not because of file size as my files are not big. The way I worked around this issue is splitting up the image in ZEN into two individual scenes and then I could open them individually.

**Comment by petebankhead** [comment]
Very good to know about the workaround, thanks.

The latest update to the extension should improve CZI support, and hopefully there's no need to split the image any more.  There are more details [here](https://groups.google.com/d/msg/qupath-users/78PpZuu2J1s/su6ZjY0mAgAJ).
