### ISSUE TITLE
TMA detection in CZI format fails also in WSI format with only 1 scene

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#48]
starting TMA detection ends up in on cirle in the middle of the image. Looks like that: 
![image](https://cloud.githubusercontent.com/assets/16352785/22471404/8a804fe4-e7d2-11e6-8c46-1cc888be4422.png)

**Comment by petebankhead** [comment]
This happens whenever QuPath is unable to detect any cores.  There are a few reasons why this may occur:

* The *Image type* is wrong (e.g. set to fluorescence rather than brightfield) - this can be seen after clicking on the *Image* tab on the left.  There is a screenshot [here](https://github.com/qupath/qupath/wiki/Preprocessing#viewing-the-default-stain-vectors).
* The specified TMA core diameter is either too large or too small.  QuPath determines the expected TMA grid from 'complete' cores, which have a diameter within a small tolerance of the value set in the dialog box.  If no cores fall within this tolerance, the grid cannot be found.
* The intensity threshold is either too high or too low (but it is automatically determined from the data, and I don't see any reason in your image why it would be determined wrongly).

If the image type is set correctly, then I would try increasing and decreasing the *TMA core diameter* to see if this gives any improvements.  If not, then there may be some issue happening internally when trying to read from the CZI file - although I have not seen such a problem before.  The contents of *View &rarr; Show log* may be helpful to track down the problem.

**Comment by rawatenator** [comment]
I have the same problem and it doesn't go away even when I change these settings. In this case is it possible to manually mark the locations of each core? I can't seem tonmake a grid from this view directly.

**Comment by petebankhead** [comment]
I understand from others that it may be possible to export the TMA cores from the Zeiss software as individual czi files, and then import these into a project as separate images.  I guess it should be possible to then dearray each image to have only one core within QuPath... although I have never tried this.

Otherwise, hopefully the answer at #77 helps with the grid.
