### ISSUE TITLE
display >3 channels in fluorescence MRXS files

### ISSUE THREAD

**Issue by mariokreutzfeldt** [qupath/qupath#49]
Hi,

we've scanned fluorescence slides in MRXS format. The scans have 4 color channels (DAPI, FITC, TRITC, Cy5). But when opened with Qupath, we can only access the first 3 (mislabeled as RGB).
I guess this is more an issue with openslide rather than Qupath, but I couldn't find any information about that on the openslide page and wanted to check.

Best regards,
Mario

**Comment by Svidro** [comment]
Hi!  I was just considering this problem, and I was wondering if you have tried splitting the image into two as a possible work-around?

There are multiple problems with this, but...  one thing to try is:
1. Get Pannoramic Viewer (Caseviewer does not do this) from 3DHISTECH.
2. Export your image twice, and select only 3 of the 4 channels each time, with one different between the images.
3. Import both images into QuPath, calculate your values, then recombine the images at the end.

Since your DAPI channel should be the exact same, the cells generated should pair 1 to 1, and we even have XY coordinates now!  Another downside though is that Pannoramic Viewer only exports .mrxs files in JPEG PNG and BMP, not JPEGXR, so you might lose some information there if you took the images in another format, or your files might end up being huge.  Please let me know if this works for you!  I may end up trying it some day...

**Comment by Svidro** [comment]
Actually, I suppose you probably weren't in JPEGXR if you were already working in QuPath ^_^

**Comment by mariokreutzfeldt** [comment]
Hi Svidro,
thank you for your suggestions. The problem is, that I need all the 4 channels to analyze co-expression of markers. Hence, exporting every image twice is not feasible (and too slow). 
Could you explain to me why is it so problematic to access more than 3 channels? 

Cheers,
Mario

**Comment by Svidro** [comment]
I am afraid I do not know what the problem is with more than 3 channels, and I certainly do not have the programming experience to dive into it, unfortunately!   I agree that it would be nice to be able to handle more fluorescence channels.

I also understand the need to study co-expression of markers, however, which is very possible even after you split the channels into two images, provided each image still has DAPI in order for QuPath to generate the same exact cell population.  Merging the data sets later gives you your co-expressors.

For example, since the Detections output file is in the same cell by cell order, the first cell from image 1 might be positive for markers A and B, with the first cell in the second image positive or negative for marker C.  Fluorescent channels are independent, anyway, though you would need an extra program such as R (or just Excel if your sample is small enough) to combine the data sets to see the co-expressing population cell by cell, and you would lack the visualization tools of QuPath, but you could get the data (percentage positive for each type, or per mm^2) with a fairly straightforward script!

As a side note, I think increasing the tile size to maximum dramatically decreases the export time in Pannoramic viewer.  I have spent quite a while with it running on multiple computers though, so I understand it can be frustrating.

**Comment by mariokreutzfeldt** [comment]
These are indeed very good ideas! Didn't know about the possibility to combine Qupath's output this way. I can find my war around R, so no problem! And I'll definitively try increasing the tile size during export! 
Thanks again for your help!
