### ISSUE TITLE
"Show Names (N)" option not saved when reopening QuPath

### ISSUE THREAD

**Issue by lacan** [qupath/qupath#499]
When we have Annotations with user generated names, we need to press N to hide the names. This setting is not saved within QuPath. 

So reopening QuPath and loading the image will always display the names of the Annotations

**Comment by petebankhead** [comment]
This isn't actually a bug... showing/hiding the names is an `overlay option`. These are not global, and none are persistent. They are like showing/hiding detections or annotations, which are also not persistent.

There is probably an argument for making them persistent, but this gets tricky because multiple non-identical instances of [OverlayOptions](https://github.com/qupath/qupath/blob/42cedef3d9252f974f77d2af6d3d3445081406c9/qupath-gui-fx/src/main/java/qupath/lib/gui/viewer/OverlayOptions.java) can exist - in which case QuPath would need to distinguish between which options are persistent and which aren't.

This would be doable, but would take a bit of thought. I don't really want to introduce several more persistent preferences at this stage, immediately before the stable release, when the current behavior is not actually buggy.

**Comment by lacan** [comment]
Sounds good. Thought it was a bug, no worries. Is there a way to have the names disabled by default?

**Comment by petebankhead** [comment]
Not currently... do you think off is a better default? My thinking is that:

* names often aren't used (might be different for you)
* most people won't know names can be displayed at all if they are not revealed by default
* pressing `n` doesn't cost much

It might well become persistent in the next release, but for now it's not worth the risk of getting it wrong and introducing late bugs.

**Comment by lacan** [comment]
I think it may be better off by default. 
For example my most common use case would be sending overlays back from ImageJ.

Sending an overlay back to QuPath from ImageJ as Annotations send the ROIs with their names (Those obscure IJ ROI names).
In which case, the user would have to switch the names off each time they reopen their project, as these tend to be dense. Otherwise I have to give them a script to run after the import, to remove the names from the annotations and ease their visual burden ^^

**Comment by petebankhead** [comment]
Well, only each time they open QuPath. The burden of pressing `n` seems less of the burden of running a script. Or, depending upon how the ROIs are created, stripping the names off in ImageJ first.

**Comment by lacan** [comment]
Sure I can do that thanks for the help and hope that the conversation was useful for future consideration
