### ISSUE TITLE
Extension > Send region to ImageJ sends RGB image with burned in overlays & objects

### ISSUE THREAD

**Issue by sstoma** [qupath/qupath#5]
Overlays and object visibility was turned off. I would expect that the objects are not send at all (or if you are my hero, they are translated into ImageJ selections).

![screen shot 2016-10-13 at 18 56 18](https://cloud.githubusercontent.com/assets/3015577/19358629/d2befb96-9176-11e6-88b6-d1856d484206.png)

**Comment by petebankhead** [comment]
This should be fixed now in the next release, so that the visibility of an object is used to determine whether it is sent to ImageJ or not.  This also includes whether cells are shown with their boundaries and/or nuclei.

Regarding converting to ImageJ selections, that should already happen.  It should already be the case that the objects are sent as ImageJ Rois on top of an ImageJ overlay - so you can either remove the overlay, or send its Rois to the ROI manager.  If you do the latter, you should also see that the names of the Rois have also been set according to their names/classifications within QuPath.

Also, the 'primary' selected object (i.e. the one that was currently active whenever the *Extract region to ImageJ* command was run) should automatically be converted to an ImageJ Roi and set as the active selection in ImageJ - *unless* it was a rectangle.  There isn't really so much point in sending rectangles Rois, since they will simply occupy the whole image (and can easily be recreated in ImageJ if necessary with *Edit &rarr; Selection &rarr; Select All*) - but all non-rectangles should be transferred, as shown below.

Hopefully that works well enough to be suitably heroic...

![ij_screenshot](https://cloud.githubusercontent.com/assets/4690904/19360208/7cf2f31c-9175-11e6-9a60-b8878b6e7543.jpg)

**Comment by petebankhead** [comment]
I've now updated the documentation on using ImageJ with QuPath at https://github.com/qupath/qupath/wiki/Working-with-ImageJ

I'll close this issue now, but please reopen it if things aren't working as described.  The use of visibility status to influence what is sent to ImageJ should be available in the v0.0.4 release of QuPath.
