### ISSUE TITLE
Extensions Folder not set properly in QuPath 0.2.0-m12

### ISSUE THREAD

**Issue by lacan** [qupath/qupath#500]
**To Reproduce**
1. Make a directory and add a QuPath Extension
2. Within  Edit > Preferences > QuPath user Directory and set it to your created directory above.
2. Close QuPath And Reopen
3. **Go to Help > Installed Extensions, the extension is not there.**
4. Drag and Drop extension into QuPath
5. QuPath says "No Extensions Directory is set" (So it is not the user directory?) and offers to create it at C:\Users\username
6. Set the Extension directory to where it was created in step 1
7. Now Extension is loaded but inside an 'extensions' directory

**Expected behavior**
When the `User Directory` is set (Which I guess used to be called `Extensions Directory`, which is no longer in preferences), and restarting QuPath, all extensions from that directory should be loaded.
Moreover the location of the Extension Directory should be accessible somewhere in the preferences.
We would expect the Extensions directory be independent from the User Directory. This seems like a non-braking change as there is no documentation on how to load extensions in QuPath 0.2.0 in readthedocs and most people are not using extensions (Except us)

**Additional Remarks**
As a core facility, Extensions make little sense on a 'per user' basis, especially given how complex and supposedly independent they are from each other, or from the individual user's needs. For us they are more suitably used like in ImageJ: All extensions (or plugins) are loaded by ImageJ/Fiji regardless of the currently logged in user. This ensures a streamlined experience for all our users without intervention on our side.

We see that we can load or save preferences, so we can do this for each user as needed, but it makes it more tedious for us to distribute and debug issues when such settings are per-user.

**Desktop (please complete the following information):**
 - Windows 10 x64
 - QuPath Version .2.0-m12

Thank you for your time.

**Comment by petebankhead** [comment]
The user directory is not exactly the same as the extensions directory.

Rather, the extensions directory should be an automatically-generated (when required) sub-directory of the user directory.

From your description, it sounds like QuPath is doing what it is supposed to.

The reason is that the user-directory can contain other things: including a 'scripts' directory and even a 'startup.groovy' file. Basically a directory where QuPath can store stuff that isn't associated with a specific project. The documentation will catch up eventually....

It might be a naming issue; I don't think QuPath should care if the user directory is actually somewhere totally different. Does this help figure out a solution that works for your facility?

**Comment by lacan** [comment]
thanks for the reply. 
I do not think that there is a naming issue... Or I am missing something and am slow to get it :) 
For us Extensions are not per user, however users can of course have their own personal directory, which is great. 

In the case of extensions, it feels that it is like the 'ImageJ plugins directory'. Is that one per-user or is it configured for the whole of QuPath?

So there would be:
* User directory (scripts, logs, custom classifiers they want to reuse [just spitballing], ...)
* ImageJ plugins directory (global for the QuPath installation)
* QuPath Extensions directory (global as well)

What is the logic to saying the Extensions directory should be configured individually for each user? Perhaps if I had a use-case I would understand it better.

**Comment by petebankhead** [comment]
Perhaps I'm misremembering, but I think the extensions directory was *always* configured on a per-user basis? As in... it was stored in the user preferences, alongside all the other preferences. This has not changed.

It is also true for all persistent preferences, since in the end they depend upon `Preferences.userRoot();` ([here](https://github.com/qupath/qupath/blob/master/qupath-gui-fx/src/main/java/qupath/lib/gui/prefs/PathPrefs.java#L312)).

With that in mind, I expect that in your case the 'user directory' is basically equivalent to the old extensions directory (except that the extensions themselves are stored 'one level down'). Of course, you may need to tell individual users not to mess with it, because it is kept for facility use... but I presume this was always the case.

**Comment by lacan** [comment]
I think you are right, but I saw the current naming being an upgrade, like

"Each user has their own folder where they can have their own code and settings."

Which meant that other settings like ImageJ directory and Extensions directory could be system-wide.

But I think I am being too wishful, because like you said: since the start, options that in my opinion should be system-wide are not...

Like when a new user logs-in they have to set the QuPath Setup options even though someone else already set them (even though the amount of RAM should not change from user to user, nor the Locale).

Of course I am not going to pretend it is a dealbreaker, but it puts overhead on us when debugging issues: Did the user set the right amount of RAM? Where did they set the folder for the extensions?If we do not chase after our users, they each could have their own extensions folder in the default location (C:\Users\) which might be an issue for us [We are looking configure our workstations so that they do not keep any user preferences upon logging out because AppData tends to overfill over time, choking the C:\ drive in Windows].

But we favor apps that have a 'configure once' behaviour for these things. We have already been struggling with Imaris for years on this very issue. 

This simply adds to the tedium of maintaining something in a multi-user environment.

**Comment by petebankhead** [comment]
You can set the RAM in the configuration: https://qupath.readthedocs.io/en/latest/docs/reference/faqs.html#why-can-i-not-set-the-maximum-memory
You can also set other command line arguments there, including `-q` to start up in 'quiet' mode. Check out the command line help for more.

Imagine the overhead we have dealing with issues raised by users from anywhere....

I will close this because, as before, there is no bug. We may discuss further improvements on the forum for future versions, but really for now my focus is on any remaining issues for v0.2.0. There is no time for further enhancements at this late stage.

**Comment by lacan** [comment]
Sounds good. Thanks for the discussion
