### ISSUE TITLE
libstdc++.so.6 on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by rananthan3** [qupath/qupath#51]
I untarred the file and tried to start the program but got a dependency error on Linux

./QuPath: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./QuPath)

I ran sudo apt-get install libstdc++6

libstdc++6 is already the newest version.

Any idea what may be causing the issue?

Appreciated.

**Comment by petebankhead** [comment]
I'm afraid I don't have much experience of handling dependencies on Linux.  There is a little more information the binaries were created at https://github.com/qupath/qupath/issues/2

Basically I compiled it on Ubuntu 16.04 and have not tested it on 14.04.

The possibilities that I can think of that might help would be:
* Try a newer version of Ubuntu if possible.
* Make sure Java is installed in Ubuntu.  I don't think this should be necessary (since it is included in the QuPath download)... but perhaps.
* Try removing any ```.jar``` files connected to OpenSlide / OpenCV / JInput / JPen from within QuPath (the libraries should be mentioned in the ```qupath-***.jar``` file name).  Apart from the Java Runtime Environment (JRE) itself, these are the parts that depend on native libraries.  QuPath should still work without them, but will miss some features - such as whole slide image handling and classification.  If the JRE is not the problem then hopefully this would enable QuPath to start, and you can recover some of the missing functionality by downloading [extensions](https://github.com/qupath/qupath/wiki/Extensions) that don't require native libraries.
* Try compiling QuPath from source from within Eclipse.  You may find this easier to set up using Oracle's Java Development Kit than OpenJDK... but both should work.
* Try launching QuPath from the command line, setting the ```java.library.path``` variable and possibly using a different JRE if required... figuring out how to do this could be tricky, although [this](https://github.com/qupath/qupath/issues/27) may help a little bit.

I hope something in there might be useful.  If you are able to find a solution, it would be great if you could post it here.

**Comment by rananthan3** [comment]
Thanks for your suggestions.  I found another computer and installed 16.04.  It ran without any issue.
