### ISSUE TITLE
Different cell detection result categories.

### ISSUE THREAD

**Issue by FridoB** [qupath/qupath#52]
So far I have figured out how to detect cells in my TMA, make classifiers and "train" them and get the results outputted nicely from it. 
However I would love to make cell detections withing different regions of my TMA, namely CD3 positive cells  which are located in the stroma and those which are located in the tumor region. 
Does anybody have some advice? (@petebankhead great talk in Bern 2 weeks ago btw.)
regards
frido

**Comment by Svidro** [comment]
I think you have a couple of options depending on how easy it is to determine stroma vs tumor in your samples, and positive vs negative.  If the differentiation is clear, and easy for the classifier to make, I would start with using one of the built in classifiers to sort all of the cells in the TMA into Stroma and Tumor classes.  
Then, by right clicking on the right hand side of the annotation tab, I would "Add Class" and make "Tumor CD3 Positive" and "Stroma CD3 Positive" classes.  After you have those made, use the Classify->Classify By Specific Feature.  This will take two steps, but it will let you select first "Stroma" class cells as the input and "Stroma CD3 Positive"/"Stroma" classes as the outputs.  A second pass lets you do the same for the "Tumor" cells.
The downside to this is the Classify by specific feature command does not show up in the workflow and can be annoying to use on multiple images since you have to type it out each time.  There is also a script that I can hunt down, if you want, that lets you automate the process, I forget if Peter posted it somewhere on the Wiki.  You do need to rewrite the script somewhat for what you specifically want, however.  
The other option , if you cannot use the classifier to determine Stroma vs Tumor, and want to draw annotations in each core by hand, you can use a simple script that is currently the most recently discussed topic on the Gitter page, seen here [https://gitter.im/qupath-users/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link](url)
After you use the annotations to assign the initial classes, proceed the same way.  Of course, I am sure there are other ways to do it as well, this is quite versatile software!

**Comment by Svidro** [comment]
The top of this Wiki page shows how to add classes, as I mentioned in my post, and also offers another alternative towards the bottom, derived classes, which is probably a more elegant solution than creating new ones as I suggested!

**Comment by FridoB** [comment]
@Svidro you have solved my issue. thank you very much!!! I was not aware of the specific classifier feature regarding only 1 input measure. great stuff.
