### ISSUE TITLE
install qupath 0.2.1 on ubuntu 20.04

### ISSUE THREAD

**Issue by medskillz** [qupath/qupath#546]
Hi,

I have trouble installing qupath 0.2.1 on ubuntu 20.04

I extracted the file to /Home but what do I have to do next? - I tried it several times also with downloading other packages in the past,  but I forgot the steps, but I was not successful whatsoever. And I am new to Ubuntu. I was hoping there is just some "make install" command?

Best,
Sophia

**Comment by petebankhead** [comment]
Hi Sophie, it seems that in previous versions of Ubuntu you could just double-click the QuPath file (under the 'bin' directory) to run it. It seems now that you need to run the same file from a terminal.

(Since this isn't a QuPath bug, [the forum](https://forum.image.sc/tag/qupath) is the best place to discuss this and ask any further questions.)

**Comment by medskillz** [comment]
Hi Pete, thank you for the quick reply and sorry that I posted in the wrong place. I posted it in the forum again.

Best,
Sophia

**Comment by Tkilvaer** [comment]
Sorry for commenting on this. But by checking the old versions it seems that this behavior changed from 0.2m9 to 0.2m10. I do not know if this was intentional? 

I can confirm that 0.2m9 opens by double clicking in Ubuntu 20.04, while 0.2m10 (and any more recent releases do not).

**Comment by petebankhead** [comment]
No problem @medskillz !

@Tkilvaer Yes, I recall the change was recent. It came up on the forum:
* https://forum.image.sc/t/making-shared-library-file-type-executable-on-linux/37778
* https://forum.image.sc/t/exe-missing-with-qupath-0-2-0-m11-and-0-2-0-m12-releases/38073

It wasn't intentional - but I don't know exactly what update caused it. I don't see how it could have been a change in the QuPath code, since the launcher is generated using jpackage. I don't know if something in Ubuntu or jpackage changed that caused this. Happy to include a workaround if anyone finds one, but since the software does still run (and the number of Linux downloads is much lower than other platforms) it isn't something we've been exploring much.
