### ISSUE TITLE
Import legacy projects does not align annotations

### ISSUE THREAD

**Issue by Tkilvaer** [qupath/qupath#547]
## Bug report
**Describe the bug**
Import legacy project (0.1.2/0.1.3) does not correctly align annotations when openslide is the image server because the bounding box is activated. This only applies to formats that do have the bounding box (eg. .mxrs and others)

**To Reproduce**
Import legacy project (0.1.2/0.1.3) based on .mxrs files into 0.2.1 

**Expected behavior**
Annotations should align

**Screenshots**
![image](https://user-images.githubusercontent.com/33515823/85854178-30444c00-b7b4-11ea-9e83-b9928a951bd8.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - QuPath Version 0.1.3 (the legacy project) and 0.2.1_tf_cpu (the new project)

**Comment by petebankhead** [comment]
I'm not convinced the import script should try to correct for this special case - since v0.1.2 doesn't encode the specific image reader used in the project, and different images can have bounding boxes (which might be handled in different ways by different readers), any automatic correction could potentially also produce the *wrong* result. For example, Bio-Formats doesn't generally use the bounding box, even in v0.1.2.

I think it is cleaner to handle any additional translation later. A fix can be scripted if required.

**Comment by petebankhead** [comment]
An example script (not tested on a real example!):

```groovy
double dx = -getCurrentServer().boundsX
double dy = -getCurrentServer().boundsY

getTMACoreList().each {it.ROI = it.ROI.translate(dx, dy)}
getAnnotationObjects().each {it.ROI = it.ROI.translate(dx, dy)}
fireHierarchyUpdate()
```

This moves only TMA cores and annotations (not detections... but transferring detections really isn't recommended, since many detection commands are substantially different in v0.2.0 compared to v0.1.2).
