### ISSUE TITLE
regionrequest into imageplus object has inconsistent beightness/contrast across the whole image.

### ISSUE THREAD

**Issue by rmd06** [qupath/qupath#551]
I use Qupath to export a .scn file as tiles of imageplus object and save as jpg, then load them into html pyramid browser.
![43254234](https://user-images.githubusercontent.com/22294036/86387026-272c1100-bcc5-11ea-9aad-87823e3ed9d2.png)

```
imp = IJTools.convertToImagePlus(server, request).getImage()
IJ.save(imp, filepath))
```

When I deal with RGB slide, it works fine.
However, when I deal with 4-channel fluorescent image, it seems that each jpg tile has its own different brightness/contrast when saving, making the whole image looks like mosaic when merged in html.
Especially in corner background, the black background was augmented to high noise.

Is there something wrong, or how can I prevent it from auto-adjusting the image?

Thanks

![152432434](https://user-images.githubusercontent.com/22294036/86386975-14194100-bcc5-11ea-8c98-bb025ab28bd4.png)

**Comment by rmd06** [comment]
I tried to save imageplus object as tif/bmp format, but the tiles lookes pure grey. 
![3242341432](https://user-images.githubusercontent.com/22294036/86387577-f5677a00-bcc5-11ea-8e16-e90052fff887.png)

**Comment by petebankhead** [comment]
This doesn't look like a bug in QuPath, but rather in that when converting a region to an `ImagePlus` ImageJ will automatically be setting the brightness/contrast based upon the only part of the image it sees.

You'll need to use ImageJ-specific functions to set the min/max display values, or else use the `writeRenderedImageRegion` method from QuPath instead and skip the ImageJ step entirely. See [here](https://qupath.readthedocs.io/en/latest/docs/advanced/exporting_images.html#rendered-images) for information about writing rendered images generally (the `writeRenderedImageRegion` method isn't documented specifically, but it's a combination of `writeRenderedImage` and `writeImageRegion`).

I will close this issue because there is no bug; any further discussion is better on the forum at https://forum.image.sc/tag/qupath
