### ISSUE TITLE
Classify

### ISSUE THREAD

**Issue by bpavie** [qupath/qupath#56]
Dear Pete,

I was wandering  if we could use qupath to perform pixel classification, similar to what exist with weka plugin for ImageJ. And if yes, is there a tutorial for that. I have to detect adypocyte and did it with success with ImageJ/Weka but it require to export the slide to a lower resolution so ImageJ can open the image. I would be delighted to use Qupath for that if it was possible.
Benjamin

**Comment by Svidro** [comment]
I have kept meaning to try the Weka plugin, but never seemed to get around to it!  This sounds like an excellent chance to test it out.
Somewhat related, I am not sure I understand exactly what you are measuring, but if you are measuring "the amount of white space" in your tissue, I have a couple of suggestions.
1. Create a macro that sends your annotation areas to ImageJ, which can then create detection objects from a mask created to detect below/above a certain "white" threshold.
2. Built in, create a smallish annotation that includes significant whitespace and your tissue of interest.  Next use the Analyze->Preprocessing->Estimate stain vectors to both set your background to the mode (first popup), and secondly set one stain vector as best you can to line up with your detections, and the other you can pretty much ignore.
![step1](https://cloud.githubusercontent.com/assets/23145209/23876638/b0997bee-07fb-11e7-9c2a-434dacaddead.JPG)
3. Use the Analyze->Region Identification->Positive Pixel Count (experimental) with very a very low threshold for the stain vector you used in the previous step, and an absurdly high threshold for your second vector which we will ignore.  I would iterate a few times on a VERY small area, as this is very computationally intensive, and the program tends to respond very slowly for me after running it on a large area.
4.  Once you have your settings and run the pixel count on your annotation, you can use your pixel area and the total area to get a percentage of total pixels that are below threshold.  In the case of my image, I used the hematoxylin vector, so I multiplied the negative pixel count times the area of my pixels (seen under the image tab, Pixel Width and Pixel Height) and used that to obtain a percentage of non-tissue area within my annotation.  You can see that in the Excel window, and that it roughly matches up with what you can see in the annotation.
![step2](https://cloud.githubusercontent.com/assets/23145209/23877031/93cfeda2-07fd-11e7-9b0d-3119377d03a3.JPG)

**Comment by bpavie** [comment]
Thanks for the dedtail answer.
What I wanted to do was more something similar to what Ilastik or the Trainable Weka segmentation plugin for ImageJ offer, meaning you select manually some areas (in my case, I could define 3 classes of pixels, adipocytes, background and others) and after having applied multiple filters (gaussian, hessian etc...), the classifier is generated from my selection and applied to the rest of the image's pixels.

I first thought that the integration of Weka was doing that but I realized then that it is used to classify annotations based on intensity and shape features, which is a bit different.

Itwould be interesting to perform this kind of analysis because sometime that which give the best result in term of segmentation.
The threshold based approach didn't give me similar result, especially because background and inside of adypocyte have similar intensity.
The main advantage to use it in qpath instead of ImageJ will be to run it on the max resolution to get more precise result.

![image](https://cloud.githubusercontent.com/assets/1775952/23906471/53031de0-08ce-11e7-88ce-d89736289278.png)

**Comment by Svidro** [comment]
Hmm, I still think your best option will be running something like the Simple Tissue Detection to get your annotation area to exclude all background that is external to your tissue (you may have to go over the edges yourself, and definitely play with the Max fill area, as setting it to just larger than the largest fat globule you want to measure is key!) so that you only have two populations, background/fat globule (low OD) and tissue (high OD).
You might also play with tiling your tissue annotation (pretty much everything I suggest will involve generating an annotation, I'm afraid) and then sending each tile to ImageJ for thresholding (Extensions->ImageJ->ImageJ Macro runner).  The returned detections end up looking something like these... and depending on how much you play with your thesholds (both size and OD) you will see more or less of the errors around the edges.  The tiling allows you to analyze the image in small enough sections such that ImageJ can handle the full resolution.
![lipid area original](https://cloud.githubusercontent.com/assets/23145209/23907432/62750fee-088e-11e7-96c6-1f120a4f43b2.JPG)
![lipid area measurement](https://cloud.githubusercontent.com/assets/23145209/23907431/62706eee-088e-11e7-8fba-21464fea38cb.JPG)

**Comment by Svidro** [comment]
Actually, looking at Ilaskit, I would probably start with trying to run that through QuPath (point the ImageJ plugins directory to the correct place in Preferences).  Some modules are not compatible, but if that one is, it would probably be the way to go for segmentation.  If it works, just find the largest tiles ImageJ can handle at a time, assuming you can store your training set for QuPath to access on each call.

**Comment by bpavie** [comment]
Thanks for your answer.
I tried to follow your tips, but I am a bit lost with the different steps and how to perform them.

1/ Detect tissue using : `Analyze>Preprocessing>Simple Tissue Detection` ✓ 
2/ Split it into multiple tiles : `Analyze>Region Identification>Tiles & Super Pixels` then select `Make annotation tiles` and `Remove parents annotation` ✓ 
3/ Sending each tile to ImageJ for thresholding : `Extensions->ImageJ->ImageJ Macro runner`
So at this step, I am not sure how to perform that. As an example, I set the following into the Image Macro runner:
```
run("8-bit");
setAutoThreshold("Huang dark");
//setThreshold(187, 255);
setOption("BlackBackground", false);
run("Convert to Mask");
run("Analyze Particles...", "  show=Overlay display clear");
```
Then I selected `Send ROI to ImageJ`,  `Clear Current child Object` and `Create detection object from ImageJ overlay`.

![image](https://cloud.githubusercontent.com/assets/1775952/23943366/7c26ced2-096f-11e7-9cb9-f8ca32c9e1eb.png)


To run it on the wholde slide, I selected all the annotation and pressed `Run`. Is that the correct way ?

And after running, indeed it worked:
![image](https://cloud.githubusercontent.com/assets/1775952/23943815/fe38edd2-0970-11e7-9b84-b3cf189a51b3.png)

For some reason, the background has also been selected, although it was outside of the tile.
-My first question is how to avoid that?

-Second question, all detected objects are by tile, is there a way to merge the connected one?

And finally, it works tile by tile, but in case I would like to perform the Weka segmentation (which could be done easily thanks to the bridge you made via an ImageJ Macro), since the weka segmentation perform filtering (gqussian, hessian etc...), ideally, I would like to process the tile with a little bit of extra border so for example a gaussian filter with a kernel of 4 will take into account the pixel outside of the tile. But right now, it will only take into account the pixels inside the tile.

Anyway, thanks a lot for your help, I am going to play more with QuPath to test all the other possibilities!

**Comment by Svidro** [comment]
Yes, I did run into some of the same problems with the external measurements since the ImageJ macro runner takes squares, not the actual annotation.  The advantage here is QuPath's heriarchy system, where everything "outside" of the annotation will show up separately (not underneath in the tree), and can be selected and deleted.  Probably easier to do this after you go to the annotations tab, CTRL-A (or whatever to select all) and then go to the Objects menu and "Merge annotations."  Then you get only one annotation and all of the external detections in the Hierarchy tab.  This makes it easy to once again select all, deselect your annotation, and delete all of the "outside" detection areas.

Downside, merging all of the tiles does NOT actually do what you might hope, and mesh them all into one contiguous annotation.  It does add them all together, however, which lets you use the show annotation measurements to see the sum totals of all of your annotation tiles.  You will see better after you do it once.

**Comment by Svidro** [comment]
Ooops, I misread part of your question.  I do not know of any way to merge the two detection measurements from either side of a square, if you figure it out please let me know!

The best suggestion I can offer there is to make your tile sizes as large as ImageJ can handle on a per-tile basis.

**Comment by petebankhead** [comment]
Hi, sorry I'm coming to this a bit late...

From looking at the image, I agree that it would be good to try to find a way to detect the regions you want with a threshold (maybe *Simple tissue detection* or an ImageJ macro).  However, I can't really say very confidently how well this will work since I have not tried an application like this before.

With regard to *Trainable Weka segmentation*, you might be able to run it through QuPath by pointing the ImageJ plugins directory (under *Edit &rarr; Preferences...*, double-click on the text field beside *ImageJ plugins directory*) somewhere where the *Trainable Weka segmentation* plugin and all its dependencies can be found (e.g. the *plugins* directory of a Fiji installation).
Then use *Send region to ImageJ* to send all or part of the image to ImageJ for processing, and call the *Trainable Weka segmentation* from there.

> Note that QuPath won't actually use Fiji itself, but rather ImageJ1, so whenever you set the *plugins* directory to be that of a Fiji installation you may find that some commands don't work (if they have Fiji-specific dependencies).  But I think *Trainable Weka segmentation* is ok.

However, that might not be necessary.  QuPath doesn't offer a pixel classifier like *Trainable Weka segmentation* or *ilastik*, but you can use QuPath's object classifiers to get a similar result.  The process would be something like this:

* Create an annotation around an area of interest (e.g. manually, or with *Simple tissue detection*)
* Run *Analyze &rarr; Region identification &rarr; Tiles & superpixels &rarr; Create tiles* to create square tiles of any size (*don't* choose 'Make annotation tiles' in this case!)
* Run *Analyze &rarr; Calculate features &rarr; Add Intensity features (experimental)* and choose a few color transforms along with *Mean* and *Compute Haralick features* from the bottom (and others if you like).  If your square tiles are tiny, set *Region* to be either *Square tiles* or *Circular tiles* and choose a tile diameter depending upon how widely you want QuPath to look around each tile for calculating textures.  Press *Run* and then choose *Process all: Detections*.
* Train a classifier as described [in the Wiki](https://github.com/qupath/qupath/wiki/Classifying-objects).  Check out [this issue](https://github.com/qupath/qupath/issues/50) if you find the *Brush tool* isn't working for you.
* Optionally run *Analyze &rarr; Region identification &rarr; Tiles & superpixels &rarr; Tile classifications to annotations*.... if you find it helpful.  It's always best to save your data before doing this, since all the options have some kind of logic behind them... but it's often not entirely clear which are the options you want on a first go.  There is no *Undo*, but if you save before running the command, *File &rarr; Revert* can get you back to where you were.

The end result is a rather 'blocky' classification, where the size of the blocks depends upon how large the tiles are that you created.  But if you need to downsample your image 8 times to get good enough performance with the Weka plugin, then using tiles that are 8x8 pixels gives you just as good a resolution in the end.  Furthermore, with QuPath you can add some other kinds of features, particularly Haralick texture features on color-deconvolved images, which can be a better fit for pathology applications compared to some of the Weka features (which may be better for other applications). And you can do other things in QuPath to help with efficiency, such as create a script to find all pixels with high intensity values (background?) and remove them - thereby allowing you to avoid the memory and computational requirements of storing and classifying them.

Therefore while there is some overhead involved in QuPath using objects rather than pixels in the way that *ilastik* and *Trainable Weka segmentation* do, QuPath's use of objects is sufficiently efficient and optimized that I think it offers a viable alternative in many cases.

**Comment by petebankhead** [comment]
One other thing... I find that the easiest way to avoid detecting outside the annotation is to modify the ImageJ macro, rather than do post-processing in QuPath.  You can take advantage of the fact that, for any non-rectangular region, QuPath sends the ROI to ImageJ as well.  And so ImageJ's *Edit &rarr; Clear Outside* can help.

(In practice, it can be a bit more tricky than that... you might need to complicate your macro with checks to see whether there is a ROI present in the first place, and you might need to use *Edit &rarr; Selection &rarr; Select None* and *Edit &rarr; Selection &rarr; Restore Selection* within your macro if you find that you need to do some processing prior to using *Clear Outside*.)

**Comment by Svidro** [comment]
Randomly looking for something else, but now in M2 there is a pixel classifier!
