### ISSUE TITLE
How to continue training saved classifier

### ISSUE THREAD

**Issue by LieseCharlotte** [qupath/qupath#57]
I am sure the answer to this question is simple but I just don´t find it in the "user guide". I created a detection classifier (to distinguish between tumor, stroma and immune cells) which was doing ok, so I saved it for later use. When I created it, it got better and better as I drew more annotations and set their class. However it is not working as well as it needs to. So I loaded it again today in an attempt to continue training it. I opened the classifier (Classify -> load classifier (the one I had saved the other day) -> run classifier. At this point it worked like it had when I saved it. How do I continue teaching it from here on? Drawing annotations and setting their class doesn´t work like it did when I created the classifier. Selecting Classify -> create detection classifier does not work because this way I am creating a whole new classifier. How can I get my existing classifier in the mode where I can press auto update or where it automatically continues to update?  I must be missing a very simple step! 

I have one more question: I am using the classifier on a TMA slide. The TMA cores differ quite a bit. So I have to adjust/train the classifier slightly for each single core until it works the way I want. Do these changes in classification only apply to the selected annotation (TMA core) or does this automatically change the classifications already made using the classifier in other TMA cores on the same slide? 
Thank you very much for your help! 

Kind regards,

Liese

**Comment by petebankhead** [comment]
When you save the classifier, QuPath really just saves what it needs to apply the classification - but it doesn't store all the information about where exactly the training information came from.  That's why you aren't able to load the classifier again and update it... not enough information has been saved in the ```.qpclassifier``` file to make that possible.

The ```.qpclassifier``` file should therefore be considered 'locked-down', since you can't really change that classifier again directly.

Fortunately, so long as you've saved the data for each image as you went along (including your annotations), you can work around this.  To do so, you start by creating a new detection classifier and starting to train it by adding annotations and setting their classifications on any image.  Then if you open each of the images you previously annotated for training, QuPath will look for any annotated regions and (optionally) add them to the training as well.  Using this approach, you end up with a whole new classifier - but it can be based on the old training, plus whatever you want to add.

This is ok if you only used one or two images for training in the past, but it could be a bit annoying if you annotated lots of images in a project.  In this case, there is a shortcut that you can use.  Click on *Advanced options* in the *Create detection classifier* window and select the ```More...``` button on the right.  If you choose *Rebuild training from project* QuPath will then loop through *all* the images in the project and use any annotations it finds to train the new classifier.

For your other question, the classifier is applied across the entire slide that is currently open - so that means that the classification will be updated for all TMA cores that are on the current slide (but *not* TMA cores that are on a different slide!).  When you train the classifier and open a new image, you have the option to retain your training (i.e. continue to build a classifier, using all the information from the old slide that you are closing and also the new slide that you are opening) or not (i.e. discard all the training information from the slide that was previously open).

Again, the ```More...``` button can be useful.  You can use it to find out how many objects have been used for training for each image in the project (*Show training object counts*).  You can also use this button to apply the current classifier to all images in the project (*Classify project images*).

Probably, you would want to train a classifier that works reasonably across all your TMA cores and all your slides, and then apply this across all your slides at the end - to make sure they all have the same classifier applied the same way.  You can either do this with the *Classify project images* option under ```More...```, by opening each image in turn and loading/running the classifier, or by using a script to automate the process.

I hope that helps explain things a bit.  I admit that things get a bit more complicated whenever you need to train a classifier across multiple images, and then update it later... but sometimes I also find that it is necessary.

**Comment by LieseCharlotte** [comment]
Dear Pete, 
Thank you so so much for your quick and detailed answer! I appreciate your help very much!! Too bad there is no direct way to continue training a classifier once it has been saved and closed. I am sure however that your suggested solutions will work fine in my case. Thank you! As for your answer concerning my second question I am unsure how to create a classifier that would work fine for all TMA cores in one slide as the immunecells in core A look very similar to the tumor cells in core B for example (so when I train the classifier it either works for well for core A or B). Also the tumor cells differ a lot in appearance from core to core. I understand that using the same classifier for the entire slide or better all slides in one project would be a more elegant solution but I don´t see how this should work in my case. I understand from your answer to my first question that even if I created a new classifier for each core it would automatically change the detections in another core on the same slide previously made using another classifier....Do you have any suggestions how to address this problem? I should also use this opportunity to point out how well quPath works in general! Great software!
Thank you so much for your help and support!

**Comment by petebankhead** [comment]
Hi Liese,

You might be able to directly continue retaining a classifier if you use the *Save training objects* option under the ```More``` button, and then *Load training objects* next time.  At least that is what that option is intended for... although I can’t say I have used it very much, so it hasn’t had a lot of testing.

Regarding the second question, I feared that this would be the problem when I wrote my reply... I suppose that in the absence of an elegant solution, it is worth considering inelegant ones.

I can think of a few possibilities, although how feasible they are would depend upon how many cores you need to analyze, what outputs you require, and just how different the cores are.

---

Here are some ideas (not necessarily all good ones):

1. You could annotate regions of interest and detect cells only inside your annotations - no need for a classifier at all.  This would mean you need to draw an awful lot of annotations (one or more for every core), but at least you are in full control of what is annotated.

2. You could train up a classifier for all the ‘similar-enough-looking’ cores on one slide, and save that classifier.  For all the cores that aren’t handled well enough, you could go through and set them as ‘Missing’.  When you export your results, you need to be careful to ignore all the ‘Missing’ cores.
Then, you can duplicate your project, and delete all your annotations.  You can go through and set all the ‘Missing’ cores to be available, and all the available cores to be ‘Missing’.  Then train up a new classifier, and export the results again.
This way you can use multiple classifiers.  It’s not very elegant at all, and I’m not sure that I would recommend it… but it is an option.
> If you try this, you could toggle the ‘Missing’ status in a script or manually.  If you do it manually, I’d suggest opening the ‘Hierarchy’ tab on the left of the screen, and selecting the first core.  Make sure you have clicked somewhere inside the main viewer to activate it, then use the arrow keys to move around the TMA grid, and press ‘backspace’ to toggle the ‘Missing’ status.  Because the default settings mean that selected cores are shown as yellow, rather than dark/light blue, having the ‘Hierarchy’ tab open is useful to show you whether the selected core is missing or not.

3. You could do something similar to the above, but set the ‘missing’ status before cell detection… so you end up without any cells in the cores that shouldn’t be included.  This helps avoid generating a lot of badly-classified data that you then need to remember to ignore later.  However, it does then require being able to estimate in advance which cores should be classified together.

4. If you want to use a separate classifier for every core, you could try a more drastic approach of exporting every core as a separate image.  To do this, first dearray your slide.  Then, you can use [Extension &rarr; ImageJ &rarr; ImageJ macro runner](https://github.com/qupath/qupath/wiki/Working-with-ImageJ#running-macros) to export each image.  You need a very simple macro, like the one below:
```
saveAs("tif", "/Users/peteb/Desktop/export/" + getTitle())
```
where you’ll need to change the path to be something more suitable for your computer.  It takes advantage of the fact that the ‘title’ of the image sent to ImageJ is the same as the TMA core, so using this as the filename can help you identify the core afterwards.

> This may give you individual core images that are a bit big... you can change "tif” to “jpg” to decrease the file size, or you can set the "Downsample factor” value to 2 to export a lower-resolution image.  The advantage of using “tif” is that the micron information is preserved, while if you use “jpg” then this is lost.

After doing this export you can then import all your core images into a new project.  You’ll almost certainly want to use scripting for batch processing in this case, and there will be another couple of things to do (e.g. apply dearraying to detect a single core in each image, or use *Objects &rarr; Create full image annotation* to give you a region in which to detect cells).

---

Personally, I think Option 1 is the ‘cleanest’ solution, but may be very time-consuming.  All the others would give some kind of data management headache - but maybe it is worth it.

Of course, there may also be more creative solutions that I haven’t considered.  I would be interested to know what you choose in the end.

Good luck!

Pete

PS. Thanks for the positive feedback!

**Comment by LieseCharlotte** [comment]
Dear Pete,
Thank you for your answer! Now I have multiple options how to proceed from here on. And I am sure it will work out one way or another. To me drawing annotations manually and setting classes for each core seems to be the best option. Drawing annotations is ok, it´s just annoying when you have cores in which there are hardly any clusters of cells of the same type but rather a homogenous mix. This is the case in some of my cores meaning I´d have to draw 200 annotations in one core. I´d have to classify roughly 1200 cores in total which, of course, can be done although it is a lot of work. I might opt for a combination of option 1 and 2. Classifying those that look similar in one go and doing the rest manually after saving and exporting the data. I´ll just try different ways and see what works best for me. Thank you so much for coming up with so many different approaches to my problem! I ´ll certainly let you know which option I decide to use, if you leave this issue unclosed so I can comment on it.
Thank you so much once again!

**Comment by Svidro** [comment]
I was looking into this, and ways to classify multiple sets of cells within an image, and found one way that may or may not work for one.
Massive disclaimer, this does not work for using the "Create Detection Classifier," but does work for the script Peter wrote to perform classifications based on features.  I'll add a copy in at the end.

1. Create an annotation around the cells you want to generate in a certain way (sometimes I want to create larger cells for muscles vs smaller for other tissues), then generate your cells for each annotation.
2. This step could use a short script from Peter (select all cells within a certain annotation class), but if you select a given subset of cells by picking one annotation (usually easy enough by clicking on that annotation in the hierarchy and shift+clicking) you can then add a dummy measurement to those cells using settings in the Compute Intensity Features (or a script, probably) that you do not need for classification.  In my case I chose Hue-Mean.
3. Include Hue-Mean in your classification script as a measurement it checks for the presence of, and if not found, the classifier does not even try to classify those cells.

I tested this by adding Hue-Mean, Saturation-Min, and Saturation-Max to three different sets of cells, and was able to run 3 different classifiers on all of my cells, and only have the correct cells (the ones with the dummy measurement) receive the results of the correct classification.
I'm sure this is somewhat complicated by the TMAs and dealing with multiple cores, and I haven't had a chance to figure out how to make that work since you can't draw an annotation to include multiple TMA cores, but maybe this could prove useful as a stepping stone for running multiple classifiers within a TMA.

Here is the code for the dummy Hue-Mean classifier (specifically run at 0.50 µm).  I have muddled around in the code here, and I think this is working because I never create a "def" for my "baseClass" of "Tumor."  There is almost certainly a more elegant way of doing this instead of my hacking and slashing at the code until it does what I want.

```import qupath.lib.objects.classes.PathClass
import qupath.lib.objects.classes.PathClassFactory
import qupath.lib.scripting.QP

// Parameters to modify
List<String> includeClassesWithName = ["Tumor", "Stroma"] as List<String>
def feature = "Nucleus: DAB OD mean"
def threshold = 0.1
def feature2 = "ROI: 0.50 µm per pixel: Hue:  Mean"
//def threshold2 = 0
// Check what base classifications we should be worried about
// It's possible to specify 'All', or select specific classes and exclude others
def doAll = includeClassesWithName.contains("All")
def includeClasses = [null]
//def Stroma = PathClassFactory.getPathClass("Stroma")
def Positive = PathClassFactory.getPathClass("Positive")
def Negative = PathClassFactory.getPathClass("Negative")
//def DualPos = PathClassFactory.getPathClass("Dual Positive")
if (!doAll) {
    for (String n : includeClassesWithName)
        includeClasses.add(PathClassFactory.getPathClass(n))
}

// Loop through all detections
for (def pathObject : QP.getDetectionObjects()) {

    // Get the base classification
    PathClass baseClass = pathObject.getPathClass()
    if (baseClass != null)
        baseClass = baseClass.getBaseClass()
    else if (PathClassFactory.isPositiveClass(baseClass) || PathClassFactory.isNegativeClass(baseClass))
        // In the event that we have a positive or negative classification that lacks a base class,
        // this implies that the base class should be null
        baseClass = "Tumor"
    // Apply classification, if required
    if (doAll || includeClasses.contains(baseClass)) {

        // Check if we have a measurement - if not, assign the base class
        double val = pathObject.getMeasurementList().getMeasurementValue(feature)
        if (Double.isNaN(val)) {
            pathObject.setPathClass(baseClass)
            continue
        }
        double val2 = pathObject.getMeasurementList().getMeasurementValue(feature2)
        if (Double.isNaN(val2)) {
            pathObject.setPathClass(baseClass)
            continue
        }


        // Set positive or negative class
        if (val >= threshold ){
            pathObject.setPathClass(Positive)
            }else pathObject.setPathClass(Negative)

    }


}

// Fire update event
QP.getCurrentHierarchy().fireHierarchyChangedEvent(this)

// Make sure we know we're done
println("Done!")
```
With as many defined values, thresholds, and if statements as you want, you can basically create your own decision trees.  Maybe I should have posted this on the Google group instead :)

**Comment by Svidro** [comment]
Another possibility for TMAs might be something like 
```getDetectionObjects() each {detection -> detection.setName(detection.getParent().getName())}
fireHierarchyUpdate()```
in order to name all cells after their parent TMA core (assuming no other annotations have been drawn at this point).  

At that point, there could be a list of TMA cores you wanted to apply that particular classifier to which the script checks before applying the current classification steps.  
Downside: you would have to create both the list and each classifier.  
Upside: you would have complete control over the classifier and once created it would be easy to apply across many TMAs.

PS. It might be more streamlined to check the parent annotation name within the classifier script against the list, though.

**Comment by LieseCharlotte** [comment]
Dear Svidro, 
Thank you very much for your input. I am quite new to quPath and  have not tried scripting yet. Maybe I should give it a try. Especially your second suggestion sounds like it might work for my purposes! 
Thank you for your help!

Kind regards,
Liese

**Comment by yuzeranil** [comment]
Hello Dear Pete, 

First of all, thanks for this great program. You must be genius. Second of all, does "Click on Advanced options in the Create detection classifier window and select the More... button on the right. If you choose Rebuild training from project QuPath will then loop through all the images in the project and use any annotations it finds to train the new classifier." still work? I couldn´t really find it.
