### ISSUE TITLE
Cell detection and tissue detection not compatible at same level of hierarchy

### ISSUE THREAD

**Issue by hartlandj** [qupath/qupath#60]
After detecting cells within each TMA core I then ran tissue detection on the same TMA cores.
It found all tissue areas but replaced all objects. I had thousands of objects per core (for each cell) and now there is one object per core (tissue).
I was able to do cell detection within the tissue detection annotation earlier, but then didn't have the core name in my output.
I will save each separately.

**Comment by petebankhead** [comment]
If I understand correctly, this is expected behavior.  If you run cell or tissue detection inside an object, then the existing contents of that object will be removed and the results of running the command will be added instead.

This is the best way that I could think of to make the behavior predictable and (generally) unobtrusive.  Otherwise, if you ran either command multiple times you would end up having multiple tissue annotations or cell objects relating to the same structures in the image.  To get around this, you'd need to explicitly delete the older objects... which would be laborious if you want to run the same command multiple times to test out different settings.

Also, in this specific example, by detecting cells first and then tissue you could very easily end up with cells within a TMA core being located outside the tissue region... which could be rather confusing.

For these reasons, if you want both tissue annotations *and* cell detections, then you should create the tissue first and then detect the cells inside the tissue.  If you want, you can delete the tissue annotations afterwards but keep the cells (e.g. *Objects &rarr; Delete... &rarr; Delete all annotations*).

As described in #59, if the goal is to have the core name exported along with the individual cell measurements then that can be done by scripting.  There are lots of ways to approach this in a script, although I can't think of a way currently to get that specific output without writing a script.
