### ISSUE TITLE
Multiviewer does not use "Keep settings" for channel displays

### ISSUE THREAD

**Issue by Svidro** [qupath/qupath#601]
Before submitting your bug report, please check the following:
Searched for "keep settings multiviewer" 

## Bug report

**Describe the bug**
When "Keep settings" in the brightness and contrast dialog is checked, each image opened in the project will have the same display settings, and so they will be comparable by eye. When opening multiple images with the multiviewer, they open with the default settings calculated by QuPath.

**To Reproduce**
Cycle through a group of fluorescent images in the main viewer, with Keep settings checked. They will each open with comparable display settings.
Open two viewers, and load a second image (of the same type and number of channels) into the second viewer. It will not keep the same display settings as the primary image. 

**Expected behavior**
Images opened in the multiview will be comparable to each other, as they are when opened sequentially in a single viewer with Keep settings checked. Currently, something like a negative control will be ramped up in brightness due to QuPath's auto-balance.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/23145209/92514285-7e1efc80-f1c6-11ea-8924-2d33b4ff7bda.JPG)
Right side: two individual QuPath instances, showing how two images look when cycling through the list of images one at a time with "Keep settings"
Left side: Attempting to compare two images side by side using multiviewer, but the settings are not kept between viewers. When comparing 8 samples, it gets a little bit tedious adjusting all of the channels (though it could probably be done by script).
Horizontally, the images are the same.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - QuPath Version [e.g. 0.2.2]

**Additional context**

**Comment by petebankhead** [comment]
I've submitted a pull request at https://github.com/qupath/qupath/pull/602 with a proposed solution - can you check and see if it works (or it breaks something else)?

There should be a v0.2.3 soon to fix bugs. This seems a little bit borderline, since the old behavior is kind of logical and consistent... but I tend towards agreeing that it's a bug, and so if the fix works then it should be included. What do you think?

**Comment by Svidro** [comment]
Yes, this seems to work, and doesn't cause problems with comparing images of differing types in different viewers, which would have been my main concern for a potential problem.
The other option might be having another selection within the multiviewer menu that sets all displays to the current display. That would allow keeping the current settings while still giving users an easy way to equalize all of the views without scripting, assuming all of the viewers are showing the same image type with the same number of channels. 

I prefer the new build since I don't see any _good_ reason to rebalance the display between images you are viewing, unless maybe you had duplicates of the same image and wanted to view it with two different display values... ?

**Comment by petebankhead** [comment]
Thanks, I can't see any good reason for the old behavior either - I'll merge the change :)

Equalizing views would be a bit too big a change for a 0.0.x release... perhaps one day, but the whole brightness/contrast/color code is pretty horrible, and so it probably is a case of rewriting it entirely rather than trying to push it much further. (It was thanks to @melvingelbard that the issue was found so quickly, I was hesitant to delve into the mess myself...)

For reference, the logic of the update is:
* retain the settings from the previous image in the current viewer, if it's compatible with the one being opened
* if there wasn't a compatible image already open, find the first viewer that *does* have a compatible image and use the display settings from that
