### ISSUE TITLE
Make Report in Excel 

### ISSUE THREAD

**Issue by brijeshwar2002** [qupath/qupath#612]
Hi Pete,

If i have counted out the positive and negative cells in qupath software and then i want to have an report of it in MS Excel or MS Word so how can i do it ?

Regards,
Brijeshwar Arora

**Comment by TMM-98** [comment]
Click Measure -> Export measurements. A window pops up (or select "export measurements" via command list cmd+L)
2. Select the images from which you want the data to be exported (e.g. everything but
training images)
3. Choose and name an output file (e.g. measurements.tsv)
4. Choose .tsv as separator, since MS Excel can read this format
5. Click Populate and choose which columns to export (e.g. Image, Name, pos.cells, Area)
6. Click Export
Now in your documents folder, right-click on the created file to open it with Excel. Make sure to convert to .xlsx directly to ensure that all your calculations are saved properly.

**Comment by TMM-98** [comment]
I believe that the GitHub platform isn't quite the right place to ask these questions, since this site deals more with technical difficulties and development. The place to go would likely be the forum image.sc
But I am sure that other people can say more to this. I hope I was able to help ;-)
Thiemo

**Comment by brijeshwar2002** [comment]
Hi Thiemo,

Ok I'll keep that in mind and thank you it was helpful.

Regards,
Brijeshwar

**Comment by petebankhead** [comment]
Thanks @TMM-98 👍 

@brijeshwar2002 you can get this info by searching for *exporting measurements* in the documentation [here](https://qupath.readthedocs.io/en/latest/search.html?q=export+measurements&check_keywords=yes&area=default) - and please do use http://forum.image.sc/tag/qupath rather than GitHub for questions about the software.

I will close this issue now.
