### ISSUE TITLE
stable release 0.2.3 linux installation path

### ISSUE THREAD

**Issue by elmbeech** [qupath/qupath#614]
## Bug report

**Describe the bug**
If the stable release folder *QuPath-0.2.3/* is placed behind a *bin* folder, QuPath will not run.

**To Reproduce**
1. `wget https://github.com/qupath/qupath/releases/download/v0.2.3/QuPath-0.2.3-Linux.tar.xz`
2. `tar -xvf QuPath-0.2.3-Linux.tar.xz`
3. `cd  QuPath-0.2.3/bin/`
4. `./QuPath-0.2.3`

**Behavior**

If QuPath runs, is dependent under which path it is installed.

+  `/home/elmar/QuPath-0.2.3/bin`  this works
+  `/home/elmar/abc/QuPath-0.2.3/bin`  this works
+  `/home/elmar/bin/QuPath-0.2.3/bin`  this will **not** work!

This is the error I receive: 
```
elmar@computer ~/bin/QuPath-0.2.3/bin $ ./QuPath-0.2.3
Error: could not find libjava.so
Error: Could not find Java SE Runtime Environment.
```    

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - QuPath Version 0.2.3 stable release

**Comment by petebankhead** [comment]
Intriguing... the packaging is performed using `jpackage` - which is part of the JDK, but currently is an incubator module - and so that is really where paths are handled.

My guess is that it relates to this: https://bugs.openjdk.java.net/browse/JDK-8219962

I don't see any way to resolve it within QuPath directly, it looks like the bug is deeper in Java. A little bit of googling has shown that other applications have the same issue.

**Comment by petebankhead** [comment]
I've now added a reference to this in the documentation: https://qupath.readthedocs.io/en/latest/docs/intro/installation.html#linux

I'll close the issue since it seems that the bug is outside QuPath and therefore I don't think it's something we can resolve, beyond documenting the workaround.

**Comment by elmbeech** [comment]
Ok! Thank you for looking into this.
And thank you for writing QuPath! So far the software comes in very handy.
