### ISSUE TITLE
File Location changes the resolution

### ISSUE THREAD

**Issue by PhGaertner** [qupath/qupath#659]
Hey guys,

I had following problem. When I open a .mrxs-file on my backup drive, I only get a pixelated picture with unknown pixel size, magnification and a size of 4 mb. When I open the same file in CaseViewer, I have no problem.

I dragged the file on my desktop and from there I can open the file in QuPath in full resolution.

I checked other files and some are working and others I have to change their file location.

Anybody got a better solution than manually copy&paste all the files?

Best,
Phillip

**Comment by petebankhead** [comment]
I'd recommend posting to the forum, where other users who have .mrxs files may see it: http://forum.image.sc/tag/qupath

There are lots of mrxs-related discussions there, see https://forum.image.sc/search?q=qupath%20mrxs

Since QuPath outsources reading proprietary file formats to OpenSlide and Bio-Formats, there's not a lot we can do on our side - QuPath is just showing what the reading library (in this case OpenSlide, probably) returns. mrxs is incredibly awkward for open source software... see also
https://qupath.readthedocs.io/en/latest/docs/intro/formats.html#mrxs-3d-histech

**Comment by PhGaertner** [comment]
Still thank you for that awesome programm. Can't imagine doing it with any other. Tools like pixel classifier and object classifier with the new software are perfect for DAB + Color stainings!

 
 

Gesendet: Freitag, 08. Januar 2021 um 12:01 Uhr
Von: "Pete" <notifications@github.com>
An: "qupath/qupath" <qupath@noreply.github.com>
Cc: "PhGaertner" <gaertner.phillip@gmx.at>, "Author" <author@noreply.github.com>
Betreff: Re: [qupath/qupath] File Location changes the resolution (#659)


 

I'd recommend posting to the forum, where other users who have .mrxs files may see it: http://forum.image.sc/tag/qupath

There are lots of mrxs-related discussions there, see https://forum.image.sc/search?q=qupath%20mrxs

Since QuPath outsources reading proprietary file formats to OpenSlide and Bio-Formats, there's not a lot we can do on our side - QuPath is just showing what the reading library (in this case OpenSlide, probably) returns. mrxs is incredibly awkward for open source software... see also
https://qupath.readthedocs.io/en/latest/docs/intro/formats.html#mrxs-3d-histech
