### ISSUE TITLE
Feature request - for "Brightness & contrast" panel

### ISSUE THREAD

**Issue by ajay1685** [qupath/qupath#669]
In the Min display value & Max display value sliders, Is it possible to increase significant digits after the decimal to two instead of one. It will be really helpful when working with 32-bit float component data from inForm.

Thanks.

**Comment by petebankhead** [comment]
If you double-click on the number, you can get lots of digits... is that sufficient?

If not, it looks like something we should be able to change by switching the [formatting here](https://github.com/qupath/qupath/blob/43aad4ecda893a7eb03c30774e64da5b9547bc86/qupath-gui-fx/src/main/java/qupath/lib/gui/commands/BrightnessContrastCommand.java#L202) (to use a `NumberFormatter`, so that decimal places aren't added when not needed) @melvingelbard 

(PS. I'd really rather use [the forum](http://image.sc/tag/qupath) for discussions/ requests, and GitHub only for bugs/dev use for specific releases)

**Comment by petebankhead** [comment]
@ajay1685 Chatting about this with @melvingelbard today, would it be helpful/sufficient to provide 2 decimal places when the value is < 10, and 1 decimal place otherwise?

I think that gets a balance between providing enough info without taking up space where it isn't needed (and potentially a 32-bit image *could* have large pixel values, so having 2 dp every time wouldn't always be desirable).

**Comment by ajay1685** [comment]
@petebankhead and @melvingelbard , sorry for the late response. I will use image.sc for feature requests if that is more suitable. (I thought it might easy for you to track features and interlink them with commit ids here)

I can access the numbers by double clicking, thanks for pointing that out. That should help a little. It would be nice to see at least 2 decimal places near the slider for the 32 float images (with low intensity values). I am not sure if it will hurt to have 2 decimal places when the values are greater than 10, or will it somehow affect the usability of the slider.

Your suggestion might be better, to have 2 decimal places when the value is < 10, and 1 decimal place otherwise.

Thanks for looking into this.

**Comment by petebankhead** [comment]
The code is now merged in https://github.com/qupath/qupath/tree/dev-0.3 if you want to try this out.

**Comment by ajay1685** [comment]
Thanks for the update. Looks great 👍, I will continue  testing dev-0.3 branch. I am closing this.
