### ISSUE TITLE
Error in Measurement with StarDist script with RGB fluorescence images

### ISSUE THREAD

**Issue by Jooppie** [qupath/qupath#686]
## Bug report

**Describe the bug**
I compiled QuPath with Stardist as described in the docs. The detection of nuclei on the blue channel works fine (although the cell expansion value is ignored). The Measurements are however not correct! I get only values for the red channel of a RGB image (see attachment) and they are incorrect (negative values, see screenshot). There are no values for the green channel.

**To Reproduce**
The script (I have it in a subfolder of the QuPath executable 'ScriptStardist', it finds the model then automatically.
[ScriptStardist.zip](https://github.com/qupath/qupath/files/6183384/ScriptStardist.zip)

The image (ImageJ Tiff file)
[CTRL-01.zip](https://github.com/qupath/qupath/files/6183389/CTRL-01.zip)

**Expected behavior**
Measurements like the 'Cell Detection' command.

**Screenshots**
Screenshot of the negative values.
![ss-negative-values](https://user-images.githubusercontent.com/46439648/112015678-5244e200-8b2c-11eb-9654-41fcd2c50c4f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - QuPath Version 0.2.3 and 0.3.0 Snapshot 22/3/2021

**Comment by petebankhead** [comment]
I can replicate the problem with the measurements. Basically, RGB images are a special case. QuPath + StarDist should measure them properly if they are brightfield (after color deconvolution), but if a fluorescence image is RGB then it just uses the packed RGB value as a single channel - rather than splitting out the red, green and blue components.

This is a bug that we can fix.

I don't see a problem with the cell expansion, but note that
* you're constraining the cell expansion with the ` .cellConstrainScale(1.5)` option
* the pixel size of your image is 0.5, but based upon the scalebar it should be closer to 0.161 µm

In the short term, you can open your images in ImageJ/Fiji and run *Image &rarr; Color &rarr; Make Composite*. While you're there, you can call *Analyze &rarr; Set Scale...* with a line drawn over the scalebar and input the true length to fix the pixel size.

I've attached an example of the image after conversion; this should work in QuPath properly.
[CTRL-01-composite.tif.zip](https://github.com/qupath/qupath/files/6183862/CTRL-01-composite.tif.zip)

Finally, my guess is that your RGB image isn't the raw data - since it has a scalebar burned in to it. So the pixel values might be changed and analysis might not make sense anyway. I've written a bit about this topic in my image analysis handbook, e.g. [here](https://petebankhead.gitbooks.io/imagej-intro/content/chapters/files/files.html) (and some other chapters about RGB conversion).

**Comment by Jooppie** [comment]
Thanks for the quick response. Converting to composite works. Is it an option to let QuPath do this automatically when the image type is set to Fluorescence? And for the standard "Cell Detection" the RGB Data was not a problem.
I overlooked the .cellConstrainScale(1.5) option.
You are right about the data not being the RAW data. This RAW data was lost by the researcher.
Thanks for the great program. We like QuPath a lot!

**Comment by petebankhead** [comment]
> Converting to composite works. Is it an option to let QuPath do this automatically when the image type is set to Fluorescence? 

I'm afraid not, QuPath doesn't really allow you to modify the image in any way, so changes like this are difficult. Batch conversion in ImageJ is the easiest 'fix' I can think of.

The code used to make measurements with StarDist is a lot more generic than the code for the built-in cell detection... but I overlooked the RGB problem since I didn't have any images quite like that. Good to know about it now so we can fix it before the next release.

> Thanks for the great program. We like QuPath a lot!

I'm glad! If you haven't already, it would be great if you could fill in the [user survey](https://edinburgh.onlinesurveys.ac.uk/qupath-user-survey-2021) - and please share it with anyone else you know uses the software!

**Comment by Jooppie** [comment]
I filled in the Survey a few days a ago already. I will ask my colleagues to do this also.

**Comment by petebankhead** [comment]
Great, thanks!
(I'll keep this open for a few days to make sure I don't forget to fix it...)

**Comment by petebankhead** [comment]
Closing now, since the fix is now merged and will be in v0.3.0.
