### ISSUE TITLE
Cell Detection Error On Large TIF File

### ISSUE THREAD

**Issue by ClnSchlssr** [qupath/qupath#69]
Hi,

Cell detection seems to fail when being performed on large areas of tiff images. I seem to be able to run the cell detection on smaller areas, but when running on larger areas, it generates some message (that disappears too quickly to be read) and then leaves yellow box elements seen in the attached picture, which was taken after trying to do one of these cell detection. 
The image I'm using is a single large tiff image (~500Mb) generated by stitching tiles of a scan made by a Zeiss microscope together. Perhaps there is a better way to stitch these files to mimic one of the more standard file types?

![capture](https://cloud.githubusercontent.com/assets/4945684/25635069/c14857f0-2f31-11e7-9d81-8209ca5bab58.JPG)

**Comment by petebankhead** [comment]
This may well be because of the image format, or QuPath might be having trouble for some other reason (not enough memory?).  If you choose *View &rarr; Show log* does anything informative appear?

It may also be beneficial to update your version of Bio-Formats, if you have not already done so.  I see on the [changelog for version 5.4.0](http://www.openmicroscopy.org/site/support/bio-formats5.4/about/whats-new.html) there is a mention of improved performance of large, uncompressed CZI files.  Is exporting as CZI an option?

Currently, QuPath works best for images that are small enough to handle directly, or large whole slide images stored in a tiled, pyramidal format of some kind.
