### ISSUE TITLE
3rd Party Library Dependencies in Scripts

### ISSUE THREAD

**Issue by ClnSchlssr** [qupath/qupath#76]
Is it possible to write scripts which depend on 3rd party libraries and run them from within QuPath? How would the dependencies be handled by QuPath, or is this a situation in which I should fork QuPath and recompile everything with the extra library?
I am making the first steps towards creating a script which classifies tiles based on a [previously trained] CNN using the [DL4J library](https://deeplearning4j.org).

**Comment by petebankhead** [comment]
Yes, it's possible to use 3rd party libraries without recompiling, although I'm not sure how easy it will be to set up in this case.

Firstly, you need all the (Java) jar files visible to the classloader in QuPath; the easiest way to do that is to put them in the *extensions* folder - normally just by dragging them onto QuPath when it's running.  You might need to restart QuPath to make sure they are picked up.

Secondly, in this case, you need all the native libraries of dl4j to be visible as well; these might have been distributed in jar files, in which case they need to be extracted (as far as I know - unless dl4j is doing something different here).  There is some more information about where to put them to get them on the ```java.library.path``` [here](https://github.com/qupath/qupath/wiki/Paths-&-configuration).

That is probably the easiest approach... if it works.  Alternatively, if you choose to use Eclipse instead, you don't necessarily need to fork QuPath since you shouldn't need to modify it, you just an Eclipse project to be set up with the source.  You can then create an extension and set up everything specific to your project there.  You could choose an existing extension as a base and then modify it, using Maven to manage all the dl4j dependencies, and then add it to the build path for the main QuPath project.

I haven't tried this exact configuration myself.  Since this requires some knowledge of Eclipse, Maven, library paths, QuPath and dl4j, I imagine it isn't the easiest thing to get working... but I think it should be doable.

**Comment by ClnSchlssr** [comment]
Thanks Peter. Quick and clear as usual. 
I'm getting the feeling that the latter will be a bit longer but more reliable. I assume the same approach could be taken with IntelliJ, no? 
It might be a bit of work but I think this would be an interesting feature for QuPath to have, and there might be a way to get several different user groups to collaborate and contribute images for training.
Thanks again for the direction.

**Comment by petebankhead** [comment]
I assume so as well, although I've never done it.  I generally use Eclipse for working with the full QuPath source/extensions, and IntelliJ for most other things.  I dabbled briefly with dl4j in IntelliJ, but never introduced it to QuPath and never took the time to figure out how to set up QuPath in IntelliJ.

I wouldn't claim my Eclipse setup is particularly elegant, but there is some information [here](https://github.com/qupath/qupath/blob/076fb69112b22a299e70819b5af31bd469e47e8a/src/main/resources/eclipse/README.md).  The ability to run in debug more, and even to change the code in a running application (within limits), is extremely useful.

If you did want to keep the worlds separate, with QuPath in Eclipse (or as a standalone application) and dl4j in IntelliJ, then you might have some benefit in creating a symbolic link in your QuPath extensions folder to wherever your dl4j jars are located; if I remember correctly, QuPath should look into subdirectories (symbolically linked or otherwise) for dependencies.  At least that may allow the jars to be managed by IntelliJ, and updated without needing to copy them over to QuPath again.  Native libraries will still need to be handled, but this only involves setting the path to the directory containing them anyway.
