### ISSUE TITLE
Exporting annotations from multiple slides into a single excel spreadsheet

### ISSUE THREAD

**Issue by elijahedmondson** [qupath/qupath#79]
I most commonly analyze multiple slides at one time -- what sort of script could I use to take specific measurements out of each individual slide and put them all together in a single spreadsheet?

**Comment by Svidro** [comment]
I don't yet have a quick and easy answer to this, but the following may help:

https://groups.google.com/forum/#!topic/qupath-users/_YdKRcGx4eQ

**Comment by Svidro** [comment]
I thought I might have posted this somewhere before, but I can't find it now.  Anyway, rough workflow for me:
`def string = "G:\\MyProjectData\\Data"
saveDetectionMeasurements(string, )
saveTMAMeasurements(string, )
saveAnnotationMeasurements(string, )`
I first use that script and edit it for whatever project I want to export from, then "Run for project" and select all of the slides.  I specifically need the double slashes because I am running Windows.

Once all of the annotation files are in one place, I use the following R code to merge it all into one .csv file, which I finally open in Excel, edit for clarity, and save.  You may find it easier to edit the file names before running the R script, I usually use a bulk file rename utility.
```
library(dplyr)
library(readr)
#Takes multiple annotation files in a "Path" directory and mergest them into a single CSV document. Each line of the 
#CSV file represents an annotation, and if a file has multiple annotations, only the first is listed with the file name
# and all subsequent blank names are part of the first listed file.
path = "G:/MyProjectData/Data"
setwd(path)
outFile <-"Tumor Assay Annotation measurements.csv"

#Replace .txt with whatever identifier will pick up all of the files you want to analyze. Detections or Annotations are common choices
Annotationfiles <- dir(path,pattern = ".txt")

#an empty frame to place data into
Measurements <- data.frame()
#simple for loop to read each file and keep a sum of the cell areas.
for(i in 1:length(Annotationfiles)){
  data.raw <- read_delim(Annotationfiles[i],"\t", escape_double = FALSE, trim_ws = TRUE)
  
  #place the file names in the first column
  Sample = tools::file_path_sans_ext(Annotationfiles[i])
  data.raw[1,2]<-Sample
  Measurements<-bind_rows(Measurements, data.raw)
  
  
}


#set row names to F if you don't want a numbered list as the first column
write.csv(Measurements, outFile, row.names=T)
```

I am not an expert R coder, so I am sure there are more elegant ways to accomplish this, but it works for me!

**Comment by elijahedmondson** [comment]
Thank you very much, that works great. - Elijah
