### ISSUE TITLE
"Cell detection" variability between tiles

### ISSUE THREAD

**Issue by elijahedmondson** [qupath/qupath#80]
![17032701](https://cloud.githubusercontent.com/assets/15114623/26643056/f94028f8-45fd-11e7-9c55-953359b2a21b.png)

I apologize if this issue has already been posted. Sometimes, when running the cell detection algorithm, certain tiles demonstrate variability in detection (as pictured). 

How can I reduce or remove this variability between tiles?

**Comment by Svidro** [comment]
Could you post your workflow script?  Farthest tab on the right (Workflow) should have a "Create Script" at the bottom which you can copy and paste here.

I suppose a more specific question would be which Cell Detection you were using to get this result.  (Cell detection+membrane comes to mind as having some odd behavior on certain types of background).

**Comment by elijahedmondson** [comment]
This was the WatershedCellDetection, for some reason, I have gotten this type of tiling variability on ~10% of my files. 

setImageType('UNSET');
setImageType('BRIGHTFIELD_H_DAB');
setColorDeconvolutionStains('{"Name" : "H-DAB default", "Stain 1" : "Hematoxylin", "Values 1" : "0.65111 0.70119 0.29049 ", "Stain 2" : "DAB", "Values 2" : "0.26917 0.56824 0.77759 ", "Background" : " 255 255 255 "}');
runPlugin('qupath.imagej.detect.tissue.SimpleTissueDetection2', '{"threshold": 235,  "requestedPixelSizeMicrons": 20.0,  "minAreaMicrons": 10000.0,  "maxHoleAreaMicrons": 1000000.0,  "darkBackground": false,  "smoothImage": true,  "medianCleanup": true,  "dilateBoundaries": false,  "smoothCoordinates": true,  "excludeOnBoundary": false,  "singleAnnotation": true}');
runPlugin('qupath.imagej.detect.nuclei.WatershedCellDetection', '{"detectionImageBrightfield": "Hematoxylin OD",  "requestedPixelSizeMicrons": 0.5,  "backgroundRadiusMicrons": 50.0,  "medianRadiusMicrons": 0.0,  "sigmaMicrons": 1.5,  "minAreaMicrons": 10.0,  "maxAreaMicrons": 400.0,  "threshold": 0.1,  "maxBackground": 2.0,  "watershedPostProcess": true,  "excludeDAB": false,  "cellExpansionMicrons": 5.0,  "includeNuclei": true,  "smoothBoundaries": true,  "makeMeasurements": true}');
setColorDeconvolutionStains('{"Name" : "H-DAB default", "Stain 1" : "Hematoxylin", "Values 1" : "0.65111 0.70119 0.29049 ", "Stain 2" : "DAB", "Values 2" : "0.26917 0.56824 0.77759 ", "Background" : " 255 255 255 "}');
runClassifier('/Users/elijahedmondson/Desktop/Projects/MetH/classifiers/MetH.qpclassifier');
setColorDeconvolutionStains('{"Name" : "H-DAB default", "Stain 1" : "Hematoxylin", "Values 1" : "0.65111 0.70119 0.29049 ", "Stain 2" : "DAB", "Values 2" : "0.26917 0.56824 0.77759 ", "Background" : " 255 255 255 "}');

**Comment by elijahedmondson** [comment]
I ramp the "backgroundRadiusMicrons" up to 50.

The error seems to only affect tiles that are along the periphery (i.e., tiles that are only partially complete).

**Comment by Svidro** [comment]
Yes, I usually turn my background radius off (0).  I would see how that works.  50 is huge!

**Comment by petebankhead** [comment]
Yes, the trouble comes from the background estimate whenever a large region is broken up into tiles for processing.

The technique QuPath is using to estimate the background is 'opening by reconstruction'; this starts out by estimating the background locally for every pixel, and then propagating this information throughout the tile.  The propagation is helpful most of the time, since this handles cases where there may be quite a lot of texture in the background quite well; and usually it doesn't propagate very far.  But it's not helpful all of the time... particularly where there are substantial differences in the amount of 'background' (or staining outside nuclei) within tiles and between neighboring tiles.

So my suggestion would also be to either set the background radius very high, or set it to zero to turn off background estimation entirely.  The second option is likely better if you can still find nucleus detection settings that work.

Depending upon what you want to do next, you might also try the 'Fast cell counts' command.  It is much simpler and does not provide nearly so much information, but it also does not handle background in the same way.... so gives an alternative.
