### ISSUE TITLE
whole image vs ROI coordinates in exported annotations

### ISSUE THREAD

**Issue by vladpopovici** [qupath/qupath#820]
Hello,

Let me begin by thanking you for this nice application and for introducing the GeoJSON support for annotations.
My goal is to use GeoJSON for interoperability between my (Python-based) environment and QuPath. With this in mind, I generated some annotations for testing purposes and I realized that the coordinate system used in QuPath is based on a cropped (ROI) version of the level-0 image in the pyramid. 
Is there a way to save the annotations in whole image (level-0/native magnification) coordinates instead of ROI-based coordinates? Or, maybe, just save the ROI coordinates along with the annotations as a pseudo-annotation in GeoJSON?

Thanks a lot for all your work,

Vlad

**Comment by petebankhead** [comment]
Hi @vladpopovici 

There's more info about this behavior on the user forum [here](https://forum.image.sc/t/qupath-is-cropping-white-background-in-whole-slide-image-how-to-avoid-this-behavior/40853/2). Basically, you'll need to get the bounding box coordinates from OpenSlide. You can do this either from within a Groovy script in QuPath, or later by accessing OpenSlide through Python.

Pete

PS. I'll close this as an issue because the [forum](http://forum.image.sc/tag/qupath) is really the best place for non-bug-related QuPath questions

PPS. Nice to see QuPath could be useful for you, I recognize your name from [this](https://doi.org/10.1093/bioinformatics/btx027) :)

**Comment by vladpopovici** [comment]
Thanks @petebankhead for the tips, I will move to the forum. Ref PPS: ;)
