### ISSUE TITLE
QuPath installation fails on Mac OS X

### ISSUE THREAD

**Issue by asmagen** [qupath/qupath#832]
I keep getting the following error while installing QuPath on MacOS Big Sur v 11.6.
Nothing shows up in the security settings, so it's not the normal case of being blocked and needing to approve installation in settings.
What can be done?

Thanks
<img width="438" alt="Screen Shot 2021-10-21 at 9 36 33 AM" src="https://user-images.githubusercontent.com/11299568/138761171-413c2c15-f636-49cf-9f2a-ca22deca134c.png">

**Comment by petebankhead** [comment]
I'm afraid I have no idea, I've installed QuPath without problem on Big Sur 11.6 :/
All that should be required is to right-click and select 'open' (see [docs](https://qupath.readthedocs.io/en/stable/docs/intro/installation.html#macos)).

Does that method give the installation failed result for you? Could you find any solution?

**Comment by asmagen** [comment]
Yes this method doesn't work.
Are there any dependencies for this installation like Java etc? Can I install through brew? (brew.sh)
________________________________

**Comment by petebankhead** [comment]
No external dependencies should be needed - a Java Runtime Environment is included in the installation.

A google search for `"the installer encountered an error that caused the installation to fail"` reveals quite a few discussions about all kinds of different software applications where the error appeared, but I'm afraid I can't replicate the issue so I can't test any of the proposed solutions.

**Comment by Svidro** [comment]
It was never stated, but I assume the basics were tried? Redownload the program, and try installing some other open source software to make sure it is not a general installer issue?

**Comment by asmagen** [comment]
These didn't work
________________________________

**Comment by petebankhead** [comment]
Is there an installer log available with useful information (as described at [this post](https://apple.stackexchange.com/questions/275915/debugging-the-installer-encountered-an-error-that-caused-the-installation-to-fa))?

**Comment by Svidro** [comment]
If other software did not work as well,  ("_These didn't work_") then it sounds like the problem might be broader than QuPath.

**Comment by petebankhead** [comment]
I will close this issue because there isn't anything we can replicate or fix. I see there have been about >4,500 downloads of the macOS version of v0.3 at this point, and since there haven't been other reports I guess it may be a system-specific problem that we can't fix on the QuPath side.

Please do add comments if there is further info.

Meanwhile, it might be possible to get a version of QuPath that works for you by following the [build from source](https://qupath.readthedocs.io/en/stable/docs/reference/building.html) instructions. This can directly generate an .app rather than a .pkg, so might work around any installer problems.
