### ISSUE TITLE
Qpath error in opening JPEG file

### ISSUE THREAD

**Issue by gianlucadirienzo** [qupath/qupath#834]
![qpath error](https://user-images.githubusercontent.com/93468785/139575561-68c59679-13b1-47bb-ac60-265c55da2c7a.jpg)

Good morning,

Qpath won't open some of my JPEG files. When I try to do so, an out of memory error pops up. I have tried to decrease the number of parallel threads as suggested, but the issue persists. The involved files are larger than 100 MB, have been compressed and sent to me via TransferNow.

Thank you for your attention.
Gianluca

**Comment by petebankhead** [comment]
Hi @gianlucadirienzo are you able to share any of your files so we can replicate the problem?

In any case, my guess is that JPEG is probably the wrong format to share the files; QuPath works best with [pyramidal images](https://qupath.readthedocs.io/en/stable/docs/intro/formats.html). I suggest asking whoever send the files if they can do so using a different format.

If a JPEG is 100 MB, then it is probably much much larger when uncompressed. This would cause the error you see.

**Comment by gianlucadirienzo** [comment]
I have started a repository to share the files with you.  

Thank you for your help.

**Comment by petebankhead** [comment]
Thanks, I see the image with the smallest file size is 44304 x 25156.

Uncompressed, this would require at least 44304 * 25156 * 3 bytes of memory (assuming three, 8-bit channels) - or just over 3 GB. In practice, more memory would be required as the image is being read and uncompressed.

I find that I cannot open it in QuPath or ImageJ, and Bio-Formats also fails with an error 
```
java.io.IOException: Restart interval and markers invalid
	at loci.formats.services.JPEGTurboServiceImpl.initialize(JPEGTurboServiceImpl.java:222)
	at loci.formats.in.TileJPEGReader.reopenFile(TileJPEGReader.java:144)
	at loci.formats.in.TileJPEGReader.initFile(TileJPEGReader.java:121)
	at loci.formats.FormatReader.setId(FormatReader.java:1421)
	at loci.formats.DelegateReader.setId(DelegateReader.java:300)
	at loci.formats.in.JPEGReader.setId(JPEGReader.java:87)
	at loci.plugins.in.ImportProcess.initializeFile(ImportProcess.java:499)
	at loci.plugins.in.ImportProcess.execute(ImportProcess.java:142)
	at loci.plugins.in.Importer.showDialogs(Importer.java:140)
	at loci.plugins.in.Importer.run(Importer.java:76)
	at loci.plugins.LociImporter.run(LociImporter.java:78)
```

JPEG is just not the right file format to use for images of this size. Even if the file *could* be opened, performance would be really bad because of the memory requirements.

QuPath *could* handle a pyramidal TIFF that is much bigger very efficiently. The file names include the words 'cropped region', therefore I would suggest requesting the original files. QuPath might be able to handle them already.

I will close this issue because it doesn't seem to be a bug in QuPath (comparable software also can't open the image). If you'd like to discuss formats / suggestions, the forum would be the best place: http://forum.image.sc/tag/qupath

**Comment by gianlucadirienzo** [comment]
I see. 
Thank you for your advice.
