### ISSUE TITLE
Compile source under windows

### ISSUE THREAD

**Issue by erexhepa** [qupath/qupath#84]
Hi,

Thank you first for making qupath available to the community. I think is a great tool and something like this was missing. 

I'm trying to compile the source under windows using Oracle JDK for the java part and I'm getting all kind of errors but before I embark into the debugging process was wondering if you guys would have any recommendations ?

Thanks
Elton

**Comment by Svidro** [comment]
Ah, I really wanted to get into this but I keep getting distracted!  All I know of was posted here:
https://github.com/qupath/qupath/tree/master/src/main/resources/eclipse
Although that might not help (Eclipse), maybe some of the information you need is similar?  If you do get it working, I'd love to know how.

**Comment by Svidro** [comment]
I also know that a few other people have worked on getting the code to compile over on the forum.
https://groups.google.com/forum/#!forum/qupath-users

**Comment by erexhepa** [comment]
Thank you for the tips. I'm using JIdea for the compilation but I will have a look at the Eclipse page above. I will update the thread once I get it working.

**Comment by erexhepa** [comment]
I'm still debugging but there seems to be at least on issue with one of the dependencies.

org.slf4j

it's not among the sources and it is not described in the POM file for Maven neither.

**Comment by erexhepa** [comment]
beside the library above there was also javax.script that was not installed properly. After adding two entries for the lib above with the last version of github I could run it in debug mode with JIdea and then create a single JAR including all jar files. 

Somehow (maybe because of Intelli JIdea) the target version of interpreter and java compiler did not match. I had to change for all the different modules to 1.8. 

The ant build did not work but finally the jar file is fine for our needs. Somehow it is also much smaller then the Windows install. It makes about 30MB instead of 300MB for the windows install but maybe there is some lib I didn't include. Anyway If something comes up will update the thread.

**Comment by Svidro** [comment]
Thanks for the info!  If you get a chance to post a workflow for what all you did to get it working, I'm sure it would be greatly appreciated on the forum!

**Comment by erexhepa** [comment]
There is still one issue that I just discovered with the browsing of the digital slides from the compiled version. The slides are open only at thumbnail and the displayed image is not adjusted when zooming int or out.

**Comment by Svidro** [comment]
That sounds like what happens when it does not recognize the format and  can only open the thumbnail.  It still does this for jpegxr images.  What is the server type listed in the image tab in each version?  I would start there.

**Comment by erexhepa** [comment]
yes you're right. It is trying to use ImageJ to open both .svs and mrxs files and I guess is using Bioformat because that is what Bioformat does it gives you by default the thumbnail (or lowest resolution representation). 

But it should call openslide isn't it ? That should be case even for more standart format like jpeg, tiff etc ? The openslide library is included thought in the list of jar. With try to debug and see why is calling ImageJ.

**Comment by Svidro** [comment]
I am afraid I don't know what is causing the difference!  Haven't had the chance to get into the coding myself yet, I just recognize the signs and symptoms.  Pete may know more once he's back from travelling.

**Comment by petebankhead** [comment]
I've only set up the entire project with Eclipse, using the approach briefly described at https://github.com/qupath/qupath/tree/v0.1.2/src/main/resources/eclipse - I'm afraid I don't know how to address the issues when using other IDE's.
(Incidentally, those instructions are a little old now, not all steps may be necessary.  For example, from memory I think only the .project file needs updated, not the .classpath file.)

However, here are some notes that might be helpful:

* Most of the POM files should descend from the 'base' POM, which specifies that the compiler should be compatible with [Java 8 here](https://github.com/qupath/qupath/blob/v0.1.2/pom.xml#L176).  I believe this should then be inherited across the project.
* slf4j-api is a dependency of logback-classic.  This is specified in the base POM, and so Maven should still take care of slf4j even if it isn't mentioned directly.  I don't know why anything involving javax.script would be troublesome.
* The jar files alone required for QuPath are reasonably small, but the JRE is required for running it.  The JavaFX packager can be used to put them all together in one (larger) installer, but if you already have a compatible JRE installed then you shouldn't need this.
* OpenSlide and OpenCV require native libraries... which opens a new area of effort for configuring everything properly.

I suspect this final point is critical for the 'opening only thumbnails' issue.  When opening a new image from a given path, QuPath will test all potential file readers it has access to and check if they can handle the path.  If you are only getting the thumbnails, then this implies that the OpenSlide check doesn't pass - which, because OpenSlide *can* certainly handle .svs, suggests that the OpenSlide native libraries are not properly accessible to QuPath, even if the jar is there.

When QuPath shows 'ImageJ' as the reader, it does mean just this; ImageJ1 is being used, which can handle a range of small (non-whole-slide) images only, with a combination of its own TIFF reader and Java's ImageIO.  It can also sometimes extract the thumbnail from a whole slide image, but only that.  If you want to use Bio-Formats you can, but need to download and add it separately - see https://github.com/qupath/qupath-bioformats-extension

If you do install the Bio-Formats extension, then that postpones the immediate need to solve the problem of accessing native libraries; at least, you should be able to open the formats supported by Bio-Formats so long as QuPath can find the Bio-Formats jar file.  Still, you won't be able to use OpenSlide or any commands reliant on OpenCV (including the Wand tool).

The easiest way to get the native libraries to work is generally to copy them to the directory from which you run the application in the first place.  You should be able to find the libraries by looking within an existing QuPath installation, or downloading the binaries for Windows from the OpenSlide/OpenCV websites.   But for running from within an IDE, I have only set this up with Eclipse to date and don't know the specifics of getting it to work elsewhere.

Finally, I've no doubt that the project could be structured in a way that makes it easier to use different IDEs.  The combination of Java 8, JavaFX, Maven, Ant and native libraries makes it more difficult than a project using Java alone, and there wasn't previously a critical need.  Still, the portability is something that I hope will be improved in the future.

**Comment by Svidro** [comment]
Setting the working directory to the native libraries folder was what fixed the same issue with the ImageJ server opening thumbnails in Eclipse.
