### ISSUE TITLE
select annotation results in annotation measurement table causes system crash - bug

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#86]
i created a list of annotations from classificated tiles. 
Then i split up the annotation class into a lot of single annotations. 
If I open the annotation measurement table and I can click on annotations and viewer jumps to the clicked annotation in the measurement table. 
Under special condition (i didnt find out which), it is possible to mark an arbitrary number of annotations in the measurement list. they will be selected in the annotation tab at the same time. 
I want to do this, to deleat alle annotations below an area treshold. 
But because of any reason the software collapses if I press shift and select more than one annotation in the annotation measurement table: 
![grafik](https://user-images.githubusercontent.com/16352785/28391415-46c6cba2-6cde-11e7-852d-faa34938f80d.png)

**Comment by DavidMHaumann** [comment]
I found out, that system collapse only happens, if there are still child objects. If they are deleted, selecting an arbitrary amount of annotations is possible.

**Comment by DavidMHaumann** [comment]
Opening the annotation hierarchy also crashes the system, if there a lot of objects.

**Comment by Svidro** [comment]
While I can't guarantee it isn't crashing, it also is likely that it only seems like it is crashing because the hierarchy is often VERY slow to load.  If one CPU core is still chugging away, it might come back in a few hours.  Some more information may be found here:
https://github.com/qupath/qupath/issues/41

**Comment by petebankhead** [comment]
I've flagged this as a duplicate, since it sounds the same as the issue linked to by @Svidro.  I've given the details there, and potential direction for how it might be addressed in the long term.

In this case, it might be possible to improve matters by ensuring that all entries in the 'hierarchy' tab are first closed - or that there are no child objects.  Then the results in the annotation table can be sorted by area, and all the top entries (with low areas) selected in one go.

In the longer term, the better way to handle this would be to write a script that finds all the annotations with an area below a specified threshold, and removes them directly from the object hierarchy.  Using a script it is possible to avoid the need for selecting the annotations in the GUI entirely, and get *much* better performance.

Clearly this is a bit more work to begin with, but I highly recommend working through the scripting parts on the Wiki if you haven't done so already - this is the kind of application where scripting can be invaluable.
