### ISSUE TITLE
Problem in recognizing fluoresence channels of qptiff file

### ISSUE THREAD

**Issue by lidailiop** [qupath/qupath#864]
Hello, 
We have recently acquired multiplex fluorescent images acquired by Codex technology. 
We process the files normally and we ended up having a qptiff file. 
In 4 out of 5 computers we tried to open the file using QuPATH, only the DAPI staining is recognized. 
Only on one computer, we have managed to open it with all the stainings depicted.
We are using exactly the same process of opening the file and we have the same QuPATH version. 
Is there any idea, what can create this problem specifically in some of the computers?

**Comment by MichaelSNelson** [comment]
Is there any chance qptiff is being directed to a particular server type on the system where it works? The server can be found in the Image tab and set in the preferences by extension, or during the import process.

**Comment by petebankhead** [comment]
My suggestion would be the same as @MichaelSNelson's, to check the image server.

I'll close this issue because without a response there isn't really anything we can do on the QuPath side. Also, since it's not clear that there is any bug, the forum would be a better place to discuss further: https://forum.image.sc/tag/qupath
