### ISSUE TITLE
Error exists when open a tiff file

### ISSUE THREAD

**Issue by SikangSHU** [qupath/qupath#872]
Hello! As I’d like to get a pyramidal tiff with which the colourspace is ‘grey16’ and open it in Qupath. But when I convert it in this way, the Qupath can’t open the tiff tile. How can I do for that? Thank you for any suggestion!
![image](https://user-images.githubusercontent.com/95743639/147184080-b0deb5af-bb2e-4c00-ac5f-01e5a3100899.png)

**Comment by petebankhead** [comment]
Hi @SikangSHU I'm closing this issue because you've also posted it at https://github.com/qupath/qupath/issues/221 and https://forum.image.sc/t/error-exists-when-open-a-tiff-image/61380

Please help us manage the demand for QuPath support by posting each question only once. The forum is the right place to ask so I've responded [there](https://forum.image.sc/t/error-exists-when-open-a-tiff-image/61380).
