### ISSUE TITLE
Numerous artefacts in case of "Tile classifications to annotations"

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#88]
If i convert tiles to annotations, it happens that numerous artefacts appear at the edges of the large tiles that are analysed in queue by RAM. It looks like that: 

![grafik](https://user-images.githubusercontent.com/16352785/28670613-cf45a150-72d9-11e7-9d7a-bebc3c29b807.png)

all small red dots that appear as a line from top to bottom shall not be there. They appear in the list of ROIs and make the result of the analysis wrong.

**Comment by petebankhead** [comment]
It's not clear that there is any bug here.  Equally-spaced vertical lines can be common artefact of the scanning process.  They may be sufficiently subtle not to be evident when looking at the image directly, but result in misclassifications - which then carry through when converting tiles to annotations.  The solution is to spend more time training the classifier/provide additional features to the classifier.

By playing around with the brightness/contrast to extreme levels you may see that the lines in your example correspond to lines in the original scanned slide.

I will close this issue for now.  If this explanation is wrong and you observe a problem with 'Tile classifications to annotations' that is not due to the tile classifications, please provide more detail - and ideally a way to replicate the problem.

**Comment by DavidMHaumann** [comment]
yes, pete, i was able to rain the artefacts out. everything worked afterwards. Thanks for your advice.
