### ISSUE TITLE
Low Resolution In windows but not in Mac

### ISSUE THREAD

**Issue by CptPatate1812** [qupath/qupath#891]
Hello, 

Sorry to bother, I have an issue with QuPath 0.3.2 on win10. 

I have some slices to analyse, however they appear in very low resolution (Unknown pixel resolution in the image tab) on windows10.
This however doesn't happen in MacOS QuPath version. 

I don't know what to do from that, any advice appreciated ! 
Thank you,

**Comment by MichaelSNelson** [comment]
And is the same server being used for both? I am not sure why it would not be, but I am not sure how much the installations may have been modified.

**Comment by petebankhead** [comment]
Upon reflection, it could also be a .vsi file with the core data directory missing - but it's really not possible for us to guess with much confidence.

I'll close this issue due to a lack of information.

Bug reports here should really follow the defined template shown when creating a new issue, so that they contain enough information for us to understand and address any issues. Please feel free to start a topic on https://forum.image.sc/tag/qupath for any general discussion to try to identify what may be going wrong.

**Comment by CptPatate1812** [comment]
Hello,

Sorry for not being able to reply, in the end I didn't bother and used the
mac instead of my windows laptop.
The name server was the same for both indeed;
As for the .vsi file, I didn't find it, however I used the same source
(external hdd), so the files used were exactly the same between the test on
windows and the test on mac.

Again, Sorry for the late reply,
If you want to further explore this bug, I can try to fetch the logs for
you.

Best,
PA

**Comment by petebankhead** [comment]
If you're working with .vsi files, then the problem I've seen before is that the accompanying .ets files are missing or inaccessible. For example, see https://forum.image.sc/t/open-vsi-images-in-qupath/41481/6

Although I'm not sure how that could happen using the same hard drive.

No need for logs from my side - QuPath relies on Bio-Formats to read .vsi files, so I'm not sure if there is any QuPath bug to fix anyway :) The forum would be the best place to post if this becomes more problematic, since the Bio-Formats team are active there (along with some others who I know use .vsi files with QuPath routinely).
