### ISSUE TITLE
Weird core dump in tile generation script

### ISSUE THREAD

**Issue by jdenholm** [qupath/qupath#932]
## Bug report
I have a script which extracts tiles from specific regions in WSIs. In a python object, I call a subprocess which runs this script on WSIs. I'm using a mixture of tif files (from ventana), svs (from aperio) and ndpi (from hamamatsu). When I run the tile extraction over my ~1000 scans, things work fine for the most part, but occasionally I get a core dump error from java. If I run the code on the *same* image it just broke on again, it works fine. There is seemingly no regularity to which images it fails on, other than they seem to be ".tif" files. I have never had this bug appear on previous versions of QuPath. I attach the log I get when Java core dumps, and I also attach the tile extraction script I am using  (converted to txt as it won't let me upload a groovy script).

Somewhat out of my depth when it comes to understanding this, but it seems pretty clear it's a bug.

[wsi_patch_extractor.txt](https://github.com/qupath/qupath/files/8168829/wsi_patch_extractor.txt)

[hs_err_pid314639.log](https://github.com/qupath/qupath/files/8168813/hs_err_pid314639.log)

**To Reproduce**
I run the groovy script with "qupath script my_script --args [...]", and have a symbolic link to the qupath binary in "/home/user/bin/qupath". I'm not sure sending test images will help, as it sometimes runs on 100s before breaking.

**Expected behavior**
In the vast majority of cases, the tile extractor script works exactly as I'd expect, and creates a directory filled with tiles.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - QuPath Version 0.3.2

**Comment by petebankhead** [comment]
From the log, it looks like you're calling the script with `40770,35790` as the width and height parameters - which seems much too big, leading to a memory allocation error.

Could it be that the bug is in whatever script you're using to make the request from QuPath?

**Comment by jdenholm** [comment]
Hi Pete,

Thank you for your reply. Unless I misunderstand, what I've asked for from the image is okay. I figured it would easier to show rather than tell. Would you take a look at the attached video, please?

Note: at the end when I say aperio, I meant to say ventana and got mixed up. Sorry...

https://user-images.githubusercontent.com/44713405/156379941-d0cdefd5-8a81-4fc2-855c-011a8c480f0e.mp4

**Comment by jdenholm** [comment]
Hi Pete,

Thank you for your reply. I attach another video which goes back in time to find which version was last able to open the image in question. In short, it's 0.3.0, but the video serves as evidence that I checked them correctly.

I will rerun the tile extraction using QuPath 0.3.0 tonight (as opposed to 0.3.2, which is the one that failed). I hope this new information helps.

When I say the code fails on one image, but works if I rerun it, I'm really not joking. It is super weird. I was thinking of putting it inside a try and except statement and giving it three or four goes before accepting failure because it never seems to fail on the same image twice in a row.

I'd like to try building from source out of curiosity. I will also ask my PI if I'm allowed to get the image to you, if you'd like to try it for yourself?

https://user-images.githubusercontent.com/44713405/156409401-178cd9aa-81b1-4c2d-b76a-4bc8965f394c.mp4



Best,

Jim

**Comment by petebankhead** [comment]
I think the video is showing exactly this issue: https://github.com/qupath/qupath/issues/894
It relates to opening a subset of images *outside of a project* using Bio-Formats in v0.3.1 and v0.3.2, when QuPath hangs. Not all svs files are affected, it depends upon how labels/macro images are stored inside. Some other formats (e.g. .vsi, .lif) suffer the issue too.

I've already fixed that and the fix will be in the next release.

Because that particular bug is related to the UI, I don't think it should have any impact when called from the command line - so I think it's different from the original tiling issue here.

I'm really interested to find out of the tiling issue is avoided when using QuPath v0.3.0.

There was a change in how tiles are requested in parallel in QuPath v0.3.1 and v0.3.2. This didn't directly *cause* the UI problem, but it revealed its existence (because the UI code was requesting tiles from an image after it was closed, and that caused the hang).

Intermittent issues like the tiling one here do sound like parallelisation is somehow involved, but the initial error on this thread is strange.

**Comment by jdenholm** [comment]
Hi Pete,
I ran the tile extraction procedure overnight with ~1400 WSIs using QuPath 0.3.0 without any issues. I've never been able to do this with 0.3.2, so I guess it follows that your are right about the source of parallelisation bug.

I guess the best thing to do for now is stick with 0.3.0?

Thank you, sincerely, for your help.

**Comment by petebankhead** [comment]
That's good to know, thanks. Poking deeper into the error I see
```
qupath.lib.images.servers.bioformats.BioFormatsImageServer$ReaderPool.openImage(Lqupath/lib/images/servers/TileRequest;IIZLjava/awt/image/ColorModel;)Ljava/awt/image/BufferedImage;+249
```
which is definitely a new line connected with how tiles are paralleled in QuPath's Bio-Formats reading since v0.3.1.

However, the bigger context is very mysterious:
```
# Problematic frame:
# C  [libc.so.6+0x9a23b]  __libc_malloc+0x12b

[...more stuff...]

Current thread (0x00007f594d8d5540):  JavaThread "tile-exporter10" daemon [_thread_in_vm, id=314754, stack(0x00007f4ec1aaf000,0x00007f4ec1bb0000)]

Stack: [0x00007f4ec1aaf000,0x00007f4ec1bb0000],  sp=0x00007f4ec1bac3d0,  free space=1012k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x9a23b]  __libc_malloc+0x12b

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 758  java.lang.ClassLoader.defineClass1(Ljava/lang/ClassLoader;Ljava/lang/String;[BIILjava/security/ProtectionDomain;Ljava/lang/String;)Ljava/lang/Class; java.base@16.0.2 (0 bytes) @ 0x00007f594243a6f0 [0x00007f594243a640+0x00000000000000b0]
J 754 c1 java.lang.ClassLoader.defineClass(Ljava/lang/String;[BIILjava/security/ProtectionDomain;)Ljava/lang/Class; java.base@16.0.2 (43 bytes) @ 0x00007f593b0f1dc4 [0x00007f593b0f1a80+0x0000000000000344]
J 939 c1 java.security.SecureClassLoader.defineClass(Ljava/lang/String;[BIILjava/security/CodeSource;)Ljava/lang/Class; java.base@16.0.2 (16 bytes) @ 0x00007f593b150c8c [0x00007f593b150bc0+0x00000000000000cc]
J 739 c1 jdk.internal.loader.BuiltinClassLoader.defineClass(Ljava/lang/String;Ljdk/internal/loader/Resource;)Ljava/lang/Class; java.base@16.0.2 (121 bytes) @ 0x00007f593b0e9acc [0x00007f593b0e8c20+0x0000000000000eac]
J 653 c1 jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Ljava/lang/String;)Ljava/lang/Class; java.base@16.0.2 (64 bytes) @ 0x00007f593b0be434 [0x00007f593b0bd460+0x0000000000000fd4]
J 3884 c1 jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Ljava/lang/String;Z)Ljava/lang/Class; java.base@16.0.2 (143 bytes) @ 0x00007f593b6e8024 [0x00007f593b6e71c0+0x0000000000000e64]
J 632 c1 jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Ljava/lang/String;Z)Ljava/lang/Class; java.base@16.0.2 (40 bytes) @ 0x00007f593b0b206c [0x00007f593b0b1a60+0x000000000000060c]
J 631 c1 java.lang.ClassLoader.loadClass(Ljava/lang/String;)Ljava/lang/Class; java.base@16.0.2 (7 bytes) @ 0x00007f593b0b1134 [0x00007f593b0b1040+0x00000000000000f4]
v  ~StubRoutines::call_stub
j  qupath.lib.images.servers.bioformats.BioFormatsImageServer$ReaderPool.openImage(Lqupath/lib/images/servers/TileRequest;IIZLjava/awt/image/ColorModel;)Ljava/awt/image/BufferedImage;+249
j  qupath.lib.images.servers.bioformats.BioFormatsImageServer.readTile(Lqupath/lib/images/servers/TileRequest;)Ljava/awt/image/BufferedImage;+21
```
This makes it look like something has gone wrong deeper in the bowels of Java, and I don't see how to resolve it from the QuPath side. I'm reluctant to return to the v0.3.0 method of parallelisation, since it had other (more frequent) problems https://github.com/qupath/qupath/issues/865

**Comment by petebankhead** [comment]
I'll close this issue, because it has been over a year and QuPath v0.4.x has come along in the meantime with other changes that may have helped (including Bio-Formats updates)... or at least taken us further away from figuring out what happened in v0.3.2 specifically.

v0.5.0 will also be long soon; feel free to reopen if the issue reoccurs with it.
