### ISSUE TITLE
How to save coordinates of all points comprising the annotated region

### ISSUE THREAD

**Issue by andanis** [qupath/qupath#95]
Hi
I am working with whole-slide-images. I zoom in a bit, do some annotations. Then I zoom out and continue annotating more regions. 
Is it possible to have all coordinates of points comprising of the annotated region stored as an array in the highest possible magnification level? At this point I only found some information about the annotated region like : centroid, perimeter, area by using: 
"Measure > Show annotation measurements"
Is it possible to have more information?

**Comment by petebankhead** [comment]
This is certainly possible in a script, since the coordinates are stored at that level.  But the details depend on the kind of regions you are drawing, and how you need them to be exported.

For example, you can get the bounding box of any shape like this:
```groovy
def roi = getSelectedObject().getROI()
print([roi.getBoundsX(), roi.getBoundsY(), roi.getBoundsWidth(), roi.getBoundsHeight()])
```

That is really all you need to represent a rectangle or an ellipse.

For a line, you could get the end points:
```groovy
def roi = getSelectedObject().getROI()
print([roi.getX1(), roi.getY1(), roi.getX2(), roi.getY2()])
```

Or, if you have a polygon then this will print the points:
```groovy
def roi = getSelectedObject().getROI()
print roi.getPolygonPoints()
```

As far as I recall, you can also use the final option for other shapes.  But beware of complex 'areas', which could be composed of multiple polygons and include holes etc.  Extracting and interpreting the coordinates for these is somewhat more difficult.

If you need more than this, I would recommend looking at the scripting documentation on the wiki, and then exploring in more detail the code for each of the ROI (region of interest) classes to see how their points are stored and accessible.

**Comment by cklat** [comment]
Hi Pete,

having basically the same problem, could you give me a hint on how to extract all the polygons that are made in the image at once? So far your suggested code works for one polygon. I believe it works when you have selected one prior running the script. I was trying to select all (=make them all yellow) and then running the script but it still gives me only the coordinates of one polygon. Is there a way to avoid this heavy time-consuming task of selecting all the polygons individually and exporting them?

**Comment by Svidro** [comment]
I should be able to get back to this a bit later, but in short you want to use something like getAnnotationObjects()  or getDetectionObjects() depending on your targets of interest, and assign them to a variable.  There are some good examples of looping on the google group forums, but you probably want something like:

annotations = getAnnotationObjects()
annotations.each{ println( it.getROI().getPolygonPoints()}

**Comment by andanis** [comment]
@cklat  After your post, I started experimenting and found way to do it:

1. Select all the annotations
2. Go to "Object" -> "merge selected annotations"
Now both the annotations should represent one annotation with some "Area(AWT)" name.
Now go to "Automate" -> "Show script editor"
Use script :
def roi = getSelectedObject().getROI()
print roi.getPolygonPoints()

and run
In the console, you should be able to see the annotations and it should contain coordinates of all previous regions.
What I don't know is how to go back to original setting of having many ROIs (unmerged) and how to say which all coordinates belong to first roi and where does the next roi coordinates start as the above returns a concatenated list of coordinates.

**Comment by petebankhead** [comment]
Here's a script that will loop through all objects (of any kind), and write out the polygon points to a text file inside the current project directory:
```groovy
// Create an empty text file
def path = buildFilePath(PROJECT_BASE_DIR, 'polygons.txt')
def file = new File(path)
file.text = ''

// Loop through all objects & write the points to the file
for (pathObject in getAllObjects()) {
    // Check for interrupt (Run -> Kill running script)
    if (Thread.interrupted())
        break
    // Get the ROI
    def roi = pathObject.getROI()
    if (roi == null)
        continue
    // Write the points; but beware areas, and also ellipses!
    file << roi.getPolygonPoints() << System.lineSeparator()
}
print 'Done!'
```
Be wary of any `Area` ROIs though (including `Area (AWT)`) - these can contain complex polygons with discontinuous regions, and you might well not get the expected output using this method.  Any further help on this would require knowing exactly what the 'expected output' should be for these tricky cases.

There are a few blog posts that describe other kinds of export, e.g. with raster images rather than vertices, which would help avoid the troublesome shapes.  [This posts](https://petebankhead.github.io/qupath/scripting/2018/03/14/script-export-labelled-images.html), for example.

**Comment by Svidro** [comment]
@andanis 
One script that I think does what you are referring to:
https://gist.github.com/Svidro/5829ba53f927e79bb6e370a6a6747cfd#file-split-annotations-into-contiguous-areas-groovy

But I think Pete has things covered!

**Comment by petebankhead** [comment]
Thanks @Svidro, I have lost track of which scripts I've written and where :)
But yes, that would give a way to handle areas... and shows the trouble involved (separate list of external polygons and holes).

It's also possible to get `java.awt.Shape` objects for any QuPath `ROI` and have the task of exporting them; still a job to do, but at least there is likely to be more documentation available.

It would be worthwhile to have a general export function within QuPath; but my question is about which format should be used for export.  Ideally it would be a standard, open format of general usefulness in the digital pathology community.  Ideas welcome!

**Comment by cklat** [comment]
Thanks for the fast replies @all!

What I eventually want to do with the extracted polygon vertices, is to convert them to a binary mask, i.e. all the pixels inside the polygon will be marked as one class and the pixels of the polygon will be marked as another class.

@andanis 
This approach isn't going to work out for drawing a binary mask, I think. The polygon vertices must be seperated, otherwise I will probably have all the stuff that is between each polygon also marked as the same class in the binary mask.

@petebankhead 
Thanks for the code, Pete. But when I execute it, I get a blank text file. I changed `for (pathObject in getAllObjects())` to `for (pathObject in getAnnotationObjects())` which is giving the desired coordinates of all the polygons.

Could you explain a little bit more about what you mean by complex polygons in discontinous regions? What do you mean by regions and when can they be discontinous?

**Comment by petebankhead** [comment]
I mean polygons that might have multiple separate regions and yet are still treated as the same shape, or contain holes inside them - and so can't be represented simply by a list of vertices.

You can create such shapes using the brush or wand tool - hold down 'Alt' to turn on 'subtract mode', and this lets you remove areas from inside an existing shape.  You can also hold down shift when using the brush to create multiple polygons but which are treated as the same object (which you can see by the fact they are all selected together... using the default colors this means all shown as yellow).

Given that your plan is to create a binary mask, definitely check out the blog.  It should be much easier to do this directly from within QuPath and not need to handle another way to handle the shapes.  From memory, there are a few posts where I described this kind of thing.

**Comment by cklat** [comment]
Hi Pete,

I tried your code from your blog regarding creating binary masks: https://gist.githubusercontent.com/petebankhead/0b14beef131312042686c01056104b85/raw/8223a934f10761a885ef6cab20d71f786029bb84/QuPath-Export%20binary%20masks.groovy

It works perfectly smooth and would save me lots of work. There's just one thing that gives me a bit of trouble: The binary masks are not embedded in the whole image, meaning if I read them in somewhere else, I just get the mask according to those squared little images but I don't know where exactly they are located in the whole image that I'm annotating (unless there's something I'm overlooking right now). Could you tell me how to modify your code from the blog in order to save the binary masks embedded in the whole image?

**Comment by Svidro** [comment]
I don't think QuPath directly modifies any of the images.  You can create new files with a "burned in" mask at whatever size/downsample as long as they are within the allowable size for that file type, but modifying pyramidal files might be rough.  Similar question here perhaps: https://github.com/qupath/qupath/issues/166

Side note, the square images should have XY coordinates as part of their name so that they can be reconstructed from the file names.  You may also be able to create the binary mask as Pete posted above, but as a single image with a known downsample, then expand it back to normal size within the program you are using to merge it into your (I assume) tiff.

If you want essentially an extra channel with the mask in it, I think you want a file of a size that FIJI/ImageJ can handle, and merge the extra channel in there after exporting the mask from QuPath.  That still leaves stitching all of the files together using another plugin or program, if you exported as many tiles.

https://imagej.net/Stitch_and_Align_a_sequence_of_grid_images_Tutorial

**Comment by petebankhead** [comment]
As @Svidro says, QuPath doesn't modify the whole slide images - and nor can it write a whole slide image itself (unless you were to do all the low-level stuff in a script yourself - just about anything should be possible then).

Personally, I've never needed this functionality; or, more accurately, I've always found a way around it that was much easier than solving the problem of writing an entirely new whole slide image.  These include:
* Exporting the original pixels along with the binary image (e.g. if using the masks to define training regions to create a new algorithm)
* Exporting the binary image at a low resolution, and either exporting the scaling factor (downsample) or approximating this later based on the width & height compared to the original
* Exporting cropped regions, and including the bounding box and scale information in the file name
* Exporting cropped regions as ImageJ TIFFs, where QuPath is able to set the key information in the image properties to facilitate reading the regions back later

QuPath requests pixels using `RegionRequest` objects.  To generate a string containing the key information from a `RegionRequest` you might use the following:
```groovy
String name = String.format('%s_(%.2f,%d,%d,%d,%d)',
            server.getShortServerName(),
            request.getDownsample(),
            request.getX(),
            request.getY(),
            request.getWidth(),
            request.getHeight()
    )
```
The script [here](https://petebankhead.github.io/qupath/scripting/2018/03/14/script-export-labelled-images.html) uses this when exporting to include this information in the file name.

If none of these methods seem like they would work for you, it would help if you describe a bit more what you need the final output for and what software you would be using next to read the images.

**Comment by cklat** [comment]
Hi,

thanks all for your responses. I'm not sure if I can follow what you actually mean but I think we talking about two different things. Anyways, I think, I'm good to go with the information that is included in the file name. I didn't notice at first that the coordinates given in the file name was '0,0'-coordinate of the respective small image. I believe that I just can generate an array with filled zeros in the size of the RoI and then fill in the binary mask at the coordinates in the file name,

Thanks a lot to you guys for your help!

**Comment by ab-rawat** [comment]
Hello All,
I am working on something similar for exporting annotation objects from QUpath as shapefiles .shp/.dbf/.shx for later import into definiens.  
I would say I am 80% through.
Currently I have a python script that (given polygon vertices) dumps out the shapefiles that definiens is able to ingest. Not yet tested with complex shapes like holes within polygons though!
Also I have a groovy script along the lines mentioned above by Peter that dumps out vertices from QUpath annotations.
Ideally I would like to have a single python script that does both (using Jython within QUpath maybe). Not sure if anyone has tried Jython in QUpath before?
In case Peter is thinking of developing this functionality for exporting annotations objects from QUpath, I would say shapefiles is one such format that is widely used (and has third party libraries for handing the read/write).
cheers!
rawat.

**Comment by petebankhead** [comment]
I should probably admit that I didn't know anything about shapefiles - I'll look out for them from now on!  If you happen to know of other pathology software that can export/import them (can Definiens do both?) that would be very good to know.

I actually made a half-hearted attempt to incorporate Jython support in the early days, before I went all-in for Groovy because trying to be multilingual took extra effort that (at the time) didn't seem worth it.  _However_, this means that if you download the Jython standalone jar and drag it onto QuPath then a new 'Jython' option will appear as an available scripting language.

Now the half-hearted bit: there's a tiny error in the default import statement for Jython in v0.1.2 - so until that's fixed you'll need to *uncheck* the option *Run &rarr; Include default bindings*.  This means that the normal [`QPEx` things](https://github.com/qupath/qupath/wiki/Writing-custom-scripts#default-methods--imports) will not be available in the script, and you'll need to import these separately... and possibly remember to turn the default imports back on if your Groovy scripts require them.

The following works for me, after installing the jar and setting the script language to `Jython`:
```python
from qupath.lib.scripting.QPEx import *
annotations = getAnnotationObjects()
print annotations
```

The fix to address this in the code appears trivial (switching `+` to `,` in the code), so potentially this won't be necessary in later versions.

**Comment by petebankhead** [comment]
The import issue should be fixed [on my fork](https://petebankhead.github.io/qupath/2018/03/19/qupath-updates.html).

**Comment by ab-rawat** [comment]
Hi Peter,
Ya, definiens can do both import and export of shapefiles.
There are also third party libraries such as pyshp that I am using for reading/writing shapefiles in python.....so there is reasonable support for the format already.
I am just poking around QUpath to figure out the best way to export annotations directly into shapefile preferably in a single step. I will let you guys know how my efforts work out.
What would you recommend for handling complex shapes (polygons with holes etc)? I am able to dump out the vertices using groovy script, but am not sure how they will get interpreted once converted to shapefile.......or maybe that is a pyshp/definiens problem.
In any case, I will be in touch as this develops.
cheers!
rawat.

**Comment by petebankhead** [comment]
You can convert any existing QuPath ROI into a [`java.awt.Shape`](https://docs.oracle.com/javase/8/docs/api/index.html?java/awt/Shape.html) with [`PathROIToolsAwt`](https://github.com/qupath/qupath/blob/v0.1.2/qupath-core-awt/src/main/java/qupath/lib/roi/PathROIToolsAwt.java#L204).

While it doesn't solve the shapefile problem, at least it gets the ROIs into a more QuPath-independent format, from with you can request vertices in a standard way (with a [PathIterator](https://docs.oracle.com/javase/8/docs/api/index.html?java/awt/Shape.html)) that is fairly well documented.  Using [`java.awt.geom.Area`](https://docs.oracle.com/javase/8/docs/api/index.html?java/awt/Shape.html) is also an option for anything other than a `LineROI`.

You _might_ then be able to find a library that converts a Java `Shape` into a more shapefile-friendly format (if you find a suitable library as a `.jar` file, you can just drag it onto QuPath to copy it to the extensions directory and then it should be accessible in your scripts - and potentially add it as a dependency in IntelliJ for easier scripting).  Otherwise I guess I'd look for whatever way your shapefile-writing library represents complex shapes, and with the help of the `PathIterator` try to export from QuPath in the closest way I could.

In general, I think QuPath needs better support for shapes and things that may be done with shapes, and every now and then I look towards [Java Topology Suite](https://github.com/locationtech/jts).  I've written a couple of scripts with it, and am tentatively thinking of creating converters for all QuPath ROIs to a JTS representation... I just haven't had a big enough need for it yet.  As far as I can see, JTS has support for reading shapefiles, but I don't see any for writing them.  Although it may write GeoJSON - which is another candidate for a format.  I've seen it used for pathology in [QuIP](https://sbu-bmi.github.io/quip_distro/), but I haven't noticed any other examples yet.

I guess your main task is to get QuPath annotations into Definiens, right?  Are there any other candidate formats that it could import?

**Comment by ab-rawat** [comment]
Hi Peter,
Sorry about not updating earlier.
I have finally worked out the problem by using a combination of groovy and python scripts.
I am now able to export pretty much any number of annotations with complex shapes such as holes etc and import them into definiens as shapefiles.
There were challenges regarding how the polygon vertices are fetched by something like it.getROI().getPolygonPoints() ......I noticed the number of returned vertices is not the same as number of vertices being plotted while doing the annotation. Also some vertices seem to be repeated for no obvious reason. (I had no time to figure out why this was the case). 
Furthermore, for complex shapes outer polygon must be returned clockwise and inner "holes" must be returned counter-clockwise and so on. 
In any case it works now. Thanks all for the tips!
In case you plan to include this functionality in QUpath, do drop me a line and I can help with the same.
cheers!
rawat.

**Comment by tfisher1995** [comment]
Hey Peter,

This is my first time commenting, but I have been following your forums on QuPath for a while. I want to apologize in advance if I do not post my question correctly. I developed a groovy script based on the comments posted on this issue. The output is a spreadsheet of points from each annotation made (code is shown below). With a little bash scripting, I can format these two spreadsheets into one CSV file that looks like the attached picture (attachment). However, I am not familiar with groovy nor the syntax of groovy. I am not sure if the points per annotation are the pixel units at level 0 (highest resolution) or micrometer at level 0 or something completely different. My question to you is, what are the points units, and at what level/resolution are these taken? Please ask any questions, and I am happy to answer them. 

![Screenshot from 2020-09-10 20-15-22](https://user-images.githubusercontent.com/41245184/92829599-643a1100-f3a2-11ea-8599-77236dbde92a.png)



`
setImageType('BRIGHTFIELD_H_E');
setColorDeconvolutionStains('{"Name" : "H&E default", "Stain 1" : "Hematoxylin", "Values 1" : "0.63348 0.72052 0.28205 ", "Stain 2" : "Eosin", "Values 2" : "0.16986 0.95793 0.23134 ", "Background" : " 229 221 218 "}');

// Create an empty text file
def name = getProjectEntry().getImageName() + '.txt'
def path = buildFilePath(PROJECT_BASE_DIR, 'points_results')
mkdirs(path)
def file = new File(path,name)
file.text = ''

// Loop through all objects & write the points to the file
// for (pathObject in getAllObjects()) {
for (pathObject in getAnnotationObjects()) {
    // Check for interrupt (Run -> Kill running script)
    if (Thread.interrupted())
        break
    // Get the ROI
    def roi = pathObject.getROI()
    if (roi == null)
        continue
    // Write the points; but beware areas, and also ellipses!
    file << roi.getPolygonPoints() << System.lineSeparator()
}
print 'Done!'


// Annotations
def name2 = getProjectEntry().getImageName() + '.txt'
def path2 = buildFilePath(PROJECT_BASE_DIR, 'annotation_results')
mkdirs(path2)
path = buildFilePath(path2, name2)
saveAnnotationMeasurements(path2)
print 'Results exported to ' + path2
`

**Comment by petebankhead** [comment]
Hi, it looks like in your script the coordinates of the points will be export in pixel units.

The annotations (in the second export) will be export in µm (probably) or pixel units depending upon the image - but the column heading should tell you which.

(I edited your post to update the code formatting to make it more readable)
