### ISSUE TITLE
TMA grid view does not show all TMA cores

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#96]
Has anyone an idea why the tma grid view does not show all TMA cores? see below

![grafik](https://user-images.githubusercontent.com/16352785/29870356-590d2b3e-8d87-11e7-98dd-260d93b8c99d.png)

**Comment by Svidro** [comment]
I do not have access to a TMA at the moment but are those cores set to "missing" (they would have a lighter core outline)?

**Comment by DavidMHaumann** [comment]
No, they are blue and have content. That is the strange point. I could not find out anything yet, that the not viewed cores have in common.

**Comment by petebankhead** [comment]
The core images are loaded in a background thread, and there is a 5 second timeout associated with this - see [here](https://github.com/qupath/qupath/blob/v0.1.2/qupath-gui-fx/src/main/java/qupath/lib/gui/commands/TMAGridView.java#L254).

One possibility is that the timeout isn't generous enough in your case, and the cores are not being loaded fast enough.  I don't know why that would be the case... it might be to do with the computer specifications, where the image is located (a network share?), or the access time required for the specific file format.

Another option is that there are just too many cores.  That is my best guess, since the scrollbar thumb on the right in your screenshot looks very small.  There is a limit to the size of the cache used to store the TMA cores to reduce the risk of memory errors, see [here](https://github.com/qupath/qupath/blob/v0.1.2/qupath-gui-fx/src/main/java/qupath/lib/gui/commands/TMAGridView.java#L133) for the location in the code.

Currently there is no way to increase the size of the cache through the user interface to support more cores in the grid view.  Although, as is often the case, there is a way through a script.  You could try running this to double the cache size to see if it helps.
```groovy
qupath.lib.gui.commands.TMAGridView.MAX_CACHE_SIZE = 500
```

**Comment by petebankhead** [comment]
I've updated these limits in v0.2.1. Hopefully that is enough to avoid this issue resurfacing.
