### ISSUE TITLE
Image null

### ISSUE THREAD

**Issue by miyakorogers** [qupath/qupath#968]
Hi I am processing around 55 images in qupath they are all composite tiffs, which have all been compiled using the bioformats importer in imagej, so in theory they should all be the same type of image. they are about 2,000,000 KB each.

At around image 30, every so often I would add an image and it would be image null. When this happens everything crashes. It is really slowing down the whole process! Any help would be appreciated

**Comment by petebankhead** [comment]
Hi @miyakorogers 

Although I agree that QuPath should really handle this more elegantly, I'd recommend posting a question on the forum instead: https://forum.image.sc/tag/qupath

There's no bug report template here for me to act on, so this seems more an issue of how QuPath is being used rather than a clear bug with steps to reproduce.

The images sound huge, which is probably the real problem. Any solution is likely to require converting to a [pyramidal OME-TIFF](https://qupath.readthedocs.io/en/stable/docs/intro/formats.html) to reduce memory requirements. You can do this using the QuPath [`convert-ome` command on the command line](https://qupath.readthedocs.io/en/stable/docs/advanced/command_line.html) - you may find some tips via https://forum.image.sc/search?q=qupath%20convert-ome or post a new question.
