### ISSUE TITLE
Identifying dye combinations per cell

### ISSUE THREAD

**Issue by slarmour16** [qupath/qupath#98]
I have been trying to find a way to quantify some staining I have done using 4 different fluorophores (see example image below). As I am struggling to identify cell boundaries I have ended up manually marking each cell that is positive for each fluorophore using ImageJ. Using ImageJ I can identify how many cells are stained positive for each dye but not whether a cell is marked for multiple dyes.
Is there a way of identifying this in QuPath, perhaps identifying all the markers within a certain proximity to each other? 
I would greatly appreciate any ideas as I have over 400 images so counting them manually would be a huge task!!

![markers_counter window - r026 czi - crop r026 czi 01](https://user-images.githubusercontent.com/31700648/30119489-cb0cc51e-931d-11e7-9d1b-2ae19e76c9cc.jpg)

**Comment by Svidro** [comment]
I'm not sure about your file type, but the one method I know of for handling more than 3 channels is listed here:  https://github.com/qupath/qupath/issues/49
If you have more questions about a project specifically and not a bug in the software, you may be better off trying the forum.
https://groups.google.com/forum/#!forum/qupath-users

**Comment by petebankhead** [comment]
It's not totally clear to me whether this is something best approached using QuPath or Fiji.  Factors to consider would be:

* Is there a DAPI channel?  If so, QuPath's cell detection could give a head start.
* Is 'detecting peaks in each color channel' a suitable way to determine whether a cell is positive?  This would depend on whether the staining is localized in each cell (e.g. in the nucleus, or dispersed elsewhere).
* Are you using (part of) a whole slide image?

Apart from that, [this ImageJ forum post](http://forum.imagej.net/t/counting-double-labeled-cells-in-fiji/3832/2?u=petebankhead) might help to get started.

**Comment by slarmour16** [comment]
Thank you for your suggestions. I will try having 2 images with 3 stains and merging at the end. 

I think the peaks in each cell would certainly do for seeing whether it was positive or negative however in Fiji I am struggling to get the boundaries of each cell as it splits the cells between neighbouring nuclei rather than putting a boundary around each nuclei. I have 2 cytoplasmic stains and 2 nuclear stains (one of which is dapi) and need to find combinations of each dye per cell. 
Is there a certain format the images should be in for the separate channels to appear in the image properties. At the moment I think it is being treated as one image which may be why I'm struggling.

**Comment by Svidro** [comment]
It does need to be in a format that has multiple channels, I think.  Tiff, mrxs, svs are some of the ones I am most familiar with.

**Comment by petebankhead** [comment]
In what format is your image?  How does it appear in Fiji?  Can you switch between 4 channels in either Fiji or QuPath?  In the case of QuPath that would be under the 'Brightness/Contrast' option.

It's possible the image is being loaded as a 3-channel RGB... either because of the way it is being opened, or the way in which it was previously saved.  But we would need more information, or an example image, to be able to help further.  It should be possible to work with 4-channel images in both Fiji or QuPath, if they have been saved in a suitable file format.

I have written a bit about different kinds of multichannel images [here](https://petebankhead.gitbooks.io/imagej-intro/content/chapters/colors/colors.html).
