### ISSUE TITLE
identifying Renal Cortex, Medulla and extrarenal tissue.

### ISSUE THREAD

**Issue by khalifa1989** [qupath/qupath#99]
![111](https://user-images.githubusercontent.com/31824571/30250353-233ffab2-964d-11e7-8df9-09bcddfdb1a9.png)

Hello all, 
Sorry if my question is basic but I could'nt find an answer and am looking for your help.
So I have 500 Scans of renal biopsies which are stained for Macrophages (CD68). The question is how can I tile the already marked tissue Area through (Simple Tissue detection) into 3 regions of interest (Cortex, Medulla and extrarenal tissue)?. Does it work somehow to draw lines to seperate the areas?.
Next question is, can I get a table with the percentages of positive Area for each ROI in all 500 slides? 

Many Thanks

**Comment by petebankhead** [comment]
It's definitely not too basic a question... I haven't personally needed anything quite like this, and unfortunately can't think of any really elegant way to do it currently.  However, I think it should be possible in an inelegant way.

This is how I would suggest:

* First unlock you annotation (it’s locked by default during simple tissue detection).  Either select it, right click and choose *Annotations &rarr; Unlock*, or else run the following script to unlock all annotations in the image.

```groovy
getAnnotationObjects().each {it.setLocked(false)}
```

* Create separation lines using the brush tool with the 'Alt' key pressed (to put it into eraser mode).  This won't entirely solve the problem, because the resulting split region will still be treated as one 'object' - giving one set of measurements, and taking one classification… but it’s a start.

* Split the multi-part (area) annotation into separate polygons.  The following script should do this (be sure to save your data before trying it, in case it doesn’t give the result that you want).

```groovy
import static qupath.lib.roi.PathROIToolsAwt.splitAreaToPolygons
import qupath.lib.roi.AreaROI
import qupath.lib.objects.PathAnnotationObject

// Get all the annotations
def annotations = getAnnotationObjects()

// Prepare to add/remove annotations in batch
def toAdd = []
def toRemove = []

// Loop through the annotations, preparing to make changes
for (annotation in annotations) {
    def roi = annotation.getROI()
    // If we have an area, prepare to remove it - 
    // and add the separated polygons
    if (roi instanceof AreaROI) {
        toRemove << annotation
        for (p in splitAreaToPolygons(roi)[1]) {
            toAdd << new PathAnnotationObject(p, annotation.getPathClass())
        }
    }
}

// Perform the changes
removeObjects(toRemove, true)
addObjects(toAdd)
```

* Set a classification for each new polygon, to help identify it later.

* If you do not need/want to do a cell analysis, try *Analyze &rarr; Region identification &rarr; Positive pixel count (experimental)*.  You will probably need to try different parameters.  The useful measurement should be *Positive pixel %*.

* View/export the results with the help of *Measure &rarr; Show annotation measurements*.  Some extra work might be needed to combine the results across images, see #79 for more discussion on this.

It would be possible to create a script or command to do this more easily with the help of the line drawing tool, but it would be quite a bit more complicated… this is the best I can come up with using the existing functionality.

**Comment by Svidro** [comment]
Oooh, that script would have been useful a few times!  I have wanted the ability to split ROIs, though I don't recall why at the moment.
----
If the tissue regions are visually distinct, this forum thread might also give you a way to automatically create the regions from your simple tissue detection, though it will never be perfect!  Also, the more features you use, the larger sample size you will need, and I don't know how well that will work with your data set.  Image quality/lighting also needs to be similar throughout :)

https://groups.google.com/forum/#!topic/qupath-users/gm0YYJxSriA
